Repository opentripplanner/OpenTripPlanner, pull requests merged in 2019-11, with the labels that each got.

#2863 Uk way property set
  docs/Changelog.md
  docs/Configuration.md
  src/main/java/org/opentripplanner/graph_builder/module/osm/UKWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetSource.java
Labels: OTP2

#2862 Transmodel Graph QL API
  docs/SandboxExtention.md
  docs/sandbox/TransmodelApi.md
  pom.xml
  src/ext/java/org/opentripplanner/ext/examples/statistics/api/model/StatisticsGraphQLSchemaFactory.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphIndex.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexAPI.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/TransmodelMappingUtil.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/PlaceType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/TransmodelPlaceType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/TransmodelStopPlaceType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/TransmodelTransportSubmode.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/TripTimeShortHelper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/scalars/DateScalarFactory.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/scalars/DateTimeScalarFactory.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/scalars/GeoJSONCoordinatesScalar.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/scalars/LocalTimeScalarFactory.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/scalars/TimeScalarFactory.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/api/configuration/APIEndpoints.java
  src/main/java/org/opentripplanner/common/model/GenericLocation.java
  src/main/java/org/opentripplanner/index/IndexGraphQLSchema.java
  src/main/java/org/opentripplanner/index/model/TripTimeShort.java
  src/main/java/org/opentripplanner/model/FeedScopedId.java
  src/main/java/org/opentripplanner/routing/core/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/graph/GraphIndex.java
  src/main/java/org/opentripplanner/util/OTPFeature.java
  src/test/java/org/opentripplanner/common/model/GenericLocationTest.java
Labels: OTP2

#2868 Add NeTEx Station extensions
  docs/Changelog.md
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/model/GroupOfStations.java
  src/main/java/org/opentripplanner/model/MultiModalStation.java
  src/main/java/org/opentripplanner/model/OtpTransitService.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceImpl.java
  src/main/java/org/opentripplanner/netex/loader/NetexImportDataIndex.java
  src/main/java/org/opentripplanner/netex/loader/NetexImportDataIndexReadOnlyView.java
  src/main/java/org/opentripplanner/netex/loader/mapping/CalendarMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/FeedScopedIdFactory.java
  src/main/java/org/opentripplanner/netex/loader/mapping/GroupOfStationsMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/MultiModalStationMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/NoticeAssignmentMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/NoticeMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/OperatorToAgencyMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/RouteMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/StationMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/StopAndStationMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/StopMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/StopTimesMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/TripMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/TripPatternMapper.java
  src/main/java/org/opentripplanner/netex/loader/parser/SiteFrameParser.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/test/java/org/opentripplanner/gtfs/mapping/StopAndStationMapperTest.java
  src/test/java/org/opentripplanner/netex/NetexLoaderSmokeTest.java
  src/test/java/org/opentripplanner/netex/loader/mapping/CalendarMapperTest.java
  src/test/java/org/opentripplanner/netex/loader/mapping/FeedScopedIdFactoryTest.java
  src/test/java/org/opentripplanner/netex/loader/mapping/MappingSupport.java
  src/test/java/org/opentripplanner/netex/loader/mapping/NetexTestDataSample.java
  src/test/java/org/opentripplanner/netex/loader/mapping/NoticeAssignmentMapperTest.java
  src/test/java/org/opentripplanner/netex/loader/mapping/NoticeMapperTest.java
  src/test/java/org/opentripplanner/netex/loader/mapping/OperatorToAgencyMapperTest.java
  src/test/java/org/opentripplanner/netex/loader/mapping/RouteMapperTest.java
  src/test/java/org/opentripplanner/netex/loader/mapping/StopAndStationMapperTest.java
  src/test/java/org/opentripplanner/netex/loader/mapping/StopTimesMapperTest.java
  src/test/java/org/opentripplanner/netex/loader/mapping/TripMapperTest.java
  src/test/java/org/opentripplanner/netex/loader/mapping/TripPatternMapperTest.java
Labels: OTP2

#2854 Null check on gtfs parent station
  src/main/java/org/opentripplanner/graph_builder/annotation/ParentStationNotFoundAnnotation.java
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/gtfs/MockGtfs.java
  src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/LinkStopsAndParentStationsTogether.java
  src/test/java/org/opentripplanner/gtfs/GtfsContextBuilder.java
Labels: OTP2, bug

#2870 Remove transit logic from A Star related classes
  src/main/java/org/opentripplanner/api/resource/GraphPathToTripPlanConverter.java
  src/main/java/org/opentripplanner/api/resource/PlannerResource.java
  src/main/java/org/opentripplanner/model/TripPattern.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/AStar.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/itinerary/ItineraryMapper.java
  src/main/java/org/opentripplanner/routing/bike_rental/TimeBasedBikeRentalFareService.java
  src/main/java/org/opentripplanner/routing/core/RoutingContext.java
  src/main/java/org/opentripplanner/routing/core/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/core/State.java
  src/main/java/org/opentripplanner/routing/core/StateData.java
  src/main/java/org/opentripplanner/routing/core/StateEditor.java
  src/main/java/org/opentripplanner/routing/edgetype/LegSwitchingEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/routing/fares/AddingMultipleFareService.java
  src/main/java/org/opentripplanner/routing/graph/GraphIndex.java
  src/main/java/org/opentripplanner/routing/impl/DefaultFareServiceImpl.java
  src/main/java/org/opentripplanner/routing/impl/DutchFareServiceImpl.java
  src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
  src/main/java/org/opentripplanner/routing/impl/NycFareServiceImpl.java
  src/main/java/org/opentripplanner/routing/services/FareService.java
  src/main/java/org/opentripplanner/routing/spt/GraphPath.java
  src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java
  src/test/java/org/opentripplanner/routing/algorithm/TestFares.java
  src/test/java/org/opentripplanner/routing/core/RoutingContextTest.java
  src/test/java/org/opentripplanner/routing/core/TestIgnoreRealtimeUpdates.java
  src/test/java/org/opentripplanner/routing/fares/MultipleFareServiceTest.java
Labels: OTP2

#2866 Otp2 new codestyle
  README.md
  docs/Changelog.md
  docs/Codestyle.md
  docs/Developers-Guide.md
  formatter.xml
  intellij-code-style.xml
Labels: OTP2

#2890 Update TransmodelAPI sandbox feature as code owner
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
Labels: OTP2, sandbox

#2881 Combine all OpenStreetMapProviders and OpenStreetMapContentHandlers
  docs/Basic-Tutorial.md
  docs/Changelog.md
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/openstreetmap/BinaryOpenStreetMapParser.java
  src/main/java/org/opentripplanner/openstreetmap/BinaryOpenStreetMapProvider.java
  src/main/java/org/opentripplanner/openstreetmap/impl/AnyFileBasedOpenStreetMapProviderImpl.java
  src/main/java/org/opentripplanner/openstreetmap/impl/FileBasedOpenStreetMapProviderImpl.java
  src/main/java/org/opentripplanner/openstreetmap/impl/OpenStreetMapParser.java
  src/main/java/org/opentripplanner/openstreetmap/impl/StreamedFileBasedOpenStreetMapProviderImpl.java
  src/main/java/org/opentripplanner/openstreetmap/impl/StreamedOpenStreetMapParser.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMMap.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWay.java
  src/main/java/org/opentripplanner/openstreetmap/services/OpenStreetMapContentHandler.java
  src/main/java/org/opentripplanner/openstreetmap/services/OpenStreetMapProvider.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/graph_builder/module/FakeGraph.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapParserTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/PlatformLinkerTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestOpenStreetMapGraphBuilder.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestUnconnectedAreas.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestUnroutable.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TriangleInequalityTest.java
  src/test/resources/org/opentripplanner/graph_builder/module/osm/NYC_small.osm.gz
  src/test/resources/org/opentripplanner/graph_builder/module/osm/NYC_small.osm.pbf
  src/test/resources/org/opentripplanner/graph_builder/module/osm/P+R.osm.gz
  src/test/resources/org/opentripplanner/graph_builder/module/osm/P+R.osm.pbf
  src/test/resources/org/opentripplanner/graph_builder/module/osm/coincident_pr.osm
  src/test/resources/org/opentripplanner/graph_builder/module/osm/coincident_pr.osm.pbf
  src/test/resources/org/opentripplanner/graph_builder/module/osm/coincident_pr_dupl.osm
  src/test/resources/org/opentripplanner/graph_builder/module/osm/coincident_pr_dupl.osm.pbf
  src/test/resources/org/opentripplanner/graph_builder/module/osm/coincident_pr_overlap.osm
  src/test/resources/org/opentripplanner/graph_builder/module/osm/coincident_pr_overlap.osm.pbf
  src/test/resources/org/opentripplanner/graph_builder/module/osm/coincident_pr_reverse.osm
  src/test/resources/org/opentripplanner/graph_builder/module/osm/coincident_pr_reverse.osm.pbf
  src/test/resources/org/opentripplanner/graph_builder/module/osm/hackett_pr.osm.gz
  src/test/resources/org/opentripplanner/graph_builder/module/osm/hackett_pr.osm.pbf
  src/test/resources/org/opentripplanner/graph_builder/module/osm/map.osm.gz
  src/test/resources/org/opentripplanner/graph_builder/module/osm/otp-multipolygon-test.osm
  src/test/resources/org/opentripplanner/graph_builder/module/osm/otp-multipolygon-test.osm.pbf
  src/test/resources/org/opentripplanner/graph_builder/module/osm/usf_area.osm.gz
  src/test/resources/org/opentripplanner/graph_builder/module/osm/usf_area.osm.pbf
Labels: OTP2

#2897 Update TransmodelAPI sandbox feature as code owner (2)
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
Labels: OTP2, sandbox

#2896 Fix stop lookup in dev-2.x fare calculation
  src/main/java/org/opentripplanner/routing/algorithm/raptor/itinerary/ItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/RaptorRouter.java
  src/main/java/org/opentripplanner/routing/bike_rental/TimeBasedBikeRentalFareService.java
  src/main/java/org/opentripplanner/routing/fares/AddingMultipleFareService.java
  src/main/java/org/opentripplanner/routing/impl/DefaultFareServiceImpl.java
  src/main/java/org/opentripplanner/routing/impl/DutchFareServiceImpl.java
  src/main/java/org/opentripplanner/routing/impl/NycFareServiceImpl.java
  src/main/java/org/opentripplanner/routing/impl/Ride.java
  src/main/java/org/opentripplanner/routing/impl/RideMapper.java
  src/main/java/org/opentripplanner/routing/services/FareService.java
  src/test/java/org/opentripplanner/routing/fares/MultipleFareServiceTest.java
Labels: OTP2

#2783 Mark deprecated fields in the RoutingRequest
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/api/resource/PlannerResource.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/AStar.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/RaptorRouter.java
  src/main/java/org/opentripplanner/routing/core/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/core/TraversalRequirements.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
  src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java
  src/test/java/org/opentripplanner/routing/edgetype/TestTriangle.java
Labels: OTP2, Oslo

#2894 Dependency security for dev-2.x
  pom.xml
  src/main/java/org/opentripplanner/graph_builder/module/ned/NEDDownloader.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/NEDGridCoverageFactoryImpl.java
Labels: OTP2

#2900 Ignore trip with unsupported mode and log a DataImportIssue
  docs/Changelog.md
  src/main/java/org/opentripplanner/graph_builder/issues/GTFSModeNotSupported.java
  src/main/java/org/opentripplanner/gtfs/GenerateTripPatternsOperation.java
Labels: OTP2, bug

#2895 Remove Lucene and other dependencies from dev-2.x branch
  pom.xml
  src/main/java/org/opentripplanner/routing/graph/GraphIndex.java
Labels: OTP2

#2898 Health api sandbox extension
  docs/SandboxExtention.md
  docs/sandbox/ActuatorAPI.md
  src/ext/java/org/opentripplanner/ext/readiness_endpoint/ActuatorAPI.java
  src/main/java/org/opentripplanner/api/configuration/APIEndpoints.java
  src/main/java/org/opentripplanner/util/OTPFeature.java
Labels: OTP2, sandbox

#2877 Added option to build a partial graph
  docs/Changelog.md
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/standalone/CommandLineParameters.java
Labels: OTP2
