Repository opentripplanner/OpenTripPlanner, pull requests merged in 2019-10, with the labels that each got.

#2845 Test OSM Serialization
  pom.xml
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/routing/graph/GraphSerializationTest.java
  src/test/resources/logback.xml
  src/test/resources/oslo-east-filtered.osm.pbf
  src/test/resources/portland-central-filtered.osm.pbf
Labels: OTP2

#2842 Otp2 netex siri updater
  docs/SandboxExtention.md
  docs/sandbox/SiriUpdator.md
  pom.xml
  src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java
  src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
  src/ext/java/org/opentripplanner/ext/siri/SiriHttpUtils.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTripPatternCache.java
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
  src/ext/java/org/opentripplanner/ext/siri/updater/EstimatedTimetableSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETHttpTripUpdateSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriHelper.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriVMHttpTripUpdateSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriVMUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/VehicleMonitoringSource.java
  src/main/java/org/opentripplanner/api/adapters/AgencyAndIdAdapter.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/api/model/Leg.java
  src/main/java/org/opentripplanner/api/resource/GraphPathToTripPlanConverter.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/index/IndexGraphQLSchema.java
  src/main/java/org/opentripplanner/model/TimetableSnapshotProvider.java
  src/main/java/org/opentripplanner/routing/alertpatch/Alert.java
  src/main/java/org/opentripplanner/routing/alertpatch/AlertPatch.java
  src/main/java/org/opentripplanner/routing/alertpatch/AlertUrl.java
  src/main/java/org/opentripplanner/routing/alertpatch/StopCondition.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/itinerary/ItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransitLayerMapper.java
  src/main/java/org/opentripplanner/routing/core/RoutingContext.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/routing/graph/GraphIndex.java
  src/main/java/org/opentripplanner/routing/impl/AlertPatchServiceImpl.java
  src/main/java/org/opentripplanner/routing/impl/InputStreamGraphSource.java
  src/main/java/org/opentripplanner/routing/services/AlertPatchService.java
  src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java
  src/main/java/org/opentripplanner/updater/GraphUpdater.java
  src/main/java/org/opentripplanner/updater/GraphUpdaterConfigurator.java
  src/main/java/org/opentripplanner/updater/GraphUpdaterManager.java
  src/main/java/org/opentripplanner/updater/PollingGraphUpdater.java
  src/main/java/org/opentripplanner/updater/alerts/AlertsUpdateHandler.java
  src/main/java/org/opentripplanner/updater/stoptime/PollingStoptimeUpdater.java
  src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
  src/main/java/org/opentripplanner/updater/stoptime/TripUpdateGraphWriterRunnable.java
  src/main/java/org/opentripplanner/updater/stoptime/WebsocketGtfsRealtimeUpdater.java
  src/main/java/org/opentripplanner/util/I18NString.java
  src/test/java/org/opentripplanner/GtfsTest.java
  src/test/java/org/opentripplanner/routing/core/SimpleTraversalCostModelTest.java
  src/test/java/org/opentripplanner/routing/core/TestIgnoreRealtimeUpdates.java
  src/test/java/org/opentripplanner/routing/edgetype/PlainStreetEdgeTest.java
  src/test/java/org/opentripplanner/routing/edgetype/loader/TestPatternHopFactory.java
  src/test/java/org/opentripplanner/routing/graph/GraphAlertPatchTest.java
  src/test/java/org/opentripplanner/routing/graph/GraphTest.java
  src/test/java/org/opentripplanner/routing/impl/AlertPatchServiceImplTest.java
  src/test/java/org/opentripplanner/routing/vertextype/IntersectionVertexTest.java
  src/test/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSourceTest.java
  src/test/java/org/opentripplanner/updater/stoptime/TripUpdateGraphWriterRunnableTest.java
Labels: OTP2, Oslo, WIP DO NOT MERGE

#2789 Raptor router bugfix - prevent cleaning up temporary edges twice
  src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/AccessEgressRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/Transfer.java
  src/main/java/org/opentripplanner/routing/core/RoutingRequest.java
Labels: OTP2, Oslo, bug

#2837 Realtime improvements for dev-2.x
  src/main/java/org/opentripplanner/routing/alertpatch/AlertPatch.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/RaptorTransitLayerGraphUpdater.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransitLayerMapper.java
  src/main/java/org/opentripplanner/routing/edgetype/TimetableSnapshot.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/standalone/Router.java
  src/main/java/org/opentripplanner/updater/GraphUpdaterConfigurator.java
  src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
  src/main/java/org/opentripplanner/updater/stoptime/TripPatternCache.java
Labels: OTP2

#2847 Remove multi-router system
  src/main/java/org/opentripplanner/api/configuration/APIEndpoints.java
  src/main/java/org/opentripplanner/api/resource/Routers.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/linking/TransitToStreetNetworkModule.java
  src/main/java/org/opentripplanner/graph_builder/module/PruneFloatingIslands.java
  src/main/java/org/opentripplanner/graph_builder/module/TransitStopsRegionsSourceImpl.java
  src/main/java/org/opentripplanner/openstreetmap/services/RegionsSource.java
  src/main/java/org/opentripplanner/routing/impl/GraphLoader.java
  src/main/java/org/opentripplanner/routing/impl/GraphScanner.java
  src/main/java/org/opentripplanner/routing/impl/InputStreamGraphSource.java
  src/main/java/org/opentripplanner/routing/impl/MemoryGraphSource.java
  src/main/java/org/opentripplanner/routing/services/GraphRefreshListener.java
  src/main/java/org/opentripplanner/routing/services/GraphService.java
  src/main/java/org/opentripplanner/routing/services/GraphSource.java
  src/main/java/org/opentripplanner/standalone/CommandLineParameters.java
  src/main/java/org/opentripplanner/standalone/GrizzlyServer.java
  src/main/java/org/opentripplanner/standalone/OTPAppConstruction.java
  src/main/java/org/opentripplanner/standalone/OTPMain.java
  src/main/java/org/opentripplanner/standalone/OTPServer.java
  src/main/java/org/opentripplanner/standalone/Router.java
  src/main/java/org/opentripplanner/standalone/config/OTPConfiguration.java
  src/main/java/org/opentripplanner/util/OTPFeature.java
  src/main/java/org/opentripplanner/util/ThrowableUtils.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/GtfsTest.java
  src/test/java/org/opentripplanner/api/resource/RoutersTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestIntermediatePlaces.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestOpenStreetMapGraphBuilder.java
  src/test/java/org/opentripplanner/routing/impl/GraphServiceTest.java
Labels: OTP2, Oslo

#2852 Fix: Netex import fails when Flex Lines exist in zip file. Closes #2851
  src/main/java/org/opentripplanner/netex/loader/mapping/StopTimesMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/TripMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/TripPatternMapper.java
  src/main/java/org/opentripplanner/netex/loader/parser/NetexDocumentParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/NetexParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/ServiceFrameParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/SiteFrameParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/TimeTableFrameParser.java
  src/main/java/org/opentripplanner/netex/support/DayTypeRefToServiceIdMapper.java
  src/main/java/org/opentripplanner/netex/support/DayTypeRefsToServiceIdAdapter.java
  src/test/java/org/opentripplanner/netex/loader/mapping/CalendarMapperTest.java
  src/test/java/org/opentripplanner/netex/loader/mapping/NetexTestDataSample.java
  src/test/java/org/opentripplanner/netex/loader/mapping/StopTimesMapperTest.java
  src/test/java/org/opentripplanner/netex/loader/mapping/TripMapperTest.java
  src/test/java/org/opentripplanner/netex/loader/mapping/TripPatternMapperTest.java
  src/test/java/org/opentripplanner/netex/loader/mapping/TripPatternStructure.java
Labels: OTP2

#2858 Refactor StreetWithElevationEdge and use effectiveDistance for transfers
  docs/Changelog.md
  src/main/java/org/opentripplanner/api/resource/GraphPathToTripPlanConverter.java
  src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
  src/main/java/org/opentripplanner/index/IndexAPI.java
  src/main/java/org/opentripplanner/index/IndexGraphQLSchema.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/AccessEgressRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/TransferToAccessEgressLegMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/Transfer.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransfersMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/TransferWithDuration.java
  src/main/java/org/opentripplanner/routing/core/RoutingContext.java
  src/main/java/org/opentripplanner/routing/core/StateEditor.java
  src/main/java/org/opentripplanner/routing/edgetype/BikeParkEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/ElevatorAlightEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/ElevatorBoardEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/ElevatorHopEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/FreeEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/LegSwitchingEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/ParkAndRideEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/PathwayEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/RentABikeAbstractEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/SimpleTransfer.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetBikeParkLink.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetBikeRentalLink.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetWithElevationEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/TemporaryPartialStreetEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/TimedTransferEdge.java
  src/main/java/org/opentripplanner/routing/graph/Edge.java
  src/main/java/org/opentripplanner/routing/impl/StreetVertexIndexServiceImpl.java
  src/main/java/org/opentripplanner/routing/spt/SPTWalker.java
  src/test/java/org/opentripplanner/graph_builder/module/linking/LinkingTest.java
  src/test/java/org/opentripplanner/graph_builder/module/map/TestStreetMatcher.java
  src/test/java/org/opentripplanner/routing/edgetype/PlainStreetEdgeTest.java
  src/test/java/org/opentripplanner/routing/edgetype/TemporaryPartialStreetEdgeTest.java
  src/test/java/org/opentripplanner/routing/edgetype/TestTriangle.java
  src/test/java/org/opentripplanner/routing/graph/SimpleConcreteEdge.java
  src/test/java/org/opentripplanner/routing/graph/TemporaryConcreteEdge.java
Labels: OTP2
