Repository opentripplanner/OpenTripPlanner, pull requests merged in 2020-05, with the labels that each got.

#3058 Remove Slack notifications from 2.x
  .travis.yml
Labels: OTP2

#3066 Small improvements to the configuration loading.
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/kryo/BuildConfigSerializer.java
  src/main/java/org/opentripplanner/kryo/RouterConfigSerializer.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/main/java/org/opentripplanner/standalone/config/ConfigLoader.java
  src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
  src/main/java/org/opentripplanner/standalone/config/OtpConfig.java
  src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
  src/main/java/org/opentripplanner/standalone/config/TransitRoutingConfig.java
  src/test/java/org/opentripplanner/standalone/config/BuildConfigTest.java
Labels: OTP2, improvement

#3065 Fixed type checked by contains-method
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
Labels: OTP2, bug

#2990 Elevation calculation speed-up
  docs/Changelog.md
  docs/Configuration.md
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/DegreeGridNEDTileSource.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/GeotiffGridCoverageFactoryImpl.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/NEDDownloader.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/NEDGridCoverageFactoryImpl.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/UnifiedGridCoverage.java
  src/main/java/org/opentripplanner/graph_builder/services/ned/ElevationGridCoverageFactory.java
  src/main/java/org/opentripplanner/graph_builder/services/ned/NEDTileSource.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetWithElevationEdge.java
  src/main/java/org/opentripplanner/standalone/GraphBuilderParameters.java
  src/main/java/org/opentripplanner/util/ElevationUtils.java
  src/test/java/org/opentripplanner/graph_builder/module/ElevationModuleTest.java
Labels: OTP1

#3059 Update outdated documentation links
  README.md
Labels: OTP1, OTP2, documentation

#3072 Prevent duplicate stop times entries caused by realtime updates
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/routing/graph/GraphIndex.java
Labels: OTP2, bug

#3067 Otp2 port of elevation improvements
  docs/Configuration.md
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/DegreeGridNEDTileSource.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/GeotiffGridCoverageFactoryImpl.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/NEDGridCoverageFactoryImpl.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/UnifiedGridCoverage.java
  src/main/java/org/opentripplanner/graph_builder/services/ned/ElevationGridCoverageFactory.java
  src/main/java/org/opentripplanner/graph_builder/services/ned/NEDTileSource.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetWithElevationEdge.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/main/java/org/opentripplanner/util/ElevationUtils.java
  src/test/java/org/opentripplanner/graph_builder/module/ElevationModuleTest.java
Labels: OTP2, optimization

#3063 Generalize kiss and ride mode as car_pickup mode
  docs/Changelog.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/DefaultRoutingRequest.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/main/java/org/opentripplanner/graph_builder/linking/SimpleStreetSplitter.java
  src/main/java/org/opentripplanner/routing/core/CarPickupState.java
  src/main/java/org/opentripplanner/routing/core/State.java
  src/main/java/org/opentripplanner/routing/core/StateData.java
  src/main/java/org/opentripplanner/routing/core/StateEditor.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java
  src/main/java/org/opentripplanner/routing/edgetype/TransitEntranceLink.java
  src/main/java/org/opentripplanner/routing/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/request/StreetMode.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
Labels: Entur, OTP2

#3077 Otp2 fix debug filter error
  docs/Configuration.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
  src/main/java/org/opentripplanner/api/mapping/TripSearchMetadataMapper.java
  src/main/java/org/opentripplanner/api/model/ApiTripSearchMetadata.java
  src/main/java/org/opentripplanner/model/base/ToStringBuilder.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/DebugFilterChain.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/DebugFilterWrapper.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/GroupByFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/LatestDepartureTimeFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/LongTransitWalkingFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/MaxLimitFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/OtpDefaultSortOrder.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/SortOnWalkingArrivalAndDeparture.java
  src/main/java/org/opentripplanner/routing/api/response/TripSearchMetadata.java
  src/test/java/org/opentripplanner/model/base/ToStringBuilderTest.java
  src/test/java/org/opentripplanner/model/routing/TripSearchMetadataTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/FilterChainTestData.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainBuilderTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/GroupByFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/MaxLimitFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/OtpDefaultSortOrderTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/SortOnWalkingArrivalAndDepartureTest.java
Labels: OTP2, Regression, bug
