Repository opentripplanner/OpenTripPlanner, pull requests merged in 2020-09, with the labels that each got.

#3159 Transmodel API changes
  docs/OTP2-MigrationGuide.md
  src/client/js/otp/modules/planner/PlannerModule.js
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/TransportModeSlack.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayAtDistanceType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/core/BicycleOptimizeType.java
  src/main/java/org/opentripplanner/updater/bike_rental/BCycleBikeRentalDataSource.java
  src/main/java/org/opentripplanner/updater/bike_rental/CitiBikeNycBikeRentalDataSource.java
  src/main/java/org/opentripplanner/updater/bike_rental/GbfsBikeRentalDataSource.java
  src/main/java/org/opentripplanner/updater/bike_rental/SanFranciscoBayAreaBikeRentalDataSource.java
  src/main/java/org/opentripplanner/updater/bike_rental/ShareBikeRentalDataSource.java
  src/main/java/org/opentripplanner/updater/bike_rental/UIPBikeRentalDataSource.java
  src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java
  src/test/java/org/opentripplanner/routing/edgetype/TestTriangle.java
  src/test/java/org/opentripplanner/routing/edgetype/loader/TestGeometryAndBlockProcessor.java
Labels: Entur, OTP2, sandbox

#3164 Otp2 remove legswitch and cleanup unused Astar code
  src/main/java/org/opentripplanner/api/mapping/TraverseModeMapper.java
  src/main/java/org/opentripplanner/graph_builder/module/CheckGeometryModule.java
  src/main/java/org/opentripplanner/model/plan/ItinerariesCalculateLegTotals.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/core/TraverseMode.java
  src/main/java/org/opentripplanner/routing/edgetype/BikeParkEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/DummyableEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/DwellEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/HopEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/LegSwitchingEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/ParkAndRideEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/SampleEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java
  src/main/java/org/opentripplanner/routing/edgetype/TimedTransferEdge.java
  src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
  src/main/java/org/opentripplanner/routing/vertextype/SampleVertex.java
  src/main/java/org/opentripplanner/routing/vertextype/TransitStopVertex.java
Labels: OTP2

#3161 Change the itinerary filter order
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLLegImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/TripTimeShortHelper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/ServiceJourneyType.java
  src/main/java/org/opentripplanner/api/mapping/LegMapper.java
  src/main/java/org/opentripplanner/model/base/ToStringBuilder.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/FilterChainParameters.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/AlertToLegMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/test/java/org/opentripplanner/model/base/ToStringBuilderTest.java
  src/test/java/org/opentripplanner/model/plan/ItineraryTest.java
  src/test/java/org/opentripplanner/model/plan/LegTest.java
  src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainBuilderTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/GroupByFilterTest.java
  src/test/java/org/opentripplanner/routing/edgetype/PatternInterlineDwellTest.java
Labels: OTP2, improvement

#3174 Otp2 filter generalized cost
  docs/Changelog.md
  docs/Configuration.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/scalars/DoubleFunctionScalarFactory.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/support/GqlUtil.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/FilterChainParameters.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/GroupBySimilarity.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/TransitGeneralizedCostFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RoutingRequestToFilterChainMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RoutingRequestToFilterChainParametersMapper.java
  src/main/java/org/opentripplanner/routing/api/request/RequestFunctions.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/TransitGeneralizedCostFilterTest.java
  src/test/java/org/opentripplanner/routing/api/request/RequestFunctionsTest.java
  src/test/java/org/opentripplanner/standalone/config/NodeAdapterTest.java
Labels: Entur, OTP2

#3179 Add searchWindow query parameter to legacy GraphQL API
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
Labels: OTP2

#3188 docs - Adding a section on "OTP Trip planning and Transit index APIs"
  docs/Configuration.md
  docs/SandboxExtension.md
  docs/Version-Comparison.md
  docs/sandbox/TransmodelApi.md
  mkdocs.yml
Labels: OTP2, documentation

#3186 Parse additionalNetworks in NeTEx import
  src/main/java/org/opentripplanner/netex/loader/parser/ServiceFrameParser.java
Labels: Entur, OTP2, bug

#3189 Otp2 add architecture doc
  ARCHITECTURE.md
  docs/Developers-Guide.md
  src/main/java/org/opentripplanner/api/package-info.java
  src/main/java/org/opentripplanner/api/package.md
  src/main/java/org/opentripplanner/gtfs/package-info.java
  src/main/java/org/opentripplanner/gtfs/package.md
  src/main/java/org/opentripplanner/standalone/config/package-info.java
  src/main/java/org/opentripplanner/standalone/config/package.md
  src/main/java/org/opentripplanner/transit/raptor/package-info.java
  src/main/java/org/opentripplanner/transit/raptor/package.md
  src/test/java/org/opentripplanner/transit/raptor/speed_test/package-info.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/package.md
Labels: OTP2, documentation

#3187 Add support for flexible transit routing
  docs/sandbox/Flex.md
  src/ext/java/org/opentripplanner/ext/flex/Flex.svg
  src/ext/java/org/opentripplanner/ext/flex/FlexAccessEgress.java
  src/ext/java/org/opentripplanner/ext/flex/FlexLegMapper.java
  src/ext/java/org/opentripplanner/ext/flex/FlexLocationsToStreetEdgesMapper.java
  src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
  src/ext/java/org/opentripplanner/ext/flex/FlexServiceDate.java
  src/ext/java/org/opentripplanner/ext/flex/FlexTripsMapper.java
  src/ext/java/org/opentripplanner/ext/flex/README.md
  src/ext/java/org/opentripplanner/ext/flex/edgetype/FlexTripEdge.java
  src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/DirectFlexPathCalculator.java
  src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/FlexPath.java
  src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/FlexPathCalculator.java
  src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/ScheduledFlexPathCalculator.java
  src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/StreetFlexPathCalculator.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessEgressTemplate.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessTemplate.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexEgressTemplate.java
  src/ext/java/org/opentripplanner/ext/flex/trip/FlexTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLNodeTypeResolver.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLstopAtDistanceImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/graphql-codegen.yml
  src/ext/java/org/opentripplanner/ext/transferanalyzer/DirectTransferAnalyzer.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayAtDistanceType.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/api/parameter/ApiRequestMode.java
  src/main/java/org/opentripplanner/api/parameter/QualifiedModeSet.java
  src/main/java/org/opentripplanner/graph_builder/linking/SimpleStreetSplitter.java
  src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/model/SimpleTransfer.java
  src/main/java/org/opentripplanner/model/StopTime.java
  src/main/java/org/opentripplanner/model/TransitMode.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/AccessEgressRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/FlexAccessEgressAdapter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/AccessEgressMapper.java
  src/main/java/org/opentripplanner/routing/core/StateEditor.java
  src/main/java/org/opentripplanner/routing/graphfinder/DirectGraphFinder.java
  src/main/java/org/opentripplanner/routing/graphfinder/GraphFinder.java
  src/main/java/org/opentripplanner/routing/graphfinder/NearbyStop.java
  src/main/java/org/opentripplanner/routing/graphfinder/StopFinderTraverseVisitor.java
  src/main/java/org/opentripplanner/routing/graphfinder/StreetGraphFinder.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/transit/EgressAccessRouter.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/transit/ItineraryMapper.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/transit/StreetSearch.java
Labels: OTP2, new feature

#3172 Missing transmodel queries
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/PlaceMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/TransitIdMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/TransmodelMappingUtil.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/DefaultRoutingRequestType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/PlaceAtDistanceType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/PlaceInterfaceType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
  src/main/java/org/opentripplanner/routing/bike_rental/BikeRentalStationService.java
Labels: Entur, OTP2, sandbox

#3166 Re-implementation of SIRI support
  pom.xml
  src/ext-test/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandlerTest.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java
  src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriEstimatedTimetableGooglePubsubUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriVMHttpTripUpdateSource.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/sx/PtSituationElementType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
  src/main/java/org/opentripplanner/index/IndexAPI.java
  src/main/java/org/opentripplanner/model/TripPattern.java
  src/main/java/org/opentripplanner/routing/RoutingService.java
  src/main/java/org/opentripplanner/routing/StopTimesHelper.java
  src/main/java/org/opentripplanner/routing/alertpatch/TransitAlert.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/AlertToLegMapper.java
  src/main/java/org/opentripplanner/standalone/config/DefaultUpdaterDataSourceConfig.java
  src/main/java/org/opentripplanner/standalone/config/UpdaterConfig.java
  src/main/java/org/opentripplanner/standalone/config/updaters/GooglePubsubSiriETUpdaterParameters.java
  src/main/java/org/opentripplanner/updater/GraphUpdaterConfigurator.java
  src/main/java/org/opentripplanner/updater/UpdaterParameters.java
  src/main/java/org/opentripplanner/util/HttpUtils.java
Labels: Entur, OTP2, sandbox
