Repository opentripplanner/OpenTripPlanner, pull requests merged in 2020-02, with the labels that each got.

#2945 Add a disclaimer to the fron page of the docs.
  docs/index.md
Labels: OTP2, documentation

#2932 SW_1 - Implement dynamic computation of EDT, LAT and SearchWindow.
  docs/Changelog.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/RaptorRouter.java
  src/main/java/org/opentripplanner/routing/core/RoutingRequest.java
  src/main/java/org/opentripplanner/transit/raptor/RaptorService.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/ArrivalAndDeparturePreference.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/DynamicSearchWindowCoefficients.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/RaptorRequest.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/RaptorRequestBuilder.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/RaptorTuningParameters.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/SearchParams.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/SearchParamsBuilder.java
  src/main/java/org/opentripplanner/transit/raptor/api/response/RaptorResponse.java
  src/main/java/org/opentripplanner/transit/raptor/api/view/Heuristics.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/configure/RaptorConfig.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/heuristics/HeuristicSearch.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/heuristics/HeuristicsAdapter.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/ForwardSearchTransitCalculator.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/RaptorSearchWindowCalculator.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/ReverseSearchTransitCalculator.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/TransitCalculator.java
  src/main/java/org/opentripplanner/transit/raptor/service/DestinationNotReachedException.java
  src/main/java/org/opentripplanner/transit/raptor/service/HeuristicSearchTask.java
  src/main/java/org/opentripplanner/transit/raptor/service/HeuristicToRunResolver.java
  src/main/java/org/opentripplanner/transit/raptor/service/RangRaptorDynamicSearch.java
  src/main/java/org/opentripplanner/transit/raptor/service/RequestAlias.java
  src/main/java/org/opentripplanner/transit/raptor/util/TimeUtils.java
  src/test/java/org/opentripplanner/transit/raptor/rangeraptor/transit/ForwardSearchTransitCalculatorTest.java
  src/test/java/org/opentripplanner/transit/raptor/rangeraptor/transit/RaptorSearchWindowCalculatorTest.java
  src/test/java/org/opentripplanner/transit/raptor/service/HeuristicToRunResolverTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/ResultPrinter.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTestRequest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/api/model/TripPlan.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/testcase/Result.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/testcase/TestCase.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/transit/TripPlanSupport.java
  src/test/java/org/opentripplanner/transit/raptor/util/TimeUtilsTest.java
Labels: Entur, OTP2, Regression

#2942 SW_3 - Otp2 support for paging results
  docs/Basic-Tutorial.md
  docs/Changelog.md
  docs/OTP2-MigrationGuide.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/PlanResponse.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/api/model/ApiTripSearchMetadata.java
  src/main/java/org/opentripplanner/api/model/TripPlan.java
  src/main/java/org/opentripplanner/api/resource/PlannerResource.java
  src/main/java/org/opentripplanner/api/resource/Response.java
  src/main/java/org/opentripplanner/model/routing/RoutingResponse.java
  src/main/java/org/opentripplanner/model/routing/TripSearchMetadata.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/TripPlanMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/AccessEgressRouter.java
  src/main/java/org/opentripplanner/routing/core/RoutingRequest.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/DynamicSearchWindowCoefficients.java
Labels: Entur, OTP2, improvement

#2944 SW_4 - Otp2 enable max transfer distance
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/core/RoutingRequest.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/SearchParams.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/SearchParamsBuilder.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/SearchContext.java
Labels: Entur, OTP2, Regression, bug

#2947 Add links to master, 1.x and 2.x documentation on the front page
  docs/index.md
Labels: documentation

#2949 Remove stopIndex being incremented in GraphPathToTripPlanConverter. T…
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
Labels: Entur, OTP2, bug

#2964 Do not throw NPE if linestring is null in CompactLineString
  src/main/java/org/opentripplanner/common/geometry/CompactLineString.java
  src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryAndBlockProcessor.java
Labels: OTP2, Regression, bug

#2972 Otp2 transmodel changes
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
Labels: Entur, OTP2, sandbox

#2969 Optimize copying of states to the next round
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/Stops.java
  src/main/java/org/opentripplanner/transit/raptor/util/paretoset/ParetoSet.java
  src/main/java/org/opentripplanner/transit/raptor/util/paretoset/ParetoSetWithMarker.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTestRequest.java
  src/test/java/org/opentripplanner/transit/raptor/util/paretoset/ParetoSetWithMarkerTest.java
Labels: Entur, OTP2, optimization

#2970 FL_2 - Otp2 filter results - clean code 2
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
  src/main/java/org/opentripplanner/api/mapping/ItineraryMapper.java
  src/main/java/org/opentripplanner/api/mapping/LegMapper.java
  src/main/java/org/opentripplanner/api/model/ApiLeg.java
  src/main/java/org/opentripplanner/api/resource/PlannerResource.java
  src/main/java/org/opentripplanner/model/plan/ItinerariesCalculateLegTotals.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/model/plan/Place.java
  src/main/java/org/opentripplanner/model/plan/WalkStep.java
  src/main/java/org/opentripplanner/routing/algorithm/ItineraryFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/itineraryfilters/FilterAwayLongWalkingTransit.java
  src/main/java/org/opentripplanner/routing/algorithm/itineraryfilters/ItineraryFilterChain.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/ItinerariesHelper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/core/TraverseMode.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/SearchParamsBuilder.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestIntermediatePlaces.java
  src/test/java/org/opentripplanner/model/plan/ItineraryTest.java
  src/test/java/org/opentripplanner/model/plan/ItineraryTestData.java
  src/test/java/org/opentripplanner/routing/edgetype/PatternInterlineDwellTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/api/model/AbsoluteDirection.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/api/model/Itinerary.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/api/model/Leg.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/api/model/RelativeDirection.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/api/model/TraverseMode.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/api/model/WalkStep.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/testcase/Result.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/testcase/TableTestReport.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/transit/ItineraryMapper.java
Labels: Entur, OTP2, improvement

#2963 Otp2 negative wait times fix
  docs/Changelog.md
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
Labels: OTP2, bug

#2922 Make the TransitLayerMapper multi-threaded to decrease startup time.
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransitLayerMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TripPatternForDateMapper.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/routing/graph/GraphIndex.java
Labels: OTP2, optimization

#2974 bug #2968 NullPointer
  src/main/java/org/opentripplanner/index/model/StopShort.java
Labels: OTP2, bug

#2975 Otp2 speed test add options
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTestRequest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/options/SpeedTestCmdLineOpts.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/options/SpeedTestConfig.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/testcase/Place.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/transit/StreetSearch.java
  src/test/resources/raptor/speedtest/norway/README.md
  src/test/resources/raptor/speedtest/norway/speed-test-config.json
Labels: Entur, OTP2, improvement

#2971 FL_3 - Otp2 filter results - Filter chain, walk/wait reluctance, debug
  src/client/js/otp/modules/planner/ItinerariesWidget.js
  src/client/style.css
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/api/mapping/ItineraryMapper.java
  src/main/java/org/opentripplanner/api/model/ApiItinerary.java
  src/main/java/org/opentripplanner/model/plan/ItinerariesCalculateLegTotals.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/model/plan/Place.java
  src/main/java/org/opentripplanner/model/plan/WalkStep.java
  src/main/java/org/opentripplanner/routing/algorithm/ItineraryFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/DebugFilterChain.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/FilterChain.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/GroupByFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/LatestDepartureTimeFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/LongTransitWalkingFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/MaxLimitFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/SortOnGeneralizedCost.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/SortOnWalkingArrivalAndDeparture.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/groupids/GroupByLongestLegsId.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/groupids/GroupId.java
  src/main/java/org/opentripplanner/routing/algorithm/itineraryfilters/FilterAwayLongWalkingTransit.java
  src/main/java/org/opentripplanner/routing/algorithm/itineraryfilters/ItineraryFilterChain.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/TransferToAccessEgressLegMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/RaptorRequestMapper.java
  src/main/java/org/opentripplanner/routing/core/RoutingRequest.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/McCostParams.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/RaptorRequest.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/ForwardPathMapper.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/ReversePathMapper.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/CostCalculator.java
  src/main/java/org/opentripplanner/transit/raptor/service/HeuristicSearchTask.java
  src/main/java/org/opentripplanner/transit/raptor/service/RangRaptorDynamicSearch.java
  src/main/java/org/opentripplanner/util/CoordinateUtils.java
  src/test/java/org/opentripplanner/model/plan/PlaceTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/FilterChainTestData.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainBuilderTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/GroupByFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/LatestDepartureTimeFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/LongTransitWalkingFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/MaxLimitFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/SortOnGeneralizedCostTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/SortOnWalkingArrivalAndDepartureTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/groupids/GroupByLongestLegsIdTest.java
  src/test/java/org/opentripplanner/transit/raptor/_shared/Access.java
  src/test/java/org/opentripplanner/transit/raptor/_shared/Bus.java
  src/test/java/org/opentripplanner/transit/raptor/_shared/Egress.java
  src/test/java/org/opentripplanner/transit/raptor/_shared/StopArrivalsTestData.java
  src/test/java/org/opentripplanner/transit/raptor/_shared/Walk.java
  src/test/java/org/opentripplanner/transit/raptor/api/path/PathTest.java
  src/test/java/org/opentripplanner/transit/raptor/rangeraptor/transit/CostCalculatorTest.java
  src/test/java/org/opentripplanner/util/CoordinateUtilsTest.java
Labels: Entur, OTP2, Regression, new feature

#2976 Bugfix on dynamic search-window
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/DebugFilterChain.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/RaptorRequest.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/RaptorRequestBuilder.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/SearchDirection.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/configure/RaptorConfig.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/SearchContext.java
  src/main/java/org/opentripplanner/transit/raptor/service/DebugHeuristics.java
  src/main/java/org/opentripplanner/transit/raptor/service/HeuristicSearchTask.java
  src/main/java/org/opentripplanner/transit/raptor/service/RangRaptorDynamicSearch.java
  src/main/java/org/opentripplanner/transit/raptor/service/RaptorSearchWindowCalculator.java
  src/main/java/org/opentripplanner/transit/raptor/service/RequestAlias.java
  src/test/java/org/opentripplanner/transit/raptor/service/RaptorSearchWindowCalculatorTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTestProfile.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTestRequest.java
Labels: Entur, OTP2, bug

#2978 Transmodel API - Change searchWindow unit minutes not seconds
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
  src/main/java/org/opentripplanner/api/mapping/TripSearchMetadataMapper.java
  src/main/java/org/opentripplanner/api/model/ApiTripSearchMetadata.java
  src/main/java/org/opentripplanner/model/routing/TripSearchMetadata.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/core/RoutingRequest.java
Labels: Entur, OTP2, bug, sandbox

#2959 Keep an index of realtime patternsForStop in the TimetableSnapshot.
  docs/Changelog.md
  pom.xml
  src/ext-test/java/org/opentripplanner/ext/examples/statistics/api/resource/GraphStatisticsResourceTest.java
  src/ext/java/org/opentripplanner/ext/examples/statistics/api/model/GraphStatistics.java
  src/ext/java/org/opentripplanner/ext/examples/statistics/api/model/StatisticsGraphQLSchemaFactory.java
  src/ext/java/org/opentripplanner/ext/examples/statistics/api/resource/GraphStatisticsResource.java
  src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTripPatternCache.java
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriVMUpdater.java
  src/ext/java/org/opentripplanner/ext/transferanalyzer/DirectTransferAnalyzer.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphIndex.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelRequestContext.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/TransmodelMappingUtil.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/TripTimeShortHelper.java
  src/main/java/org/opentripplanner/api/resource/PlannerResource.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryAndBlockProcessor.java
  src/main/java/org/opentripplanner/graph_builder/module/map/BusRouteStreetMatcher.java
  src/main/java/org/opentripplanner/index/IndexAPI.java
  src/main/java/org/opentripplanner/index/IndexGraphQLSchema.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/routing/RoutingService.java
  src/main/java/org/opentripplanner/routing/StopFinder.java
  src/main/java/org/opentripplanner/routing/StopTimesHelper.java
  src/main/java/org/opentripplanner/routing/TripTimesShortHelper.java
  src/main/java/org/opentripplanner/routing/alertpatch/AlertPatch.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/AlertToLegMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransitLayerMapper.java
  src/main/java/org/opentripplanner/routing/core/ServiceDay.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/routing/graph/GraphIndex.java
  src/main/java/org/opentripplanner/routing/impl/AlertPatchServiceImpl.java
  src/main/java/org/opentripplanner/routing/impl/StreetVertexIndex.java
  src/main/java/org/opentripplanner/routing/vertextype/TransitStopVertex.java
  src/main/java/org/opentripplanner/updater/GtfsRealtimeFuzzyTripMatcher.java
  src/main/java/org/opentripplanner/updater/alerts/GtfsRealtimeAlertsUpdater.java
  src/main/java/org/opentripplanner/updater/stoptime/PollingStoptimeUpdater.java
  src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
  src/main/java/org/opentripplanner/updater/stoptime/TripPatternCache.java
  src/test/java/org/opentripplanner/graph_builder/module/GtfsGraphBuilderModuleTest.java
  src/test/java/org/opentripplanner/routing/core/StateEditorTest.java
  src/test/java/org/opentripplanner/routing/graph/GraphIndexTest.java
  src/test/java/org/opentripplanner/routing/graph/RoutingServiceTest.java
  src/test/java/org/opentripplanner/updater/GtfsRealtimeFuzzyTripMatcherTest.java
  src/test/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSourceTest.java
Labels: Entur, OTP2

#2983 Otp2 api place field mapping bug
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
  src/main/java/org/opentripplanner/api/mapping/LegMapper.java
  src/main/java/org/opentripplanner/api/mapping/PlaceMapper.java
  src/main/java/org/opentripplanner/api/mapping/TripPlanMapper.java
  src/main/java/org/opentripplanner/api/resource/PlannerResource.java
  src/main/java/org/opentripplanner/model/base/ToStringBuilder.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/model/plan/Place.java
  src/main/java/org/opentripplanner/model/plan/StopArrival.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/AlertToLegMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/ItinerariesHelper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/arrivals/AbstractStopArrival.java
  src/main/java/org/opentripplanner/transit/raptor/util/TimeUtils.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestIntermediatePlaces.java
  src/test/java/org/opentripplanner/model/base/ToStringBuilderTest.java
  src/test/java/org/opentripplanner/transit/raptor/util/TimeUtilsTest.java
Labels: OTP2, Regression, bug

#2980 NeTEx import: Do not add ServiceJourney if any StopPoints are not found
  src/main/java/org/opentripplanner/netex/loader/mapping/StopTimesMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/TripPatternMapper.java
Labels: Entur, OTP2, bug

#2984 Use Raptor calculation of leg start/end times
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
Labels: Entur, OTP2, bug
