Repository opentripplanner/OpenTripPlanner, pull requests merged in 2020-01, with the labels that each got.

#2917 add links to google groups in README
  README.md
Labels: OTP2

#2920 Otp2 move raptor into otp - cleanup speed test (part 2)
  src/main/java/org/opentripplanner/transit/raptor/api/debug/DebugEvent.java
  src/main/java/org/opentripplanner/transit/raptor/api/path/AccessPathLeg.java
  src/main/java/org/opentripplanner/transit/raptor/api/path/EgressPathLeg.java
  src/main/java/org/opentripplanner/transit/raptor/api/path/IntermediatePathLeg.java
  src/main/java/org/opentripplanner/transit/raptor/api/path/Path.java
  src/main/java/org/opentripplanner/transit/raptor/api/path/PathLeg.java
  src/main/java/org/opentripplanner/transit/raptor/api/path/TransferPathLeg.java
  src/main/java/org/opentripplanner/transit/raptor/api/path/TransitPathLeg.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/DebugRequest.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/DebugRequestBuilder.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/McCostParams.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/McCostParamsBuilder.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/Optimization.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/RangeRaptorProfile.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/RangeRaptorRequest.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/RequestBuilder.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/SearchParams.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/SearchParamsBuilder.java
  src/main/java/org/opentripplanner/transit/raptor/api/view/ArrivalView.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/TransitRoutingStrategy.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/debug/DebugHandlerPathAdapter.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/debug/DebugHandlerStopArrivalAdapter.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/debug/ParetoSetDebugHandlerAdapter.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/StopArrivalParetoSet.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/arrivals/AbstractStopArrival.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/DestinationArrivalPaths.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/ForwardPathMapper.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/PathMapper.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/ReversePathMapper.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/configure/StdRangeRaptorConfig.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/debug/DebugStopArrivalsState.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/heuristics/HeuristicSearch.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/stoparrivals/EgressStopArrivalState.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/stoparrivals/view/StopArrivalViewAdapter.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/stoparrivals/view/StopsCursor.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/SearchContext.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/TransitCalculator.java
  src/main/java/org/opentripplanner/transit/raptor/service/DebugHeuristics.java
  src/main/java/org/opentripplanner/transit/raptor/util/AvgTimer.java
  src/main/java/org/opentripplanner/transit/raptor/util/CompareIntArrays.java
  src/main/java/org/opentripplanner/transit/raptor/util/PathStringBuilder.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/ResultPrinter.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTestDebugLogger.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTestProfile.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTestRequest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/api/model/Leg.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/api/model/TraverseMode.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/cli/SpeedTestCmdLineOpts.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/testcase/CsvFileIO.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/testcase/ItineraryResultMapper.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/testcase/Result.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/testcase/TableTestReport.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/testcase/TestCase.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/testcase/TestCaseResults.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/testcase/TestStatus.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/transit/EgressAccessRouter.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/transit/ItineraryMapper.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/transit/SpeedTestItinerary.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/transit/StreetSearch.java
Labels: OTP2

#2905 otp2 ds1 refactor app packages
  src/ext/java/org/opentripplanner/ext/examples/statistics/api/resource/GraphStatisticsResource.java
  src/ext/java/org/opentripplanner/ext/readiness_endpoint/ActuatorAPI.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphIndex.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexAPI.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/api/resource/BikeRental.java
  src/main/java/org/opentripplanner/api/resource/GraphInspectorTileResource.java
  src/main/java/org/opentripplanner/api/resource/PlannerResource.java
  src/main/java/org/opentripplanner/api/resource/UpdaterStatusResource.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/index/IndexAPI.java
  src/main/java/org/opentripplanner/netex/configure/NetexConfig.java
  src/main/java/org/opentripplanner/netex/loader/NetexBundle.java
  src/main/java/org/opentripplanner/routing/impl/GraphLoader.java
  src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
  src/main/java/org/opentripplanner/standalone/ConfigurationException.java
  src/main/java/org/opentripplanner/standalone/OTPMain.java
  src/main/java/org/opentripplanner/standalone/config/CommandLineParameters.java
  src/main/java/org/opentripplanner/standalone/config/GraphBuilderParameters.java
  src/main/java/org/opentripplanner/standalone/config/NetexParameters.java
  src/main/java/org/opentripplanner/standalone/config/S3BucketConfig.java
  src/main/java/org/opentripplanner/standalone/configure/OTPAppConstruction.java
  src/main/java/org/opentripplanner/standalone/server/AuthFilter.java
  src/main/java/org/opentripplanner/standalone/server/CorsFilter.java
  src/main/java/org/opentripplanner/standalone/server/GrizzlyServer.java
  src/main/java/org/opentripplanner/standalone/server/OTPApplication.java
  src/main/java/org/opentripplanner/standalone/server/OTPServer.java
  src/main/java/org/opentripplanner/standalone/server/Router.java
  src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/GtfsTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestIntermediatePlaces.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestOpenStreetMapGraphBuilder.java
  src/test/java/org/opentripplanner/standalone/config/GraphBuilderParametersTest.java
  src/test/java/org/opentripplanner/standalone/config/NetexParametersTest.java
Labels: OTP2

#2906 Otp2 ds2 consisten naming
  docs/Configuration.md
  docs/Netex-Norway.md
  src/main/java/org/opentripplanner/graph_builder/DataImportIssuesToHTML.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/EmbedConfig.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/model/GraphBundle.java
  src/main/java/org/opentripplanner/netex/configure/NetexConfig.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
  src/main/java/org/opentripplanner/routing/impl/GraphLoader.java
  src/main/java/org/opentripplanner/standalone/config/CommandLineParameters.java
  src/main/java/org/opentripplanner/standalone/config/GraphBuildParameters.java
  src/main/java/org/opentripplanner/standalone/config/GraphConfig.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/standalone/config/GraphBuildParametersTest.java
Labels: OTP2

#2907 Otp2 ds3 bugfixes logging and reflection lib
  src/main/java/org/opentripplanner/common/LoggingUtil.java
  src/main/java/org/opentripplanner/reflect/ReflectionLibrary.java
  src/test/java/org/opentripplanner/common/LoggingUtilTest.java
Labels: OTP2

#2921 Code cleanup - Number of placeholders does not match number logging args
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/main/java/org/opentripplanner/graph_builder/DataImportIssuesToHTML.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/RaptorRouter.java
  src/main/java/org/opentripplanner/standalone/config/ConfigFile.java
  src/main/java/org/opentripplanner/updater/stoptime/WebsocketGtfsRealtimeUpdater.java
Labels: OTP2

#2882 replace Long objects with Trove
  src/main/java/org/opentripplanner/common/DisjointSet.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/Area.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/AreaGroup.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/Ring.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWay.java
  src/main/java/org/opentripplanner/util/MapUtils.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapParserTest.java
Labels: OTP2

#2909 Otp2 ds5 resolve environment variables
  src/main/java/org/opentripplanner/standalone/config/ConfigLoader.java
  src/main/java/org/opentripplanner/util/EnvironmentVariableReplacer.java
  src/test/java/org/opentripplanner/standalone/config/ConfigLoaderTest.java
  src/test/java/org/opentripplanner/util/EnvironmentVariableReplacerTest.java
Labels: OTP2

#2910 Otp2 ds6 google cloud storage support
  docs/sandbox/GoogleCloudStorage.md
  pom.xml
  src/ext/java/org/opentripplanner/ext/datastore/gs/AbstractGsDataSource.java
  src/ext/java/org/opentripplanner/ext/datastore/gs/GsDataSourceRepository.java
  src/ext/java/org/opentripplanner/ext/datastore/gs/GsDirectoryDataSource.java
  src/ext/java/org/opentripplanner/ext/datastore/gs/GsFileDataSource.java
  src/ext/java/org/opentripplanner/ext/datastore/gs/GsHelper.java
  src/ext/java/org/opentripplanner/ext/datastore/gs/GsOutFileDataSource.java
  src/ext/java/org/opentripplanner/ext/datastore/gs/package-info.java
  src/main/java/org/opentripplanner/datastore/CompositeDataSource.java
  src/main/java/org/opentripplanner/datastore/OtpDataStore.java
  src/main/java/org/opentripplanner/datastore/OtpDataStoreConfig.java
  src/main/java/org/opentripplanner/datastore/base/ByteArrayDataSource.java
  src/main/java/org/opentripplanner/datastore/base/ZipStreamDataSourceDecorator.java
  src/main/java/org/opentripplanner/datastore/configure/DataStoreFactory.java
  src/main/java/org/opentripplanner/graph_builder/DataImportIssuesToHTML.java
  src/main/java/org/opentripplanner/standalone/config/GraphBuildParameters.java
  src/main/java/org/opentripplanner/standalone/config/StorageParameters.java
  src/main/java/org/opentripplanner/standalone/configure/OtpDataStoreConfigAdapter.java
  src/main/java/org/opentripplanner/util/OTPFeature.java
  src/test/java/org/opentripplanner/datastore/base/ByteArrayDataSourceTest.java
  src/test/java/org/opentripplanner/datastore/base/ZipStreamDataSourceDecoratorTest.java
  src/test/java/org/opentripplanner/ext/datastore/gs/GsDataSourceRepositoryTest.java
  src/test/java/org/opentripplanner/ext/datastore/gs/GsHelperTest.java
  src/test/java/org/opentripplanner/ext/datastore/gs/GsIntegrationTest.java
  src/test/java/org/opentripplanner/standalone/config/StorageParametersTest.java
Labels: OTP2, sandbox

#2912 Support for turning the fares calculation off, even when fares are
  docs/Changelog.md
  docs/Configuration.md
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/routing/core/Fare.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/routing/impl/DefaultFareServiceFactory.java
  src/main/java/org/opentripplanner/routing/impl/DefaultFareServiceImpl.java
  src/main/java/org/opentripplanner/routing/impl/NoopFareServiceFactory.java
  src/main/java/org/opentripplanner/routing/impl/NycFareServiceImpl.java
  src/main/java/org/opentripplanner/routing/impl/StreetVertexIndex.java
  src/main/java/org/opentripplanner/routing/services/FareService.java
Labels: OTP2

#2926 Otp2 limit transit service period
  docs/Changelog.md
  docs/Configuration.md
  src/main/java/org/opentripplanner/api/adapters/ServiceCalendarDateType.java
  src/main/java/org/opentripplanner/api/adapters/ServiceCalendarType.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryAndBlockProcessor.java
  src/main/java/org/opentripplanner/gtfs/GenerateTripPatternsOperation.java
  src/main/java/org/opentripplanner/gtfs/RepairStopTimesForEachTripOperation.java
  src/main/java/org/opentripplanner/gtfs/mapping/ServiceCalendarDateMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/ServiceCalendarMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/ServiceDateMapper.java
  src/main/java/org/opentripplanner/model/Stop.java
  src/main/java/org/opentripplanner/model/TripPattern.java
  src/main/java/org/opentripplanner/model/TripStopTimes.java
  src/main/java/org/opentripplanner/model/calendar/CalendarService.java
  src/main/java/org/opentripplanner/model/calendar/ServiceCalendar.java
  src/main/java/org/opentripplanner/model/calendar/ServiceCalendarDate.java
  src/main/java/org/opentripplanner/model/calendar/ServiceDate.java
  src/main/java/org/opentripplanner/model/calendar/ServiceDateInterval.java
  src/main/java/org/opentripplanner/model/calendar/impl/CalendarServiceDataFactoryImpl.java
  src/main/java/org/opentripplanner/model/calendar/impl/CalendarServiceImpl.java
  src/main/java/org/opentripplanner/model/impl/EntityById.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
  src/main/java/org/opentripplanner/netex/NetexModule.java
  src/main/java/org/opentripplanner/netex/configure/NetexConfig.java
  src/main/java/org/opentripplanner/netex/loader/mapping/CalendarMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/ServiceCalendarMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransitLayerMapper.java
  src/main/java/org/opentripplanner/routing/core/ServiceDay.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/routing/graph/GraphIndex.java
  src/main/java/org/opentripplanner/routing/transit_index/RouteSegment.java
  src/main/java/org/opentripplanner/routing/transit_index/RouteVariant.java
  src/main/java/org/opentripplanner/standalone/config/GraphBuildParameters.java
  src/test/java/org/opentripplanner/GtfsTest.java
  src/test/java/org/opentripplanner/graph_builder/module/FakeGraph.java
  src/test/java/org/opentripplanner/graph_builder/module/GtfsGraphBuilderModuleTest.java
  src/test/java/org/opentripplanner/gtfs/GtfsContextBuilder.java
  src/test/java/org/opentripplanner/gtfs/mapping/ServiceCalendarDateMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/ServiceCalendarMapperTest.java
  src/test/java/org/opentripplanner/model/calendar/ServiceDateIntervalTest.java
  src/test/java/org/opentripplanner/model/calendar/ServiceDateTest.java
  src/test/java/org/opentripplanner/model/calendar/impl/CalendarServiceDataFactoryImplTest.java
  src/test/java/org/opentripplanner/model/impl/OtpTransitServiceBuilderLimitPeriodTest.java
  src/test/java/org/opentripplanner/model/impl/OtpTransitServiceBuilderTest.java
  src/test/java/org/opentripplanner/netex/loader/mapping/CalendarMapperTest.java
  src/test/java/org/opentripplanner/standalone/config/GraphBuildParametersTest.java
Labels: OTP2, Regression

#2928 Unexpected wait cost between access and transit
  docs/Changelog.md
  src/main/java/org/opentripplanner/transit/raptor/api/request/ArrivalAndDeparturePreference.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/SearchParams.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/SearchParamsBuilder.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RangeRaptorWorker.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/WorkerLifeCycle.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/DestinationArrivalPaths.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/besttimes/BestTimes.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/CostCalculator.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/SearchContext.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/workerlifecycle/LifeCycleEventPublisher.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/workerlifecycle/LifeCycleSubscriptions.java
  src/test/java/org/opentripplanner/transit/raptor/rangeraptor/transit/CostCalculatorTest.java
  src/test/java/org/opentripplanner/transit/raptor/rangeraptor/transit/RoundTrackerTest.java
Labels: Entur, OTP2, bug

#2919 Faster TransitLayer realtime updater
  docs/Changelog.md
  src/ext/java/org/opentripplanner/ext/examples/updater/ExampleGraphUpdater.java
  src/ext/java/org/opentripplanner/ext/readiness_endpoint/ActuatorAPI.java
  src/ext/java/org/opentripplanner/ext/siri/SiriHttpUtils.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTripPatternCache.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETHttpTripUpdateSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriVMHttpTripUpdateSource.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/TripTimeShortHelper.java
  src/main/java/org/opentripplanner/api/resource/GraphPathToTripPlanConverter.java
  src/main/java/org/opentripplanner/api/resource/PlannerResource.java
  src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryAndBlockProcessor.java
  src/main/java/org/opentripplanner/model/Timetable.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/model/TripPattern.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/itinerary/ItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/StopIndexForRaptor.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/TransitLayer.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/TripPattern.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/RaptorTransitLayerGraphUpdater.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransfersMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransitLayerMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransitLayerUpdater.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TripPatternForDateMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TripPatternMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRoutingRequestTransitDataCreator.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/routing/graph/GraphIndex.java
  src/main/java/org/opentripplanner/routing/util/ConcurrentPublished.java
  src/main/java/org/opentripplanner/standalone/server/Router.java
  src/main/java/org/opentripplanner/updater/GraphUpdater.java
  src/main/java/org/opentripplanner/updater/GraphUpdaterConfigurator.java
  src/main/java/org/opentripplanner/updater/GraphUpdaterManager.java
  src/main/java/org/opentripplanner/updater/PollingGraphUpdater.java
  src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
  src/main/java/org/opentripplanner/updater/stoptime/WebsocketGtfsRealtimeUpdater.java
  src/test/java/org/opentripplanner/model/TimetableSnapshotTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/StopIndexForRaptorTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRoutingRequestTransitDataCreatorTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptor/transit/request/TripPatternWithId.java
  src/test/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSourceTest.java
Labels: OTP2
