Repository opentripplanner/OpenTripPlanner, pull requests merged in 2020-08, with the labels that each got.

#3109 Move debug timing to RoutingWorker and adapt to OTP2 routing phases
  docs/Changelog.md
  docs/OTP2-MigrationGuide.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/PlanResponse.java
  src/main/java/org/opentripplanner/api/resource/DebugOutput.java
  src/main/java/org/opentripplanner/api/resource/PlannerResource.java
  src/main/java/org/opentripplanner/api/resource/TransitTimingOutput.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/AStar.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/api/response/RoutingResponse.java
  src/main/java/org/opentripplanner/routing/core/RoutingContext.java
  src/main/java/org/opentripplanner/routing/framework/DebugAggregator.java
  src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
Labels: OTP2

#3146 Critical bugfix to the Entur Sandbox GraphQL Transmodel API
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
Labels: Entur, OTP2, bug, sandbox

#3133 Return OUTSIDE_SERVICE_PERIOD for transit trips outside the data validity
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/api/response/InputField.java
Labels: OTP2

#3143 Otp2 add tariff zone support
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
  src/main/java/org/opentripplanner/api/mapping/StopMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/StopMapper.java
  src/main/java/org/opentripplanner/model/FareZone.java
  src/main/java/org/opentripplanner/model/Stop.java
  src/main/java/org/opentripplanner/model/TripPattern.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
  src/main/java/org/opentripplanner/netex/loader/NetexImportDataIndex.java
  src/main/java/org/opentripplanner/netex/loader/NetexImportDataIndexReadOnlyView.java
  src/main/java/org/opentripplanner/netex/loader/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/StopAndStationMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/StopMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/TariffZoneMapper.java
  src/main/java/org/opentripplanner/netex/loader/parser/SiteFrameParser.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/impl/RideMapper.java
  src/test/java/org/opentripplanner/gtfs/mapping/StopAndStationMapperTest.java
  src/test/java/org/opentripplanner/netex/loader/mapping/StopAndStationMapperTest.java
Labels: Entur, OTP2

#3113 Fix dayRange error and add javadoc
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRoutingRequestTransitData.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRoutingRequestTransitDataCreator.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
Labels: OTP2, bug, documentation

#3144 Do not throw if access or egress legs are trivial
  src/main/java/org/opentripplanner/graph_builder/linking/SimpleStreetSplitter.java
  src/main/java/org/opentripplanner/model/plan/ItinerariesCalculateLegTotals.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/ItinerariesHelper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/core/RoutingContext.java
  src/main/java/org/opentripplanner/routing/error/TrivialPathException.java
  src/test/java/org/opentripplanner/routing/TestHalfEdges.java
Labels: OTP2

#3132 Return BUS for taxi extended route types, fixes #2280
  src/main/java/org/opentripplanner/gtfs/GtfsLibrary.java
Labels: OTP1, OTP2

#3108 Optimize SimpleStreetSplitter: two-stage search, remove sorting
  src/main/java/org/opentripplanner/common/geometry/HashGridSpatialIndex.java
  src/main/java/org/opentripplanner/graph_builder/linking/SimpleStreetSplitter.java
  src/test/java/org/opentripplanner/graph_builder/linking/LinkStopToPlatformTest.java
  src/test/java/org/opentripplanner/graph_builder/module/FakeGraph.java
  src/test/java/org/opentripplanner/graph_builder/module/linking/LinkingTest.java
Labels: OTP2

#3111 Fixed arraysOutOfBounds exception when copying pattern geometries to …
  src/main/java/org/opentripplanner/model/TripPattern.java
  src/main/java/org/opentripplanner/netex/loader/parser/ServiceFrameParser.java
Labels: OTP2, bug
