Repository opentripplanner/OpenTripPlanner, pull requests merged in 2020-10, with the labels that each got.

#3197 Allow caching of pre-flight options
  src/main/java/org/opentripplanner/standalone/server/CorsFilter.java
Labels: OTP2, improvement

#3191 Otp2 docs updates
  .github/pull_request_template.md
  docs/Basic-Tutorial.md
  docs/Changelog.md
  docs/Codestyle.md
  docs/Configuration.md
  docs/Interfaces-Data-Sources.md
  docs/Netex-Norway.md
  docs/OTP2-MigrationGuide.md
  docs/RoutingModes.md
  docs/SandboxExtension.md
  docs/Version-Comparison.md
  docs/sandbox/GoogleCloudStorage.md
  docs/sandbox/transferanalyzer.md
Labels: OTP2, documentation

#3208 Fix Pickup and Dropoff qualifiers for car mode
  src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/api/parameter/QualifiedModeSet.java
  src/main/java/org/opentripplanner/api/parameter/Qualifier.java
Labels: OTP2, Regression

#3207 Do not throw NPEs when routing without OSM data
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/Transfer.java
Labels: OTP2, bug

#3210 Fix issue #3195 - Build and load GTFS files for San Francisco Bay Area.
  docs/Changelog.md
  src/main/java/org/opentripplanner/model/StopLevel.java
  src/main/java/org/opentripplanner/model/TripPattern.java
Labels: OTP2, Regression, bug

#3212 Upgrade org.entur:netex-java-model to 1.0.11 (from 1.0.8)
  pom.xml
  src/main/java/org/opentripplanner/netex/loader/mapping/TripPatternMapper.java
  src/main/java/org/opentripplanner/netex/loader/parser/ServiceCalendarFrameParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/SiteFrameParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/TimeTableFrameParser.java
  src/main/java/org/opentripplanner/netex/support/DayTypeRefsToServiceIdAdapter.java
  src/test/java/org/opentripplanner/netex/NetexBundleSmokeTest.java
Labels: Entur, OTP2

#2966 Remove link "a quick introduction" in readme (which currently is 404)
  README.md
Labels: OTP1

#3216 Otp2 add progress bar to bus route street matcher
  docs/Changelog.md
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/map/BusRouteStreetMatcher.java
Labels: Regression, bug, new feature

#3220 No longer require externalLineRef on added trips - SIRI Updaters
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
Labels: Entur, improvement

#3185 Otp2 netex flex import
  src/ext/java/org/opentripplanner/ext/flex/FlexTripsMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/LineType.java
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/netex/NetexModule.java
  src/main/java/org/opentripplanner/netex/loader/NetexImportDataIndex.java
  src/main/java/org/opentripplanner/netex/loader/NetexImportDataIndexReadOnlyView.java
  src/main/java/org/opentripplanner/netex/loader/mapping/FlexStopLocationMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/OpenGisMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/RouteMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/StopTimesMapper.java
  src/main/java/org/opentripplanner/netex/loader/mapping/TripPatternMapper.java
  src/main/java/org/opentripplanner/netex/loader/parser/NetexDocumentParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/ServiceFrameParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/SiteFrameParser.java
  src/test/java/org/opentripplanner/netex/loader/mapping/FlexStopLocationMapperTest.java
  src/test/java/org/opentripplanner/netex/loader/mapping/StopTimesMapperTest.java
  src/test/java/org/opentripplanner/netex/loader/mapping/TripPatternMapperTest.java
Labels: Entur

#3219 Add `generalizedCost` to both itinerary and leg
  src/client/i18n/ca_ES.po
  src/client/i18n/de.po
  src/client/i18n/en.po
  src/client/i18n/es.po
  src/client/i18n/fr.po
  src/client/i18n/it.po
  src/client/i18n/messages.pot
  src/client/i18n/no.po
  src/client/i18n/pl.po
  src/client/i18n/pt.po
  src/client/i18n/sl.po
  src/client/js/otp/config.js
  src/client/js/otp/modules/planner/ItinerariesWidget.js
  src/client/js/otp/modules/planner/Itinerary.js
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLItineraryImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLLegImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/api/mapping/ItineraryMapper.java
  src/main/java/org/opentripplanner/api/mapping/LegMapper.java
  src/main/java/org/opentripplanner/api/model/ApiItinerary.java
  src/main/java/org/opentripplanner/api/model/ApiLeg.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/main/java/org/opentripplanner/transit/raptor/api/path/AccessPathLeg.java
  src/main/java/org/opentripplanner/transit/raptor/api/path/EgressPathLeg.java
  src/main/java/org/opentripplanner/transit/raptor/api/path/IntermediatePathLeg.java
  src/main/java/org/opentripplanner/transit/raptor/api/path/PathLeg.java
  src/main/java/org/opentripplanner/transit/raptor/api/path/TransferPathLeg.java
  src/main/java/org/opentripplanner/transit/raptor/api/path/TransitPathLeg.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorCostConverter.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/ForwardPathMapper.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/ReversePathMapper.java
  src/test/java/org/opentripplanner/transit/raptor/_shared/StopArrivalsTestData.java
  src/test/java/org/opentripplanner/transit/raptor/api/path/PathTest.java
  src/test/java/org/opentripplanner/transit/raptor/rangeraptor/path/ForwardPathMapperTest.java
  src/test/java/org/opentripplanner/transit/raptor/rangeraptor/path/ReversePathMapperTest.java
Labels: Entur, improvement

#3221 Sandbox: Add a new InteractiveOTPMain application.
  docs/sandbox/InteractiveOtpMain.md
  mkdocs.yml
  src/ext/java/org/opentripplanner/ext/interactivelauncher/CliArguments.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/InteractiveOtpMain.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/SearchForOtpConfig.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/SetupResult.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/ConfigDirsView.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/MainView.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/OptionsView.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/StartOtpButtonView.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/StatusBar.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/ViewUtils.java
Labels: improvement, sandbox

#3224 DSJ-2 : Cleanup Netex Import - Add validation step to the Netex import
  src/main/java/org/opentripplanner/netex/NetexBundle.java
  src/main/java/org/opentripplanner/netex/index/NetexEntityIndex.java
  src/main/java/org/opentripplanner/netex/index/api/HMapValidationRule.java
  src/main/java/org/opentripplanner/netex/index/api/NetexEntityIndexReadOnlyView.java
  src/main/java/org/opentripplanner/netex/index/api/ReadOnlyHierarchicalMap.java
  src/main/java/org/opentripplanner/netex/index/api/ReadOnlyHierarchicalMapById.java
  src/main/java/org/opentripplanner/netex/index/hierarchy/AbstractHierarchicalMap.java
  src/main/java/org/opentripplanner/netex/index/hierarchy/HierarchicalMap.java
  src/main/java/org/opentripplanner/netex/index/hierarchy/HierarchicalMultimap.java
  src/main/java/org/opentripplanner/netex/loader/parser/NetexDocumentParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/NetexParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/NoticeParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/ResourceFrameParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/ServiceCalendarFrameParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/ServiceFrameParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/SiteFrameParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/TimeTableFrameParser.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/NoticeAssignmentMapper.java
  src/main/java/org/opentripplanner/netex/mapping/RouteMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
  src/main/java/org/opentripplanner/netex/package.md
  src/main/java/org/opentripplanner/netex/validation/AbstractHMapValidationRule.java
  src/main/java/org/opentripplanner/netex/validation/JourneyPatternNotFoundInSJ.java
  src/main/java/org/opentripplanner/netex/validation/JourneyPatternSJMismatch.java
  src/main/java/org/opentripplanner/netex/validation/PassengerStopAssignmentQuayNotFound.java
  src/main/java/org/opentripplanner/netex/validation/Validator.java
  src/test/java/org/opentripplanner/netex/index/hierarchy/E.java
  src/test/java/org/opentripplanner/netex/index/hierarchy/HierarchicalMapTest.java
  src/test/java/org/opentripplanner/netex/index/hierarchy/HierarchicalMultimapTest.java
  src/test/java/org/opentripplanner/netex/loader/NetexEntityIndexTest.java
  src/test/java/org/opentripplanner/netex/mapping/NetexTestDataSample.java
  src/test/java/org/opentripplanner/netex/mapping/NoticeAssignmentMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/RouteMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/TripPatternMapperTest.java
Labels: Entur, documentation, improvement, technical debt
