Repository opentripplanner/OpenTripPlanner, pull requests merged in 2020-03, with the labels that each got.

#2988 Copy geometries from previous TripPattern when doing real-time updates
  docs/Changelog.md
  src/ext/java/org/opentripplanner/ext/siri/SiriTripPatternCache.java
  src/main/java/org/opentripplanner/model/TripPattern.java
  src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
  src/main/java/org/opentripplanner/updater/stoptime/TripPatternCache.java
Labels: Entur, OTP2

#2996 OTP2: include result paging metadata on results containing no itineraries
  src/client/js/otp/locale/ca_ES.json
  src/client/js/otp/locale/de.json
  src/client/js/otp/locale/en.json
  src/client/js/otp/locale/es.json
  src/client/js/otp/locale/fr.json
  src/client/js/otp/locale/it.json
  src/client/js/otp/locale/pl.json
  src/client/js/otp/locale/pt.json
  src/client/js/otp/locale/sl.json
  src/client/js/otp/modules/planner/PlannerModule.js
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/PlanResponse.java
  src/main/java/org/opentripplanner/api/common/Message.java
  src/main/java/org/opentripplanner/api/model/error/PlannerError.java
  src/main/java/org/opentripplanner/common/model/GenericLocation.java
  src/main/java/org/opentripplanner/graph_builder/linking/SimpleStreetSplitter.java
  src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
  src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryAndBlockProcessor.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/model/TripPattern.java
  src/main/java/org/opentripplanner/model/base/ToStringBuilder.java
  src/main/java/org/opentripplanner/model/base/ValueObjectToStringBuilder.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/model/plan/Place.java
  src/main/java/org/opentripplanner/model/plan/StopArrival.java
  src/main/java/org/opentripplanner/openstreetmap/BinaryOpenStreetMapParser.java
  src/main/java/org/opentripplanner/openstreetmap/BinaryOpenStreetMapProvider.java
  src/main/java/org/opentripplanner/openstreetmap/OsmParserPhase.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/impl/StreetVertexIndex.java
  src/main/java/org/opentripplanner/transit/raptor/util/TimeUtils.java
  src/main/java/org/opentripplanner/util/ProgressTracker.java
  src/main/java/org/opentripplanner/util/ProgressTrackerInputStream.java
  src/main/resources/Message.properties
  src/main/resources/Message_es.properties
  src/test/java/org/opentripplanner/api/resource/TestMessages.java
  src/test/java/org/opentripplanner/model/base/ToStringBuilderTest.java
  src/test/java/org/opentripplanner/model/base/ValueObjectToStringBuilderTest.java
  src/test/java/org/opentripplanner/util/ProgressTrackerTest.java
  src/test/resources/Message.properties
  src/test/resources/Message_es.properties
Labels: Entur, OTP2, Regression, bug

#3003 Override getDistanceMeters for SimpleTransfer
  src/main/java/org/opentripplanner/routing/edgetype/SimpleTransfer.java
Labels: Entur, OTP2, bug

#2997 Otp2 reimplement banning/whitelisting of routes/agencies
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRoutingRequestTransitData.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRoutingRequestTransitDataCreator.java
  src/main/java/org/opentripplanner/routing/core/RoutingContext.java
  src/main/java/org/opentripplanner/routing/core/RoutingRequest.java
  src/test/java/org/opentripplanner/routing/algorithm/TestBanning.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
Labels: Entur, OTP2

#3004 Otp2 Tag Itinerary with SystemNotieces
  src/client/i18n/messages.pot
  src/client/js/otp/modules/multimodal/MultimodalPlannerModule.js
  src/client/js/otp/modules/planner/ItinerariesWidget.js
  src/client/js/otp/modules/planner/PlannerModule.js
  src/client/js/otp/modules/planner/planner-style.css
  src/client/js/otp/widgets/tripoptions/TripOptionsWidget.js
  src/client/js/otp/widgets/tripoptions/tripoptions-templates.html
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
  src/main/java/org/opentripplanner/api/mapping/ItineraryMapper.java
  src/main/java/org/opentripplanner/api/mapping/SystemNoticeMapper.java
  src/main/java/org/opentripplanner/api/mapping/TripSearchMetadataMapper.java
  src/main/java/org/opentripplanner/api/model/ApiItinerary.java
  src/main/java/org/opentripplanner/api/model/ApiSystemNotice.java
  src/main/java/org/opentripplanner/model/SystemNotice.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/DebugFilterChain.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/MaxLimitFilter.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainBuilderTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/MaxLimitFilterTest.java
Labels: Entur, OTP2, new feature

#3006 Add back the 'otp/routers' REST endpoint to be backward compatible with OTP1.
  src/main/java/org/opentripplanner/api/configuration/APIEndpoints.java
  src/main/java/org/opentripplanner/api/resource/Routers.java
Labels: Entur, OTP2, Regression

#3019 Fix trip geometry bug
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
Labels: Entur, OTP2, bug

#3017 router-config file is ignored by server, it uses router-config found in loaded graph
  src/main/java/org/opentripplanner/api/resource/PlannerResource.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilderDataSources.java
  src/main/java/org/opentripplanner/graph_builder/GraphStats.java
  src/main/java/org/opentripplanner/graph_builder/module/EmbedConfig.java
  src/main/java/org/opentripplanner/routing/RoutingService.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
  src/main/java/org/opentripplanner/standalone/OTPMain.java
  src/main/java/org/opentripplanner/standalone/configure/OTPAppConstruction.java
  src/main/java/org/opentripplanner/standalone/configure/OTPConfiguration.java
  src/main/java/org/opentripplanner/standalone/server/Router.java
  src/main/java/org/opentripplanner/util/ProgressTracker.java
  src/main/java/org/opentripplanner/util/ProgressTrackerOutputStream.java
  src/test/java/org/opentripplanner/GtfsTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestIntermediatePlaces.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestOpenStreetMapGraphBuilder.java
  src/test/java/org/opentripplanner/routing/graph/GraphSerializationTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
Labels: Entur, OTP2, bug
