Repository opentripplanner/OpenTripPlanner, pull requests merged in 2020-04, with the labels that each got.

#3025 Code cleanup - Log graph de-serialization as a waring without stack-trace
  src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
Labels: OTP2, bug, technical depth

#3024 Disable write check on input base directory.
  src/main/java/org/opentripplanner/datastore/OtpDataStore.java
  src/main/java/org/opentripplanner/standalone/config/CommandLineParameters.java
Labels: Entur, OTP2, bug

#3028 Add support for blocking/allowing board/alight at each stop individually
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/TripPatternForDates.java
  src/main/java/org/opentripplanner/transit/raptor/README.md
  src/main/java/org/opentripplanner/transit/raptor/RaptorTimeLine.svg
  src/main/java/org/opentripplanner/transit/raptor/api/path/PathLeg.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTripPattern.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/McTransitWorker.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/ForwardPathMapper.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/ReversePathMapper.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/NoWaitTransitWorker.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/StdTransitWorker.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/TripTimesSearch.java
  src/test/java/org/opentripplanner/transit/raptor/_shared/StopArrivalsTestData.java
  src/test/java/org/opentripplanner/transit/raptor/_shared/TestRaptorTripSchedule.java
  src/test/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/arrivals/TransitStopArrivalTest.java
  src/test/java/org/opentripplanner/transit/raptor/rangeraptor/path/ForwardPathMapperTest.java
  src/test/java/org/opentripplanner/transit/raptor/rangeraptor/path/ReversePathMapperTest.java
  src/test/java/org/opentripplanner/transit/raptor/rangeraptor/transit/ForwardTransitCalculatorTest.java
  src/test/java/org/opentripplanner/transit/raptor/rangeraptor/transit/ReverseTransitCalculatorTest.java
  src/test/java/org/opentripplanner/transit/raptor/rangeraptor/transit/TripScheduleAlightSearchTest.java
  src/test/java/org/opentripplanner/transit/raptor/rangeraptor/transit/TripScheduleBoardSearchTest.java
  src/test/java/org/opentripplanner/transit/raptor/rangeraptor/transit/TripScheduleExactMatchSearchTest.java
  src/test/java/org/opentripplanner/transit/raptor/rangeraptor/transit/TripTimesSearchTest.java
Labels: Entur, OTP2, Regression

#3029 Bugfix: logging of unused parameters
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
  src/main/java/org/opentripplanner/standalone/config/OtpConfig.java
  src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
  src/main/java/org/opentripplanner/standalone/config/StorageConfig.java
  src/main/java/org/opentripplanner/standalone/config/TransitRoutingConfig.java
  src/test/java/org/opentripplanner/standalone/config/NodeAdapterTest.java
Labels: Entur, OTP2, bug

#3032 Use OSM parser from org.openstreetmap.osmosis, instead of the unmaintained crosby.binary
  pom.xml
  src/main/java/org/opentripplanner/openstreetmap/BinaryOpenStreetMapParser.java
  src/main/java/org/opentripplanner/openstreetmap/BinaryOpenStreetMapProvider.java
Labels: OTP2, improvement, technical depth

#3033 Improve error handling for data-sources.
  src/main/java/org/opentripplanner/datastore/DataSource.java
  src/main/java/org/opentripplanner/datastore/base/ZipStreamDataSourceDecorator.java
  src/main/java/org/opentripplanner/datastore/file/DirectoryDataSource.java
  src/main/java/org/opentripplanner/datastore/file/FileDataSource.java
  src/main/java/org/opentripplanner/datastore/file/ZipFileDataSource.java
  src/main/java/org/opentripplanner/datastore/file/ZipFileEntryDataSource.java
Labels: OTP2, bug, improvement

#3038 Clarify the OTP2 MigrationGuide documentation
  docs/OTP2-MigrationGuide.md
Labels: OTP2, documentation

#3036 Make StopAtDistance operate on Stops rather than on TransitStopVertices
  src/ext/java/org/opentripplanner/ext/transferanalyzer/DirectTransferAnalyzer.java
  src/ext/java/org/opentripplanner/ext/transferanalyzer/annotations/TransferCouldNotBeRouted.java
  src/ext/java/org/opentripplanner/ext/transferanalyzer/annotations/TransferRoutingDistanceTooLong.java
  src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/AccessEgressRouter.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/transit/StreetSearch.java
Labels: OTP2

#3037 Add startup header with deatiled version and build info.
  pom.xml
  src/main/java/org/opentripplanner/common/MavenVersion.java
  src/main/java/org/opentripplanner/standalone/OTPMain.java
  src/main/java/org/opentripplanner/standalone/OtpStartupInfo.java
  src/main/resources/maven-version.properties
Labels: OTP2

#3039 Geospatial repository url has been changed
  pom.xml
Labels: OTP2

#3046 Update geospatial repository url
  pom.xml
Labels: OTP1

#3043 Otp2 update repository urls
  pom.xml
Labels: Entur, OTP2

#3044 Update onebusaway-release repo to use https
  pom.xml
Labels: OTP1

#3045 Add isPartOfStation() and isPartOfSameStation(..) to StationElement a… …
  src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/TripTimeShortHelper.java
  src/main/java/org/opentripplanner/api/mapping/StopMapper.java
  src/main/java/org/opentripplanner/model/StationElement.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/AlertToLegMapper.java
  src/main/java/org/opentripplanner/routing/impl/AlertPatchServiceImpl.java
Labels: OTP2, Regression, bug

#3049 Authority id fix
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
Labels: Entur, OTP2, sandbox
