Repository opentripplanner/OpenTripPlanner, pull requests merged in 2020-11, with the labels that each got.

#3229 Cleanup Transmodel api, #Entur, #Sandbox
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/TripTimeShortHelper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/BannedInputType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/JourneyWhiteListed.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/ModeInputType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/PathGuidanceType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/PlanPlaceType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripPatternType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
Labels: Entur, documentation, sandbox

#3222 Alternative implementation of multi day trips
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/TripPatternForDate.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/DateMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransitLayerMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRoutingRequestTransitData.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRoutingRequestTransitDataCreator.java
  src/test/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRoutingRequestTransitDataCreatorTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
Labels: new feature

#3232 Update dependency google-cloud-storage to 1.113.2 (1.101.0).
  pom.xml
  src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
  src/main/java/org/opentripplanner/datastore/OtpDataStore.java
  src/main/java/org/opentripplanner/standalone/configure/OTPAppConstruction.java
Labels: Entur, bug

#3231 Add null check on route getName
  src/main/java/org/opentripplanner/routing/core/RouteMatcher.java
Labels: bug

#3238 Otp2 fix SIRI timezones
  src/ext-test/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandlerTest.java
  src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java
  src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
  src/main/java/org/opentripplanner/model/Timetable.java
  src/main/java/org/opentripplanner/model/calendar/ServiceDate.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/DateMapper.java
  src/test/java/org/opentripplanner/model/calendar/ServiceDateTest.java
Labels: bug, sandbox

#3244 Fix for issue #3241 : SLF4J/JUL configuration
  src/main/java/org/opentripplanner/standalone/OTPMain.java
Labels: Entur, improvement, technical debt

#3247 doc: Fix broken document links.
  docs/Basic-Tutorial.md
  docs/Governance.md
  docs/Interfaces-Data-Sources.md
  docs/Troubleshooting-Routing.md
  docs/index.md
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriVMUpdater.java
  src/main/java/org/opentripplanner/updater/alerts/GtfsRealtimeAlertsUpdater.java
  src/main/java/org/opentripplanner/updater/stoptime/PollingStoptimeUpdater.java
  src/main/java/org/opentripplanner/updater/stoptime/WebsocketGtfsRealtimeUpdater.java
  src/main/java/org/opentripplanner/updater/street_notes/WFSNotePollingGraphUpdater.java
Labels: documentation

#3246 doc: Improve the build config documentation in the MigrationGuide.
  docs/Configuration.md
  docs/OTP2-MigrationGuide.md
Labels: documentation

#3251 Improve InteractiveOtpMain with pesistent state and dialog to open a …
  src/ext/java/org/opentripplanner/ext/interactivelauncher/CliArguments.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/InteractiveOtpMain.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/Model.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/SearchForOtpConfig.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/ConfigDirsView.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/DataSourcesView.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/MainView.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/OptionsView.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/SearchDirectoryView.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/ViewUtils.java
Labels: sandbox

#3250 Reduced log level for slope costs calculation
  src/main/java/org/opentripplanner/routing/util/ElevationUtils.java
Labels: Entur, improvement

#3237 Fix TransitLayerUpdater bug
  src/ext/java/org/opentripplanner/ext/interactivelauncher/SearchForOtpConfig.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/TransitLayer.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/TripPatternForDate.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransitLayerMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransitLayerUpdater.java
Labels: bug

#3254 Insert project info in configuration files
  docs/Changelog.md
  docs/Configuration.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/ServerInfoType.java
  src/main/java/org/opentripplanner/api/resource/ServerInfo.java
  src/main/java/org/opentripplanner/common/ProjectInfo.java
  src/main/java/org/opentripplanner/model/Timetable.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/edgetype/ParkAndRideEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/ParkAndRideLinkEdge.java
  src/main/java/org/opentripplanner/routing/graph/Edge.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/routing/graph/Vertex.java
  src/main/java/org/opentripplanner/routing/trippattern/FrequencyEntry.java
  src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java
  src/main/java/org/opentripplanner/routing/vertextype/BikeParkVertex.java
  src/main/java/org/opentripplanner/routing/vertextype/BikeRentalStationVertex.java
  src/main/java/org/opentripplanner/routing/vertextype/ParkAndRideVertex.java
  src/main/java/org/opentripplanner/standalone/OTPMain.java
  src/main/java/org/opentripplanner/standalone/OtpStartupInfo.java
  src/main/java/org/opentripplanner/standalone/config/ConfigLoader.java
  src/main/java/org/opentripplanner/standalone/config/EnvironmentVariableReplacer.java
  src/test/java/org/opentripplanner/standalone/config/EnvironmentVariableReplacerTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
Labels: documentation, improvement

#3253 Make sure bug do not occour when AvgTimer is switched off.
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/debug/WorkerPerformanceTimers.java
  src/main/java/org/opentripplanner/transit/raptor/service/WorkerPerformanceTimersCache.java
  src/main/java/org/opentripplanner/transit/raptor/util/AvgTimer.java
Labels: bug

#3258 Provide a fake JavaDoc jar with readme
  docs/javadoc/README.md
  pom.xml
  src/main/java/org/opentripplanner/index/model/RouteShort.java
Labels: bug, release management, technical debt

#3257 Document the lack of support for frequency based trips, improve logging
  docs/OTP2-MigrationGuide.md
  docs/Version-Comparison.md
  src/main/java/org/opentripplanner/common/MavenVersion.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilderDataSources.java
  src/main/java/org/opentripplanner/model/base/ToStringBuilder.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceImpl.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/AccessEgress.java
  src/main/java/org/opentripplanner/routing/trippattern/FrequencyEntry.java
  src/main/java/org/opentripplanner/standalone/OTPMain.java
  src/main/java/org/opentripplanner/transit/raptor/RaptorService.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/RaptorRequest.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/SearchParams.java
  src/main/resources/logback.xml
  src/test/java/org/opentripplanner/model/base/ToStringBuilderTest.java
Labels: documentation

#3259 doc: Cleanup doc on removed/changed/new routing parameters
  docs/OTP2-MigrationGuide.md
Labels: documentation

#3267 Port dangling commits from master to 2.0-rc
  docs/Changelog.md
  docs/Governance.md
Labels: documentation

#3270 InteractiveOtpMain save flag not set.
  src/ext/java/org/opentripplanner/ext/interactivelauncher/InteractiveOtpMain.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/OptionsView.java
Labels: bug, sandbox
