Repository opentripplanner/OpenTripPlanner, pull requests merged in 2021-08, with the labels that each got.

#3527 Include stop_sequence in 1.x index API stop_times (#3528)
  src/main/java/org/opentripplanner/analyst/scenario/SkipStop.java
  src/main/java/org/opentripplanner/api/resource/GraphPathToTripPlanConverter.java
  src/main/java/org/opentripplanner/index/model/TripTimeShort.java
  src/main/java/org/opentripplanner/routing/edgetype/Timetable.java
  src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java
Labels: OTP1

#3578 Do not allow bicycle traversal on ways tagged with mtb:scale
  docs/Changelog.md
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/DefaultWayPropertySetSource.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRequestTransferCache.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
  src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/NorwayWayPropertySetSourceTest.java
  src/test/java/org/opentripplanner/routing/edgetype/TestTriangle.java
  src/test/java/org/opentripplanner/routing/edgetype/loader/TestGeometryAndBlockProcessor.java
  src/test/java/org/opentripplanner/routing/street/BicycleRoutingTest.java
Labels: improvement

#3560 Add maxAccessEgressDurationSecondsForMode to RoutingRequest
  docs/Changelog.md
  docs/Configuration.md
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/AccessEgressRouter.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
Labels: Entur test

#3576 Changes to the StopTimes method used by the graphql APIs
  docs/Changelog.md
  pom.xml
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLDepartureRowImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
  src/main/java/org/opentripplanner/index/IndexAPI.java
  src/main/java/org/opentripplanner/routing/RoutingService.java
  src/main/java/org/opentripplanner/routing/graphfinder/PatternAtStop.java
  src/main/java/org/opentripplanner/routing/stoptimes/ArrivalDeparture.java
  src/main/java/org/opentripplanner/routing/stoptimes/StopTimesHelper.java
Labels: Entur test

#3587 Fix bug in optimize transfer service decorating path
  docs/Changelog.md
  src/main/java/org/opentripplanner/model/transfer/TransferPriority.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/TripToTripTransfer.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizePathService.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizedPathFactory.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/PriorityBasedTransfersCostCalculator.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizePathServiceConstrainedTest.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizePathServiceTest.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TestTransferBuilder.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGeneratorDummy.java
  src/test/java/org/opentripplanner/transit/raptor/_data/RaptorTestConstants.java
Labels: bug, Entur test

#3591 Map Station to correct Transmodel type
  docs/Changelog.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
Labels: bug, sandbox, Regression, Entur test
