Repository opentripplanner/OpenTripPlanner, pull requests merged in 2021-09, with the labels that each got.

#3592 Add new types of PurchaseWhenEnumeration in BookingInfoMapper
  docs/Changelog.md
  src/main/java/org/opentripplanner/netex/mapping/BookingInfoMapper.java
  src/test/java/org/opentripplanner/netex/mapping/BookingInfoMapperTest.java
Labels: Entur test, Netex

#3586 Use correct values for bikesAllowed in the Transmodel API
  docs/sandbox/TransmodelApi.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
Labels: improvement

#3557 Expand pull request template
  .github/pull_request_template.md
Labels: documentation

#3572 Log warnings on missing/invalid pathways
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/gtfs/mapping/PathwayMapper.java
Labels: bug

#3601 Make vehicle rental stations feed scoped
  docs/Changelog.md
  docs/Configuration.md
  docs/RoutingModes.md
  docs/examples/entur/build-config.json
  pom.xml
  src/ext-test/java/org/opentripplanner/ext/smoovebikerental/SmooveBikeRentalDataSourceTest.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLBikeRentalStationImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPlaceImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/smoovebikerental/SmooveBikeRentalDataSource.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/PlanPlaceType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/BikeRentalStationType.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/DigitransitVehicleRentalPropertyMapper.java
  src/ext/java/org/opentripplanner/ext/vehiclerentalservicedirectory/VehicleRentalParameters.java
  src/main/java/org/opentripplanner/api/mapping/PlaceMapper.java
  src/main/java/org/opentripplanner/api/mapping/VehicleRentalStationMapper.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/issues/BikeRentalStationUnlinked.java
  src/main/java/org/opentripplanner/graph_builder/module/StreetLinkerModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/model/VehicleRentalStationInfo.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/model/plan/Place.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMNode.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/core/State.java
  src/main/java/org/opentripplanner/routing/core/StateData.java
  src/main/java/org/opentripplanner/routing/core/StateEditor.java
  src/main/java/org/opentripplanner/routing/edgetype/VehicleRentalEdge.java
  src/main/java/org/opentripplanner/routing/graphfinder/PlaceFinderTraverseVisitor.java
  src/main/java/org/opentripplanner/routing/spt/DominanceFunction.java
  src/main/java/org/opentripplanner/routing/vehicle_rental/VehicleRentalStation.java
  src/main/java/org/opentripplanner/routing/vehicle_rental/VehicleRentalStationService.java
  src/main/java/org/opentripplanner/routing/vertextype/VehicleRentalStationVertex.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/main/java/org/opentripplanner/standalone/config/updaters/VehicleRentalUpdaterConfig.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdater.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdaterParameters.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsVehicleRentalDataSource.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
  src/test/resources/portland-vehicle-rental.csv
Labels: improvement

#3603 Otp2 update dependencies
  pom.xml
  src/ext/java/org/opentripplanner/ext/examples/statistics/api/resource/GraphStatisticsResource.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/TransportModeSlack.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/JourneyWhiteListed.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripPatternType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/scalars/DateScalarFactory.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/scalars/DateTimeScalarFactory.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/scalars/GeoJSONCoordinatesScalar.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/scalars/LocalTimeScalarFactory.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/scalars/TimeScalarFactory.java
  src/main/java/org/opentripplanner/model/projectinfo/OtpProjectInfo.java
  src/main/java/org/opentripplanner/standalone/server/OTPApplication.java
  src/main/java/org/opentripplanner/standalone/server/OTPServer.java
  src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java
  src/main/resources/otp-project-info.properties
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
Labels: technical debt

#3596 Allow bicycles on ferries for Netex data
  docs/Changelog.md
  docs/Netex-Norway.md
  docs/examples/entur/build-config.json
  src/main/java/org/opentripplanner/netex/NetexBundle.java
  src/main/java/org/opentripplanner/netex/configure/NetexConfig.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/RouteMapper.java
  src/main/java/org/opentripplanner/standalone/config/NetexConfig.java
  src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
  src/test/java/org/opentripplanner/netex/mapping/RouteMapperTest.java
  src/test/java/org/opentripplanner/standalone/config/NodeAdapterTest.java
Labels: improvement, Netex

#3585 Add bicycle triangle factors to Transmodel API
  docs/sandbox/TransmodelApi.md
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TriangleFactorsInputType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/test/java/org/opentripplanner/routing/edgetype/TriangleTest.java
Labels: improvement

#3605 Correct the handling of itinerary links in the debug client
  src/client/js/otp/widgets/tripoptions/TripOptionsWidget.js
Labels: improvement

#3590 Add basic version-support for importing tariffzones
  docs/Changelog.md
  pom.xml
  src/main/java/org/opentripplanner/model/FareZone.java
  src/main/java/org/opentripplanner/netex/index/NetexEntityIndex.java
  src/main/java/org/opentripplanner/netex/index/api/NetexEntityIndexReadOnlyView.java
  src/main/java/org/opentripplanner/netex/index/api/ReadOnlyHierarchicalVersionMapById.java
  src/main/java/org/opentripplanner/netex/index/hierarchy/HierarchicalVersionMapById.java
  src/main/java/org/opentripplanner/netex/index/hierarchy/ValidOnDate.java
  src/main/java/org/opentripplanner/netex/loader/parser/NetexDocumentParser.java
  src/main/java/org/opentripplanner/netex/mapping/AuthorityToAgencyMapper.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/RouteMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopAndStationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TariffZoneMapper.java
  src/main/java/org/opentripplanner/netex/support/NetexVersionHelper.java
  src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
  src/test/java/org/opentripplanner/netex/index/hierarchy/ValidOnDateTest.java
  src/test/java/org/opentripplanner/netex/loader/NetexEntityIndexTest.java
  src/test/java/org/opentripplanner/netex/mapping/AuthorityToAgencyMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/RouteMapperTest.java
  src/test/java/org/opentripplanner/netex/support/NetexVersionHelperTest.java
Labels: bug, improvement, Entur, Entur test, Netex

#3609 Fix correct type for BookingArrangementType#latestBookingDay
  docs/sandbox/TransmodelApi.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/BookingArrangementType.java
Labels: bug, sandbox, Entur

#3584 Do not skip update just because there are no EstimatedCalls
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
Labels: Entur test

#3600 improve: Use a fixed limit for grouping itineraries
  docs/Changelog.md
  docs/Configuration.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/DefaultRoutingRequestType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/ItineraryFiltersInputType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/GroupBySimilarity.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/GroupByFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/GroupBySimilarLegsFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RoutingRequestToFilterChainMapper.java
  src/main/java/org/opentripplanner/routing/api/request/ItineraryFilterParameters.java
  src/main/java/org/opentripplanner/standalone/config/ItineraryFiltersMapper.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/GroupByFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
Labels: improvement, Entur, Entur test

#3612 Use Netex enums to check for ferries
  src/main/java/org/opentripplanner/netex/mapping/RouteMapper.java
Labels: Entur test, Netex

#3607 Serialize nulls in Transmodel GraphQL API
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLAPI.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelAPI.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraph.java
  src/main/java/org/opentripplanner/api/json/GraphQLResponseSerializer.java
Labels: bug, sandbox, Entur, Entur test

#3613 Remove null default values for Transmodel API
  docs/Changelog.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/ModeInputType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/ServiceJourneyType.java
Labels: documentation, sandbox, Entur, Entur test

#3622 Fix reverse raptor search with boarding/alighting restrictions
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RangeRaptorWorker.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/ForwardTransitCalculator.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/ReverseTransitCalculator.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/TransitCalculator.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTripPattern.java
  src/test/java/org/opentripplanner/transit/raptor/moduletests/A02_SingeRouteRestrictionsTest.java
Labels: bug, Entur test

#3620 Entur add infolinks to transmodel api
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/sx/PtSituationElementType.java
Labels: Entur test

#3375 Support multiple modes for on-street transfers
  docs/Changelog.md
  docs/Configuration.md
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/api/request/StreetMode.java
  src/main/java/org/opentripplanner/routing/graphfinder/NearbyStop.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTransfer.java
  src/test/java/org/opentripplanner/graph_builder/module/DirectTransferGeneratorTest.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGeneratorTest.java
  src/test/java/org/opentripplanner/routing/graphfinder/StreetGraphFinderTest.java
Labels: Regression

#3630 doc: Fix board/light slack doc
  docs/Configuration.md
Labels: documentation
