Repository opentripplanner/OpenTripPlanner, pull requests merged in 2021-11, with the labels that each got.

#3693 Correct usage of boardSlackForMode / alightSlackForMode
  src/ext-test/java/org/opentripplanner/ext/transmodelapi/model/TransportModeSlackTest.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/TransportModeSlack.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/SlackProvider.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
Labels: bug

#3707 Use correct capitalization for GraphQL fields [changelog skip]
  docs/sandbox/TransmodelApi.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/InterchangeType.java
Labels: bug, Entur test

#3711 Fix several small bugs with transfers and board and alight slack [changelog skip]
  src/main/java/org/opentripplanner/netex/mapping/TransferMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/SlackProvider.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/ConstrainedBoardingSearch.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGenerator.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RangeRaptorWorker.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RoutingStrategy.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/SlackProvider.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/McTransitWorker.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/NoWaitTransitWorker.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/StdTransitWorker.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/configure/StdRangeRaptorConfig.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/SlackProviderAdapter.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/TransitCalculator.java
  src/test/java/org/opentripplanner/transit/raptor/rangeraptor/transit/SlackProviderAdapterTest.java
Labels: bug, Entur test

#3717 Improve and fix the InteractiveOtpMain [changelog skip]
  src/ext/java/org/opentripplanner/ext/interactivelauncher/Model.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/DataSourcesView.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/MainView.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/OptionsView.java
Labels: sandbox

#3715 doc: Update Developers-Guide.md with changelog workflow [changelog skip]
  docs/Developers-Guide.md
Labels: documentation

#3658 add trolleybus & monorail support
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/main/java/org/opentripplanner/api/mapping/TraverseModeMapper.java
  src/main/java/org/opentripplanner/api/parameter/ApiRequestMode.java
  src/main/java/org/opentripplanner/api/parameter/QualifiedModeSet.java
  src/main/java/org/opentripplanner/graph_builder/module/map/BusRouteStreetMatcher.java
  src/main/java/org/opentripplanner/gtfs/mapping/TransitModeMapper.java
  src/main/java/org/opentripplanner/model/TransitMode.java
  src/main/java/org/opentripplanner/routing/core/TraverseMode.java
  src/main/java/org/opentripplanner/routing/core/TraverseModeSet.java
  src/test/java/org/opentripplanner/routing/core/TraverseModeSetTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTestRequest.java
Labels: new feature

#3719 Improve NeTEx import issue report
  src/main/java/org/opentripplanner/graph_builder/DataImportIssue.java
  src/main/java/org/opentripplanner/graph_builder/DataImportIssueStore.java
  src/main/java/org/opentripplanner/graph_builder/DataImportIssuesToHTML.java
  src/main/java/org/opentripplanner/graph_builder/Issue.java
  src/main/java/org/opentripplanner/netex/index/hierarchy/HierarchicalVersionMapById.java
  src/main/java/org/opentripplanner/netex/loader/parser/ServiceFrameParser.java
  src/main/java/org/opentripplanner/netex/mapping/BookingInfoMapper.java
  src/main/java/org/opentripplanner/netex/mapping/FlexStopLocationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/GroupOfStationsMapper.java
  src/main/java/org/opentripplanner/netex/mapping/MultiModalStationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/NoticeAssignmentMapper.java
  src/main/java/org/opentripplanner/netex/mapping/RouteMapper.java
  src/main/java/org/opentripplanner/netex/mapping/ServiceLinkMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopAndStationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
  src/main/java/org/opentripplanner/util/logging/AbstractFilterLogger.java
  src/main/java/org/opentripplanner/util/logging/MaxCountLogger.java
  src/main/java/org/opentripplanner/util/logging/ThrottleLogger.java
  src/test/java/org/opentripplanner/netex/mapping/AuthorityToAgencyMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/BookingInfoMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/NoticeAssignmentMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/RouteMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/StopTimesMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/TransportModeMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/TripPatternMapperTest.java
Labels: bug, Entur test

#3716 Do not create zero length StreetEdges
  pom.xml
  src/main/java/org/opentripplanner/common/geometry/SphericalDistanceLibrary.java
  src/main/java/org/opentripplanner/graph_builder/linking/AreaVisibilityAdjuster.java
  src/main/java/org/opentripplanner/graph_builder/linking/VertexLinker.java
  src/main/java/org/opentripplanner/graph_builder/module/StreetLinkerModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/PlatformLinker.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetWithElevationEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/TemporaryPartialStreetEdge.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/test/java/org/opentripplanner/common/geometry/SphericalDistanceLibraryTest.java
Labels: bug

#3710 Add pickup and dropoff booking info to REST API
  docs/sandbox/ActuatorAPI.md
  src/main/java/org/opentripplanner/api/mapping/BookingInfoMapper.java
  src/main/java/org/opentripplanner/api/mapping/BookingMethodMapper.java
  src/main/java/org/opentripplanner/api/mapping/BookingTimeMapper.java
  src/main/java/org/opentripplanner/api/mapping/ContactInfoMapper.java
  src/main/java/org/opentripplanner/api/mapping/LegMapper.java
  src/main/java/org/opentripplanner/api/model/ApiBookingInfo.java
  src/main/java/org/opentripplanner/api/model/ApiBookingTime.java
  src/main/java/org/opentripplanner/api/model/ApiContactInfo.java
  src/main/java/org/opentripplanner/api/model/ApiLeg.java
Labels: IBI test

#3664 Use the whole duration of the filtered transit data for the raptor heuristic search
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRoutingRequestTransitData.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRoutingRequestTransitDataCreator.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTransitDataProvider.java
  src/main/java/org/opentripplanner/transit/raptor/service/RangeRaptorDynamicSearch.java
  src/main/java/org/opentripplanner/transit/raptor/service/RaptorSearchWindowCalculator.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTransitData.java
  src/test/java/org/opentripplanner/transit/raptor/service/RaptorSearchWindowCalculatorTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
Labels: bug, improvement, Entur test

#3661 Perfomance improvement for flex access/egress searches
  docs/Configuration.md
  docs/SandboxExtension.md
  docs/sandbox/Flex.md
  mkdocs.yml
  src/ext/java/org/opentripplanner/ext/flex/FlexParameters.java
  src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
  src/ext/java/org/opentripplanner/ext/flex/edgetype/FlexTripEdge.java
  src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/DirectFlexPathCalculator.java
  src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/FlexPath.java
  src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/ScheduledFlexPathCalculator.java
  src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/StreetFlexPathCalculator.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessEgressTemplate.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessTemplate.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexEgressTemplate.java
  src/ext/java/org/opentripplanner/ext/flex/trip/FlexTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/DirectFlexRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/FlexAccessEgressRouter.java
  src/main/java/org/opentripplanner/routing/framework/DebugTimingAggregator.java
  src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
  src/main/java/org/opentripplanner/standalone/config/sandbox/FlexConfig.java
  src/main/resources/logback.xml
Labels: improvement, IBI test

#3722 Only run automatic changelog in the upstream repository [changelog skip]
  .github/workflows/automatic-changelog.yml
Labels: release management

#3729 Fix string formatting in NeTEx import issue report [changelog skip]
  src/main/java/org/opentripplanner/netex/mapping/StationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java
Labels: bug

#3727 Add Micrometer monitoring for GraphQL [changelog skip]
  docs/sandbox/ActuatorAPI.md
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
  src/ext/java/org/opentripplanner/ext/readiness_endpoint/MicrometerGraphQLInstrumentation.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraph.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/support/GqlUtil.java
Labels: new feature, sandbox, New GraphQL API, Entur test

#3720 Allow Flex trips to use the same stop_time for boarding and alighting [changelog skip]
  docs/Changelog.md
  docs/Interfaces-Data-Sources.md
  docs/SandboxExtension.md
  docs/sandbox/ActuatorAPI.md
  docs/sandbox/Flex.md
  mkdocs.yml
  src/ext-test/java/org/opentripplanner/ext/SandboxExtensionResourceTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/FlexTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/UnscheduledTripTest.java
  src/ext-test/resources/flex/aspen-flex-on-demand.gtfs.zip
  src/ext-test/resources/flex/cobblinc-scheduled-deviated-flex.gtfs.zip
  src/ext/java/org/opentripplanner/ext/actuator/ActuatorAPI.java
  src/ext/java/org/opentripplanner/ext/flex/README.md
  src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessEgressTemplate.java
  src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
  src/main/java/org/opentripplanner/api/configuration/APIEndpoints.java
  src/main/java/org/opentripplanner/graph_builder/model/GtfsBundle.java
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/standalone/server/OTPApplication.java
  src/main/java/org/opentripplanner/util/OTPFeature.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/graph_builder/module/geometry/GeometryAndBlockProcessorTest.java
Labels: improvement, IBI test

#3628 Add new routing errors for cases where all itineraries were filtered by post-processing
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/PlanResponse.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/RoutingErrorType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripType.java
  src/main/java/org/opentripplanner/api/mapping/PlannerErrorMapper.java
  src/main/java/org/opentripplanner/api/model/error/PlannerError.java
  src/main/java/org/opentripplanner/api/resource/PlannerResource.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChain.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/LatestDepartureTimeFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/RemoveTransitIfStreetOnlyIsBetterFilter.java
  src/main/java/org/opentripplanner/routing/api/response/RoutingError.java
  src/main/java/org/opentripplanner/routing/api/response/RoutingErrorCode.java
  src/main/java/org/opentripplanner/routing/core/RoutingContext.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainTest.java
Labels: improvement, Entur test

#3738 Transmodel API: Allow filtering by a list of ids [changelog skip]
  docs/sandbox/TransmodelApi.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
Labels: bug

#3737 Do not throw NPE in Place constructor [changelog skip]
  src/main/java/org/opentripplanner/model/plan/Place.java
  src/test/java/org/opentripplanner/model/plan/PlaceTest.java
Labels: bug

#3736 Remove AddMinSafeTransferCostFilter from itinerary-filter-chain
  docs/Configuration.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/ItineraryFiltersInputType.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filter/AddMinSafeTransferCostFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RoutingRequestToFilterChainMapper.java
  src/main/java/org/opentripplanner/routing/api/request/ItineraryFilterParameters.java
  src/main/java/org/opentripplanner/standalone/config/ItineraryFiltersMapper.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filter/AddMinSafeTransferCostFilterTest.java
Labels: bug

#3654 Add cost to maximize wait-time and avoid back-travel in optimize transfers
  docs/Configuration.md
  src/main/java/org/opentripplanner/model/base/OtpNumberFormat.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/OptimizeTransferService.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/TransferOptimizationObjCol.svg
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/api/TransferOptimizationParameters.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/configure/TransferOptimizationServiceConfigurator.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/MinSafeTransferTimeCalculator.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/OptimizedPathTail.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/TransferWaitTimeCalculator.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/package.md
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizePathDomainService.java
  src/main/java/org/opentripplanner/routing/api/request/TransferOptimizationRequest.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
  src/main/java/org/opentripplanner/transit/raptor/util/PathStringBuilder.java
  src/test/java/org/opentripplanner/model/base/OtpNumberFormatTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/model/MinSafeTransferTimeCalculatorTest.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/model/OptimizedPathTailTest.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/model/TransferWaitTimeCalculatorTest.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizePathDomainServiceConstrainedTest.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizePathDomainServiceTest.java
Labels: bug, technical debt, Entur test

#3741 Fix flex tests by taking into account that stops are a Set [changelog skip]
  src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/UnscheduledTripTest.java
  src/ext/java/org/opentripplanner/ext/flex/trip/FlexTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
Labels: IBI test

#3733 Logging first time instance reports it is ready to use
  src/ext-test/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandlerTest.java
  src/ext/java/org/opentripplanner/ext/actuator/ActuatorAPI.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriVMUpdater.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/updater/GraphUpdater.java
  src/main/java/org/opentripplanner/updater/GraphUpdaterConfigurator.java
  src/main/java/org/opentripplanner/updater/GraphUpdaterManager.java
  src/main/java/org/opentripplanner/updater/WriteToGraphCallback.java
  src/main/java/org/opentripplanner/updater/alerts/GtfsRealtimeAlertsUpdater.java
  src/main/java/org/opentripplanner/updater/stoptime/MqttGtfsRealtimeUpdater.java
  src/main/java/org/opentripplanner/updater/stoptime/PollingStoptimeUpdater.java
  src/main/java/org/opentripplanner/updater/stoptime/WebsocketGtfsRealtimeUpdater.java
  src/main/java/org/opentripplanner/updater/street_notes/WFSNotePollingGraphUpdater.java
  src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingUpdater.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdater.java
Labels: improvement, Entur test

#3746 Allow limiting the used vehicle rentals and parkings
  src/client/js/otp/widgets/tripoptions/TripOptionsWidget.js
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetVehicleParkingLink.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetVehicleRentalLink.java
  src/main/java/org/opentripplanner/routing/edgetype/VehicleRentalEdge.java
  src/main/java/org/opentripplanner/routing/vehicle_parking/VehicleParking.java
  src/main/java/org/opentripplanner/routing/vehicle_rental/VehicleRentalPlace.java
  src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
  src/test/java/org/opentripplanner/routing/algorithm/BikeRentalTest.java
  src/test/java/org/opentripplanner/routing/algorithm/CarParkAndRideTest.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
  src/test/java/org/opentripplanner/routing/algorithm/ParkAndRideTest.java
Labels: new feature

#3752 Don't filter out stops who don't have multimodal parents in Transmodel API nearest query [changelog skip]
  docs/sandbox/TransmodelApi.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/PlaceAtDistanceType.java
Labels: bug, sandbox, Entur test

#3706 Add support for car and scooter rental modes
  pom.xml
  src/client/js/otp/config.js
  src/client/js/otp/modules/planner/ItinerariesWidget.js
  src/client/js/otp/modules/planner/PlannerModule.js
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/java/org/opentripplanner/ext/smoovebikerental/SmooveBikeRentalDataSource.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/DefaultRoutingRequestType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/api/mapping/TraverseModeMapper.java
  src/main/java/org/opentripplanner/api/mapping/VehicleRentalStationMapper.java
  src/main/java/org/opentripplanner/api/parameter/ApiRequestMode.java
  src/main/java/org/opentripplanner/api/parameter/QualifiedModeSet.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/api/request/StreetMode.java
  src/main/java/org/opentripplanner/routing/core/State.java
  src/main/java/org/opentripplanner/routing/core/StateData.java
  src/main/java/org/opentripplanner/routing/core/StateEditor.java
  src/main/java/org/opentripplanner/routing/core/TraverseMode.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetTransitEntityLink.java
  src/main/java/org/opentripplanner/routing/edgetype/TemporaryFreeEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/VehicleParkingEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/VehicleRentalEdge.java
  src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
  src/main/java/org/opentripplanner/routing/spt/DominanceFunction.java
  src/main/java/org/opentripplanner/routing/vehicle_rental/RentalVehicleType.java
  src/main/java/org/opentripplanner/routing/vehicle_rental/VehicleRentalPlace.java
  src/main/java/org/opentripplanner/routing/vehicle_rental/VehicleRentalStation.java
  src/main/java/org/opentripplanner/routing/vehicle_rental/VehicleRentalVehicle.java
  src/main/java/org/opentripplanner/routing/vertextype/VehicleRentalStationVertex.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdater.java
  src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/routing/algorithm/BikeRentalTest.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
  src/test/java/org/opentripplanner/routing/algorithm/StreetModeLinkingTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/SnapshotTestBase.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/core/StateEditorTest.java
  src/test/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsVehicleRentalDataSourceTest.java
Labels: new feature, Entur test

#3753 Remove old visibility graph library from walkable area builder
  pom.xml
  src/main/java/org/opentripplanner/graph_builder/issues/AreaNotEpsilonValid.java
  src/main/java/org/opentripplanner/graph_builder/linking/VertexLinker.java
  src/main/java/org/opentripplanner/graph_builder/module/StreetLinkerModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/Area.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/AreaGroup.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/PlatformLinker.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/Ring.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  src/main/java/org/opentripplanner/routing/edgetype/AreaEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/AreaEdgeList.java
  src/main/java/org/opentripplanner/routing/edgetype/EdgeWithCleanup.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/visibility/Angle.java
  src/main/java/org/opentripplanner/visibility/BoundingBox.java
  src/main/java/org/opentripplanner/visibility/Environment.java
  src/main/java/org/opentripplanner/visibility/IncidentEdgeCompare.java
  src/main/java/org/opentripplanner/visibility/LineSegment.java
  src/main/java/org/opentripplanner/visibility/PolarEdge.java
  src/main/java/org/opentripplanner/visibility/PolarPoint.java
  src/main/java/org/opentripplanner/visibility/PolarPointWithEdgeInfo.java
  src/main/java/org/opentripplanner/visibility/Polyline.java
  src/main/java/org/opentripplanner/visibility/Ray.java
  src/main/java/org/opentripplanner/visibility/Util.java
  src/main/java/org/opentripplanner/visibility/VLPoint.java
  src/main/java/org/opentripplanner/visibility/VLPolygon.java
  src/main/java/org/opentripplanner/visibility/VisibilityGraph.java
  src/main/java/org/opentripplanner/visibility/VisibilityPolygon.java
  src/main/java/org/opentripplanner/visibility/pair.java
  src/test/java/org/opentripplanner/graph_builder/linking/LinkStopToPlatformTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/PlatformLinkerTest.java
  src/test/java/org/opentripplanner/visibility/TestVisibilityGraph.java
Labels: bug, Entur test
