Repository opentripplanner/OpenTripPlanner, pull requests merged in 2021-06, with the labels that each got.

#3190 Add snapshot routing tests using the Portland graph
  .gitignore
  docs/Developers-Guide.md
  pom.xml
  src/main/java/org/opentripplanner/api/parameter/ApiRequestMode.java
  src/main/java/org/opentripplanner/api/parameter/QualifiedMode.java
  src/main/java/org/opentripplanner/graph_builder/module/bike/BikeRentalModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/model/plan/Place.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/bike_rental/BikeRentalStation.java
  src/main/java/org/opentripplanner/routing/core/State.java
  src/main/java/org/opentripplanner/routing/core/StateEditor.java
  src/main/java/org/opentripplanner/routing/edgetype/BikeRentalEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetBikeRentalLink.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetTransitEntityLink.java
  src/main/java/org/opentripplanner/routing/spt/DominanceFunction.java
  src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/routing/algorithm/BikeRentalTest.java
  src/test/java/org/opentripplanner/routing/algorithm/CarPickupTest.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/BikeRentalSnapshotTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/SnapshotTestBase.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/TransitSnapshotTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/street/BicycleRoutingTest.java
  src/test/resources/portland-central-filtered.osm.pbf
Labels: awaiting response, technical debt

#3502 Use duration limits instead of maxWalkDistance
  src/client/js/otp/modules/multimodal/MultimodalPlannerModule.js
  src/client/js/otp/modules/planner/ItinerariesWidget.js
  src/client/js/otp/widgets/tripoptions/TripOptionsWidget.js
  src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/StreetFlexPathCalculator.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/DefaultRoutingRequestType.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/api/mapping/ItineraryMapper.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/AStar.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/strategies/DurationSkipEdgeStrategy.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/strategies/SearchTerminationStrategy.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/strategies/SkipEdgeStrategy.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/AccessEgressRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/DirectFlexRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/DirectStreetRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/FlexAccessEgressRouter.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/api/request/StreetMode.java
  src/main/java/org/opentripplanner/routing/core/TraversalRequirements.java
  src/main/java/org/opentripplanner/routing/graphfinder/PlaceFinderTraverseVisitor.java
  src/main/java/org/opentripplanner/routing/graphfinder/StopFinderTraverseVisitor.java
  src/main/java/org/opentripplanner/routing/graphfinder/StreetGraphFinder.java
  src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
  src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java
  src/test/java/org/opentripplanner/routing/TestHalfEdges.java
  src/test/java/org/opentripplanner/routing/algorithm/AStarTest.java
  src/test/java/org/opentripplanner/routing/algorithm/BikeRentalTest.java
  src/test/java/org/opentripplanner/routing/algorithm/CarPickupTest.java
  src/test/java/org/opentripplanner/routing/algorithm/MultiTargetTerminationStrategy.java
  src/test/java/org/opentripplanner/routing/algorithm/TestAStar.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/BikeRentalSnapshotTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/SnapshotTestBase.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/TransitSnapshotTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
Labels: Entur test

#3532 Do not add alert patches to legs that are not transit legs
  src/main/java/org/opentripplanner/routing/algorithm/mapping/AlertToLegMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
Labels: Entur test

#3537 Map NeTEx StopPlace and Quay descriptions
  src/main/java/org/opentripplanner/netex/mapping/StationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopMapper.java
Labels: Entur test

#3539 Allow fetching notices on stop times
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/TimetabledPassingTimeType.java
  src/main/java/org/opentripplanner/model/TripTimeShort.java
Labels: Entur test, sandbox

#3546 Fix NPE when checking for access/egress mode
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
Labels: bug

#3545 Adding support for including realtime-added trips in trip-requests
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
Labels: Entur test
