Repository opentripplanner/OpenTripPlanner, pull requests merged in 2021-03, with the labels that each got.

#3345 Add ParkAndRide API as sandbox extension
  docs/SandboxExtension.md
  docs/sandbox/ParkAndRideApi.md
  mkdocs.yml
  src/ext/java/org/opentripplanner/ext/parkAndRideApi/ParkAndRideResource.java
  src/main/java/org/opentripplanner/api/configuration/APIEndpoints.java
  src/main/java/org/opentripplanner/util/OTPFeature.java
Labels: sandbox

#3364 Use the station name for pathway levels if no value is provided
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
Labels: bug, improvement

#3365 Beautify DebugAggregator log output
  src/main/java/org/opentripplanner/routing/framework/DebugAggregator.java
Labels: bug, improvement

#3360 Simplify handling of bikes allowed
  docs/Changelog.md
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLRouteImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
  src/main/java/org/opentripplanner/api/mapping/BikeAccessMapper.java
  src/main/java/org/opentripplanner/api/mapping/RouteMapper.java
  src/main/java/org/opentripplanner/api/mapping/TripMapper.java
  src/main/java/org/opentripplanner/graph_builder/model/GtfsBundle.java
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/gtfs/mapping/BikeAccessMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/RouteMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/TripMapper.java
  src/main/java/org/opentripplanner/model/BikeAccess.java
  src/main/java/org/opentripplanner/model/Route.java
  src/main/java/org/opentripplanner/model/Trip.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RoutingRequestTransitDataProviderFilter.java
  src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java
  src/test/java/org/opentripplanner/graph_builder/module/GtfsGraphBuilderModuleTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/BikeAccessMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/RouteMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java
  src/test/java/org/opentripplanner/model/BikeAccessTest.java
  src/test/java/org/opentripplanner/netex/NetexBundleSmokeTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RoutingRequestTransitDataProviderFilterTest.java
  src/test/java/org/opentripplanner/routing/trippattern/TripTimesTest.java
Labels: improvement

#3368 Use correct method to update tripPatternsRunningOnDateMapCache
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransitLayerUpdater.java
Labels: Entur test, bug

#3367 Otp2 fix add cost for first alight slack
  docs/Changelog.md
  docs/Configuration.md
  src/main/java/org/opentripplanner/standalone/config/TransitRoutingConfig.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/DynamicSearchWindowCoefficients.java
  src/main/java/org/opentripplanner/transit/raptor/api/view/Heuristics.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/McRangeRaptorWorkerState.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/McTransitWorker.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/PatternRide.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/heuristics/HeuristicsAdapter.java
  src/main/java/org/opentripplanner/transit/raptor/service/RangRaptorDynamicSearch.java
  src/main/java/org/opentripplanner/transit/raptor/service/RaptorSearchWindowCalculator.java
  src/test/java/org/opentripplanner/transit/raptor/service/RaptorSearchWindowCalculatorTest.java
Labels: Entur test, bug, improvement

#3347 Booking rules
  pom.xml
  src/ext/java/org/opentripplanner/ext/flex/FlexLegMapper.java
  src/ext/java/org/opentripplanner/ext/flex/edgetype/FlexTripEdge.java
  src/ext/java/org/opentripplanner/ext/flex/trip/FlexTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/BookingArrangementType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/ServiceJourneyType.java
  src/main/java/org/opentripplanner/api/mapping/LegMapper.java
  src/main/java/org/opentripplanner/model/BookingInfo.java
  src/main/java/org/opentripplanner/model/BookingMethod.java
  src/main/java/org/opentripplanner/model/ContactInfo.java
  src/main/java/org/opentripplanner/model/StopTime.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/netex/mapping/BookingInfoMapper.java
  src/main/java/org/opentripplanner/netex/mapping/BookingMethodMapper.java
  src/main/java/org/opentripplanner/netex/mapping/BookingTime.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/trippattern/Deduplicator.java
  src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java
  src/main/java/org/opentripplanner/standalone/OTPMain.java
  src/test/java/org/opentripplanner/netex/mapping/BookingInfoMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/StopTimesMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/TripPatternMapperTest.java
  src/test/java/org/opentripplanner/routing/trippattern/DeduplicatorTest.java
Labels: Entur, Entur test

#3351 SimpleStreetSplitter refactor
  src/ext/java/org/opentripplanner/ext/flex/FlexLocationsToStreetEdgesMapper.java
  src/ext/java/org/opentripplanner/ext/parkAndRideApi/ParkAndRideResource.java
  src/ext/java/org/opentripplanner/ext/transferanalyzer/DirectTransferAnalyzer.java
  src/main/java/org/opentripplanner/graph_builder/linking/AreaVisibilityAdjuster.java
  src/main/java/org/opentripplanner/graph_builder/linking/DisposableEdgeCollection.java
  src/main/java/org/opentripplanner/graph_builder/linking/FlexLocationAdder.java
  src/main/java/org/opentripplanner/graph_builder/linking/LinkingDirection.java
  src/main/java/org/opentripplanner/graph_builder/linking/SameEdgeAdjuster.java
  src/main/java/org/opentripplanner/graph_builder/linking/Scope.java
  src/main/java/org/opentripplanner/graph_builder/linking/SimpleStreetSplitter.java
  src/main/java/org/opentripplanner/graph_builder/linking/StreetSpatialIndex.java
  src/main/java/org/opentripplanner/graph_builder/linking/VertexLinker.java
  src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
  src/main/java/org/opentripplanner/graph_builder/module/StopsAlerts.java
  src/main/java/org/opentripplanner/graph_builder/module/StreetLinkerModule.java
  src/main/java/org/opentripplanner/graph_builder/module/TransitToTaggedStopsModule.java
  src/main/java/org/opentripplanner/inspector/EdgeVertexTileRenderer.java
  src/main/java/org/opentripplanner/routing/RoutingService.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/DirectStreetRouter.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/core/RoutingContext.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java
  src/main/java/org/opentripplanner/routing/edgetype/TemporaryPartialStreetEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/TransitEntranceLink.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/routing/graphfinder/DirectGraphFinder.java
  src/main/java/org/opentripplanner/routing/impl/StreetVertexIndex.java
  src/main/java/org/opentripplanner/routing/vertextype/TemporarySplitterVertex.java
  src/main/java/org/opentripplanner/updater/bike_park/BikeParkUpdater.java
  src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java
  src/main/java/org/opentripplanner/updater/street_notes/WFSNotePollingGraphUpdater.java
  src/test/java/org/opentripplanner/graph_builder/linking/LinkStopToPlatformTest.java
  src/test/java/org/opentripplanner/graph_builder/linking/SimpleStreetSplitterTest.java
  src/test/java/org/opentripplanner/graph_builder/module/FakeGraph.java
  src/test/java/org/opentripplanner/graph_builder/module/linking/LinkingTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestOpenStreetMapGraphBuilder.java
  src/test/java/org/opentripplanner/routing/TestHalfEdges.java
  src/test/java/org/opentripplanner/routing/core/StateEditorTest.java
  src/test/java/org/opentripplanner/routing/edgetype/TemporaryPartialStreetEdgeTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/transit/EgressAccessRouter.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/transit/StreetSearch.java
Labels: Entur test

#3373 Improve documentation for LegacyGraphQLApi
  docs/Getting-OTP.md
  docs/sandbox/LegacyGraphQLApi.md
  docs/sandbox/MapboxVectorTilesApi.md
Labels: improvement, sandbox

#3378 Remove unused joda-time
  pom.xml
  src/main/java/org/opentripplanner/api/json/JodaLocalDateDeserializer.java
  src/main/java/org/opentripplanner/api/json/JodaLocalDateSerializer.java
  src/main/java/org/opentripplanner/util/time/RelativeTime.java
  src/main/java/org/opentripplanner/util/time/TimeUtils.java
Labels: technical debt

#3376 Code style updated.
  intellij-code-style.xml
Labels: technical debt

#3381 Otp2 improve debug logging and remove otp-batch-analyst script
  .gitignore
  pom.xml
  src/ext/java/org/opentripplanner/ext/interactivelauncher/InteractiveOtpMain.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/Model.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/OptionsView.java
  src/main/java/org/opentripplanner/model/base/ToStringBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/api/response/RoutingResponse.java
  src/main/java/org/opentripplanner/routing/framework/DebugTimingAggregator.java
  src/main/java/org/opentripplanner/transit/raptor/RaptorService.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/RaptorRequest.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/SearchParams.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RangeRaptorWorker.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/besttimes/BestTimes.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/heuristics/HeuristicsAdapter.java
  src/main/java/org/opentripplanner/transit/raptor/service/HeuristicSearchTask.java
  src/main/java/org/opentripplanner/transit/raptor/service/RangRaptorDynamicSearch.java
  src/main/resources/logback.xml
  src/scripts/otp
  src/scripts/otp-batch-analyst
  src/scripts/otp-ui
  src/test/java/org/opentripplanner/model/base/ToStringBuilderTest.java
Labels: technical debt
