Repository opentripplanner/OpenTripPlanner, pull requests merged in 2021-02, with the labels that each got.

#3335 Remove poor transit results for short trips, when walking is better
  docs/Changelog.md
  src/main/java/org/opentripplanner/api/resource/PlannerResource.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/RemoveWalkOnlyFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RoutingRequestToFilterChainMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/FilterTransitWhenDirectModeIsEmpty.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/TransferToAccessEgressLegMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/RaptorRequestMapper.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/RemoveWalkOnlyFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptor/router/FilterTransitWhenDirectModeIsEmptyTest.java
Labels: improvement

#3344 Fix: Test not working after auto merging of PRs: #3335 and #3337
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/RemoveWalkOnlyFilterTest.java
Labels: bug

#3334 Add support for actualArrivalTimes and actualDepartureTimes
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStoptimeImpl.java
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/TripTimeShortHelper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/JourneyWhiteListed.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/TimetabledPassingTimeType.java
  src/main/java/org/opentripplanner/api/mapping/TripTimeMapper.java
  src/main/java/org/opentripplanner/model/TripTimeShort.java
  src/main/java/org/opentripplanner/routing/StopTimesHelper.java
  src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java
Labels: Entur test

#3278 Save all nodes even if they contain bikeRental/bikeParking tags
  src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java
Labels: bug

#3341 Add Direction enum to OTP model and add Netex mapping
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPatternImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTripPatternIdGenerator.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/JourneyPatternType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/ServiceJourneyType.java
  src/main/java/org/opentripplanner/api/mapping/TripMapper.java
  src/main/java/org/opentripplanner/gtfs/GenerateTripPatternsOperation.java
  src/main/java/org/opentripplanner/gtfs/mapping/TripMapper.java
  src/main/java/org/opentripplanner/model/Direction.java
  src/main/java/org/opentripplanner/model/Trip.java
  src/main/java/org/opentripplanner/model/TripPattern.java
  src/main/java/org/opentripplanner/netex/DirectionMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripMapper.java
  src/main/java/org/opentripplanner/updater/GtfsRealtimeFuzzyTripMatcher.java
  src/main/java/org/opentripplanner/updater/stoptime/TripPatternCache.java
  src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java
  src/test/java/org/opentripplanner/model/impl/OtpTransitServiceBuilderLimitPeriodTest.java
  src/test/java/org/opentripplanner/netex/NetexBundleSmokeTest.java
Labels: Entur test, Netex

#3340 Otp2 include planned cancellations
  pom.xml
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/DefaultRoutingRequestType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
  src/main/java/org/opentripplanner/model/Trip.java
  src/main/java/org/opentripplanner/model/TripAlteration.java
  src/main/java/org/opentripplanner/netex/mapping/TripMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripServiceAlterationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/calendar/DatedServiceJourneyMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/TripPatternForDate.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRoutingRequestTransitDataCreator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RoutingRequestTransitDataProviderFilter.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/test/java/org/opentripplanner/netex/mapping/TripMapperTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RoutingRequestTransitDataProviderFilterTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
Labels: Entur test

#3349 Correctly fill out platformCode during itinerary mapping
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
Labels: bug

#3338 doc: Update the PR Template
  .github/pull_request_template.md
Labels: documentation

#3356 Otp2 speed test imprive graph loding
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/LineType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/ServiceJourneyType.java
  src/main/java/org/opentripplanner/netex/issues/DayTypeScheduleIsEmpty.java
  src/main/java/org/opentripplanner/netex/issues/ObjectNotFound.java
  src/main/java/org/opentripplanner/netex/mapping/TripCalendarBuilder.java
  src/main/java/org/opentripplanner/netex/mapping/calendar/DatedServiceJourneyMapper.java
  src/main/java/org/opentripplanner/netex/mapping/calendar/DayTypeAssignmentMapper.java
  src/main/java/org/opentripplanner/netex/validation/DSJOperatingDayNotFound.java
  src/main/java/org/opentripplanner/netex/validation/DSJServiceJourneyNotFound.java
  src/main/java/org/opentripplanner/netex/validation/JourneyPatternNotFoundInSJ.java
  src/main/java/org/opentripplanner/netex/validation/PassengerStopAssignmentQuayNotFound.java
  src/main/java/org/opentripplanner/standalone/config/ConfigLoader.java
  src/test/java/org/opentripplanner/netex/mapping/calendar/DayTypeAssignmentMapperTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/options/SpeedTestConfig.java
Labels: sandbox

#3350 Fix #3014. Support for depart after or arrive before a specific time
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/RaptorRequestMapper.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/SearchParams.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/SearchParamsBuilder.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/PathParetoSetComparators.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/configure/PathConfig.java
  src/test/java/org/opentripplanner/transit/raptor/api/request/SearchParamsTest.java
Labels: improvement

#3353 RAPTOR: keep track of used RaptorTransfers during traversal
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/TransferWithDuration.java
  src/main/java/org/opentripplanner/transit/raptor/api/path/TransferPathLeg.java
  src/main/java/org/opentripplanner/transit/raptor/api/view/TransferPathView.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/arrivals/TransferStopArrival.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/ForwardPathMapper.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/ReversePathMapper.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/stoparrivals/AccessStopArrivalState.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/stoparrivals/StopArrivalState.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/stoparrivals/Stops.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/stoparrivals/view/StopsCursor.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/stoparrivals/view/Transfer.java
  src/test/java/org/opentripplanner/transit/raptor/_data/stoparrival/StopArrivalsTestData.java
  src/test/java/org/opentripplanner/transit/raptor/_data/stoparrival/Walk.java
Labels: improvement
