Repository opentripplanner/OpenTripPlanner, pull requests merged in 2021-12, with the labels that each got.

#3755 Handle miscellaneous service as BUS instead of crashing build
  src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/RouteMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/TransitModeMapper.java
  src/main/java/org/opentripplanner/netex/mapping/RouteMapper.java
  src/test/java/org/opentripplanner/gtfs/mapping/FareRuleMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/FrequencyMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/RouteMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/StopTimesMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/TransferMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java
Labels: improvement, GTFS

#3744 Update all timers to micrometer instances
  src/ext/java/org/opentripplanner/ext/actuator/ActuatorAPI.java
  src/ext/java/org/opentripplanner/ext/actuator/MicrometerGraphQLInstrumentation.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLdebugOutputImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelAPI.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelAPIParameters.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraph.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/AuthorityType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/OperatorType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/JourneyPatternType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/ServiceJourneyType.java
  src/main/java/org/opentripplanner/api/resource/DebugOutput.java
  src/main/java/org/opentripplanner/api/resource/TransitTimingOutput.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/framework/DebugTimingAggregator.java
  src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
  src/main/java/org/opentripplanner/standalone/config/sandbox/TransmodelAPIConfig.java
  src/main/java/org/opentripplanner/standalone/configure/OTPAppConstruction.java
  src/main/java/org/opentripplanner/standalone/server/OTPApplication.java
  src/main/java/org/opentripplanner/standalone/server/Router.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RangeRaptorWorker.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/configure/RaptorConfig.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/debug/WorkerPerformanceTimers.java
  src/main/java/org/opentripplanner/transit/raptor/service/WorkerPerformanceTimersCache.java
  src/main/java/org/opentripplanner/transit/raptor/util/AvgTimer.java
  src/main/java/org/opentripplanner/util/logging/MetricsLogging.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/ResultPrinter.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/transit/EgressAccessRouter.java
Labels: improvement

#3762 Bugfix: ClassCastException when planning flex routes
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/OptimizedPathTail.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/model/OptimizedPathTailTest.java
  src/test/java/org/opentripplanner/transit/raptor/_data/stoparrival/BasicPathTestCase.java
Labels: IBI test

#3751 Add mode from parent StopPlace for Quays in Netex mapper
  src/main/java/org/opentripplanner/netex/mapping/StopAndStationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopMapper.java
Labels: improvement, Entur test, NeTEx

#3767 Minor performance improvements
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetTraversalPermission.java
Labels: improvement

#3766 Parallelise computing of trip pattern geometries
  src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryAndBlockProcessor.java
  src/main/java/org/opentripplanner/util/ProgressTracker.java
Labels: optimization

#3782 Fix checking allowed boarding/alighting for unscheduled flex trips
  src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
  src/main/java/org/opentripplanner/api/parameter/QualifiedModeSet.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
Labels: bug

#3742 Calculating number of days to use in StopTimes-request
  src/main/java/org/opentripplanner/routing/stoptimes/StopTimesHelper.java
Labels: Entur test

#3765 Walkable area builder improvements
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/linking/VertexLinker.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/Ring.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMNode.java
  src/main/java/org/opentripplanner/routing/edgetype/AreaEdgeList.java
  src/main/java/org/opentripplanner/standalone/configure/OTPAppConstruction.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/RingTest.java
Labels: improvement, Entur test

#3784 Remove hardcoded alighting/boarding on first/last stop
  src/main/java/org/opentripplanner/model/StopPattern.java
Labels: bug, Entur test

#3788 refactor: Rename SpeedTest config parameter to maxWalkDurationSeconds [changelog skip]
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTestRequest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/options/SpeedTestConfig.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/transit/EgressAccessRouter.java
  src/test/resources/raptor/speedtest/norway/speed-test-config.json
Labels: technical debt

#3786 Update logback dependency to 1.2.8 (1.2.5) [changelog skip]
  pom.xml
Labels: technical debt, Entur test

#3790 Add tags and openingHours to CarPark and BikePark in legacy api [changelog skip]
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLBikeParkImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLCarParkImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
Labels: sandbox

#3771 Add support for include-file-directive in config files.
  docs/Configuration.md
  src/main/java/org/opentripplanner/standalone/config/ConfigLoader.java
  src/main/java/org/opentripplanner/standalone/config/IncludeFileDirective.java
  src/test/java/org/opentripplanner/standalone/config/IncludeFileDirectiveTest.java
Labels: improvement

#3791 Remove build parameter 'useTransfersTxt'
  docs/Configuration.md
  docs/examples/entur/build-config.json
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/model/GtfsBundle.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/test/java/org/opentripplanner/GtfsTest.java
Labels: technical debt
