Repository opentripplanner/OpenTripPlanner, pull requests merged in 2022-02, with the labels that each got.

#3850 Filter out elevator ways that are also implicit areas
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
Labels: bug

#3837 Narrow down non-null types to improve schema and docs
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripPatternType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
Labels: sandbox

#3824 Dynamically compute additional search days
  src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/AdditionalSearchDays.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/DirectFlexRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/FlexAccessEgressRouter.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
  src/test/java/org/opentripplanner/routing/algorithm/FaresTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptor/router/AdditionalSearchDaysTest.java
Labels: improvement

#3844 Mode & submode filter for NeTEx Service Journeys
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RoutingRequestTransitDataProviderFilter.java
  src/test/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RoutingRequestTransitDataProviderFilterTest.java
Labels: improvement

#3858 feat: Enable Raptor stop-arrivals event debugging [changelog skip]
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/RaptorRequestMapper.java
  src/main/java/org/opentripplanner/routing/api/request/DebugRaptor.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/transit/raptor/RaptorService.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/DebugRequestBuilder.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/SystemErrDebugLogger.java
  src/test/java/org/opentripplanner/routing/api/request/DebugRaptorTest.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTransitData.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTestRequest.java
Labels: technical debt

#3856 Remove unused field `orig` from `Place` [changelog skip]
  src/main/java/org/opentripplanner/api/mapping/PlaceMapper.java
  src/main/java/org/opentripplanner/api/model/ApiPlace.java
  src/main/java/org/opentripplanner/model/plan/Place.java
Labels: technical debt

#3857 Take free-floating vehicles into account when calculating state [changelog skip]
  docs/sandbox/LegacyGraphQLApi.md
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLBikeRentalStationImpl.java
Labels: bug

#3854 Deduce enum for bookWhen in Transmodel API [changelog skip]
  docs/sandbox/TransmodelApi.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/BookingArrangementType.java
Labels: improvement, Entur test, NeTEx

#3852 Fix vehicle parking updater for ParkAPI [changelog skip]
  src/main/java/org/opentripplanner/standalone/config/updaters/VehicleParkingUpdaterConfig.java
Labels: bug

#3855 Allow for null values in vector tiles mapper [changelog skip]
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/DigitransitStopPropertyMapper.java
Labels: bug

#3859 Correct elevation profile handling in StreetWithElevationEdge [changelog skip]
  src/main/java/org/opentripplanner/routing/edgetype/StreetWithElevationEdge.java
  src/test/java/org/opentripplanner/routing/edgetype/PlainStreetEdgeTest.java
Labels: bug

#3863 Fix speed test results [changelog skip]
  test/ci-performance-test/travelSearch-expected-results.csv
Labels: technical debt

#3860 Otp2 remove lombok [changelog skip]
  pom.xml
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
  src/main/java/org/opentripplanner/index/IndexAPI.java
  src/main/java/org/opentripplanner/routing/RoutingService.java
  src/main/java/org/opentripplanner/standalone/config/IncludeFileDirective.java
  src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
  src/test/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/StopIndexForRaptorTest.java
Labels: technical debt

#3830 Implement minimum transfer time from GTFS transfers.txt
  docs/Configuration.md
  src/ext/java/org/opentripplanner/ext/reportapi/model/TransfersReport.java
  src/main/java/org/opentripplanner/gtfs/mapping/TransferMapper.java
  src/main/java/org/opentripplanner/model/transfer/TransferConstraint.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/constrainedtransfer/ConstrainedBoardingSearch.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/constrainedtransfer/ConstrainedBoardingSearchForward.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/constrainedtransfer/ConstrainedBoardingSearchReverse.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/constrainedtransfer/ConstrainedBoardingSearchStrategy.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/constrainedtransfer/ConstrainedTransferBoarding.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/constrainedtransfer/TransferIndexGenerator.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGenerator.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorConstrainedTripScheduleBoardingSearch.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTripScheduleBoardOrAlightEvent.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RangeRaptorWorker.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RoutingStrategy.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/ArrivalTimeRoutingStrategy.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/MinTravelDurationRoutingStrategy.java
  src/main/java/org/opentripplanner/util/OTPFeature.java
  src/test/java/org/opentripplanner/model/impl/OtpTransitServiceImplTest.java
  src/test/java/org/opentripplanner/model/transfer/TransferConstraintTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptor/transit/constrainedtransfer/ConstrainedBoardingSearchTest.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGeneratorTest.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestConstrainedBoardingSearch.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestConstrainedTransfer.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestRoute.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTransitData.java
  src/test/resources/testagency/transfers.txt
Labels: new feature, Regression

#3871 Fix number format exception for elevator duration parsing OSM data
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/VertexAndName.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
Labels: bug

#3864 Include generalizedCost in the optimized transfers wait-time cost
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/api/OptimizedPath.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/api/TransferOptimized.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/OptimizedPathTail.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferOptimizedFilterFactory.java
  src/main/java/org/opentripplanner/transit/raptor/util/PathStringBuilder.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/api/OptimizedPathTest.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/model/OptimizedPathTailTest.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizePathDomainServiceTest.java
Labels: bug

#3846 Minor Transmodel GraphQL API improvements [changelog skip]
  docs/sandbox/TransmodelApi.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/ServiceJourneyType.java
Labels: bug, improvement, sandbox, Entur test

#3876 Log warning if the rootdir contain configuration. [changelog skip]
  src/ext/java/org/opentripplanner/ext/interactivelauncher/Model.java
Labels: improvement, sandbox

#3831 Implement in-seat transfers per GTFS draft
  src/main/java/org/opentripplanner/gtfs/mapping/TransferMapper.java
Labels: new feature, GTFS

#3832 Add stairsTimeFactor to StreetEdge
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/Transfer.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRequestTransferCache.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetWithElevationEdge.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
Labels: improvement

#3879 Fixes NPE in Netex ServiceLinkMapper [changelog skip]
  src/main/java/org/opentripplanner/netex/mapping/ServiceLinkMapper.java
Labels: improvement, NeTEx

#3882 Update org.processing:core from 1.0.7 to 2.2.1 [changelog skip]
  pom.xml
  src/main/java/org/opentripplanner/visualizer/ShowGraph.java
Labels: technical debt

#3833 Make sure we keep the itinerary with the least number of transfers when grouping the itineraries
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/comparator/SortOrderComparator.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filter/RemoveDeletionFlagForLeastTransfersItinerary.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/comparator/SortOnNumberOfTransfersTest.java
Labels: improvement, Entur test

#3881 Update graphql codegen dependencies to fix issue with enum args [changelog skip]
  docs/sandbox/LegacyGraphQLApi.md
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLAgencyImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLFeedImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPatternImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPlaceImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLRouteImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/package.json
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/yarn.lock
Labels: technical debt

#3868 Don't expect every pattern in a route to have the specified stop with constrained transfers
  src/main/java/org/opentripplanner/model/StopPattern.java
  src/main/java/org/opentripplanner/model/TripPattern.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/constrainedtransfer/TransferIndexGenerator.java
Labels: bug

#3865 Otp2 doc updates [changelog skip]
  README.md
  docs/BuildConfiguration.md
  docs/Configuration.md
  docs/OTP2-MigrationGuide.md
  docs/RouterConfiguration.md
  mkdocs.yml
Labels: documentation

#3891 Extract StatesToWalkStepsMapper from GraphPathToItineraryMapper [changelog skip]
  src/main/java/org/opentripplanner/api/mapping/WalkStepMapper.java
  src/main/java/org/opentripplanner/api/model/ApiWalkStep.java
  src/main/java/org/opentripplanner/model/plan/WalkStep.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapper.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
Labels: technical debt

#3885 Add try/catch to find the problem of the flaky BikeRentalSnapshotTest [changelog skip]
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/error/RoutingValidationException.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/BikeRentalSnapshotTest.java
Labels: technical debt

#3892 Store a proper Geometry on the leg, not an encoded version [changelog skip]
  src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLGeometryImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLLegImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPatternImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopGeometriesImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/graphql-codegen.yml
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
  src/main/java/org/opentripplanner/api/mapping/LegMapper.java
  src/main/java/org/opentripplanner/common/geometry/GeometryUtils.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/test/java/org/opentripplanner/routing/street/BarrierRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/BicycleRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/CarRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/SplitEdgeTurnRestrictionsTest.java
Labels: technical debt

#3878 Add support for creating constrained transfers from real-time generated patterns
  src/main/java/org/opentripplanner/model/TripPattern.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/TransitLayer.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/TripPatternWithRaptorStopIndexes.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/constrainedtransfer/TransferIndexGenerator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransitLayerMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransitLayerUpdater.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TripPatternMapper.java
Labels: bug

#3888 Account for stay seated transfers when calculating the number of transfers
  src/main/java/org/opentripplanner/transit/raptor/api/path/Path.java
  src/main/java/org/opentripplanner/transit/raptor/api/path/TransitPathLeg.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTransferConstraint.java
  src/test/java/org/opentripplanner/transit/raptor/api/path/PathTest.java
Labels: bug

#3903 Avoid creating null NonLocalizedStrings for pathways [changelog skip]
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
Labels: bug

#3883 Add support for NeTEx VIA's
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/DestinationDisplayType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
  src/main/java/org/opentripplanner/model/StopTime.java
  src/main/java/org/opentripplanner/model/TripTimeOnDate.java
  src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java
  src/main/java/org/opentripplanner/routing/trippattern/Deduplicator.java
  src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java
  src/test/java/org/opentripplanner/netex/mapping/NetexTestDataSample.java
  src/test/java/org/opentripplanner/netex/mapping/StopTimesMapperTest.java
  src/test/java/org/opentripplanner/routing/trippattern/DeduplicatorTest.java
Labels: Skanetrafiken

#3918 Turn ParallelRouting off
  docs/Configuration.md
  src/main/java/org/opentripplanner/util/OTPFeature.java
Labels: bug

#3895 Use PickDrop enum in Leg and FlexTrip [changelog skip]
  src/ext/java/org/opentripplanner/ext/flex/FlexLegMapper.java
  src/ext/java/org/opentripplanner/ext/flex/trip/FlexTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLLegImpl.java
  src/main/java/org/opentripplanner/api/mapping/LegMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/TransferMapper.java
  src/main/java/org/opentripplanner/model/PickDrop.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
Labels: technical debt

#3922 feat: Fix problem with Kryo and Java immutable Set and List [changelog skip]
  src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
  src/main/java/org/opentripplanner/routing/graph/kryosupport/JavaImmutableListSerializer.java
  src/main/java/org/opentripplanner/routing/graph/kryosupport/JavaImmutableSetSerializer.java
  src/main/java/org/opentripplanner/routing/graph/kryosupport/KryoBuilder.java
Labels: technical debt

#3898 NeTEx mapping to StopTime.timepoint
  src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java
  src/test/java/org/opentripplanner/netex/mapping/StopTimesMapperTest.java
Labels: Skanetrafiken

#3924 Optimize filtering of trips in TripPatternForDate [changelog skip]
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/TripPatternForDate.java
Labels: optimization

#3923 Optimize transit data creation when only main modes are in specified request [changelog skip]
  src/main/java/org/opentripplanner/model/modes/AllowedTransitMode.java
  src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RoutingRequestTransitDataProviderFilter.java
Labels: optimization

#3896 Split Leg into interface and three implementing classes [changelog skip]
  src/ext/java/org/opentripplanner/ext/flex/FlexLegMapper.java
  src/ext/java/org/opentripplanner/ext/flex/FlexibleTransitLeg.java
  src/main/java/org/opentripplanner/api/mapping/LegMapper.java
  src/main/java/org/opentripplanner/api/model/ApiLeg.java
  src/main/java/org/opentripplanner/model/calendar/ServiceDate.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
  src/main/java/org/opentripplanner/model/plan/StreetLeg.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/test/java/org/opentripplanner/model/plan/LegTest.java
  src/test/java/org/opentripplanner/model/plan/PlanTestConstants.java
  src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/BikeRentalSnapshotTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/SnapshotTestBase.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
Labels: technical debt

#3899 Make turn restrictions faster and thread-safe by moving them into StreetEdge
  pom.xml
  src/main/java/org/opentripplanner/common/TurnRestriction.java
  src/main/java/org/opentripplanner/graph_builder/linking/VertexLinker.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/routing/RoutingService.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/TemporaryPartialStreetEdge.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/graph_builder/module/linking/LinkingTest.java
  src/test/java/org/opentripplanner/netex/mapping/RouteMapperTest.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
  src/test/java/org/opentripplanner/routing/algorithm/TurnCostTest.java
  src/test/java/org/opentripplanner/routing/algorithm/TurnRestrictionTest.java
  src/test/java/org/opentripplanner/routing/edgetype/PlainStreetEdgeTest.java
  src/test/java/org/opentripplanner/routing/graph/GraphSerializationTest.java
Labels: improvement, technical debt

#3897 Always use stop times from timetable stored in leg in Transmodel API [changelog skip]
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/TripTimeShortHelper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
  src/main/java/org/opentripplanner/model/TripTimeOnDate.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
Labels: bug

#3911 Ensure that cancellation is mapped as it should [changelog skip]
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
Labels: bug, Skanetrafiken

#3826 Rework leg creation
  src/ext/java/org/opentripplanner/ext/flex/FlexibleTransitLeg.java
  src/main/java/org/opentripplanner/api/model/ApiLeg.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/BikeRentalSnapshotTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/street/BarrierRoutingTest.java
Labels: improvement, technical debt, Entur test

#3912 Remove ET realtime override code
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
Labels: bug, Skanetrafiken

#3910 Allow traversal of pathways without traversal time, distance or steps
  pom.xml
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/model/BoardingArea.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/edgetype/PathwayEdge.java
  src/test/java/org/opentripplanner/graph_builder/module/map/TestStreetMatcher.java
  src/test/java/org/opentripplanner/routing/edgetype/PathwayEdgeTest.java
  src/test/java/org/opentripplanner/routing/vertextype/SimpleVertex.java
Labels: IBI test

#3925 Optimize merging of trip patterns on dates
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
Labels: optimization, Entur test

#3934 Fix default value for transit alerts
  src/main/java/org/opentripplanner/model/plan/Leg.java
Labels: bug
