Repository opentripplanner/OpenTripPlanner, pull requests merged in 2022-09, with the labels that each got.

#4338 Add experimental support for GTFS Fares V2
  docs/sandbox/Fares.md
  pom.xml
  src/client/js/otp/config.js
  src/client/js/otp/modules/planner/Itinerary.js
  src/client/js/otp/modules/planner/planner-style.css
  src/ext-test/java/org/opentripplanner/ext/fares/FaresFilterTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/FaresIntegrationTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/GtfsFaresV2ServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/MultipleFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
  src/ext/java/org/opentripplanner/ext/fares/impl/AddingMultipleFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/GtfsFaresService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/GtfsFaresV2Service.java
  src/ext/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/NoopFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/NycFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/SFBayFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/TimeBasedVehicleRentalFareService.java
  src/ext/java/org/opentripplanner/ext/fares/model/FareContainer.java
  src/ext/java/org/opentripplanner/ext/fares/model/FareLegRule.java
  src/ext/java/org/opentripplanner/ext/fares/model/FareProduct.java
  src/ext/java/org/opentripplanner/ext/fares/model/FareRulesData.java
  src/ext/java/org/opentripplanner/ext/fares/model/LegProducts.java
  src/ext/java/org/opentripplanner/ext/fares/model/RiderCategory.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLItineraryImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLfareComponentImpl.java
  src/main/java/org/opentripplanner/api/mapping/FareMapper.java
  src/main/java/org/opentripplanner/api/mapping/ItineraryMapper.java
  src/main/java/org/opentripplanner/api/model/ApiFare.java
  src/main/java/org/opentripplanner/api/model/ApiFareComponent.java
  src/main/java/org/opentripplanner/api/model/ApiFareProduct.java
  src/main/java/org/opentripplanner/api/model/ApiFareQualifier.java
  src/main/java/org/opentripplanner/api/model/ApiItinerary.java
  src/main/java/org/opentripplanner/api/model/ApiItineraryFares.java
  src/main/java/org/opentripplanner/api/model/ApiLegProducts.java
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/gtfs/mapping/FareLegRuleMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/FareProductMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/RouteMapper.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/routing/core/Fare.java
  src/main/java/org/opentripplanner/routing/core/FareComponent.java
  src/main/java/org/opentripplanner/routing/core/FareType.java
  src/main/java/org/opentripplanner/routing/core/ItineraryFares.java
  src/main/java/org/opentripplanner/routing/core/Money.java
  src/main/java/org/opentripplanner/routing/fares/FareService.java
  src/main/java/org/opentripplanner/transit/model/network/GroupOfRoutes.java
  src/main/java/org/opentripplanner/util/OTPFeature.java
  src/test/java/org/opentripplanner/gtfs/mapping/FareProductMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/RouteMapperTest.java
  src/test/java/org/opentripplanner/model/plan/ItineraryTest.java
  src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
Labels: new feature, bump serialization id

#4399 Configure each transit feed properties individually
  docs/BuildConfiguration.md
  docs/Configuration.md
  docs/Netex-Norway.md
  docs/Troubleshooting-Routing.md
  docs/examples/entur/build-config.json
  docs/sandbox/GoogleCloudStorage.md
  src/ext/java/org/opentripplanner/ext/datastore/gs/AbstractGsDataSource.java
  src/main/java/org/opentripplanner/datastore/api/DataSource.java
  src/main/java/org/opentripplanner/datastore/api/OtpDataStoreConfig.java
  src/main/java/org/opentripplanner/datastore/base/ByteArrayDataSource.java
  src/main/java/org/opentripplanner/datastore/base/ZipStreamDataSourceDecorator.java
  src/main/java/org/opentripplanner/datastore/file/AbstractFileDataSource.java
  src/main/java/org/opentripplanner/datastore/file/ZipFileEntryDataSource.java
  src/main/java/org/opentripplanner/graph_builder/ConfiguredDataSource.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilderDataSources.java
  src/main/java/org/opentripplanner/graph_builder/model/GtfsBundle.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetSource.java
  src/main/java/org/opentripplanner/netex/NetexBundle.java
  src/main/java/org/opentripplanner/netex/configure/NetexConfig.java
  src/main/java/org/opentripplanner/openstreetmap/OpenStreetMapProvider.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
  src/main/java/org/opentripplanner/standalone/config/StorageConfig.java
  src/main/java/org/opentripplanner/standalone/config/configure/LoadConfigModule.java
  src/main/java/org/opentripplanner/standalone/config/feed/DataSourceConfig.java
  src/main/java/org/opentripplanner/standalone/config/feed/DemExtractConfig.java
  src/main/java/org/opentripplanner/standalone/config/feed/DemExtractConfigBuilder.java
  src/main/java/org/opentripplanner/standalone/config/feed/DemExtractsConfig.java
  src/main/java/org/opentripplanner/standalone/config/feed/GtfsFeedConfig.java
  src/main/java/org/opentripplanner/standalone/config/feed/GtfsFeedConfigBuilder.java
  src/main/java/org/opentripplanner/standalone/config/feed/NetexDefaultsConfig.java
  src/main/java/org/opentripplanner/standalone/config/feed/NetexFeedConfig.java
  src/main/java/org/opentripplanner/standalone/config/feed/NetexFeedConfigBuilder.java
  src/main/java/org/opentripplanner/standalone/config/feed/OsmDefaultsConfig.java
  src/main/java/org/opentripplanner/standalone/config/feed/OsmExtractConfig.java
  src/main/java/org/opentripplanner/standalone/config/feed/OsmExtractConfigBuilder.java
  src/main/java/org/opentripplanner/standalone/config/feed/OsmExtractsConfig.java
  src/main/java/org/opentripplanner/standalone/config/feed/TransitFeedConfig.java
  src/main/java/org/opentripplanner/standalone/config/feed/TransitFeedsConfig.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/datastore/OtpDataStoreTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TriangleInequalityTest.java
  src/test/java/org/opentripplanner/standalone/config/NetexDefaultsConfigTest.java
  src/test/java/org/opentripplanner/standalone/config/StorageConfigTest.java
  src/test/resources/netex/build-config.json
  test/performance/baden-wuerttemberg/build-config.json
  test/performance/norway/build-config.json
Labels: new feature, bump serialization id

#4421 Account for boarding restrictions when calculating direct transfers
  docs/Configuration.md
  src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/transit/model/network/StopPattern.java
  src/main/java/org/opentripplanner/transit/model/network/TripPattern.java
  src/main/java/org/opentripplanner/util/OTPFeature.java
  src/test/java/org/opentripplanner/graph_builder/module/DirectTransferGeneratorTest.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
Labels: bug

#4419 Configure the import of OSM extracts individually
  docs/BuildConfiguration.md
  docs/OTP2-MigrationGuide.md
  src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  src/main/java/org/opentripplanner/openstreetmap/OSMOpeningHoursParser.java
  src/main/java/org/opentripplanner/openstreetmap/OpenStreetMapParser.java
  src/main/java/org/opentripplanner/openstreetmap/OpenStreetMapProvider.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMProvider.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
  src/main/java/org/opentripplanner/standalone/config/feed/OsmExtractConfig.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModuleTest.java
Labels: new feature, bump serialization id, config change

#4423 Configure the import of elevation data individually
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/GeotiffGridCoverageFactoryImpl.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/NEDGridCoverageFactoryImpl.java
  src/main/java/org/opentripplanner/graph_builder/services/ned/ElevationGridCoverageFactory.java
  src/main/java/org/opentripplanner/standalone/config/feed/DemExtractConfig.java
Labels: new feature, bump serialization id, config change

#4430 Fix Norwegian speed test configuration
  test/performance/norway/build-config.json
Labels: bug, skip changelog

#4427 Add timeZone parameter to hsl and parkapi vehicle parking updaters
  docs/sandbox/VehicleParking.md
  src/ext-test/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkUpdaterTest.java
  src/ext-test/java/org/opentripplanner/ext/vehicleparking/parkapi/ParkAPIUpdaterTest.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkToVehicleParkingMapper.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkUpdater.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkUpdaterParameters.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/parkapi/BicycleParkAPIUpdater.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/parkapi/CarParkAPIUpdater.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/parkapi/ParkAPIUpdater.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/parkapi/ParkAPIUpdaterParameters.java
  src/main/java/org/opentripplanner/standalone/config/updaters/VehicleParkingUpdaterConfig.java
  src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
  src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingDataSourceFactory.java
Labels: sandbox, skip changelog

#4429 Only index instances of RegularStop
  src/main/java/org/opentripplanner/transit/service/StopModelIndex.java
Labels: bug, skip changelog

#4433 Minor fixes
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
  src/main/resources/internals_no.properties
  src/main/resources/internals_sv.properties
Labels: bug, Regression

#4414 Add HSL specific fare computation in the sandbox
  docs/sandbox/Fares.md
  src/ext-test/java/org/opentripplanner/ext/fares/impl/HSLFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/FaresConfiguration.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/HSLFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/HSLFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/SFBayFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/model/FareRuleSet.java
  src/ext/java/org/opentripplanner/ext/fares/model/RouteOriginDestination.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLRequestContext.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLNodeTypeResolver.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTicketTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLfareImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/graphql-codegen.yml
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/test/java/org/opentripplanner/model/plan/PlanTestConstants.java
Labels: new feature, GTFS, sandbox, bump serialization id, skip changelog

#4447 Extract AbstractRaptorTransfer to improve performance
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/AccessEgress.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TransferWithDuration.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/AbstractRaptorTransfer.java
  src/main/java/org/opentripplanner/transit/raptor/util/ReversedRaptorTransfer.java
Labels: optimization, skip changelog

#4443 Extract LegMode from TraverseMode
  src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  src/ext/java/org/opentripplanner/ext/fares/impl/NycFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/SFBayFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/flex/FlexibleTransitLeg.java
  src/ext/java/org/opentripplanner/ext/flex/edgetype/FlexTripEdge.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLLegImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
  src/main/java/org/opentripplanner/api/mapping/LegMapper.java
  src/main/java/org/opentripplanner/api/mapping/ModeMapper.java
  src/main/java/org/opentripplanner/api/mapping/RouteMapper.java
  src/main/java/org/opentripplanner/api/mapping/TraverseModeMapper.java
  src/main/java/org/opentripplanner/api/model/ApiRouterInfo.java
  src/main/java/org/opentripplanner/graph_builder/module/PruneNoThruIslands.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
  src/main/java/org/opentripplanner/model/plan/StreetLeg.java
  src/main/java/org/opentripplanner/model/plan/TransitLeg.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/RemoveBikerentalWithMostlyWalkingFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/RemoveParkAndRideWithMostlyWalkingFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/groupids/GroupByDistance.java
  src/main/java/org/opentripplanner/routing/api/request/RequestModes.java
  src/main/java/org/opentripplanner/routing/api/request/RouteRequest.java
  src/main/java/org/opentripplanner/routing/core/TraverseMode.java
  src/main/java/org/opentripplanner/routing/core/TraverseModeSet.java
  src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
  src/main/java/org/opentripplanner/transit/model/framework/FeedScopedId.java
  src/main/java/org/opentripplanner/transit/raptor/api/path/PathStringBuilder.java
  src/main/java/org/opentripplanner/util/TravelOptionsMaker.java
  src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java
  src/main/java/org/opentripplanner/visualizer/ShowGraph.java
  src/test/java/org/opentripplanner/GtfsTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModuleTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestIntermediatePlaces.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TriangleInequalityTest.java
  src/test/java/org/opentripplanner/mmri/PreferencesTest.java
  src/test/java/org/opentripplanner/model/plan/ItineraryTest.java
  src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
  src/test/java/org/opentripplanner/routing/TestHalfEdges.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/groupids/GroupByDistanceTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/SnapshotTestBase.java
  src/test/java/org/opentripplanner/routing/core/TraverseModeSetTest.java
  src/test/java/org/opentripplanner/routing/edgetype/StreetTraversalPermissionTest.java
  src/test/java/org/opentripplanner/routing/edgetype/loader/GeometryProcessorTest.java
  src/test/java/org/opentripplanner/routing/street/BarrierRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/BicycleRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/CarRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/SplitEdgeTurnRestrictionsTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/model/testcase/CsvFileIO.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/model/testcase/ItineraryResultMapper.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/model/testcase/Result.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/model/testcase/TestCaseResults.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/options/SpeedTestConfig.java
Labels: technical debt, skip changelog

#4449 fix: TransmodelAPI fails to downcast board- and alight-slack
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/DefaultRoutingRequestType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
  src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeResource.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/AccessEgressRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectStreetRouter.java
  src/main/java/org/opentripplanner/routing/api/request/framework/DurationForEnum.java
  src/main/java/org/opentripplanner/routing/api/request/preference/StreetPreferences.java
  src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
  src/test/java/org/opentripplanner/routing/api/request/framework/DurationForEnumTest.java
Labels: bug, sandbox, Entur test, skip changelog

#4445 Hardcode initial capacities for a* search
  src/main/java/org/opentripplanner/common/pqueue/BinHeap.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/AStar.java
  src/main/java/org/opentripplanner/routing/spt/ShortestPathTree.java
Labels: technical debt, skip changelog

#4444 Move intersectionTraversalCostModel into StreetPreferences
  docs/OTP2-MigrationGuide.md
  src/main/java/org/opentripplanner/graph_builder/module/osm/AtlantaWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/DefaultWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/FinlandWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/GermanyWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/NorwayWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/UKWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetSource.java
  src/main/java/org/opentripplanner/routing/RoutingService.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/AStarBuilder.java
  src/main/java/org/opentripplanner/routing/api/request/preference/StreetPreferences.java
  src/main/java/org/opentripplanner/routing/core/State.java
  src/main/java/org/opentripplanner/routing/core/StateData.java
  src/main/java/org/opentripplanner/routing/core/intersection_model/AbstractIntersectionTraversalCalculator.java
  src/main/java/org/opentripplanner/routing/core/intersection_model/ConstantIntersectionTraversalCalculator.java
  src/main/java/org/opentripplanner/routing/core/intersection_model/DrivingDirection.java
  src/main/java/org/opentripplanner/routing/core/intersection_model/IntersectionTraversalCalculator.java
  src/main/java/org/opentripplanner/routing/core/intersection_model/IntersectionTraversalCostModel.java
  src/main/java/org/opentripplanner/routing/core/intersection_model/IntersectionTraversalModel.java
  src/main/java/org/opentripplanner/routing/core/intersection_model/NorwayIntersectionTraversalCalculator.java
  src/main/java/org/opentripplanner/routing/core/intersection_model/NorwayIntersectionTraversalCostModel.java
  src/main/java/org/opentripplanner/routing/core/intersection_model/SimpleIntersectionTraversalCalculator.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
  src/main/java/org/opentripplanner/standalone/config/WheelchairAccessibilityRequestMapper.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TriangleInequalityTest.java
  src/test/java/org/opentripplanner/routing/algorithm/TurnCostTest.java
  src/test/java/org/opentripplanner/routing/core/intersection_model/SimpleIntersectionTraversalCalculatorTest.java
  src/test/java/org/opentripplanner/routing/edgetype/TemporaryPartialStreetEdgeTest.java
Labels: technical debt, bump serialization id

#4454 Catch exceptions from updater configuration
  src/main/java/org/opentripplanner/updater/UpdaterConstructionException.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdater.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFeedLoader.java
Labels: bug, Regression, skip changelog

#4347 Add feature switch for matching ET messages on stops
  docs/examples/skanetrafiken/Readme.md
  docs/examples/skanetrafiken/router-config.json
  docs/sandbox/SiriAzureUpdater.md
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/AbstractAzureSiriUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureUpdaterParameters.java
  src/main/java/org/opentripplanner/standalone/config/updaters/azure/SiriAzureUpdaterConfig.java
Labels: improvement, Skanetrafiken

#4451 Update code conventions doc on builders
  CODE_CONVENTIONS.md
Labels: documentation, skip changelog

#4458 Take into account null values for fare details
  src/ext-test/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareService.java
  src/main/java/org/opentripplanner/api/mapping/FareMapper.java
  src/main/java/org/opentripplanner/routing/core/ItineraryFares.java
  src/test/java/org/opentripplanner/api/mapping/FareMapperTest.java
Labels: IBI, skip changelog

#4459 Allow specifying allowed/banned rental networks in the Transmodel API
  docs/sandbox/TransmodelApi.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/BannedInputType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/JourneyWhiteListed.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
Labels: sandbox, skip changelog

#4461 Use placeholders in log messages
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETHttpTripUpdateSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriVMHttpTripUpdateSource.java
  src/ext/java/org/opentripplanner/ext/smoovebikerental/SmooveBikeRentalDataSource.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkToVehicleParkingMapper.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkUtilizationToPatchMapper.java
  src/ext/java/org/opentripplanner/ext/vilkkubikerental/VilkkuBikeRentalDataSource.java
  src/main/java/org/opentripplanner/api/common/Message.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilderDataSources.java
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/graph_builder/module/map/StreetMatcher.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/DegreeGridNEDTileSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/AreaGroup.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySet.java
  src/main/java/org/opentripplanner/model/calendar/impl/CalendarServiceDataFactoryImpl.java
  src/main/java/org/opentripplanner/model/projectinfo/OtpProjectInfoParser.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/AStar.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RoutingResponseMapper.java
  src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
  src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
  src/main/java/org/opentripplanner/routing/spt/ShortestPathTree.java
  src/main/java/org/opentripplanner/standalone/OtpStartupInfo.java
  src/main/java/org/opentripplanner/transit/raptor/service/RangeRaptorDynamicSearch.java
  src/main/java/org/opentripplanner/updater/GenericJsonDataSource.java
  src/main/java/org/opentripplanner/updater/GenericXmlDataSource.java
  src/main/java/org/opentripplanner/updater/alerts/GtfsRealtimeAlertsUpdater.java
  src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
  src/main/java/org/opentripplanner/updater/stoptime/GtfsRealtimeFileTripUpdateSource.java
  src/main/java/org/opentripplanner/updater/stoptime/GtfsRealtimeHttpTripUpdateSource.java
  src/main/java/org/opentripplanner/updater/stoptime/MqttGtfsRealtimeUpdater.java
  src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingUpdater.java
  src/main/java/org/opentripplanner/updater/vehicle_positions/GtfsRealtimeHttpVehiclePositionSource.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdater.java
  src/main/java/org/opentripplanner/util/OTPFeature.java
  src/main/java/org/opentripplanner/util/resources/ResourceBundleSingleton.java
  src/main/java/org/opentripplanner/util/xml/JsonDataListDownloader.java
  src/main/java/org/opentripplanner/util/xml/XmlDataListDownloader.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/options/SpeedTestConfig.java
Labels: technical debt, skip changelog

#4463 More graph stats, better exception message
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
  src/main/java/org/opentripplanner/transit/service/TransitModel.java
Labels: IBI, skip changelog

#4453 Add support for Deduplicator generic object arrays
  src/main/java/org/opentripplanner/transit/model/basic/NonLocalizedString.java
  src/main/java/org/opentripplanner/transit/model/framework/Deduplicator.java
  src/test/java/org/opentripplanner/routing/trippattern/DeduplicatorTest.java
Labels: technical debt, bump serialization id, skip changelog

#4438 Make safety defaults customizable for walking and cycling
  src/ext/java/org/opentripplanner/ext/reportapi/model/BicycleSafetyReport.java
  src/ext/java/org/opentripplanner/ext/reportapi/resource/ReportResource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/DefaultWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/FinlandWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/SafetyFeatures.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayProperties.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertiesBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySet.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/FinlandWayPropertySetSourceTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/GermanyWayPropertySetSourceTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModuleTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetSourceTest.java
Labels: improvement

#4456 Allow the same config node to be accessed twice
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
  src/main/java/org/opentripplanner/standalone/config/OtpConfig.java
  src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
  src/test/java/org/opentripplanner/standalone/config/NodeAdapterTest.java
Labels: improvement, technical debt, skip changelog

#4468 Fix block-based interlining when importing several GTFS feeds
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/graph_builder/module/interlining/InterlineProcessor.java
  src/test/java/org/opentripplanner/graph_builder/module/GtfsModuleTest.java
Labels: bug, GTFS, optimization, IBI

#4475 Add error message for value assertion
  src/main/java/org/opentripplanner/transit/model/framework/FeedScopedId.java
  src/main/java/org/opentripplanner/transit/model/organization/Agency.java
  src/main/java/org/opentripplanner/transit/model/organization/Operator.java
  src/main/java/org/opentripplanner/util/lang/StringUtils.java
  src/test/java/org/opentripplanner/util/lang/StringUtilsTest.java
Labels: improvement

#4473 Add error message when GTFS-RT feed returns 404
  src/main/java/org/opentripplanner/updater/stoptime/GtfsRealtimeHttpTripUpdateSource.java
Labels: IBI, RealTimeUpdate, skip changelog

#4464 Setting transportmode on added Trip
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
Labels: Entur test, skip changelog

#4474 Do not remove patterns with non-running DatedServiceJourneys
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/DatedServiceJourneyType.java
  src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
  src/main/java/org/opentripplanner/netex/NetexBundle.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/calendar/CalendarServiceBuilder.java
  src/main/java/org/opentripplanner/transit/model/framework/EntityById.java
  src/test/java/org/opentripplanner/model/impl/OtpTransitServiceBuilderLimitPeriodTest.java
  src/test/java/org/opentripplanner/netex/mapping/RouteMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/TripMapperTest.java
Labels: Regression, Entur test, NeTEx

#4476 Discard direct walking results if direct mode is flex
  src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
Labels: sandbox, Regression, Entur test
