Repository opentripplanner/OpenTripPlanner, pull requests merged in 2022-03, with the labels that each got.

#3938 Add invalid GTFS transfers to the issue store [changelog skip]
  src/main/java/org/opentripplanner/graph_builder/issues/IgnoredGtfsTransfer.java
  src/main/java/org/opentripplanner/graph_builder/issues/InvalidGtfsTransfer.java
  src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/TransferMapper.java
  src/test/java/org/opentripplanner/gtfs/mapping/TransferMapperTest.java
Labels: bug

#3932 Add the visualizer to the interactive launcher
  src/ext/java/org/opentripplanner/ext/interactivelauncher/InteractiveOtpMain.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/Model.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/MainView.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/OptionsView.java
  src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java
  src/main/java/org/opentripplanner/visualizer/ShowGraph.java
Labels: improvement

#3935 Fix date handling for estimated calls for service journey on specific date in Transmodel API
  src/main/java/org/opentripplanner/model/TripTimeOnDate.java
Labels: bug

#3931 feat: Set override for toString method in p2 class [changelog skip]
  src/main/java/org/opentripplanner/common/model/P2.java
Labels: technical debt

#3929 Fix handling null in pathway [changelog skip]
  src/main/java/org/opentripplanner/api/model/ApiWalkStep.java
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/model/plan/WalkStep.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapper.java
Labels: bug

#3946 Fix data fetcher for destinationDisplay in TimetabledPassingTime [changelog skip]
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/TimetabledPassingTimeType.java
Labels: bug, sandbox, Entur test

#3936 Via headsign bugfix
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
  src/main/java/org/opentripplanner/model/TripTimeOnDate.java
  src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java
Labels: bug, Skanetrafiken

#3945 NeTEx mapping for WheelChairBoarding
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopAndStationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopMapper.java
  src/main/java/org/opentripplanner/netex/mapping/WheelChairMapper.java
  src/test/java/org/opentripplanner/netex/mapping/StopAndStationMapperTest.java
Labels: new feature, Skanetrafiken

#3964 Account for from/to splitting when copying turnRestrictions [changelog skip]
  src/main/java/org/opentripplanner/common/TurnRestriction.java
  src/main/java/org/opentripplanner/graph_builder/linking/VertexLinker.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/TemporaryPartialStreetEdge.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/test/java/org/opentripplanner/routing/edgetype/StreetEdgeTest.java
Labels: bug

#3965 Add StopPlace parent to Quay [changelog skip]
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopAndStationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopMapper.java
  src/test/java/org/opentripplanner/netex/mapping/StopAndStationMapperTest.java
Labels: Skanetrafiken

#3954 Make sure NonLocalizedString is correctly initialized [changelog skip]
  src/main/java/org/opentripplanner/util/NonLocalizedString.java
  src/test/java/org/opentripplanner/model/plan/PlaceTest.java
Labels: improvement

#3953 Implement trip banning
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/BannedInputType.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilter.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilterTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
Labels: Regression

#3906 Improve performance of Park+Ride, Bike+Ride and Bike+Transit
  docs/SandboxExtension.md
  docs/sandbox/VehicleToStopHeuristics.md
  mkdocs.yml
  src/ext/java/org/opentripplanner/ext/vehicletostopheuristics/BikeToStopSkipEdgeStrategy.java
  src/ext/java/org/opentripplanner/ext/vehicletostopheuristics/VehicleToStopSkipEdgeStrategy.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/model/TransitMode.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/AStar.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/strategies/ComposingSkipEdgeStrategy.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/strategies/EuclideanRemainingWeightHeuristic.java
  src/main/java/org/opentripplanner/routing/core/intersection_model/SimpleIntersectionTraversalCostModel.java
  src/main/java/org/opentripplanner/routing/graph/GraphIndex.java
  src/main/java/org/opentripplanner/routing/spt/ShortestPathTree.java
  src/main/java/org/opentripplanner/util/OTPFeature.java
  src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java
Labels: optimization, IBI test

#3951 Convert stream to list for constrained boarding search [changelog skip]
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/ConstrainedBoardingSearch.java
Labels: optimization

#3968 Make raptor transfer lists immutable for faster iteration [changelog skip]
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/RaptorTransferIndex.java
Labels: optimization

#3967 Remove unused functionality to partially ban trips [changelog skip]
  docs/OTP2-MigrationGuide.md
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilter.java
  src/main/java/org/opentripplanner/routing/api/request/BannedStopSet.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
Labels: technical debt

#3986 Use native type for distance, as it is always defined[changelog skip]
  src/ext/java/org/opentripplanner/ext/flex/FlexibleTransitLeg.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
  src/main/java/org/opentripplanner/model/plan/StreetLeg.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/RemoveBikerentalWithMostlyWalkingFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/groupids/GroupByTripIdAndDistance.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/groupids/GroupByTripIdAndDistanceTest.java
Labels: technical debt

#3985 Re-add GraphCoherencyCheckerModule
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/GraphCoherencyCheckerModule.java
Labels: technical debt

#3984 Remove wayId from StreetEdge and remove custom geometry serialization [changelog skip]
  pom.xml
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLScalars.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkToVehicleParkingMapper.java
  src/main/java/org/opentripplanner/api/model/ApiRouterInfo.java
  src/main/java/org/opentripplanner/common/geometry/DelaunayIsolineBuilder.java
  src/main/java/org/opentripplanner/common/geometry/DelaunayTriangulation.java
  src/main/java/org/opentripplanner/common/geometry/GeoJsonModule.java
  src/main/java/org/opentripplanner/common/geometry/GeometryDeserializer.java
  src/main/java/org/opentripplanner/common/geometry/GeometrySerializer.java
  src/main/java/org/opentripplanner/common/geometry/GeometryUtils.java
  src/main/java/org/opentripplanner/common/geometry/IsolineBuilder.java
  src/main/java/org/opentripplanner/common/geometry/PackedCoordinateSequence.java
  src/main/java/org/opentripplanner/common/geometry/RecursiveGridIsolineBuilder.java
  src/main/java/org/opentripplanner/common/geometry/ReversibleLineStringWrapper.java
  src/main/java/org/opentripplanner/graph_builder/linking/VertexLinker.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/routing/vertextype/SplitterVertex.java
  src/main/java/org/opentripplanner/routing/vertextype/TemporarySplitterVertex.java
  src/test/java/org/opentripplanner/common/geometry/GeoJsonTest.java
  src/test/java/org/opentripplanner/graph_builder/module/PruneNoThruIslandsTest.java
  src/test/java/org/opentripplanner/graph_builder/module/linking/LinkingTest.java
  src/test/java/org/opentripplanner/routing/edgetype/StreetEdgeTest.java
Labels: technical debt

#3978 Do not override already set flex window [changelog skip]
  src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java
Labels: bug, sandbox, Entur test, NeTEx

#3972 Optimize routeIterator by adding a pattern index and pre-calculating allowed stops [changelog skip]
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TripPatternWithRaptorStopIndexes.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitData.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripPatternForDates.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTransitDataProvider.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RangeRaptorWorker.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreatorTest.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTransitData.java
Labels: optimization, Entur test

#3983 Otp2 clean code 2657 [changelog skip]
  src/main/java/org/opentripplanner/api/common/Message.java
  src/main/java/org/opentripplanner/graph_builder/module/CheckGeometryModule.java
  src/main/java/org/opentripplanner/graph_builder/module/GraphStatisticsModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/CreativeNamerEditor.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/NotePropertiesEditor.java
  src/main/java/org/opentripplanner/routing/core/StateFactory.java
  src/main/java/org/opentripplanner/routing/impl/LoggingTraverseVisitor.java
  src/main/java/org/opentripplanner/routing/util/NullExtraEdges.java
  src/main/java/org/opentripplanner/util/IntUtils.java
  src/main/java/org/opentripplanner/util/Properties.java
  src/main/java/org/opentripplanner/util/ResourceBundleAdaptor.java
  src/main/java/org/opentripplanner/util/stats/DiscreteDistribution.java
  src/test/java/org/opentripplanner/api/resource/MessageTest.java
  src/test/java/org/opentripplanner/api/resource/TestMessages.java
  src/test/resources/Message.properties
  src/test/resources/Message_de.properties
  src/test/resources/Message_es.properties
  src/test/resources/Message_fr.properties
Labels: technical debt

#3987 Make SiriETGooglePubsubUpdater wait for runnable completition [changelog skip]
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/main/java/org/opentripplanner/updater/GraphUpdaterManager.java
  src/main/java/org/opentripplanner/updater/WriteToGraphCallback.java
  src/test/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingUpdaterTest.java
Labels: bug

#3991 Update enunciate and site plugin in order to build API docs [changelog skip]
  pom.xml
Labels: technical debt

#3993 Remove unused classes, m2eclipse config [changelog skip]
  pom.xml
  src/main/java/org/opentripplanner/graph_builder/module/DownloadableGtfsInputSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/SafetyFeaturesEditor.java
  src/main/java/org/opentripplanner/graph_builder/module/shapefile/AttributeFeatureConverter.java
  src/main/java/org/opentripplanner/graph_builder/module/shapefile/CaseBasedBicycleSafetyFeatureConverter.java
  src/main/java/org/opentripplanner/graph_builder/module/shapefile/CaseBasedBooleanConverter.java
  src/main/java/org/opentripplanner/graph_builder/module/shapefile/CaseBasedTraversalPermissionConverter.java
  src/main/java/org/opentripplanner/graph_builder/module/shapefile/CompositeBooleanConverter.java
  src/main/java/org/opentripplanner/graph_builder/module/shapefile/CompositeStreetTraversalPermissionConverter.java
  src/main/java/org/opentripplanner/graph_builder/module/shapefile/DirectSafetyReader.java
  src/main/java/org/opentripplanner/graph_builder/module/shapefile/FeatureIdConverter.java
  src/main/java/org/opentripplanner/graph_builder/module/shapefile/JoinedFeatureConverter.java
  src/main/java/org/opentripplanner/graph_builder/module/shapefile/NullBooleanConverter.java
  src/main/java/org/opentripplanner/graph_builder/module/shapefile/ShapefileFeatureSourceFactoryImpl.java
  src/main/java/org/opentripplanner/graph_builder/module/shapefile/ShapefileStreetModule.java
  src/main/java/org/opentripplanner/graph_builder/module/shapefile/ShapefileStreetSchema.java
  src/main/java/org/opentripplanner/graph_builder/module/shapefile/StringAttributeFeatureConverter.java
  src/main/java/org/opentripplanner/graph_builder/module/vehicle/VehicleParkingModule.java
  src/main/java/org/opentripplanner/graph_builder/services/shapefile/SimpleFeatureConverter.java
  src/main/java/org/opentripplanner/openstreetmap/BinaryOpenStreetMapProvider.java
  src/main/java/org/opentripplanner/routing/impl/PathWeightComparator.java
  src/main/java/org/opentripplanner/routing/services/OnBoardDepartService.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/TripHelper.java
  src/test/java/org/opentripplanner/graph_builder/module/shapefile/CompositeConverterTest.java
  src/test/java/org/opentripplanner/graph_builder/module/shapefile/StubSimpleFeature.java
  src/test/java/org/opentripplanner/graph_builder/module/shapefile/TestCaseBasedTraversalPermissionConverter.java
  src/test/java/org/opentripplanner/graph_builder/module/shapefile/TestShapefileStreetGraphBuilderImpl.java
Labels: technical debt

#3979 OTP 2.1.0 release [changelog skip]
  CONTRIBUTING.md
  README.md
  docs/Basic-Tutorial.md
  docs/BuildConfiguration.md
  docs/Changelog.md
  docs/Codestyle.md
  docs/Configuration.md
  docs/Deployments.md
  docs/Developers-Guide.md
  docs/Getting-OTP.md
  docs/Governance.md
  docs/Localization.md
  docs/Netex-Norway.md
  docs/OTP2-MigrationGuide.md
  docs/RouterConfiguration.md
  docs/SandboxExtension.md
  docs/Version-Comparison.md
  docs/examples/entur/build-config.json
  docs/examples/entur/otp-config.json
  docs/examples/entur/router-config.json
  docs/index.md
  docs/sandbox/GoogleCloudStorage.md
  docs/sandbox/transferanalyzer.md
  pom.xml
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
  src/main/java/org/opentripplanner/model/projectinfo/GraphFileHeader.java
Labels: release management

#3998 Solve problem with "wheelchairAccessible" [changelog skip]
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
Labels: improvement, sandbox

#3808 Read translations from GTFS and Netex sources for stop names
  .gitignore
  pom.xml
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLUtils.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/java/org/opentripplanner/ext/reportapi/model/TransfersReport.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/MonoOrMultiModalStation.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/api/mapping/StopMapper.java
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/gtfs/mapping/BoardingAreaMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/EntranceMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/LocationGroupMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/LocationMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/PathwayNodeMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/StationMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/StopMapper.java
  src/main/java/org/opentripplanner/model/BoardingArea.java
  src/main/java/org/opentripplanner/model/Entrance.java
  src/main/java/org/opentripplanner/model/FlexLocationGroup.java
  src/main/java/org/opentripplanner/model/FlexStopLocation.java
  src/main/java/org/opentripplanner/model/MultiModalStation.java
  src/main/java/org/opentripplanner/model/PathwayNode.java
  src/main/java/org/opentripplanner/model/Station.java
  src/main/java/org/opentripplanner/model/StationElement.java
  src/main/java/org/opentripplanner/model/Stop.java
  src/main/java/org/opentripplanner/model/StopLocation.java
  src/main/java/org/opentripplanner/model/plan/Place.java
  src/main/java/org/opentripplanner/netex/mapping/FlexStopLocationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/MultiModalStationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StationMapper.java
  src/main/java/org/opentripplanner/routing/vertextype/TransitBoardingAreaVertex.java
  src/main/java/org/opentripplanner/routing/vertextype/TransitEntranceVertex.java
  src/main/java/org/opentripplanner/routing/vertextype/TransitPathwayNodeVertex.java
  src/main/java/org/opentripplanner/routing/vertextype/TransitStopVertex.java
  src/main/java/org/opentripplanner/util/TranslationHelper.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/gtfs/mapping/BoardingAreaMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/EntranceMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/PathwayMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/PathwayNodeMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/StopAndStationMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/StopTimesMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/TransferMapperTest.java
  src/test/java/org/opentripplanner/model/plan/PlaceTest.java
  src/test/java/org/opentripplanner/model/plan/PlanTestConstants.java
  src/test/java/org/opentripplanner/netex/NetexBundleSmokeTest.java
  src/test/java/org/opentripplanner/netex/mapping/FlexStopLocationMapperTest.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/groupids/GroupByAllSameStationsTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/StopIndexForRaptorTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/model/Place.java
  src/test/java/org/opentripplanner/util/TranslationHelperTest.java
Labels: new feature, NeTEx

#3994 Update to Java 17 and Kryo 5
  .github/workflows/cibuild.yml
  .github/workflows/performance-test.yml
  docs/Basic-Tutorial.md
  pom.xml
  src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryAndBlockProcessor.java
  src/main/java/org/opentripplanner/kryo/BuildConfigSerializer.java
  src/main/java/org/opentripplanner/kryo/HashBiMapSerializer.java
  src/main/java/org/opentripplanner/kryo/RouterConfigSerializer.java
  src/main/java/org/opentripplanner/kryo/UnmodifiableCollectionsSerializer.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/routing/graph/kryosupport/JavaImmutableListSerializer.java
  src/main/java/org/opentripplanner/routing/graph/kryosupport/JavaImmutableMapSerializer.java
  src/main/java/org/opentripplanner/routing/graph/kryosupport/JavaImmutableSetSerializer.java
  src/main/java/org/opentripplanner/routing/graph/kryosupport/KryoBuilder.java
  src/test/java/org/opentripplanner/updater/alerts/AlertsUpdateHandlerTest.java
Labels: technical debt

#4004 Remove optimize=TRANSFERS
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/routing/core/BicycleOptimizeType.java
Labels: technical debt

#3981 Consume GTFS-RT Vehicle Positions, introduce API
  docs/RouterConfiguration.md
  src/ext-test/java/org/opentripplanner/ext/legacygraphqlapi/GraphQLIndexTest.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPatternImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopRelationshipImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLVehiclePositionImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/graphql-codegen.yml
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/model/TripPattern.java
  src/main/java/org/opentripplanner/model/calendar/ServiceDate.java
  src/main/java/org/opentripplanner/model/vehicle_position/RealtimeVehiclePosition.java
  src/main/java/org/opentripplanner/model/vehicle_position/RealtimeVehiclePositionBuilder.java
  src/main/java/org/opentripplanner/routing/RoutingService.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/routing/impl/StreetVertexIndexServiceImpl.java
  src/main/java/org/opentripplanner/routing/services/RealtimeVehiclePositionService.java
  src/main/java/org/opentripplanner/standalone/config/UpdatersConfig.java
  src/main/java/org/opentripplanner/standalone/config/updaters/VehiclePositionsUpdaterConfig.java
  src/main/java/org/opentripplanner/updater/DataSourceType.java
  src/main/java/org/opentripplanner/updater/GraphUpdaterConfigurator.java
  src/main/java/org/opentripplanner/updater/UpdatersParameters.java
  src/main/java/org/opentripplanner/updater/vehicle_positions/GtfsRealtimeHttpVehiclePositionSource.java
  src/main/java/org/opentripplanner/updater/vehicle_positions/PollingVehiclePositionUpdater.java
  src/main/java/org/opentripplanner/updater/vehicle_positions/VehiclePositionPatternMatcher.java
  src/main/java/org/opentripplanner/updater/vehicle_positions/VehiclePositionSource.java
  src/main/java/org/opentripplanner/updater/vehicle_positions/VehiclePositionUpdaterRunnable.java
  src/main/java/org/opentripplanner/updater/vehicle_positions/VehiclePositionsUpdaterParameters.java
  src/main/java/org/opentripplanner/util/HttpUtils.java
  src/main/java/org/opentripplanner/util/xml/JsonDataListDownloader.java
  src/test/java/org/opentripplanner/updater/vehicle_positions/VehiclePositionParsingTest.java
  src/test/java/org/opentripplanner/updater/vehicle_positions/VehiclePositionsMatcherTest.java
  src/test/resources/vehicle-positions/king-county-metro-1.pb
  src/test/resources/vehicle-positions/king-county-metro-2.pb
Labels: new feature, IBI test

#4013 Cleanup unused classes [changelog skip]
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/KeyValueType.java
  src/main/java/org/opentripplanner/api/common/LocationNotAccessible.java
  src/main/java/org/opentripplanner/api/common/ParameterException.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/api/json/QualifiedModeSetDeserializer.java
  src/main/java/org/opentripplanner/api/json/QualifiedModeSetSerializer.java
  src/main/java/org/opentripplanner/api/json/TraverseModeSetDeserializer.java
  src/main/java/org/opentripplanner/api/json/TraverseModeSetSerializer.java
  src/main/java/org/opentripplanner/api/parameter/BoundingBox.java
  src/main/java/org/opentripplanner/api/parameter/IsoTimeParameter.java
  src/main/java/org/opentripplanner/common/DebugUtils.java
  src/main/java/org/opentripplanner/common/Histogram.java
  src/main/java/org/opentripplanner/common/Namer.java
  src/main/java/org/opentripplanner/graph_builder/issues/AgencyNameCollision.java
  src/main/java/org/opentripplanner/graph_builder/issues/BogusEdgeGeometry.java
  src/main/java/org/opentripplanner/graph_builder/issues/BogusVertexGeometry.java
  src/main/java/org/opentripplanner/graph_builder/issues/HopZeroDistance.java
  src/main/java/org/opentripplanner/graph_builder/issues/NonStationParentStation.java
  src/main/java/org/opentripplanner/graph_builder/issues/StopAtEntrance.java
  src/main/java/org/opentripplanner/graph_builder/issues/TimeMissingForTrip.java
  src/main/java/org/opentripplanner/graph_builder/issues/TripDuplicate.java
  src/main/java/org/opentripplanner/graph_builder/issues/TripDuplicateDeparture.java
  src/main/java/org/opentripplanner/graph_builder/issues/TripOvertaking.java
  src/main/java/org/opentripplanner/graph_builder/issues/VertexShapeError.java
  src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryAndBlockProcessor.java
  src/main/java/org/opentripplanner/graph_builder/services/shapefile/FeatureSourceFactory.java
  src/main/java/org/opentripplanner/gtfs/RepairStopTimesForEachTripOperation.java
  src/main/java/org/opentripplanner/netex/support/DayTypeRefToServiceIdMapper.java
  src/main/java/org/opentripplanner/netex/support/DayTypeRefsToServiceIdAdapter.java
  src/main/java/org/opentripplanner/routing/core/OverlayGraph.java
  src/main/java/org/opentripplanner/routing/spt/SPTWalker.java
  src/main/java/org/opentripplanner/routing/util/IncrementingIdGenerator.java
  src/main/java/org/opentripplanner/routing/util/UniqueIdGenerator.java
  src/main/java/org/opentripplanner/util/MapUtils.java
  src/test/java/org/opentripplanner/netex/support/DayTypeRefToServiceIdMapperTest.java
  src/test/java/org/opentripplanner/routing/core/TestOverlayGraph.java
  src/test/java/org/opentripplanner/routing/util/IncrementingIdGeneratorTest.java
Labels: technical debt

#4017 Fix mapping of URL in REST API [changelog skip]
  src/main/java/org/opentripplanner/api/mapping/StopMapper.java
  src/main/java/org/opentripplanner/model/StopLocation.java
Labels: technical debt

#4020 Handle unsupported modes gracefully by logging to issue store. [changelog skip]
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/RouteMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TransportModeMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
  src/test/java/org/opentripplanner/netex/mapping/TransportModeMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/TripMapperTest.java
Labels: improvement

#4023 Use PackedCoordinateSequence from JTS [changelog skip]
  src/main/java/org/opentripplanner/common/geometry/CompactElevationProfile.java
  src/main/java/org/opentripplanner/common/geometry/CompactLineString.java
  src/main/java/org/opentripplanner/common/geometry/GeometryUtils.java
  src/main/java/org/opentripplanner/common/geometry/PackedCoordinateSequence.java
  src/main/java/org/opentripplanner/common/geometry/Serializable2DPackedCoordinateSequenceFactory.java
  src/main/java/org/opentripplanner/common/geometry/Subgraph.java
  src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryAndBlockProcessor.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
  src/main/java/org/opentripplanner/inspector/EdgeVertexTileRenderer.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetWithElevationEdge.java
  src/main/java/org/opentripplanner/routing/util/ElevationUtils.java
  src/test/java/org/opentripplanner/common/geometry/CompactElevationProfileTest.java
  src/test/java/org/opentripplanner/graph_builder/module/map/TestStreetMatcher.java
  src/test/java/org/opentripplanner/routing/edgetype/PlainStreetEdgeTest.java
  src/test/java/org/opentripplanner/routing/edgetype/TriangleTest.java
Labels: technical debt

#4026 debug-client: add 🚶 to walkingBike steps [changelog skip]
  src/client/js/otp/util/Itin.js
Labels: improvement

#4012 Enable GBFS floating vehicles by default
  docs/Configuration.md
  src/main/java/org/opentripplanner/util/OTPFeature.java
Labels: improvement

#4024 Check all conditions when filtering trips [changelog skip]
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilter.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilterTest.java
Labels: bug

#4019 Don't try to repair trips with negative dwell or driving times, drop them instead
  src/main/java/org/opentripplanner/graph_builder/issues/NegativeDwellTime.java
  src/main/java/org/opentripplanner/gtfs/RepairStopTimesForEachTripOperation.java
Labels: bug, technical debt

#4029 Remove unused field GtfsBundle#url [changelog skip]
  src/main/java/org/opentripplanner/graph_builder/model/GtfsBundle.java
  src/main/java/org/opentripplanner/util/HttpUtils.java
Labels: technical debt

#4028 Avoid reading Graph/RoutingContext from GraphPath [changelog skip]
  src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessTemplate.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/AlertToLegMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectStreetRouter.java
  src/main/java/org/opentripplanner/routing/core/State.java
  src/main/java/org/opentripplanner/routing/spt/GraphPath.java
  src/test/java/org/opentripplanner/GtfsTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestIntermediatePlaces.java
  src/test/java/org/opentripplanner/routing/street/BarrierRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/BicycleRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/CarRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/SplitEdgeTurnRestrictionsTest.java
Labels: technical debt

#4006 Use WheelchairBoarding enum instead of boolean [changelog skip]
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLUtils.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/graphql-codegen.yml
  src/main/java/org/opentripplanner/api/mapping/TripMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/TripMapper.java
  src/main/java/org/opentripplanner/model/StopLocation.java
  src/main/java/org/opentripplanner/model/Trip.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilter.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetTransitEntityLink.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetTransitEntranceLink.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetTransitStopLink.java
  src/main/java/org/opentripplanner/routing/vertextype/TransitEntranceVertex.java
  src/main/java/org/opentripplanner/routing/vertextype/TransitStopVertex.java
  src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java
  src/test/java/org/opentripplanner/netex/NetexBundleSmokeTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilterTest.java
  src/test/resources/gtfs/farecomponents.gtfs.zip
Labels: improvement, technical debt, IBI test

#4036 Sandbox vector tiles stop name translation fix [changelog skip]
  src/ext-test/java/org/opentripplanner/ext/vectortiles/StopsLayerTest.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/stations/DigitransitStationPropertyMapper.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/DigitransitStopPropertyMapper.java
  src/main/java/org/opentripplanner/model/Stop.java
Labels: bug, sandbox

#4031 Fix HTTP client timeout [changelog skip]
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/main/java/org/opentripplanner/util/HttpUtils.java
Labels: improvement, technical debt

#3889 Add support for NeTex DatedServiceJourneys
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/DatedServiceJourneyQuery.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/DatedServiceJourneyType.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/model/TripOnServiceDate.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
  src/main/java/org/opentripplanner/netex/NetexModule.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripCalendarBuilder.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapperResult.java
  src/main/java/org/opentripplanner/netex/mapping/calendar/DatedServiceJourneyMapper.java
  src/main/java/org/opentripplanner/routing/DatedServiceJourneyHelper.java
  src/main/java/org/opentripplanner/routing/RoutingService.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/routing/graph/GraphIndex.java
  src/test/java/org/opentripplanner/netex/mapping/NetexTestDataSample.java
  src/test/java/org/opentripplanner/netex/mapping/TripCalendarBuilderTest.java
  src/test/java/org/opentripplanner/netex/mapping/TripPatternMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/calendar/DatedServiceJourneyMapperTest.java
Labels: new feature, Skanetrafiken

#3960 Add support for SKIPPED stop time updates in SCHEDULED update handling
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStoptimeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/main/java/org/opentripplanner/index/IndexAPI.java
  src/main/java/org/opentripplanner/model/StopPattern.java
  src/main/java/org/opentripplanner/model/Timetable.java
  src/main/java/org/opentripplanner/model/TripPattern.java
  src/main/java/org/opentripplanner/model/TripTimesPatch.java
  src/main/java/org/opentripplanner/routing/RoutingService.java
  src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
  src/main/java/org/opentripplanner/updater/stoptime/TripPatternCache.java
  src/main/java/org/opentripplanner/updater/stoptime/TripUpdateGraphWriterRunnable.java
  src/test/java/org/opentripplanner/GtfsTest.java
  src/test/java/org/opentripplanner/model/TimetableSnapshotTest.java
  src/test/java/org/opentripplanner/model/TimetableTest.java
  src/test/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSourceTest.java
Labels: improvement, RealTimeUpdate

#3728 New Norwegian way properties profile
  src/main/java/org/opentripplanner/graph_builder/module/osm/DefaultWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/NorwayWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OSMFilter.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetSource.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/NorwayWayPropertySetSourceTest.java
Labels: Entur test

#4037 Cleanup routing context & AStar [changelog skip]
  src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  src/ext/java/org/opentripplanner/ext/dataoverlay/DataOverlayStreetEdgeCostExtension.java
  src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/StreetFlexPathCalculator.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/DefaultRoutingRequestType.java
  src/ext/java/org/opentripplanner/ext/vehicletostopheuristics/BikeToStopSkipEdgeStrategy.java
  src/ext/java/org/opentripplanner/ext/vehicletostopheuristics/VehicleToStopSkipEdgeStrategy.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/AStar.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/AStarBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/strategies/ComposingSkipEdgeStrategy.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/strategies/DurationSkipEdgeStrategy.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/strategies/EuclideanRemainingWeightHeuristic.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/strategies/RemainingWeightHeuristic.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/strategies/SkipEdgeStrategy.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/strategies/TrivialRemainingWeightHeuristic.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/ItinerariesHelper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/AccessEgressRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectStreetRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/FlexAccessEgressRouter.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/core/RoutingContext.java
  src/main/java/org/opentripplanner/routing/core/State.java
  src/main/java/org/opentripplanner/routing/core/StateData.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdgeCostExtension.java
  src/main/java/org/opentripplanner/routing/graphfinder/PlaceFinderTraverseVisitor.java
  src/main/java/org/opentripplanner/routing/graphfinder/StopFinderTraverseVisitor.java
  src/main/java/org/opentripplanner/routing/graphfinder/StreetGraphFinder.java
  src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
  src/main/java/org/opentripplanner/routing/spt/ShortestPathTree.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
  src/main/java/org/opentripplanner/util/time/DateUtils.java
  src/test/java/org/opentripplanner/graph_builder/module/DirectTransferGeneratorTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestUnroutable.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TriangleInequalityTest.java
  src/test/java/org/opentripplanner/model/TimetableTest.java
  src/test/java/org/opentripplanner/routing/TestHalfEdges.java
  src/test/java/org/opentripplanner/routing/algorithm/AStarTest.java
  src/test/java/org/opentripplanner/routing/algorithm/BikeRentalTest.java
  src/test/java/org/opentripplanner/routing/algorithm/BikeWalkingTest.java
  src/test/java/org/opentripplanner/routing/algorithm/CarPickupTest.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
  src/test/java/org/opentripplanner/routing/algorithm/ParkAndRideTest.java
  src/test/java/org/opentripplanner/routing/algorithm/StreetModeLinkingTest.java
  src/test/java/org/opentripplanner/routing/algorithm/TestAStar.java
  src/test/java/org/opentripplanner/routing/algorithm/TestDominanceFunction.java
  src/test/java/org/opentripplanner/routing/algorithm/TestGraphPath.java
  src/test/java/org/opentripplanner/routing/algorithm/TurnCostTest.java
  src/test/java/org/opentripplanner/routing/algorithm/TurnRestrictionTest.java
  src/test/java/org/opentripplanner/routing/core/RoutingContextDestroyTest.java
  src/test/java/org/opentripplanner/routing/core/StateEditorTest.java
  src/test/java/org/opentripplanner/routing/edgetype/PlainStreetEdgeTest.java
  src/test/java/org/opentripplanner/routing/edgetype/loader/TestGeometryAndBlockProcessor.java
  src/test/java/org/opentripplanner/routing/edgetype/loader/TestHopFactory.java
Labels: technical debt

#4047 Error in SpeedTest input parser [changelog skip]
  .github/workflows/performance-test.yml
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/model/testcase/CsvFileIO.java
  test/ci-performance-test/travelSearch.csv
Labels: bug

#4030 Re-add some GTFS-based tests [changelog skip]
  src/ext-test/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandlerTest.java
  src/test/java/org/opentripplanner/GtfsTest.java
  src/test/java/org/opentripplanner/mmri/AllModesAndAgenciesTest.java
  src/test/java/org/opentripplanner/mmri/BeneficialChangesTest.java
  src/test/java/org/opentripplanner/mmri/ExcludedRoutesTest.java
  src/test/java/org/opentripplanner/mmri/ExcludedStopsTest.java
  src/test/java/org/opentripplanner/mmri/ExcludedTripsTest.java
  src/test/java/org/opentripplanner/mmri/FirstForbiddenTripToTripTransferTest.java
  src/test/java/org/opentripplanner/mmri/FirstPreferredTripToTripTransferTest.java
  src/test/java/org/opentripplanner/mmri/FirstUnpreferredTransferTest.java
  src/test/java/org/opentripplanner/mmri/MMRI Testdocument.pdf
  src/test/java/org/opentripplanner/mmri/MmriTest.java
  src/test/java/org/opentripplanner/mmri/OnTripTest.java
  src/test/java/org/opentripplanner/mmri/OptimizationTest.java
  src/test/java/org/opentripplanner/mmri/PlannerstackScenarioTest.java
  src/test/java/org/opentripplanner/mmri/PreferencesTest.java
  src/test/java/org/opentripplanner/mmri/SecondForbiddenTripToTripTransferTest.java
  src/test/java/org/opentripplanner/mmri/SecondPreferredTripToTripTransferTest.java
  src/test/java/org/opentripplanner/mmri/SecondUnpreferredTransferTest.java
  src/test/java/org/opentripplanner/mmri/ServiceAlertTest.java
  src/test/java/org/opentripplanner/mmri/StopToStopTransfersTest.java
  src/test/java/org/opentripplanner/mmri/TimeTest.java
  src/test/java/org/opentripplanner/mmri/TransferTimeTest.java
  src/test/java/org/opentripplanner/mmri/UnplannedChangesTest.java
  src/test/java/org/opentripplanner/mmri/WheelchairTest.java
  src/test/java/org/opentripplanner/mmri/package-info.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainTest.java
  src/test/java/org/opentripplanner/routing/edgetype/PatternInterlineDwellTest.java
  src/test/java/org/opentripplanner/routing/graph/RoutingServiceTest.java
  src/test/java/org/opentripplanner/updater/GtfsRealtimeFuzzyTripMatcherTest.java
Labels: Regression, technical debt

#4049 Always parse Netex flexible lines
  src/main/java/org/opentripplanner/netex/loader/parser/ServiceFrameParser.java
Labels: bug, NeTEx

#4039 Improve DatedServiceJourney implementation [changelog skip]
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/DatedServiceJourneyQuery.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/DatedServiceJourneyType.java
  src/main/java/org/opentripplanner/model/TripOnServiceDate.java
  src/main/java/org/opentripplanner/netex/index/api/ReadOnlyHierarchicalMap.java
  src/main/java/org/opentripplanner/netex/index/hierarchy/AbstractHierarchicalMap.java
  src/main/java/org/opentripplanner/netex/index/hierarchy/HierarchicalMap.java
  src/main/java/org/opentripplanner/netex/index/hierarchy/HierarchicalMultimap.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripCalendarBuilder.java
  src/main/java/org/opentripplanner/netex/mapping/TripMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripServiceAlterationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/calendar/DatedServiceJourneyMapper.java
  src/main/java/org/opentripplanner/netex/mapping/support/NetexMapperIndexes.java
  src/main/java/org/opentripplanner/routing/DatedServiceJourneyHelper.java
  src/test/java/org/opentripplanner/netex/mapping/TripPatternMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/calendar/DatedServiceJourneyMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/support/NetexMapperIndexesTest.java
Labels: bug, improvement, Entur test
