Repository opentripplanner/OpenTripPlanner, pull requests merged in 2022-12, with the labels that each got.

#4641 Add carpool and taxi modes
  docs/RouteRequest.md
  src/client/images/mode/carpool.png
  src/client/images/mode/carpool_darkbg.png
  src/client/js/otp/config.js
  src/client/js/otp/util/Itin.js
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/api/mapping/ModeMapper.java
  src/main/java/org/opentripplanner/api/mapping/RouteTypeMapper.java
  src/main/java/org/opentripplanner/api/parameter/ApiRequestMode.java
  src/main/java/org/opentripplanner/api/parameter/QualifiedMode.java
  src/main/java/org/opentripplanner/gtfs/mapping/TransitModeMapper.java
  src/main/java/org/opentripplanner/transit/model/basic/TransitMode.java
  src/test/java/org/opentripplanner/api/parameter/ApiRequestModeTest.java
  src/test/java/org/opentripplanner/api/parameter/QualifiedModeSetTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/RouteMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/TransitModeMapperTest.java
Labels: new feature, bump serialization id

#4649 Add flex speed test for Washington State
  .github/workflows/performance-test.yml
  src/test/java/org/opentripplanner/standalone/config/ExampleConfigTest.java
  src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
  test/performance/README.md
  test/performance/washington-state/build-config.json
  test/performance/washington-state/generate_test_cases.py
  test/performance/washington-state/otp-config.json
  test/performance/washington-state/speed-test-config.json
  test/performance/washington-state/travelSearch-expected-results.csv
  test/performance/washington-state/travelSearch.csv
Labels: IBI, skip changelog

#4653 Update list of PLC members
  docs/Governance.md
Labels: documentation, skip changelog

#4614 Prevent bicycles from using stairs
  docs/RouteRequest.md
  docs/RouterConfiguration.md
  src/main/java/org/opentripplanner/routing/api/request/preference/BikePreferences.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/specifier/WayTestData.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/tagmapper/DefaultMapperTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeCostTest.java
  src/test/resources/standalone/config/router-config.json
Labels: bug

#4597 Bugfix for interchanges that start and end from the same stop
  src/main/java/org/opentripplanner/gtfs/mapping/TransferMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TransferMapper.java
  src/test/java/org/opentripplanner/gtfs/mapping/GtfsTestData.java
  src/test/java/org/opentripplanner/gtfs/mapping/TransferMapperTest.java
Labels: bug, Entur test, Skanetrafiken

#4639 fix: forBoarding and forAlighting on cancelled calls in transmodel api
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
Labels: bug, sandbox, Entur test

#4658 Add test for keeping Transmodel GraphQL schema in sync
  src/ext-test/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchemaTest.java
  src/ext/graphql/transmodelapi/schema.graphql
Labels: improvement

#4642 Make maxFlexTripDuration configurable
  doc-templates/Flex.md
  docs/RouterConfiguration.md
  docs/examples/ibi/atlanta/router-config.json
  docs/sandbox/Flex.md
  src/ext-test/java/org/opentripplanner/ext/flex/FlexTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/UnscheduledTripTest.java
  src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
  src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/StreetFlexPathCalculator.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessEgressTemplate.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessTemplate.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexEgressTemplate.java
  src/ext/java/org/opentripplanner/ext/flex/trip/FlexTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectFlexRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/FlexAccessEgressRouter.java
  src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
  src/main/java/org/opentripplanner/standalone/config/sandbox/FlexConfig.java
  src/test/java/org/opentripplanner/generate/doc/FlexConfigurationDocTest.java
  src/test/java/org/opentripplanner/generate/doc/RouterConfigurationDocTest.java
  src/test/resources/standalone/config/router-config.json
Labels: new feature, sandbox, Entur test, config change

#4593 Extract separate conditions for "equals", "greater than", "absent" during OSM tag mapping, add Portland tag mapping
  doc-templates/BuildConfiguration.md
  docs/BuildConfiguration.md
  src/main/java/org/opentripplanner/graph_builder/module/osm/specifier/BestMatchSpecifier.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/specifier/Condition.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/specifier/ExactMatchSpecifier.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/specifier/OsmSpecifier.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/tagmapping/OsmTagMapper.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/tagmapping/PortlandMapper.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
  src/test/java/org/opentripplanner/generate/doc/framework/TemplateUtil.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModuleTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/specifier/BestMatchSpecifierTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/specifier/ConditionTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/specifier/SpecifierTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/specifier/WayTestData.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/tagmapping/AtlantaMapperTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/tagmapping/DefaultMapperTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/tagmapping/FinlandMapperTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/tagmapping/GermanyMapperTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/tagmapping/HoustonMapperTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/tagmapping/NorwayMapperTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/tagmapping/PortlandMapperTest.java
  src/test/java/org/opentripplanner/routing/graph/GraphSerializationTest.java
Labels: new feature, IBI

#4627 Expose opening hours in Stadtnavi parking vector tiles
  src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/VehicleParkingsLayerTest.java
  src/ext-test/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkUpdaterTest.java
  src/ext-test/java/org/opentripplanner/ext/vehicleparking/parkapi/ParkAPIUpdaterTest.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/DigitransitVehicleParkingPropertyMapper.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/StadtnaviVehicleParkingPropertyMapper.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/parkapi/ParkAPIUpdater.java
  src/main/java/org/opentripplanner/model/calendar/openinghours/OHCalendar.java
  src/main/java/org/opentripplanner/model/calendar/openinghours/OpeningHours.java
  src/main/java/org/opentripplanner/model/calendar/openinghours/OsmOpeningHoursSupport.java
Labels: improvement, sandbox, skip changelog

#4604 Expose parameters for filtering in APIs
  docs/RouteRequest.md
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/DefaultRouteRequestType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
  src/main/java/org/opentripplanner/api/common/RequestToPreferencesMapper.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/raptor/api/request/SearchParams.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RaptorRequestMapper.java
  src/main/java/org/opentripplanner/routing/api/request/framework/Units.java
  src/main/java/org/opentripplanner/routing/api/request/preference/RaptorPreferences.java
  src/main/java/org/opentripplanner/routing/api/request/preference/TransferPreferences.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  src/test/java/org/opentripplanner/routing/api/request/preference/TransferPreferencesTest.java
Labels: improvement, Entur test, skip changelog

#4617 Better fallback in shape geometry processing
  src/main/java/org/opentripplanner/graph_builder/issues/BogusShapeGeometryCaught.java
  src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryProcessor.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/model/ShapeGeometryTest.java
  src/test/resources/gtfs/shape_dist_traveled/agency.txt
  src/test/resources/gtfs/shape_dist_traveled/calendar.txt
  src/test/resources/gtfs/shape_dist_traveled/routes.txt
  src/test/resources/gtfs/shape_dist_traveled/shapes.txt
  src/test/resources/gtfs/shape_dist_traveled/stop_times.txt
  src/test/resources/gtfs/shape_dist_traveled/stops.txt
  src/test/resources/gtfs/shape_dist_traveled/trips.txt
Labels: improvement

#4594 Separate mixin properties from way properties
  src/ext/java/org/opentripplanner/ext/reportapi/model/BicycleSafetyReport.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/DefaultMapper.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/GermanyMapper.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/NorwayMapper.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/PortlandMapper.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/MixinProperties.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/MixinPropertiesBuilder.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/SafetyFeatures.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/WayPropertyPicker.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/WayPropertySet.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModuleTest.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/OsmTagMapperTest.java
  src/test/java/org/opentripplanner/openstreetmap/wayproperty/MixinPropertiesBuilderTest.java
Labels: technical debt, IBI, skip changelog

#4659 Clean up flex implementation
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/LineType.java
  src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java
Labels: bug, sandbox, technical debt, Entur test

#4655 Add limits for flex access/egress walking
  docs/RouterConfiguration.md
  docs/sandbox/Flex.md
  src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessEgressTemplate.java
  src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeResource.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/AccessEgressRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectFlexRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/FlexAccessEgressRouter.java
  src/main/java/org/opentripplanner/standalone/config/sandbox/FlexConfig.java
  src/test/java/org/opentripplanner/standalone/config/sandbox/FlexConfigTest.java
  src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
  src/test/java/org/opentripplanner/transit/speed_test/options/SpeedTestConfig.java
  src/test/resources/standalone/config/router-config.json
  test/performance/washington-state/speed-test-config.json
Labels: sandbox, IBI

#4664 Add OSM-formatted opening hours to GraphQL API
  src/ext-test/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkUpdaterTest.java
  src/ext-test/java/org/opentripplanner/ext/vehicleparking/parkapi/ParkAPIUpdaterTest.java
  src/ext-test/resources/vehicleparking/parkapi/herrenberg.json
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLBikeParkImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLCarParkImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLOpeningHoursImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLVehicleParkingImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/README.md
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/graphql-codegen.yml
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/package.json
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/yarn.lock
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/model/calendar/openinghours/OsmOpeningHoursSupport.java
Labels: sandbox, skip changelog, bbnavi

#4669 Convert vehicle rental source parameters to records
  src/ext/java/org/opentripplanner/ext/smoovebikerental/SmooveBikeRentalDataSource.java
  src/ext/java/org/opentripplanner/ext/smoovebikerental/SmooveBikeRentalDataSourceParameters.java
  src/ext/java/org/opentripplanner/ext/vehiclerentalservicedirectory/GbfsDataSourceParameters.java
  src/ext/java/org/opentripplanner/ext/vilkkubikerental/VilkkuBikeRentalDataSource.java
  src/ext/java/org/opentripplanner/ext/vilkkubikerental/VilkkuBikeRentalDataSourceParameters.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsVehicleRentalDataSource.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/VehicleRentalDataSourceFactory.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/params/GbfsVehicleRentalDataSourceParameters.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/params/VehicleRentalDataSourceParameters.java
Labels: technical debt, skip changelog

#4674 Make Prometheus endpoint take Accept header into account
  src/ext/java/org/opentripplanner/ext/actuator/ActuatorAPI.java
Labels: improvement, sandbox

#4672 Advertise Gitter channel in documentation [ci skip]
  CONTRIBUTING.md
  README.md
  docs/index.md
Labels: documentation, skip changelog

#4666 Add entrances to parking lots that are unconnected in OSM
  src/main/java/org/opentripplanner/graph_builder/issues/ParkAndRideUnlinked.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/AreaGroup.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/ParkingProcessor.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModuleTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/UnconnectedAreasTest.java
Labels: improvement, bbnavi

#4671 World envelope service - cleanup
  ARCHITECTURE.md
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderFactory.java
  src/main/java/org/opentripplanner/graph_builder/module/geometry/CalculateWorldEnvelopeModule.java
  src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
  src/main/java/org/opentripplanner/service/package.md
  src/main/java/org/opentripplanner/service/worldenvelope/WorldEnvelopeRepository.java
  src/main/java/org/opentripplanner/service/worldenvelope/WorldEnvelopeService.java
  src/main/java/org/opentripplanner/service/worldenvelope/configure/WorldEnvelopeModule.java
  src/main/java/org/opentripplanner/service/worldenvelope/configure/WorldEnvelopeRepositoryModule.java
  src/main/java/org/opentripplanner/service/worldenvelope/configure/WorldEnvelopeServiceModule.java
  src/main/java/org/opentripplanner/service/worldenvelope/internal/DefaultWorldEnvelopeRepository.java
  src/main/java/org/opentripplanner/service/worldenvelope/internal/DefaultWorldEnvelopeService.java
  src/main/java/org/opentripplanner/service/worldenvelope/service/WorldEnvelopeModel.java
  src/main/java/org/opentripplanner/standalone/OTPMain.java
  src/main/java/org/opentripplanner/standalone/api/OtpServerRequestContext.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationFactory.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationModule.java
  src/main/java/org/opentripplanner/standalone/configure/LoadApplication.java
  src/main/java/org/opentripplanner/standalone/configure/LoadApplicationFactory.java
  src/main/java/org/opentripplanner/standalone/server/DefaultServerRequestContext.java
  src/test/java/org/opentripplanner/TestServerContext.java
  src/test/java/org/opentripplanner/routing/graph/GraphSerializationTest.java
  src/test/java/org/opentripplanner/service/worldenvelope/internal/WorldEnvelopeRepositoryTest.java
  src/test/java/org/opentripplanner/service/worldenvelope/internal/WorldEnvelopeServiceTest.java
  src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
Labels: technical debt, bump serialization id, skip changelog

#4665 Add new fields to Transmodel API
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/flex/trip/FlexTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/sx/PtSituationElementType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/TimetabledPassingTimeType.java
Labels: improvement, sandbox, Entur test, skip changelog

#4574 Include crossing=traffic_signals and use it for walking/cycling penalty on crossings
  src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMNode.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/FinlandMapper.java
  src/main/java/org/opentripplanner/street/model/vertex/IntersectionVertex.java
  src/main/java/org/opentripplanner/street/model/vertex/OsmBoardingLocationVertex.java
  src/main/java/org/opentripplanner/street/model/vertex/OsmVertex.java
  src/main/java/org/opentripplanner/street/model/vertex/SplitterVertex.java
  src/main/java/org/opentripplanner/street/search/intersection_model/AbstractIntersectionTraversalCalculator.java
  src/main/java/org/opentripplanner/street/search/intersection_model/SimpleIntersectionTraversalCalculator.java
  src/main/java/org/opentripplanner/visualizer/ShowGraph.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModuleTest.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/FinlandMapperTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/ElevationSnapshotTest.snap
  src/test/java/org/opentripplanner/street/integration/BicycleRoutingTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeTest.java
  src/test/java/org/opentripplanner/street/model/vertex/IntersectionVertexTest.java
  src/test/java/org/opentripplanner/street/search/intersection_model/SimpleIntersectionTraversalCalculatorTest.java
Labels: improvement, bump serialization id, Digitransit test

#4679 Add amenity=ferry terminal to boarding locations
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
Labels: skip changelog

#4620 Improve support for replaced departure in siri
  src/ext-test/java/org/opentripplanner/ext/siri/AddedTripHelperTest.java
  src/ext-test/java/org/opentripplanner/ext/siri/TimeTableHelperTest.java
  src/ext/java/org/opentripplanner/ext/siri/AddedTripHelper.java
  src/ext/java/org/opentripplanner/ext/siri/Mode.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/TimeForStop.java
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
  src/main/java/org/opentripplanner/transit/service/TransitModel.java
Labels: Skanetrafiken, RealTimeUpdate

#4677 Date-based tag for container image
  .github/workflows/cibuild.yml
Labels: skip changelog

#4668 Extract elevator handling into separate class
  src/main/java/org/opentripplanner/graph_builder/module/osm/ElevatorProcessor.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/ParkingProcessor.java
Labels: technical debt, skip changelog

#4685 Remove extra type for vehicle rental service directory
  .github/workflows/cibuild.yml
  src/ext/java/org/opentripplanner/ext/vehiclerentalservicedirectory/GbfsDataSourceParameters.java
  src/ext/java/org/opentripplanner/ext/vehiclerentalservicedirectory/VehicleRentalServiceDirectoryFetcher.java
Labels: bug, sandbox, skip changelog
