Repository opentripplanner/OpenTripPlanner, pull requests merged in 2022-05, with the labels that each got.

#4116 Improve stop linking by taking OSM platform polygons into account
  docs/BoardingLocations.md
  docs/BuildConfiguration.md
  docs/images/buckhead-station.png
  mkdocs.yml
  pom.xml
  src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
  src/ext-test/java/org/opentripplanner/ext/vectortiles/StopsLayerTest.java
  src/ext-test/java/org/opentripplanner/ext/vectortiles/VehicleParkingsLayerTest.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModule.java
  src/main/java/org/opentripplanner/graph_builder/module/TransitToTaggedStopsModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OSMFilter.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  src/main/java/org/opentripplanner/inspector/TraversalPermissionsEdgeRenderer.java
  src/main/java/org/opentripplanner/openstreetmap/OpenStreetMapParser.java
  src/main/java/org/opentripplanner/openstreetmap/OpenStreetMapProvider.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMNode.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWay.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/edgetype/BoardingLocationToStopLink.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetTransitEntityLink.java
  src/main/java/org/opentripplanner/routing/vertextype/OsmBoardingLocationVertex.java
  src/main/java/org/opentripplanner/routing/vertextype/TransitStopStreetVertex.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/graph_builder/linking/LinkStopToPlatformTest.java
  src/test/java/org/opentripplanner/graph_builder/module/FakeGraph.java
  src/test/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModuleTest.java
  src/test/java/org/opentripplanner/graph_builder/module/PruneNoThruIslandsTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModuleTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapParserTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/PlatformLinkerTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TemplateLibraryTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TriangleInequalityTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/UnconnectedAreasTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/UnroutableTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetTest.java
  src/test/java/org/opentripplanner/openstreetmap/model/BicycleNetworkRelationsTest.java
  src/test/java/org/opentripplanner/openstreetmap/model/OSMNodeTest.java
  src/test/java/org/opentripplanner/openstreetmap/model/OSMWayTest.java
  src/test/java/org/opentripplanner/openstreetmap/model/OSMWithTagsTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
  src/test/java/org/opentripplanner/standalone/config/BuildConfigTest.java
Labels: improvement, new feature, IBI test

#4134 Fix departuresPerTripPattern when limitOnDestinationDisplay is true [changelog skip]
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
Labels: bug, sandbox, Entur test

#4133 Generate trip patterns for flex trips [changelog skip]
  src/main/java/org/opentripplanner/graph_builder/issues/TripDegenerate.java
  src/main/java/org/opentripplanner/gtfs/GenerateTripPatternsOperation.java
Labels: improvement

#4118 Clean up AStar related classes [changelog skip]
  src/ext/java/org/opentripplanner/ext/flex/FlexibleTransitLeg.java
  src/ext/java/org/opentripplanner/ext/flex/edgetype/FlexTripEdge.java
  src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/StreetFlexPathCalculator.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/AStar.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/AStarBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapper.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/core/RoutingContext.java
  src/main/java/org/opentripplanner/routing/core/State.java
  src/main/java/org/opentripplanner/routing/core/StateData.java
  src/main/java/org/opentripplanner/routing/core/StateEditor.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetTransitEntityLink.java
  src/main/java/org/opentripplanner/routing/graph/Edge.java
  src/main/java/org/opentripplanner/routing/graphfinder/StreetGraphFinder.java
  src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
  src/main/java/org/opentripplanner/routing/spt/DominanceFunction.java
  src/main/java/org/opentripplanner/routing/spt/ShortestPathTree.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TriangleInequalityTest.java
  src/test/java/org/opentripplanner/routing/algorithm/TestDominanceFunction.java
  src/test/java/org/opentripplanner/routing/core/TraverseResultTest.java
  src/test/java/org/opentripplanner/routing/edgetype/PlainStreetEdgeTest.java
Labels: technical debt

#4139 Guard against null nameType in Netex mapper [changelog skip]
  src/main/java/org/opentripplanner/netex/mapping/StationMapper.java
Labels: bug, Entur test, NeTEx

#4138 Fix platform edge name [changelog skip]
  src/main/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModule.java
  src/main/java/org/opentripplanner/util/LocalizedString.java
  src/test/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModuleTest.java
Labels: bug

#4143 Code cleanup [changelog skip]
  src/main/java/org/opentripplanner/model/calendar/ServiceDate.java
  src/main/java/org/opentripplanner/model/calendar/impl/CalendarServiceDataFactoryImpl.java
Labels: technical debt

#4131 Adapt documentation for walkReluctance, comment on performance [changelog skip]
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
Labels: technical debt

#4127 TransferGenerator fix [changelog skip]
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGenerator.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferServiceAdaptor.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTripSchedule.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGeneratorTest.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTransferPoint.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTransitData.java
Labels: bug, NeTEx, Skanetrafiken

#4144 Solve bug in SiriAlertsUpdateHandler [changelog skip]
  src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java
Labels: bug, Skanetrafiken

#4145 Remove duplicated documentation file [changelog skip]
  docs/sandbox/SiriAzureUpdaters.md
Labels: improvement, documentation

#4123 Transmodel API transport mode not present or null is all transport modes [changelog skip]
  docs/sandbox/TransmodelApi.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
Labels: sandbox, Entur test

#4136 Bugfix on setHopGemometriesFromPattern [changelog skip]
  src/main/java/org/opentripplanner/model/TripPattern.java
  src/test/java/org/opentripplanner/model/TripPatternTest.java
Labels: bug, Skanetrafiken

#4055 Fallback to recorded/expected arrival/departure time if other one is missing in SIRI-ET
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/DateMapper.java
Labels: improvement, Entur test, RealTimeUpdate

#4149 Filter out GBFS stations that are missing required information [changelog skip]
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsStationInformationMapper.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsVehicleRentalDataSource.java
  src/test/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsVehicleRentalDataSourceTest.java
  src/test/resources/gbfs/helsinki/station_information.json
Labels: improvement

#4153 doc: add headers GBFS config doc
  docs/RouterConfiguration.md
Labels: documentation

#4154 Add "arrive by" searches to speed test [changelog skip]
  test/ci-performance-test/build-config.json
  test/ci-performance-test/travelSearch-expected-results.csv
  test/ci-performance-test/travelSearch.csv
Labels: improvement

#4125 Use actual distance for walk distance in StreetEdge
  pom.xml
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetElevationExtension.java
  src/test/java/org/opentripplanner/routing/edgetype/TriangleTest.java
Labels: bug, Entur test

#4129 Port isochrone/travel time surface support from OTP1 into a sandbox API
  docs/SandboxExtension.md
  docs/sandbox/TravelTime.md
  pom.xml
  src/ext/java/org/opentripplanner/ext/traveltime/IsochroneData.java
  src/ext/java/org/opentripplanner/ext/traveltime/IsochroneRenderer.java
  src/ext/java/org/opentripplanner/ext/traveltime/IsolineMetric.java
  src/ext/java/org/opentripplanner/ext/traveltime/SampleGridRenderer.java
  src/ext/java/org/opentripplanner/ext/traveltime/SampleGridSPTVisitor.java
  src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeRequest.java
  src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeResource.java
  src/ext/java/org/opentripplanner/ext/traveltime/WTWD.java
  src/ext/java/org/opentripplanner/ext/traveltime/WTWDAccumulativeMetric.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/AccumulativeGridSampler.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/AccumulativeMetric.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/DelaunayEdge.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/DelaunayIsolineBuilder.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/DelaunayPoint.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/DelaunayTriangulation.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/IsolineBuilder.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/SparseMatrix.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/SparseMatrixZSampleGrid.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/ZMetric.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/ZSampleGrid.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/ZSamplePoint.java
  src/ext/java/org/opentripplanner/ext/traveltime/spt/SPTVisitor.java
  src/ext/java/org/opentripplanner/ext/traveltime/spt/SPTWalker.java
  src/main/java/org/opentripplanner/api/configuration/APIEndpoints.java
  src/main/java/org/opentripplanner/routing/core/StateData.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/SearchParams.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/SearchParamsBuilder.java
  src/main/java/org/opentripplanner/util/OTPFeature.java
Labels: new feature, sandbox, Regression, Entur test

#4164 Enable codecov report on PRs [changelog skip]
  codecov.yml
Labels: technical debt

#4151 Otp2 arch test [changelog skip]
  pom.xml
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/OtpArchitectureModules.java
  src/test/java/org/opentripplanner/_support/arch/ArchComponent.java
  src/test/java/org/opentripplanner/_support/arch/Module.java
  src/test/java/org/opentripplanner/_support/arch/Package.java
  src/test/java/org/opentripplanner/transit/model/TransitModelArchitectureTest.java
  src/test/java/org/opentripplanner/util/UtilArchitectureTest.java
Labels: technical debt

#4162 Option to add customized logging features [changelog skip]
  src/main/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModule.java
  src/main/resources/logback.xml
Labels: improvement

#3962 Don't indicate stop has been updated when NO_DATA is defined
  pom.xml
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
  src/main/java/org/opentripplanner/model/Timetable.java
  src/main/java/org/opentripplanner/model/TripTimeOnDate.java
  src/main/java/org/opentripplanner/routing/trippattern/StopRealTimeState.java
  src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java
  src/test/java/org/opentripplanner/model/TimetableTest.java
  src/test/java/org/opentripplanner/routing/trippattern/TripTimesTest.java
  src/test/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSourceTest.java
Labels: improvement, RealTimeUpdate

#4165 Implement nearby searches for car and bicycle parking
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLUtils.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLplaceAtDistanceImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/PlaceMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/PlaceAtDistanceType.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/inspector/BikeSafetyEdgeRenderer.java
  src/main/java/org/opentripplanner/inspector/TraversalPermissionsEdgeRenderer.java
  src/main/java/org/opentripplanner/model/VehicleRentalStationInfo.java
  src/main/java/org/opentripplanner/model/plan/Place.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapper.java
  src/main/java/org/opentripplanner/routing/core/State.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetVehicleRentalLink.java
  src/main/java/org/opentripplanner/routing/edgetype/VehicleRentalEdge.java
  src/main/java/org/opentripplanner/routing/graphfinder/PlaceAtDistance.java
  src/main/java/org/opentripplanner/routing/graphfinder/PlaceFinderTraverseVisitor.java
  src/main/java/org/opentripplanner/routing/graphfinder/PlaceType.java
  src/main/java/org/opentripplanner/routing/graphfinder/StreetGraphFinder.java
  src/main/java/org/opentripplanner/routing/vertextype/VehicleRentalPlaceVertex.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdater.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/model/impl/EntityByIdTest.java
  src/test/java/org/opentripplanner/model/impl/OtpTransitServiceBuilderLimitPeriodTest.java
  src/test/java/org/opentripplanner/model/impl/OtpTransitServiceBuilderTest.java
  src/test/java/org/opentripplanner/model/plan/LegTest.java
  src/test/java/org/opentripplanner/model/plan/PlaceTest.java
  src/test/java/org/opentripplanner/model/plan/pagecursor/PageCursorTest.java
  src/test/java/org/opentripplanner/routing/algorithm/BikeRentalTest.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
  src/test/java/org/opentripplanner/routing/graphfinder/StreetGraphFinderTest.java
Labels: improvement, IBI test

#4171 Rename WheelchairBoarding to WheelchairAccessibility [changelog skip]
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLUtils.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
  src/main/java/org/opentripplanner/api/mapping/StopMapper.java
  src/main/java/org/opentripplanner/api/mapping/WheelchairAccessibilityMapper.java
  src/main/java/org/opentripplanner/api/mapping/WheelchairBoardingMapper.java
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/gtfs/mapping/BoardingAreaMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/EntranceMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/PathwayNodeMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/StopMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/StopMappingWrapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/TripMapper.java
  src/main/java/org/opentripplanner/inspector/WheelchairEdgeRenderer.java
  src/main/java/org/opentripplanner/model/BoardingArea.java
  src/main/java/org/opentripplanner/model/Entrance.java
  src/main/java/org/opentripplanner/model/PathwayNode.java
  src/main/java/org/opentripplanner/model/StationElement.java
  src/main/java/org/opentripplanner/model/Stop.java
  src/main/java/org/opentripplanner/model/StopLocation.java
  src/main/java/org/opentripplanner/model/Trip.java
  src/main/java/org/opentripplanner/model/TripPattern.java
  src/main/java/org/opentripplanner/model/WheelchairAccessibility.java
  src/main/java/org/opentripplanner/netex/mapping/StopAndStationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripMapper.java
  src/main/java/org/opentripplanner/netex/mapping/WheelChairMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filter/AccessibilityScoreFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/WheelchairCostCalculator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/frequency/FrequencyBoardOrAlightEvent.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripPatternForDates.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleWithOffset.java
  src/main/java/org/opentripplanner/routing/edgetype/BoardingLocationToStopLink.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetTransitEntityLink.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetTransitEntranceLink.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetTransitStopLink.java
  src/main/java/org/opentripplanner/routing/vertextype/TransitBoardingAreaVertex.java
  src/main/java/org/opentripplanner/routing/vertextype/TransitEntranceVertex.java
  src/main/java/org/opentripplanner/routing/vertextype/TransitPathwayNodeVertex.java
  src/main/java/org/opentripplanner/routing/vertextype/TransitStopVertex.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTripSchedule.java
  src/test/java/org/opentripplanner/gtfs/mapping/BoardingAreaMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/EntranceMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/PathwayNodeMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/StopAndStationMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java
  src/test/java/org/opentripplanner/netex/NetexBundleSmokeTest.java
  src/test/java/org/opentripplanner/netex/mapping/FlexStopLocationMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/StopAndStationMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/TripMapperTest.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/WheelchairCostCalculatorTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilterTest.java
  src/test/java/org/opentripplanner/routing/edgetype/StreetTransitEntityLinkTest.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTripSchedule.java
Labels: technical debt, IBI test

#4155 Refactor TimetableHelper in order to make testing easier [changelog skip]
  src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
  src/main/java/org/opentripplanner/model/Timetable.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/model/TripTimeOnDate.java
  src/main/java/org/opentripplanner/routing/TripTimesShortHelper.java
Labels: technical debt

#4166 Do not link cars to stop vertices in routing
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/routing/impl/StreetVertexIndex.java
  src/test/java/org/opentripplanner/routing/algorithm/StreetModeLinkingTest.java
Labels: improvement, Entur test

#4161 Split journey pattern geometries [changelog skip]
  docs/sandbox/TransmodelApi.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/GeometryMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/JourneyPatternType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/StopToStopGeometryType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/util/EncodedPolylineBeanWithStops.java
Labels: improvement, Skanetrafiken

#4159 Report on sample level in SpeedTest to Micrometer [changelog skip]
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RaptorRequestMapper.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingTag.java
  src/main/java/org/opentripplanner/routing/api/request/Tags.java
  src/main/java/org/opentripplanner/routing/framework/DebugTimingAggregator.java
  src/main/java/org/opentripplanner/routing/framework/MicrometerUtils.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/RaptorRequest.java
  src/main/java/org/opentripplanner/transit/raptor/api/request/RaptorRequestBuilder.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/configure/RaptorConfig.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/debug/WorkerPerformanceTimers.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTestRequest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/model/testcase/CsvFileIO.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/model/testcase/TestCaseDefinition.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/model/timer/SpeedTestTimer.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/options/SpeedTestCmdLineOpts.java
  test/ci-performance-test/travelSearch.csv
Labels: improvement

#4174 Add support filterByInUse in nearest query in Transmodel API [changelog skip]
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
Labels: Regression, Entur test

#4175 Add rental networks to REST API [changelog skip]
  src/main/java/org/opentripplanner/api/mapping/PlaceMapper.java
  src/main/java/org/opentripplanner/api/model/ApiPlace.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/ElevationSnapshotTest.snap
Labels: IBI test, IBI

#4183 Return null when deserializing empty page cursor [changelog skip]
  src/main/java/org/opentripplanner/model/plan/pagecursor/PageCursorSerializer.java
  src/test/java/org/opentripplanner/model/plan/pagecursor/PageCursorTest.java
Labels: improvement
