Repository opentripplanner/OpenTripPlanner, pull requests merged in 2022-06, with the labels that each got.

#4158 Add gtfs stop description translations
  .gitignore
  pom.xml
  src/ext-test/java/org/opentripplanner/ext/vectortiles/StopsLayerTest.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/MonoOrMultiModalStation.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/DigitransitStopPropertyMapper.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/api/mapping/StopMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/BoardingAreaMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/EntranceMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/LocationMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/PathwayNodeMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/StationMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/StopMapper.java
  src/main/java/org/opentripplanner/model/BoardingArea.java
  src/main/java/org/opentripplanner/model/Entrance.java
  src/main/java/org/opentripplanner/model/FlexLocationGroup.java
  src/main/java/org/opentripplanner/model/FlexStopLocation.java
  src/main/java/org/opentripplanner/model/PathwayNode.java
  src/main/java/org/opentripplanner/model/Station.java
  src/main/java/org/opentripplanner/model/StationElement.java
  src/main/java/org/opentripplanner/model/Stop.java
  src/main/java/org/opentripplanner/model/StopLocation.java
  src/main/java/org/opentripplanner/netex/mapping/StationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopMapper.java
  src/test/java/org/opentripplanner/gtfs/mapping/BoardingAreaMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/EntranceMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/PathwayNodeMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/StopAndStationMapperTest.java
  src/test/java/org/opentripplanner/routing/edgetype/StreetTransitEntityLinkTest.java
Labels: improvement, GTFS

#4187 Replaced TripPatterns leave unwanted Timetables [changelog skip]
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
Labels: bug, Entur test, Skanetrafiken, RealTimeUpdate

#4192 Correct English translation of 'Car Only' in debug client [changelog skip]
  src/client/i18n/ca_ES.po
  src/client/i18n/de.po
  src/client/i18n/en.po
  src/client/i18n/es.po
  src/client/i18n/fr.po
  src/client/i18n/hu.po
  src/client/i18n/it.po
  src/client/i18n/messages.pot
  src/client/i18n/no.po
  src/client/i18n/pl.po
  src/client/i18n/pt.po
  src/client/i18n/sl.po
  src/client/js/otp/locale/ca_ES.json
  src/client/js/otp/locale/de.json
  src/client/js/otp/locale/en.json
  src/client/js/otp/locale/es.json
  src/client/js/otp/locale/fr.json
  src/client/js/otp/locale/hu.json
  src/client/js/otp/locale/it.json
  src/client/js/otp/locale/no.json
  src/client/js/otp/locale/pl.json
  src/client/js/otp/locale/pt.json
  src/client/js/otp/locale/sl.json
Labels: bug

#4194 Upgrade graphql-java to version 18
  pom.xml
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLplaceAtDistanceImpl.java
Labels: technical debt

#4195 Add option to discard min transfer times
  docs/BuildConfiguration.md
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/gtfs/MockGtfs.java
  src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/TransferMapper.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/gtfs/GtfsContextBuilder.java
  src/test/java/org/opentripplanner/gtfs/mapping/TransferMapperTest.java
Labels: new feature, GTFS, Entur test

#4035 Use negative delay from first stop in a GTFS RT update in previous stop times when required
  docs/RouterConfiguration.md
  src/main/java/org/opentripplanner/model/Timetable.java
  src/main/java/org/opentripplanner/model/TripTimeOnDate.java
  src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
  src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java
  src/main/java/org/opentripplanner/standalone/config/updaters/MqttGtfsRealtimeUpdaterConfig.java
  src/main/java/org/opentripplanner/standalone/config/updaters/PollingStoptimeUpdaterConfig.java
  src/main/java/org/opentripplanner/updater/stoptime/BackwardsDelayPropagationType.java
  src/main/java/org/opentripplanner/updater/stoptime/MqttGtfsRealtimeUpdater.java
  src/main/java/org/opentripplanner/updater/stoptime/MqttGtfsRealtimeUpdaterParameters.java
  src/main/java/org/opentripplanner/updater/stoptime/PollingStoptimeUpdater.java
  src/main/java/org/opentripplanner/updater/stoptime/PollingStoptimeUpdaterParameters.java
  src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
  src/test/java/org/opentripplanner/model/TimetableSnapshotTest.java
  src/test/java/org/opentripplanner/model/TimetableTest.java
Labels: improvement, RealTimeUpdate

#4173 Solve problems with timezones in Siri Updater module [changelog skip]
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/DateMapper.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/DateMapperTest.java
Labels: bug, Entur test, Skanetrafiken

#4205 OTP2 no longer crashes on invalid GTFS stop time sequences
  src/main/java/org/opentripplanner/gtfs/RepairStopTimesForEachTripOperation.java
Labels: bug, GTFS

#4207 Improve HTML message for a stop linked to an island [changelog skip]
  src/main/java/org/opentripplanner/common/OsmUrlGenerator.java
  src/main/java/org/opentripplanner/graph_builder/issues/PrunedIslandStop.java
Labels: improvement

#4216 Fix TransmodelGraphQLSchema after GraphQL lib update [changelog skip]
  src/ext-test/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchemaTest.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
Labels: bug, NeTEx

#4198 Add possibility to filter dated service journeys by replacementFor in the Transmodel API [changelog skip]
  docs/sandbox/TransmodelApi.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/DatedServiceJourneyQuery.java
Labels: improvement

#4200 Fix npe in null stop description translation [changelog skip]
  src/main/java/org/opentripplanner/gtfs/mapping/StationMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/StopMapper.java
  src/main/java/org/opentripplanner/util/TranslationHelper.java
Labels: bug

#4163 Cost-based accessibility routing for streets
  docs/Accessibility.md
  docs/examples/ibi/router-config.json
  src/ext-test/java/org/opentripplanner/ext/transmodelapi/model/TransportModeSlackTest.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/DefaultRoutingRequestType.java
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/inspector/TraversalPermissionsEdgeRenderer.java
  src/main/java/org/opentripplanner/inspector/WheelchairEdgeRenderer.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/ItinerariesHelper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/Transfer.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/WheelchairCostCalculator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRequestTransferCache.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilter.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/api/request/WheelchairAccessibilityRequest.java
  src/main/java/org/opentripplanner/routing/core/RoutingContext.java
  src/main/java/org/opentripplanner/routing/edgetype/ElevatorBoardEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/ElevatorHopEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/PathwayEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdgeReluctanceCalculator.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetTransitEntityLink.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
  src/main/java/org/opentripplanner/standalone/config/WheelchairAccessibilityRequestMapper.java
  src/test/java/org/opentripplanner/common/geometry/GeometryUtilsTest.java
  src/test/java/org/opentripplanner/common/model/LocationStringParserTest.java
  src/test/java/org/opentripplanner/datastore/file/FileDataSourceTest.java
  src/test/java/org/opentripplanner/graph_builder/module/linking/LinkingTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/GermanyWayPropertySetSourceTest.java
  src/test/java/org/opentripplanner/model/projectinfo/MavenProjectVersionTest.java
  src/test/java/org/opentripplanner/netex/mapping/DurationMapperTest.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/WheelchairCostCalculatorTest.java
  src/test/java/org/opentripplanner/routing/api/request/WheelchairAccessibilityRequestTest.java
  src/test/java/org/opentripplanner/routing/edgetype/ElevatorHopEdgeTest.java
  src/test/java/org/opentripplanner/routing/edgetype/PathwayEdgeTest.java
  src/test/java/org/opentripplanner/routing/edgetype/PlainStreetEdgeTest.java
  src/test/java/org/opentripplanner/routing/edgetype/StreetEdgeCostTest.java
  src/test/java/org/opentripplanner/routing/edgetype/StreetEdgeSplittingTest.java
  src/test/java/org/opentripplanner/routing/edgetype/StreetEdgeTest.java
  src/test/java/org/opentripplanner/routing/edgetype/StreetEdgeWheelchairCostTest.java
  src/test/java/org/opentripplanner/routing/edgetype/StreetTransitEntityLinkTest.java
  src/test/java/org/opentripplanner/routing/edgetype/StreetTraversalPermissionTest.java
  src/test/java/org/opentripplanner/routing/edgetype/TemporaryPartialStreetEdgeTest.java
  src/test/java/org/opentripplanner/routing/graph/EdgeTest.java
  src/test/java/org/opentripplanner/routing/graph/GraphSerializationTest.java
  src/test/java/org/opentripplanner/routing/vertextype/BarrierVertexTest.java
  src/test/java/org/opentripplanner/standalone/config/NetexConfigTest.java
  src/test/java/org/opentripplanner/standalone/config/RoutingRequestMapperTest.java
  src/test/java/org/opentripplanner/util/OtpAppExceptionTest.java
  src/test/java/org/opentripplanner/util/time/DateUtilsTest.java
Labels: improvement, IBI test, IBI

#4217 Expose SIRI ET PredictionInaccurate in Transmodel-API
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
  src/main/java/org/opentripplanner/model/TripTimeOnDate.java
Labels: RealTimeUpdate

#4224 Remove JUnit 4 [changelog skip]
  pom.xml
  src/test/java/org/opentripplanner/test/support/PolylineAssert.java
  src/test/java/org/opentripplanner/updater/alerts/AlertsUpdateHandlerTest.java
Labels: technical debt

#4218 Fix similar legs filter for frequency-based trips [changelog skip]
  src/main/java/org/opentripplanner/model/plan/FrequencyTransitLeg.java
  src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/groupids/GroupByTripIdAndDistanceTest.java
Labels: bug

#4214 Fix geometries for frequency-based trips [changelog skip]
  src/main/java/org/opentripplanner/model/TripPattern.java
  src/test/java/org/opentripplanner/graph_builder/module/GtfsModuleTest.java
  src/test/resources/testagency/trips.txt
Labels: improvement

#4225 Do not apply walkable area processing to open platform geometries
  src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWay.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapParserTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
Labels: improvement

#4232 Add support for groupOfLines in top level Transmodel API [changelog skip]
  docs/sandbox/TransmodelApi.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/GroupOfLinesType.java
  src/main/java/org/opentripplanner/routing/graph/GraphIndex.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/TransitService.java
Labels: improvement, sandbox, Entur test

#4226 When restoring debug UI from URL, zoom to route bounds and keep selected map layer [changelog skip]
  src/client/js/otp/config.js
  src/client/js/otp/core/Map.js
  src/client/js/otp/modules/multimodal/MultimodalPlannerModule.js
  src/client/js/otp/modules/planner/PlannerModule.js
Labels: OTP Debug UI

#4229 Fix IBI's P+R API [changelog skip]
  src/ext/java/org/opentripplanner/ext/parkAndRideApi/ParkAndRideResource.java
  src/main/java/org/opentripplanner/routing/vehicle_parking/VehicleParking.java
Labels: sandbox, IBI

#4231 Automatically bump serialization version id [changelog skip]
  .github/pull_request_template.md
  .github/workflows/post-merge.yml
Labels: bump serialization id

#4239 Reactivate snapshot test
  src/test/java/org/opentripplanner/routing/algorithm/mapping/TransitSnapshotTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
Labels: technical debt, skip changelog
