Repository opentripplanner/OpenTripPlanner, pull requests merged in 2022-10, with the labels that each got.

#4490 Atlanta fare service
  docs/BuildConfiguration.md
  docs/sandbox/Fares.md
  src/ext-test/java/org/opentripplanner/ext/fares/impl/AtlantaFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/FaresConfiguration.java
  src/ext/java/org/opentripplanner/ext/fares/impl/AtlantaFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/AtlantaFareServiceFactory.java
  src/main/java/org/opentripplanner/routing/core/FareType.java
Labels: sandbox, IBI, bump serialization id, skip changelog

#4491 Add initial get data timeout to SiriETGooglePubsubUpdater
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdaterParameters.java
  src/main/java/org/opentripplanner/standalone/config/updaters/SiriETGooglePubsubUpdaterConfig.java
  src/main/java/org/opentripplanner/util/lang/ToStringBuilder.java
  src/test/java/org/opentripplanner/util/lang/ToStringBuilderTest.java
Labels: sandbox, Entur test, skip changelog, config change

#4492 Document JVM configuration options
  docs/Configuration.md
Labels: documentation

#4482 Add support for HTTPS datasource for Graph Building
  docs/BuildConfiguration.md
  src/main/java/org/opentripplanner/datastore/api/DataSource.java
  src/main/java/org/opentripplanner/datastore/configure/DataStoreModule.java
  src/main/java/org/opentripplanner/datastore/https/HttpsDataSourceMetadata.java
  src/main/java/org/opentripplanner/datastore/https/HttpsDataSourceRepository.java
  src/main/java/org/opentripplanner/datastore/https/HttpsFileDataSource.java
  src/main/java/org/opentripplanner/util/HttpUtils.java
  src/test/java/org/opentripplanner/datastore/https/HttpsDataSourceRepositoryTest.java
  src/test/java/org/opentripplanner/datastore/https/HttpsFileDataSourceTest.java
Labels: new feature

#4465 Add detailed graph statistics report
  docs/sandbox/ReportApi.md
  src/ext/java/org/opentripplanner/ext/reportapi/model/GraphReportBuilder.java
  src/ext/java/org/opentripplanner/ext/reportapi/model/TransfersReport.java
  src/ext/java/org/opentripplanner/ext/reportapi/resource/ReportResource.java
  src/main/java/org/opentripplanner/common/model/CachedValue.java
Labels: new feature, sandbox, skip changelog

#4497 Otp2 use optional in data source
  src/main/java/org/opentripplanner/datastore/api/DataSource.java
  src/main/java/org/opentripplanner/datastore/file/AbstractFileDataSource.java
  src/main/java/org/opentripplanner/datastore/https/HttpsDataSourceMetadata.java
  src/test/java/org/opentripplanner/datastore/file/DirectoryDataSourceTest.java
  src/test/java/org/opentripplanner/datastore/file/FileDataSourceTest.java
Labels: technical debt, skip changelog

#4493 Remove filtering of flex patterns in NeTEX import
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/TimetabledPassingTimeType.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
Labels: improvement, technical debt, Entur test, NeTEx

#4489 Extract AStarRequest from RouteRequest
  src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
  src/ext/java/org/opentripplanner/ext/dataoverlay/DataOverlayStreetEdgeCostExtension.java
  src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeResource.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/graph_builder/module/PruneNoThruIslands.java
  src/main/java/org/opentripplanner/graph_builder/module/map/MatchState.java
  src/main/java/org/opentripplanner/model/plan/Place.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/AStarBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/RaptorTransferIndex.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/Transfer.java
  src/main/java/org/opentripplanner/routing/api/request/RouteRequest.java
  src/main/java/org/opentripplanner/routing/core/AStarRequest.java
  src/main/java/org/opentripplanner/routing/core/AStarRequestBuilder.java
  src/main/java/org/opentripplanner/routing/core/AStarRequestMapper.java
  src/main/java/org/opentripplanner/routing/core/State.java
  src/main/java/org/opentripplanner/routing/core/StateData.java
  src/main/java/org/opentripplanner/routing/core/StateEditor.java
  src/main/java/org/opentripplanner/routing/core/intersection_model/IntersectionTraversalCalculator.java
  src/main/java/org/opentripplanner/routing/edgetype/CarPickupableEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/ElevatorHopEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/PathwayEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetTransitEntityLink.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetVehicleParkingLink.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetVehicleRentalLink.java
  src/main/java/org/opentripplanner/routing/edgetype/TemporaryFreeEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/VehicleParkingEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/VehicleRentalEdge.java
  src/main/java/org/opentripplanner/routing/services/notes/StreetNotesService.java
  src/main/java/org/opentripplanner/routing/spt/DominanceFunction.java
  src/main/java/org/opentripplanner/routing/spt/GraphPath.java
  src/test/java/org/opentripplanner/graph_builder/module/map/StreetMatcherTest.java
  src/test/java/org/opentripplanner/routing/TestHalfEdges.java
  src/test/java/org/opentripplanner/routing/algorithm/DominanceFunctionTest.java
  src/test/java/org/opentripplanner/routing/core/StateEditorTest.java
  src/test/java/org/opentripplanner/routing/core/TraverseResultTest.java
  src/test/java/org/opentripplanner/routing/edgetype/ElevatorHopEdgeTest.java
  src/test/java/org/opentripplanner/routing/edgetype/PathwayEdgeTest.java
  src/test/java/org/opentripplanner/routing/edgetype/StreetEdgeCostTest.java
  src/test/java/org/opentripplanner/routing/edgetype/StreetEdgeTest.java
  src/test/java/org/opentripplanner/routing/edgetype/StreetEdgeWheelchairCostTest.java
  src/test/java/org/opentripplanner/routing/edgetype/StreetTransitEntityLinkTest.java
  src/test/java/org/opentripplanner/routing/edgetype/TemporaryPartialStreetEdgeTest.java
  src/test/java/org/opentripplanner/routing/edgetype/VehicleParkingEdgeTest.java
Labels: technical debt, skip changelog

#4484 Make walk and bicycle safety defaults adjustable based on speed limits on ways
  src/main/java/org/opentripplanner/graph_builder/module/osm/DefaultWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/FinlandWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertiesBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySet.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/FinlandWayPropertySetSourceTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModuleTest.java
Labels: improvement

#4486 Add Houston WayPropertySet
  src/ext/java/org/opentripplanner/ext/reportapi/model/BicycleSafetyReport.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/HoustonWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayProperties.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertyPicker.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySet.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetSource.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/HoustonWayPropertySetSourceTest.java
Labels: IBI, skip changelog

#4501 Fix typo in JVM tuning configuration
  docs/Configuration.md
Labels: documentation, skip changelog

#4471 Metrics for realtime trip updaters
  pom.xml
  src/ext/java/org/opentripplanner/ext/actuator/ActuatorAPI.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdaterParameters.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdaterParameters.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdaterParameters.java
  src/main/java/org/opentripplanner/common/model/Result.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/model/UpdateError.java
  src/main/java/org/opentripplanner/standalone/config/UpdatersConfig.java
  src/main/java/org/opentripplanner/standalone/config/updaters/PollingStoptimeUpdaterConfig.java
  src/main/java/org/opentripplanner/updater/TimetableSnapshotSourceParameters.java
  src/main/java/org/opentripplanner/updater/UpdatersParameters.java
  src/main/java/org/opentripplanner/updater/alerts/GtfsRealtimeAlertsUpdater.java
  src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
  src/main/java/org/opentripplanner/updater/stoptime/MqttGtfsRealtimeUpdater.java
  src/main/java/org/opentripplanner/updater/stoptime/MqttGtfsRealtimeUpdaterParameters.java
  src/main/java/org/opentripplanner/updater/stoptime/PollingTripUpdater.java
  src/main/java/org/opentripplanner/updater/stoptime/PollingTripUpdaterParameters.java
  src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
  src/main/java/org/opentripplanner/updater/stoptime/TripUpdateGraphWriterRunnable.java
  src/main/java/org/opentripplanner/updater/stoptime/UpdateResult.java
  src/main/java/org/opentripplanner/updater/stoptime/UrlUpdaterParameters.java
  src/main/java/org/opentripplanner/updater/stoptime/WebsocketGtfsRealtimeUpdater.java
  src/main/java/org/opentripplanner/updater/stoptime/WebsocketGtfsRealtimeUpdaterParameters.java
  src/main/java/org/opentripplanner/updater/stoptime/metrics/BatchTripUpdateMetrics.java
  src/main/java/org/opentripplanner/updater/stoptime/metrics/StreamingTripUpdateMetrics.java
  src/main/java/org/opentripplanner/updater/stoptime/metrics/TripUpdateMetrics.java
  src/test/java/org/opentripplanner/model/TimetableSnapshotTest.java
Labels: new feature, Entur test, RealTimeUpdate

#4495 Enable fuzzyTripMatching in other SIRI-ET updaters
  src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java
  src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdaterParameters.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdaterParameters.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/AbstractAzureSiriUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  src/main/java/org/opentripplanner/standalone/config/updaters/SiriETGooglePubsubUpdaterConfig.java
  src/main/java/org/opentripplanner/standalone/config/updaters/SiriETUpdaterConfig.java
Labels: technical debt, Entur test, RealTimeUpdate, config change

#4508 Add support for importing zip datasets containing large entries
  src/main/java/org/opentripplanner/datastore/base/ZipStreamDataSourceDecorator.java
  src/main/java/org/opentripplanner/datastore/file/AbstractFileDataSource.java
  src/main/java/org/opentripplanner/datastore/file/TemporaryFileDataSource.java
  src/test/java/org/opentripplanner/datastore/base/ZipStreamDataSourceDecoratorTest.java
Labels: improvement

#4504 Use omitCanceled argument for stop times queries
  docs/sandbox/LegacyGraphQLApi.md
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/main/java/org/opentripplanner/index/IndexAPI.java
  src/main/java/org/opentripplanner/routing/graphfinder/PatternAtStop.java
  src/main/java/org/opentripplanner/routing/stoptimes/StopTimesHelper.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/TransitService.java
  src/test/java/org/opentripplanner/routing/stoptimes/StopTimesHelperTest.java
Labels: sandbox, skip changelog

#4512 Add feature toggle for turning off the debug client
  docs/Configuration.md
  src/main/java/org/opentripplanner/standalone/server/GrizzlyServer.java
  src/main/java/org/opentripplanner/util/OTPFeature.java
Labels: new feature

#4506 Add built-in GraphQL client
  docs/sandbox/LegacyGraphQLApi.md
  src/client/legacygraphql/graphiql/index.html
Labels: skip changelog

#4509 Add fare service for combining interlined legs
  docs/BuildConfiguration.md
  docs/sandbox/Fares.md
  src/ext-test/java/org/opentripplanner/ext/fares/FaresConfigurationTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/CombinedInterlinedLegsFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/FareModelForTest.java
  src/ext/java/org/opentripplanner/ext/fares/FaresConfiguration.java
  src/ext/java/org/opentripplanner/ext/fares/impl/AtlantaFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/CombineInterlinedLegsFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/CombinedInterlinedLegsFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/CombinedInterlinedTransitLeg.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/GtfsFaresService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/HSLFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/SFBayFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/main/java/org/opentripplanner/util/lang/ListUtils.java
  src/test/java/org/opentripplanner/standalone/config/BuildConfigTest.java
  src/test/java/org/opentripplanner/util/lang/ListUtilsTest.java
Labels: bug, sandbox, IBI, skip changelog

#4450 Translations trips stoptimes
  src/ext/java/org/opentripplanner/ext/flex/FlexibleTransitLeg.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPatternImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStoptimeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/java/org/opentripplanner/ext/reportapi/model/TransfersReport.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/api/mapping/LegMapper.java
  src/main/java/org/opentripplanner/api/mapping/TripMapper.java
  src/main/java/org/opentripplanner/api/mapping/TripTimeMapper.java
  src/main/java/org/opentripplanner/graph_builder/module/TripPatternNamer.java
  src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/StopTimeMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/TripMapper.java
  src/main/java/org/opentripplanner/model/StopTime.java
  src/main/java/org/opentripplanner/model/TripTimeOnDate.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
  src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripMapper.java
  src/main/java/org/opentripplanner/transit/model/basic/I18NString.java
  src/main/java/org/opentripplanner/transit/model/network/TripPattern.java
  src/main/java/org/opentripplanner/transit/model/timetable/Trip.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripBuilder.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripTimes.java
  src/test/java/org/opentripplanner/gtfs/mapping/FrequencyMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/StopTimesMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/TransferMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java
  src/test/java/org/opentripplanner/netex/NetexBundleSmokeTest.java
  src/test/java/org/opentripplanner/netex/mapping/StopTimesMapperTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TestRouteData.java
  src/test/java/org/opentripplanner/transit/model/timetable/TripTest.java
Labels: new feature, GTFS, bump serialization id, skip changelog

#4518 Generate Config doc - OSM - Part 2
  src/ext/java/org/opentripplanner/ext/reportapi/model/BicycleSafetyReport.java
  src/ext/java/org/opentripplanner/ext/reportapi/resource/ReportResource.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilderDataSources.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/parameters/OsmDefaultParameters.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/parameters/OsmExtractParameters.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/parameters/OsmExtractParametersBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/parameters/OsmExtractParametersList.java
  src/main/java/org/opentripplanner/openstreetmap/OpenStreetMapProvider.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
  src/main/java/org/opentripplanner/standalone/config/feed/OsmConfig.java
  src/main/java/org/opentripplanner/standalone/config/feed/OsmDefaultsConfig.java
  src/main/java/org/opentripplanner/standalone/config/feed/OsmExtractConfigBuilder.java
  src/main/java/org/opentripplanner/standalone/config/feed/OsmExtractsConfig.java
  src/main/java/org/opentripplanner/standalone/config/framework/json/ParameterBuilder.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TriangleInequalityTest.java
  src/test/java/org/opentripplanner/standalone/config/BuildConfigTest.java
  src/test/java/org/opentripplanner/standalone/config/RouterConfigTest.java
  src/test/resources/standalone/config/build-config.json
  src/test/resources/standalone/config/router-config.json
Labels: documentation, technical debt, bump serialization id, skip changelog, config change

#4516 Add separate vector tile layers for free-floating vehicles and rental stations
  docs/sandbox/MapboxVectorTilesApi.md
  src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/mapper/VehicleRentalLayerTest.java
  src/ext/java/org/opentripplanner/ext/vectortiles/VectorTilesResource.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/VehicleRentalLayerBuilder.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/VehicleRentalPlacesLayerBuilder.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/VehicleRentalStationsLayerBuilder.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/VehicleRentalVehiclesLayerBuilder.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/mapper/DigitransitRentalVehiclePropertyMapper.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/mapper/DigitransitVehicleRentalPropertyMapper.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/mapper/DigitransitVehicleRentalStationPropertyMapper.java
  src/main/java/org/opentripplanner/routing/vehicle_rental/VehicleRentalStation.java
  src/main/java/org/opentripplanner/routing/vehicle_rental/VehicleRentalStationService.java
  src/main/java/org/opentripplanner/util/lang/SetUtils.java
  src/test/java/org/opentripplanner/standalone/config/RouterConfigTest.java
  src/test/java/org/opentripplanner/util/lang/SetUtilsTest.java
  src/test/resources/standalone/config/router-config.json
Labels: sandbox, IBI, skip changelog

#4515 Specificity support for no-thru traffic restrictions
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetSource.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetSourceTest.java
  src/test/java/org/opentripplanner/openstreetmap/model/OSMWithTagsTest.java
Labels: bug, skip changelog

#4525 Remove unnecessary sourceType attribute from GTFS-RT configuration
  docs/RouterConfiguration.md
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriVMUpdater.java
  src/main/java/org/opentripplanner/standalone/config/updaters/PollingStoptimeUpdaterConfig.java
  src/main/java/org/opentripplanner/standalone/config/updaters/VehiclePositionsUpdaterConfig.java
  src/main/java/org/opentripplanner/updater/DataSourceType.java
  src/main/java/org/opentripplanner/updater/trip/PollingTripUpdater.java
  src/main/java/org/opentripplanner/updater/trip/PollingTripUpdaterParameters.java
  src/main/java/org/opentripplanner/updater/vehicle_position/PollingVehiclePositionUpdater.java
  src/test/resources/standalone/config/router-config.json
Labels: RealTimeUpdate, config change

#4526 Do not yet allow passthrough traffic by foot/bike=yes tags in Finland
  src/main/java/org/opentripplanner/graph_builder/module/osm/FinlandWayPropertySetSource.java
Labels: skip changelog

#4519 Generate Config doc - Elevation - Part 3
  src/main/java/org/opentripplanner/graph_builder/GraphBuilderDataSources.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/parameter/DemExtractParameters.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/parameter/DemExtractParametersBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/parameter/DemExtractParametersList.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/main/java/org/opentripplanner/standalone/config/feed/DemConfig.java
  src/main/java/org/opentripplanner/standalone/config/feed/DemExtractConfigBuilder.java
  src/main/java/org/opentripplanner/standalone/config/feed/DemExtractsConfig.java
  src/test/resources/standalone/config/build-config.json
Labels: documentation, technical debt, bump serialization id, skip changelog, config change

#4532 Move all speed test data onto speed test server
  .github/workflows/performance-test.yml
  test/performance/README.md
  test/performance/baden-wuerttemberg/build-config.json
  test/performance/germany/build-config.json
  test/performance/norway/build-config.json
Labels: skip changelog

#4533 Rename and move WayPropertySetSources
  docs/Troubleshooting-Routing.md
  src/ext/java/org/opentripplanner/ext/reportapi/model/BicycleSafetyReport.java
  src/ext/java/org/opentripplanner/ext/reportapi/resource/ReportResource.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/LocalizedStringMapper.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/NoteProperties.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySet.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/parameters/OsmDefaultParameters.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/parameters/OsmExtractParameters.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/parameters/OsmExtractParametersBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/specifier/ExactMatchSpecifier.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/tagmapping/AtlantaMapper.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/tagmapping/DefaultMapper.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/tagmapping/FinlandMapper.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/tagmapping/GermanyMapper.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/tagmapping/HoustonMapper.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/tagmapping/NorwayMapper.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/tagmapping/OsmTagMapper.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/tagmapping/UKMapper.java
  src/main/java/org/opentripplanner/openstreetmap/OpenStreetMapProvider.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMProvider.java
  src/main/java/org/opentripplanner/standalone/config/feed/OsmConfig.java
  src/main/java/org/opentripplanner/transit/model/basic/LocalizedString.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/graph_builder/module/FakeGraph.java
  src/test/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModuleTest.java
  src/test/java/org/opentripplanner/graph_builder/module/PruneNoThruIslandsTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModuleTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OsmTagMapperTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/PlatformLinkerTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TriangleInequalityTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/UnconnectedAreasTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/UnroutableTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetSourceTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/tagmapper/AtlantaMapperTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/tagmapper/DefaultMapperTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/tagmapper/FinlandMapperTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/tagmapper/GermanyMapperTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/tagmapper/HoustonMapperTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/tagmapper/NorwayMapperTest.java
Labels: technical debt, skip changelog

#4528 Fix npe in way properties
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayProperties.java
Labels: bug, skip changelog

#4534 Do not allow boarding/alighting at GroupStops in RAPTOR
  src/main/java/org/opentripplanner/transit/model/network/StopPattern.java
  src/test/java/org/opentripplanner/transit/model/_data/TransitModelForTest.java
  src/test/java/org/opentripplanner/transit/model/network/StopPatternTest.java
Labels: bug, Entur test

#4521 Generate Config doc - VectorTile & DataOverlay - Part 5
  src/ext-test/java/org/opentripplanner/ext/vectortiles/VehicleParkingsLayerTest.java
  src/ext/java/org/opentripplanner/ext/vectortiles/VectorTilesResource.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
  src/main/java/org/opentripplanner/standalone/config/UpdatersConfig.java
  src/main/java/org/opentripplanner/standalone/config/VectorTileConfig.java
  src/main/java/org/opentripplanner/standalone/config/buildconfig/DemConfig.java
  src/main/java/org/opentripplanner/standalone/config/buildconfig/NetexConfig.java
  src/main/java/org/opentripplanner/standalone/config/buildconfig/OsmConfig.java
  src/main/java/org/opentripplanner/standalone/config/buildconfig/TransferRequestConfig.java
  src/main/java/org/opentripplanner/standalone/config/buildconfig/TransitFeedConfig.java
  src/main/java/org/opentripplanner/standalone/config/buildconfig/TransitFeeds.java
  src/main/java/org/opentripplanner/standalone/config/sandbox/DataOverlayConfigMapper.java
  src/test/java/org/opentripplanner/standalone/config/buildconfig/NetexConfigTest.java
  src/test/java/org/opentripplanner/standalone/config/framework/JsonSupport.java
  src/test/java/org/opentripplanner/standalone/config/sandbox/DataOverlayConfigMapperTest.java
  src/test/resources/standalone/config/build-config.json
  src/test/resources/standalone/config/sandbox/build-config-data-overlay.json
Labels: documentation, technical debt, skip changelog

#4487 Add mapping for LimitedUse.ISOLATED - noTransfer to Station
  docs/BuildConfiguration.md
  src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
  src/main/java/org/opentripplanner/netex/NetexBundle.java
  src/main/java/org/opentripplanner/netex/config/NetexFeedParameters.java
  src/main/java/org/opentripplanner/netex/configure/NetexConfigure.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopAndStationMapper.java
  src/main/java/org/opentripplanner/standalone/config/buildconfig/NetexConfig.java
  src/main/java/org/opentripplanner/transit/model/site/RegularStop.java
  src/main/java/org/opentripplanner/transit/model/site/Station.java
  src/main/java/org/opentripplanner/transit/model/site/StationBuilder.java
  src/main/java/org/opentripplanner/transit/model/site/StopLocation.java
  src/test/java/org/opentripplanner/graph_builder/module/DirectTransferGeneratorTest.java
  src/test/java/org/opentripplanner/netex/mapping/StopAndStationMapperTest.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
Labels: new feature, bump serialization id, skip changelog

#4511 Add ETags handling to vector tile response
  src/ext/java/org/opentripplanner/ext/vectortiles/VectorTilesResource.java
  src/main/java/org/opentripplanner/standalone/server/EtagRequestFilter.java
  src/main/java/org/opentripplanner/standalone/server/OTPWebApplication.java
  src/main/java/org/opentripplanner/standalone/server/VaryRequestFilter.java
  src/test/java/org/opentripplanner/standalone/server/EtagRequestFilterTest.java
Labels: new feature, skip changelog

#4514 Merge AbstractRaptorTransfer and its extending classes into DefaultRaptorTransfer
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/DefaultRaptorTransfer.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/RaptorTransferIndex.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/Transfer.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TransferWithDuration.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/AbstractRaptorTransfer.java
  src/main/java/org/opentripplanner/transit/raptor/util/ReversedRaptorTransfer.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTransitData.java
Labels: technical debt, skip changelog

#4543 Rename unpreferredRouteCost back to unpreferredCost
  docs/sandbox/LegacyGraphQLApi.md
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/routing/api/request/preference/TransitPreferences.java
  src/main/java/org/opentripplanner/standalone/config/routingrequest/RoutingRequestMapper.java
  src/test/java/org/opentripplanner/generate/doc/BuildConfigurationDocTest.java
Labels: Regression, skip changelog

#4540 Cleanup in A*
  src/main/java/org/opentripplanner/routing/algorithm/astar/AStar.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
Labels: optimization, technical debt, skip changelog

#4553 Increase connection timeout for HTTPS datasources
  src/main/java/org/opentripplanner/datastore/https/HttpsDataSourceRepository.java
  src/main/java/org/opentripplanner/datastore/https/HttpsFileDataSource.java
  src/main/java/org/opentripplanner/util/HttpUtils.java
Labels: bug, skip changelog

#4513 Add possibility to supply generalized cost from Heuristic
  src/main/java/org/opentripplanner/transit/raptor/configure/RaptorConfig.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/internalapi/HeuristicAtStop.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/internalapi/Heuristics.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/configure/McRangeRaptorConfig.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/heuristic/HeuristicAtStop.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/heuristic/HeuristicsProvider.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/configure/StdRangeRaptorConfig.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/heuristics/HeuristicsAdapter.java
  src/main/java/org/opentripplanner/transit/raptor/service/DebugHeuristics.java
  src/main/java/org/opentripplanner/transit/raptor/service/HeuristicSearchTask.java
Labels: improvement

#4539 Improve error codes for non-increasing trip times
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
  src/main/java/org/opentripplanner/model/Timetable.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/model/UpdateError.java
  src/main/java/org/opentripplanner/transit/model/framework/Result.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripTimes.java
  src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
  src/main/java/org/opentripplanner/updater/trip/UpdateResult.java
  src/test/java/org/opentripplanner/model/TimetableSnapshotTest.java
  src/test/java/org/opentripplanner/model/TimetableTest.java
  src/test/java/org/opentripplanner/routing/trippattern/TripTimesTest.java
  src/test/java/org/opentripplanner/transit/model/framework/ResultTest.java
Labels: RealTimeUpdate, skip changelog

#4523 Handle cancelled trips correctly in SIRI ET module
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
Labels: bug, Skanetrafiken, RealTimeUpdate, skip changelog

#4551 Read service date from ET messages
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
Labels: improvement, Skanetrafiken, RealTimeUpdate, skip changelog

#4524 Unit tests for example configurations
  docs/examples/entur/Readme.md
  docs/examples/entur/build-config.json
  docs/examples/entur/router-config.json
  docs/examples/ibi/atlanta/build-config.json
  docs/examples/ibi/atlanta/otp-config.json
  docs/examples/ibi/atlanta/router-config.json
  docs/examples/ibi/houston/build-config.json
  docs/examples/ibi/septa/router-config.json
  docs/examples/skanetrafiken/build-config.json
  docs/examples/skanetrafiken/router-config.json
  src/main/java/org/opentripplanner/standalone/config/framework/project/EnvironmentVariableReplacer.java
  src/test/java/org/opentripplanner/standalone/config/ExampleConfigTest.java
  src/test/java/org/opentripplanner/standalone/config/RouterConfigTest.java
  src/test/java/org/opentripplanner/standalone/config/framework/JsonSupport.java
  src/test/java/org/opentripplanner/test/support/FilePatternArgumentsProvider.java
  src/test/java/org/opentripplanner/test/support/FilePatternSource.java
  src/test/resources/standalone/config/invalid-config.json
  test/performance/norway/build-config.json
Labels: skip changelog

#4530 Configuration for Skånetrafiken speed tests
  .github/workflows/performance-test.yml
  test/performance/README.md
  test/performance/skanetrafiken/build-config.json
  test/performance/skanetrafiken/speed-test-config.json
  test/performance/skanetrafiken/travelSearch-expected-results.csv
  test/performance/skanetrafiken/travelSearch.csv
Labels: Skanetrafiken, skip changelog

#4529 Translations for vector tiles sandbox
  docs/sandbox/MapboxVectorTilesApi.md
  src/ext-test/java/org/opentripplanner/ext/vectortiles/StopsLayerTest.java
  src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/stops/StopsLayerTest.java
  src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/VehicleParkingGroupsLayerTest.java
  src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/VehicleParkingsLayerTest.java
  src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/mapper/VehicleRentalLayerTest.java
  src/ext/java/org/opentripplanner/ext/vectortiles/I18NStringMapper.java
  src/ext/java/org/opentripplanner/ext/vectortiles/LayerBuilderFactory.java
  src/ext/java/org/opentripplanner/ext/vectortiles/VectorTilesResource.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/stations/DigitransitStationPropertyMapper.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/stations/StationsLayerBuilder.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/DigitransitStopPropertyMapper.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/StopsLayerBuilder.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/DigitransitVehicleParkingGroupPropertyMapper.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/DigitransitVehicleParkingPropertyMapper.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/StadtnaviVehicleParkingPropertyMapper.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/VehicleParkingGroupsLayerBuilder.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/VehicleParkingsLayerBuilder.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/VehicleRentalLayerBuilder.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/VehicleRentalPlacesLayerBuilder.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/VehicleRentalStationsLayerBuilder.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/VehicleRentalVehiclesLayerBuilder.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/mapper/DigitransitRealtimeVehicleRentalStationPropertyMapper.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/mapper/DigitransitRentalVehiclePropertyMapper.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/mapper/DigitransitVehicleRentalPropertyMapper.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/mapper/DigitransitVehicleRentalStationPropertyMapper.java
  src/test/java/org/opentripplanner/transit/raptor/api/view/BoardAndAlightTimeTest.java
Labels: improvement, sandbox, skip changelog

#4542 Update GH Actions versions
  .github/workflows/cibuild.yml
  .github/workflows/close_stale_pr_and_issues.yml
  .github/workflows/performance-test.yml
  .github/workflows/post-merge.yml
Labels: technical debt, skip changelog
