Repository opentripplanner/OpenTripPlanner, pull requests merged in 2022-07, with the labels that each got.

#4245 Fix name and label for OsmBoardingLocationVertex
  src/main/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModule.java
Labels: skip changelog

#4241 Move fare calculation into sandbox module
  docs/SandboxExtension.md
  docs/sandbox/Fares.md
  mkdocs.yml
  src/ext-test/java/org/opentripplanner/ext/fares/FaresFilterTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/FaresIntegrationTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/MultipleFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
  src/ext/java/org/opentripplanner/ext/fares/FaresConfiguration.java
  src/ext/java/org/opentripplanner/ext/fares/FaresFilter.java
  src/ext/java/org/opentripplanner/ext/fares/impl/AddingMultipleFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DutchFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DutchFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/MultipleFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/NoopFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/NycFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/NycFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/Ride.java
  src/ext/java/org/opentripplanner/ext/fares/impl/RideMapper.java
  src/ext/java/org/opentripplanner/ext/fares/impl/SFBayFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/SFBayFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/SeattleFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/SeattleFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/TimeBasedVehicleRentalFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/TimeBasedVehicleRentalFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryAndBlockProcessor.java
  src/main/java/org/opentripplanner/kryo/RouterConfigSerializer.java
  src/main/java/org/opentripplanner/netex/NetexModule.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RoutingRequestToFilterChainMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/api/request/ItineraryFilterParameters.java
  src/main/java/org/opentripplanner/routing/core/Fare.java
  src/main/java/org/opentripplanner/routing/core/Money.java
  src/main/java/org/opentripplanner/routing/core/WrappedCurrency.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/graph_builder/module/GtfsModuleTest.java
Labels: bump serialization id, skip changelog

#4236 Implement fallback for flex place names
  src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  src/main/java/org/opentripplanner/graph_builder/linking/VertexLinker.java
  src/main/java/org/opentripplanner/gtfs/mapping/LocationMapper.java
  src/main/java/org/opentripplanner/model/FlexStopLocation.java
  src/main/java/org/opentripplanner/model/plan/Place.java
  src/main/java/org/opentripplanner/netex/mapping/FlexStopLocationMapper.java
  src/main/java/org/opentripplanner/routing/location/StreetLocation.java
  src/main/java/org/opentripplanner/routing/vertextype/SplitterVertex.java
  src/main/java/org/opentripplanner/routing/vertextype/TemporarySplitterVertex.java
  src/main/java/org/opentripplanner/util/LocalizedString.java
  src/main/java/org/opentripplanner/util/ResourceBundleAdaptor.java
  src/main/java/org/opentripplanner/util/ResourceBundleSingleton.java
  src/main/resources/internals.properties
  src/main/resources/internals_de.properties
  src/main/resources/internals_fi.properties
  src/main/resources/internals_fr.properties
  src/main/resources/internals_hu.properties
  src/main/resources/internals_no.properties
  src/main/resources/internals_sv.properties
  src/test/java/org/opentripplanner/graph_builder/module/linking/LinkingTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/LocationMapperTest.java
  src/test/java/org/opentripplanner/model/plan/PlaceTest.java
  src/test/java/org/opentripplanner/model/plan/RelativeDirectionTest.java
  src/test/java/org/opentripplanner/routing/edgetype/StreetEdgeSplittingTest.java
Labels: IBI, skip changelog

#4256 Remove unused files
  src/main/java/org/opentripplanner/routing/core/SpecificTransfer.java
  src/main/resources/org/opentripplanner/profile/fares/marc.csv
  src/main/resources/org/opentripplanner/profile/fares/metrorail.csv
  src/main/resources/org/opentripplanner/profile/fares/vre.csv
  src/test/java/org/opentripplanner/routing/core/TestSpecificTransfer.java
Labels: technical debt, skip changelog

#4259 Move transit alert mapping to itinerary filter chain
  src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filter/TransitAlertFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RoutingRequestToFilterChainMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectStreetRouter.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestIntermediatePlaces.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filter/TransitAlertFilterTest.java
  src/test/java/org/opentripplanner/routing/street/BarrierRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/BicycleRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/CarRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/SplitEdgeTurnRestrictionsTest.java
Labels: technical debt, skip changelog

#4243 Remove Ride class from DefaultFareService implementations
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DutchFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/NycFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/Ride.java
  src/ext/java/org/opentripplanner/ext/fares/impl/RideMapper.java
  src/ext/java/org/opentripplanner/ext/fares/impl/SFBayFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/SeattleFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/TimeBasedVehicleRentalFareService.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
Labels: sandbox, bump serialization id, skip changelog

#4258 Report better issues from shape geometry errors
  src/main/java/org/opentripplanner/graph_builder/issues/MissingShapeGeometry.java
  src/main/java/org/opentripplanner/graph_builder/issues/ShapeGeometryTooFar.java
  src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryAndBlockProcessor.java
Labels: bug, GTFS, skip changelog

#4260 Use full seconds for A-star state
  src/main/java/org/opentripplanner/routing/core/State.java
  src/main/java/org/opentripplanner/routing/core/StateEditor.java
  src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
Labels: technical debt

#4261 Read in NeTEx geometries directly
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryAndBlockProcessor.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java
  src/main/java/org/opentripplanner/model/TripPattern.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceImpl.java
  src/main/java/org/opentripplanner/netex/NetexBundle.java
  src/main/java/org/opentripplanner/netex/NetexModule.java
  src/main/java/org/opentripplanner/netex/configure/NetexConfig.java
  src/main/java/org/opentripplanner/netex/loader/parser/ServiceCalendarFrameParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/ServiceFrameParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/TimeTableFrameParser.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/ServiceLinkMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
  src/main/java/org/opentripplanner/transit/model/timetable/Trip.java
  src/test/java/org/opentripplanner/model/impl/OtpTransitServiceBuilderLimitPeriodTest.java
  src/test/java/org/opentripplanner/netex/mapping/ServiceLinkMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/TripMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/TripPatternMapperTest.java
Labels: optimization, technical debt, NeTEx

#4265 Encapsulate access to TransitModel/StopModel properties
  src/ext-test/java/org/opentripplanner/ext/flex/FlexTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/UnscheduledTripTest.java
  src/ext-test/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandlerTest.java
  src/ext/java/org/opentripplanner/ext/actuator/ActuatorAPI.java
  src/ext/java/org/opentripplanner/ext/flex/FlexIndex.java
  src/ext/java/org/opentripplanner/ext/flex/FlexLocationsToStreetEdgesMapper.java
  src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessTemplate.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexEgressTemplate.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/reportapi/resource/ReportResource.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTripPatternCache.java
  src/ext/java/org/opentripplanner/ext/transferanalyzer/DirectTransferAnalyzer.java
  src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeResource.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/stations/DigitransitStationPropertyMapper.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/DigitransitStopPropertyMapper.java
  src/main/java/org/opentripplanner/api/resource/UpdaterStatusResource.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/GraphStats.java
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/graph_builder/module/map/BusRouteStreetMatcher.java
  src/main/java/org/opentripplanner/index/IndexAPI.java
  src/main/java/org/opentripplanner/netex/NetexModule.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransfersMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerMapper.java
  src/main/java/org/opentripplanner/routing/impl/DelegatingTransitAlertServiceImpl.java
  src/main/java/org/opentripplanner/routing/impl/TransitAlertServiceImpl.java
  src/main/java/org/opentripplanner/standalone/server/MetricsLogging.java
  src/main/java/org/opentripplanner/standalone/server/Router.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/StopModel.java
  src/main/java/org/opentripplanner/transit/service/StopModelIndex.java
  src/main/java/org/opentripplanner/transit/service/TransitModel.java
  src/main/java/org/opentripplanner/transit/service/TransitModelIndex.java
  src/main/java/org/opentripplanner/transit/service/TransitService.java
  src/main/java/org/opentripplanner/updater/GraphUpdaterConfigurator.java
  src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
  src/main/java/org/opentripplanner/updater/vehicle_positions/PollingVehiclePositionUpdater.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/graph_builder/module/DirectTransferGeneratorTest.java
  src/test/java/org/opentripplanner/graph_builder/module/GtfsModuleTest.java
  src/test/java/org/opentripplanner/model/TimetableSnapshotTest.java
  src/test/java/org/opentripplanner/model/TimetableTest.java
  src/test/java/org/opentripplanner/routing/TestHalfEdges.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
  src/test/java/org/opentripplanner/routing/edgetype/loader/GeometryAndBlockProcessorTest.java
  src/test/java/org/opentripplanner/routing/graph/RoutingServiceTest.java
  src/test/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSourceTest.java
Labels: skip changelog

#4269 Configure idempotent upload to Google Cloud Storage
  src/ext/java/org/opentripplanner/ext/datastore/gs/GsFileDataSource.java
  src/ext/java/org/opentripplanner/ext/datastore/gs/GsOutFileDataSource.java
Labels: sandbox

#4264 Re-add block-based interlining
  src/main/java/org/opentripplanner/graph_builder/DataImportIssueStore.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/model/GtfsBundle.java
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/graph_builder/module/geometry/BlockIdAndServiceId.java
  src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryProcessor.java
  src/main/java/org/opentripplanner/graph_builder/module/interlining/InterlineProcessor.java
  src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/StaySeatedNotAllowed.java
  src/main/java/org/opentripplanner/gtfs/mapping/TransferMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/TransferMappingResult.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
  src/main/java/org/opentripplanner/model/plan/ItinerariesCalculateLegTotals.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/GtfsTest.java
  src/test/java/org/opentripplanner/graph_builder/module/geometry/GeometryProcessorTest.java
  src/test/java/org/opentripplanner/graph_builder/module/interlining/InterlineProcessorTest.java
  src/test/java/org/opentripplanner/gtfs/integration/InterliningTest.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphPathTest.java
  src/test/java/org/opentripplanner/routing/edgetype/PatternInterlineDwellTest.java
  src/test/java/org/opentripplanner/routing/edgetype/loader/GeometryProcessorTest.java
  src/test/java/org/opentripplanner/routing/edgetype/loader/HopFactoryTest.java
  src/test/java/org/opentripplanner/transit/model/_data/TransitModelForTest.java
  src/test/java/org/opentripplanner/updater/vehicle_positions/VehiclePositionsMatcherTest.java
  src/test/resources/gtfs/interlining/routes.txt
  src/test/resources/gtfs/interlining/stop_times.txt
  src/test/resources/gtfs/interlining/stops.txt
  src/test/resources/gtfs/interlining/transfers.txt
  src/test/resources/gtfs/interlining/trips.txt
Labels: GTFS, Regression, IBI

#4242 Add mapping layer between REST API and internal fare model
  src/main/java/org/opentripplanner/api/mapping/FareMapper.java
  src/main/java/org/opentripplanner/api/mapping/ItineraryMapper.java
  src/main/java/org/opentripplanner/api/model/ApiCurrency.java
  src/main/java/org/opentripplanner/api/model/ApiFare.java
  src/main/java/org/opentripplanner/api/model/ApiFareComponent.java
  src/main/java/org/opentripplanner/api/model/ApiFareType.java
  src/main/java/org/opentripplanner/api/model/ApiItinerary.java
  src/main/java/org/opentripplanner/api/model/ApiMoney.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/ElevationSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
Labels: skip changelog

#4267 Add Houston fare calculator
  docs/BuildConfiguration.md
  docs/sandbox/Fares.md
  src/ext-test/java/org/opentripplanner/ext/fares/FaresConfigurationTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/FaresConfiguration.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceFactory.java
  src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
  src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
  src/test/java/org/opentripplanner/standalone/config/BuildConfigTest.java
Labels: sandbox, IBI, bump serialization id, skip changelog

#4270 Change log level of a debug log line
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
Labels: skip changelog

#4213 Add debug layer just for pathways
  src/client/js/otp/config.js
  src/client/js/otp/core/Map.js
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/gtfs/mapping/PathwayMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/PathwayModeMapper.java
  src/main/java/org/opentripplanner/inspector/PathwayEdgeRenderer.java
  src/main/java/org/opentripplanner/inspector/TileRendererManager.java
  src/main/java/org/opentripplanner/model/Pathway.java
  src/main/java/org/opentripplanner/model/PathwayMode.java
  src/main/java/org/opentripplanner/routing/edgetype/PathwayEdge.java
  src/test/java/org/opentripplanner/gtfs/mapping/PathwayMapperTest.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
  src/test/java/org/opentripplanner/routing/edgetype/PathwayEdgeTest.java
Labels: OTP Debug UI, skip changelog, WhereIsMyTransport

#4276 Fix param names in docs
  docs/OTP2-MigrationGuide.md
Labels: documentation, skip changelog

#4279 Vehicle rental network whitelisting and banning for legacy API
  docs/sandbox/LegacyGraphQLApi.md
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
Labels: sandbox, skip changelog

#4277 Make Money a record
  src/ext-test/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/MultipleFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/impl/AddingMultipleFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DutchFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLfareComponentImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLfareImpl.java
  src/main/java/org/opentripplanner/api/mapping/FareMapper.java
  src/main/java/org/opentripplanner/routing/core/Fare.java
  src/main/java/org/opentripplanner/routing/core/Money.java
Labels: technical debt, bump serialization id, skip changelog

#4228 Vehicle parking opening hours part 1
  pom.xml
  src/ext-test/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkUpdaterTest.java
  src/ext-test/java/org/opentripplanner/ext/vehicleparking/parkapi/ParkAPIUpdaterTest.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkToVehicleParkingMapper.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkUpdater.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/parkapi/BicycleParkAPIUpdater.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/parkapi/CarParkAPIUpdater.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/parkapi/ParkAPIUpdater.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/model/calendar/openinghours/OHCalendar.java
  src/main/java/org/opentripplanner/model/calendar/openinghours/OHCalendarBuilder.java
  src/main/java/org/opentripplanner/model/calendar/openinghours/OHSearchContext.java
  src/main/java/org/opentripplanner/model/calendar/openinghours/OpeningHours.java
  src/main/java/org/opentripplanner/model/calendar/openinghours/OpeningHoursCalendarService.java
  src/main/java/org/opentripplanner/openstreetmap/OSMOpeningHoursParser.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/routing/trippattern/Deduplicator.java
  src/main/java/org/opentripplanner/routing/vehicle_parking/VehicleParking.java
  src/main/java/org/opentripplanner/updater/GraphUpdaterConfigurator.java
  src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingDataSourceFactory.java
  src/main/java/org/opentripplanner/util/time/TimeUtils.java
  src/test/java/org/opentripplanner/model/calendar/openinghours/OHCalendarTest.java
  src/test/java/org/opentripplanner/openstreetmap/OSMOpeningHoursParserTest.java
  src/test/java/org/opentripplanner/routing/trippattern/DeduplicatorTest.java
Labels: new feature, bump serialization id, skip changelog

#4288 Update Jackson to 2.13.3, fix security vulnerability
  pom.xml
Labels: technical debt, skip changelog

#4287 refactor: Cleanup TransitModel
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/model/calendar/CalendarServiceData.java
  src/main/java/org/opentripplanner/netex/NetexModule.java
  src/main/java/org/opentripplanner/transit/service/TransitModel.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/routing/TestHalfEdges.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphPathTest.java
  src/test/java/org/opentripplanner/routing/edgetype/loader/GeometryProcessorTest.java
  src/test/java/org/opentripplanner/routing/edgetype/loader/HopFactoryTest.java
Labels: technical debt, skip changelog

#4290 Use correct context for type resolution
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLplaceAtDistanceImpl.java
Labels: bug, sandbox, skip changelog

#4292 Fix npe when no services for a date
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
Labels: bug, skip changelog

#4286 Remove usage of gtfsCode from internal enum values
  src/ext/java/org/opentripplanner/ext/flex/FlexTripsMapper.java
  src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLAlertImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPatternImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLRouteImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStoptimeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTripPatternIdGenerator.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/JourneyPatternType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/ServiceJourneyType.java
  src/main/java/org/opentripplanner/api/mapping/DirectionMapper.java
  src/main/java/org/opentripplanner/api/mapping/TripMapper.java
  src/main/java/org/opentripplanner/api/mapping/WheelchairAccessibilityMapper.java
  src/main/java/org/opentripplanner/gtfs/GenerateTripPatternsOperation.java
  src/main/java/org/opentripplanner/gtfs/mapping/DirectionMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/PickDropMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/StopMappingWrapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/StopTimeMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/TripMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/WheelchairAccessibilityMapper.java
  src/main/java/org/opentripplanner/index/IndexAPI.java
  src/main/java/org/opentripplanner/model/PickDrop.java
  src/main/java/org/opentripplanner/model/StopPattern.java
  src/main/java/org/opentripplanner/model/StopTime.java
  src/main/java/org/opentripplanner/routing/alertpatch/EntitySelector.java
  src/main/java/org/opentripplanner/routing/impl/DelegatingTransitAlertServiceImpl.java
  src/main/java/org/opentripplanner/routing/impl/TransitAlertServiceImpl.java
  src/main/java/org/opentripplanner/routing/services/TransitAlertService.java
  src/main/java/org/opentripplanner/transit/model/basic/WheelchairAccessibility.java
  src/main/java/org/opentripplanner/transit/model/timetable/Direction.java
  src/main/java/org/opentripplanner/transit/model/timetable/Trip.java
  src/main/java/org/opentripplanner/updater/GtfsRealtimeFuzzyTripMatcher.java
  src/main/java/org/opentripplanner/updater/alerts/AlertsUpdateHandler.java
  src/main/java/org/opentripplanner/updater/stoptime/TripPatternCache.java
  src/test/java/org/opentripplanner/gtfs/mapping/BoardingAreaMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/FrequencyMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/StopTimesMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/TransferMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java
  src/test/java/org/opentripplanner/model/impl/OtpTransitServiceBuilderLimitPeriodTest.java
Labels: technical debt, skip changelog

#4296 Filter out parks with no bike/car spaces for legacy type
  docs/sandbox/LegacyGraphQLApi.md
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPlaceImpl.java
Labels: improvement, sandbox, skip changelog

#4289 Introduce a dependency injection framework - Dagger2
  pom.xml
  src/ext/java/org/opentripplanner/ext/datastore/gs/AbstractGsDataSource.java
  src/ext/java/org/opentripplanner/ext/datastore/gs/GsDataSourceModule.java
  src/ext/java/org/opentripplanner/ext/datastore/gs/GsDataSourceRepository.java
  src/ext/java/org/opentripplanner/ext/datastore/gs/GsDirectoryDataSource.java
  src/ext/java/org/opentripplanner/ext/datastore/gs/GsFileDataSource.java
  src/ext/java/org/opentripplanner/ext/datastore/gs/GsOutFileDataSource.java
  src/main/java/org/opentripplanner/datastore/OtpDataStore.java
  src/main/java/org/opentripplanner/datastore/api/CompositeDataSource.java
  src/main/java/org/opentripplanner/datastore/api/DataSource.java
  src/main/java/org/opentripplanner/datastore/api/FileType.java
  src/main/java/org/opentripplanner/datastore/api/GoogleStorageDSRepository.java
  src/main/java/org/opentripplanner/datastore/api/OtpDataStoreConfig.java
  src/main/java/org/opentripplanner/datastore/base/ByteArrayDataSource.java
  src/main/java/org/opentripplanner/datastore/base/DataSourceRepository.java
  src/main/java/org/opentripplanner/datastore/base/LocalDataSourceRepository.java
  src/main/java/org/opentripplanner/datastore/base/ZipStreamDataSourceDecorator.java
  src/main/java/org/opentripplanner/datastore/configure/DataStoreModule.java
  src/main/java/org/opentripplanner/datastore/file/AbstractFileDataSource.java
  src/main/java/org/opentripplanner/datastore/file/DirectoryDataSource.java
  src/main/java/org/opentripplanner/datastore/file/FileDataSource.java
  src/main/java/org/opentripplanner/datastore/file/FileDataSourceRepository.java
  src/main/java/org/opentripplanner/datastore/file/ZipFileDataSource.java
  src/main/java/org/opentripplanner/datastore/file/ZipFileEntryDataSource.java
  src/main/java/org/opentripplanner/graph_builder/DataImportIssuesToHTML.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilderDataSources.java
  src/main/java/org/opentripplanner/graph_builder/model/GtfsBundle.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/GeotiffGridCoverageFactoryImpl.java
  src/main/java/org/opentripplanner/netex/NetexBundle.java
  src/main/java/org/opentripplanner/netex/configure/NetexConfig.java
  src/main/java/org/opentripplanner/netex/loader/GroupEntries.java
  src/main/java/org/opentripplanner/netex/loader/NetexDataSourceHierarchy.java
  src/main/java/org/opentripplanner/openstreetmap/OpenStreetMapProvider.java
  src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
  src/main/java/org/opentripplanner/standalone/OTPMain.java
  src/main/java/org/opentripplanner/standalone/OtpStartupInfo.java
  src/main/java/org/opentripplanner/standalone/config/ConfigModel.java
  src/main/java/org/opentripplanner/standalone/config/ConfigModule.java
  src/main/java/org/opentripplanner/standalone/config/OtpBaseDirectory.java
  src/main/java/org/opentripplanner/standalone/config/StorageConfig.java
  src/main/java/org/opentripplanner/standalone/config/package.md
  src/main/java/org/opentripplanner/standalone/configure/OTPAppConstruction.java
  src/main/java/org/opentripplanner/standalone/configure/OTPApplicationFactory.java
  src/main/java/org/opentripplanner/standalone/configure/OTPConfiguration.java
  src/main/java/org/opentripplanner/standalone/configure/OtpDataStoreConfigAdapter.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/datastore/OtpDataStoreTest.java
  src/test/java/org/opentripplanner/datastore/base/ByteArrayDataSourceTest.java
  src/test/java/org/opentripplanner/datastore/base/ZipStreamDataSourceDecoratorTest.java
  src/test/java/org/opentripplanner/datastore/file/DirectoryDataSourceTest.java
  src/test/java/org/opentripplanner/datastore/file/FileDataSourceTest.java
  src/test/java/org/opentripplanner/datastore/file/ZipFileDataSourceTest.java
  src/test/java/org/opentripplanner/ext/datastore/gs/GsDataSourceRepositoryTest.java
  src/test/java/org/opentripplanner/ext/datastore/gs/GsIntegrationTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TriangleInequalityTest.java
  src/test/java/org/opentripplanner/routing/graph/GraphSerializationTest.java
  src/test/java/org/opentripplanner/util/OTPFeatureTest.java
Labels: technical debt, bump serialization id, skip changelog

#4297 Make it explicit when an itinerary's deletion flags are removed
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filter/RemoveDeletionFlagForLeastTransfersItinerary.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filter/GroupByFilterTest.java
Labels: technical debt, skip changelog

#4300 Upgrade Geotools, cleanup pom
  pom.xml
Labels: technical debt, skip changelog

#4305 Fix RAPTOR metrics reporting
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RaptorRequestMapper.java
Labels: bug, skip changelog

#4303 Allow turning off block-based interlining
  docs/BuildConfiguration.md
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
Labels: GTFS, IBI, skip changelog

#4306 Otp2 make otp server context req scoped
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLAPI.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraph.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeResource.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/index/IndexAPI.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectStreetRouter.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
  src/main/java/org/opentripplanner/standalone/OTPMain.java
  src/main/java/org/opentripplanner/standalone/api/HttpRequestScoped.java
  src/main/java/org/opentripplanner/standalone/api/OtpServerContext.java
  src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
  src/main/java/org/opentripplanner/standalone/configure/OTPAppConstruction.java
  src/main/java/org/opentripplanner/standalone/configure/OTPApplicationFactory.java
  src/main/java/org/opentripplanner/standalone/server/DefaultServerContext.java
  src/main/java/org/opentripplanner/standalone/server/MetricsLogging.java
  src/main/java/org/opentripplanner/standalone/server/OTPWebApplication.java
  src/main/java/org/opentripplanner/standalone/server/Router.java
  src/main/java/org/opentripplanner/util/time/DurationUtils.java
  src/test/java/org/opentripplanner/TestServerContext.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/SnapshotTestBase.java
  src/test/java/org/opentripplanner/routing/street/BarrierRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/BicycleRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/CarRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/SplitEdgeTurnRestrictionsTest.java
  src/test/java/org/opentripplanner/standalone/config/RouterConfigTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
Labels: technical debt, skip changelog

#4304 Move StopIndexForRaptor implementation to StopModelIndex
  src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessEgressTemplate.java
  src/ext/java/org/opentripplanner/ext/geocoder/LuceneIndex.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/PlaceAtDistanceType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
  src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeResource.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/StopsLayerBuilder.java
  src/main/java/org/opentripplanner/api/mapping/StopMapper.java
  src/main/java/org/opentripplanner/graph_builder/linking/FlexLocationAdder.java
  src/main/java/org/opentripplanner/graph_builder/module/StreetLinkerModule.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/FlexAccessEgressAdapter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/StopIndexForRaptor.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TransitLayer.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/TransferIndexGenerator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/TransferPointForPatternFactory.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/AccessEgressMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransfersMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TripPatternMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitData.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/StopModel.java
  src/main/java/org/opentripplanner/transit/service/StopModelIndex.java
  src/main/java/org/opentripplanner/transit/service/TransitModel.java
  src/main/java/org/opentripplanner/transit/service/TransitModelIndex.java
  src/main/java/org/opentripplanner/transit/service/TransitService.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/ConstrainedBoardingSearchTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerMapperTest.java
  src/test/java/org/opentripplanner/routing/graph/RoutingServiceTest.java
  src/test/java/org/opentripplanner/transit/service/StopIndexMock.java
Labels: technical debt, skip changelog

#4311 Migrate FlexStopLocation and FlexLocationGroup entities to new transit model
  src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
  src/ext/java/org/opentripplanner/ext/flex/FlexIndex.java
  src/ext/java/org/opentripplanner/ext/flex/FlexLocationsToStreetEdgesMapper.java
  src/ext/java/org/opentripplanner/ext/flex/trip/FlexTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/PlanPlaceType.java
  src/main/java/org/opentripplanner/graph_builder/linking/FlexLocationAdder.java
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/graph_builder/module/StreetLinkerModule.java
  src/main/java/org/opentripplanner/gtfs/mapping/LocationGroupMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/LocationMapper.java
  src/main/java/org/opentripplanner/model/OtpTransitService.java
  src/main/java/org/opentripplanner/model/StopPattern.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceImpl.java
  src/main/java/org/opentripplanner/model/plan/Place.java
  src/main/java/org/opentripplanner/netex/mapping/FlexStopLocationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
  src/main/java/org/opentripplanner/routing/vertextype/StreetVertex.java
  src/main/java/org/opentripplanner/transit/model/site/FlexLocationGroup.java
  src/main/java/org/opentripplanner/transit/model/site/FlexLocationGroupBuilder.java
  src/main/java/org/opentripplanner/transit/model/site/FlexStopLocation.java
  src/main/java/org/opentripplanner/transit/model/site/FlexStopLocationBuilder.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/StopModel.java
  src/main/java/org/opentripplanner/transit/service/StopModelIndex.java
  src/main/java/org/opentripplanner/transit/service/TransitModel.java
  src/main/java/org/opentripplanner/transit/service/TransitService.java
  src/test/java/org/opentripplanner/model/plan/PlaceTest.java
  src/test/java/org/opentripplanner/netex/mapping/FlexStopLocationMapperTest.java
  src/test/java/org/opentripplanner/transit/model/site/FlexLocationGroupTest.java
  src/test/java/org/opentripplanner/transit/model/site/FlexStopLocationTest.java
Labels: skip changelog

#4188 Include waiting time at beginning and end in TransitGeneralizedCostFilter
  docs/RouterConfiguration.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/ItineraryFiltersInputType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/api/TransitGeneralizedCostFilterParams.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/TransitGeneralizedCostFilter.java
  src/main/java/org/opentripplanner/routing/api/request/ItineraryFilterParameters.java
  src/main/java/org/opentripplanner/standalone/config/ItineraryFiltersMapper.java
  src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/TransitGeneralizedCostFilterTest.java
Labels: improvement, Entur test, WhereIsMyTransport

#4309 Add speed test data set for Baden-Württemberg
  .github/workflows/performance-test.yml
  README.md
  src/test/java/org/opentripplanner/transit/raptor/speed_test/model/timer/SpeedTestTimer.java
  test/ci-performance-test/README.md
  test/performance/README.md
  test/performance/baden-wuerttemberg/build-config.json
  test/performance/baden-wuerttemberg/speed-test-config.json
  test/performance/baden-wuerttemberg/travelSearch-expected-results.csv
  test/performance/baden-wuerttemberg/travelSearch.csv
  test/performance/norway/build-config.json
  test/performance/norway/speed-test-config.json
  test/performance/norway/travelSearch-expected-results.csv
  test/performance/norway/travelSearch.csv
Labels: optimization, skip changelog

#4316 Encapsulate TransitService
  src/ext/java/org/opentripplanner/ext/flex/FlexIndex.java
  src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
  src/ext/java/org/opentripplanner/ext/flex/FlexServiceDate.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexEgressTemplate.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLAlertImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLRouteImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
  src/ext/java/org/opentripplanner/ext/reportapi/model/TransfersReport.java
  src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/OperatorType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/LineType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/sx/PtSituationElementType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/DatedServiceJourneyQuery.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/ServiceJourneyType.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/index/IndexAPI.java
  src/main/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReference.java
  src/main/java/org/opentripplanner/routing/DatedServiceJourneyHelper.java
  src/main/java/org/opentripplanner/routing/TripTimesShortHelper.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/TransitEditorService.java
  src/main/java/org/opentripplanner/transit/service/TransitModel.java
  src/main/java/org/opentripplanner/transit/service/TransitModelIndex.java
  src/main/java/org/opentripplanner/transit/service/TransitService.java
  src/main/java/org/opentripplanner/updater/GtfsRealtimeFuzzyTripMatcher.java
  src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
  src/main/java/org/opentripplanner/util/TravelOptionsMaker.java
Labels: technical debt, skip changelog

#4310 Improve logging of GBFS parsing errors
  src/main/java/org/opentripplanner/updater/GraphUpdaterConfigurator.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdater.java
Labels: IBI, skip changelog

#4315 Take nullable transit alert dates into account
  src/main/java/org/opentripplanner/api/mapping/AlertMapper.java
  src/main/java/org/opentripplanner/routing/alertpatch/TransitAlert.java
Labels: bug, IBI, skip changelog

#4318 Use way-properties for the Portland test graph
  src/main/java/org/opentripplanner/model/StreetNote.java
  src/main/java/org/opentripplanner/routing/services/notes/MatcherAndStreetNote.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/ElevationSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/graph/GraphSerializationTest.java
Labels: bug, bump serialization id, skip changelog

#4299 Include trips with skipped stops in stopTimesForPattern query
  docs/sandbox/LegacyGraphQLApi.md
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/main/java/org/opentripplanner/model/StopPattern.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/model/TripPattern.java
Labels: improvement, sandbox, skip changelog

#4313 Remove parsing of GBFS timezones
  src/main/java/org/opentripplanner/routing/vehicle_rental/VehicleRentalStation.java
  src/main/java/org/opentripplanner/routing/vehicle_rental/VehicleRentalSystem.java
  src/main/java/org/opentripplanner/routing/vehicle_rental/VehicleRentalVehicle.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFreeVehicleStatusMapper.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsStationStatusMapper.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsSystemInformationMapper.java
Labels: IBI, skip changelog

#4314 Remove duplicate stop index from Graph
  src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/UnscheduledTripTest.java
  src/ext-test/java/org/opentripplanner/ext/vectortiles/StopsLayerTest.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/ext/java/org/opentripplanner/ext/parkAndRideApi/ParkAndRideResource.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/DigitransitStopPropertyMapper.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/StopsLayerBuilder.java
  src/main/java/org/opentripplanner/api/mapping/StopMapper.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/index/IndexAPI.java
  src/main/java/org/opentripplanner/routing/RoutingService.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/routing/graphfinder/DirectGraphFinder.java
  src/main/java/org/opentripplanner/routing/graphfinder/NearbyStop.java
  src/main/java/org/opentripplanner/routing/impl/StreetVertexIndex.java
  src/main/java/org/opentripplanner/transit/model/site/Stop.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/StopModelIndex.java
  src/main/java/org/opentripplanner/transit/service/TransitModel.java
  src/main/java/org/opentripplanner/transit/service/TransitService.java
  src/test/java/org/opentripplanner/routing/TestHalfEdges.java
  src/test/java/org/opentripplanner/routing/graph/RoutingServiceTest.java
  src/test/java/org/opentripplanner/routing/graphfinder/DirectGraphFinderTest.java
  src/test/java/org/opentripplanner/routing/graphfinder/StreetGraphFinderTest.java
Labels: technical debt, skip changelog

#4326 Convert StopCollections to TransitEntity2
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/MonoOrMultiModalStation.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/PlaceAtDistanceType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/model/GroupOfStations.java
  src/main/java/org/opentripplanner/model/MultiModalStation.java
  src/main/java/org/opentripplanner/model/OtpTransitService.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceImpl.java
  src/main/java/org/opentripplanner/netex/mapping/GroupOfStationsMapper.java
  src/main/java/org/opentripplanner/netex/mapping/MultiModalStationMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filter/TransitAlertFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/AlertToLegMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RoutingRequestToFilterChainMapper.java
  src/main/java/org/opentripplanner/transit/model/basic/I18NString.java
  src/main/java/org/opentripplanner/transit/model/site/GroupOfStations.java
  src/main/java/org/opentripplanner/transit/model/site/GroupOfStationsBuilder.java
  src/main/java/org/opentripplanner/transit/model/site/GroupOfStationsPurpose.java
  src/main/java/org/opentripplanner/transit/model/site/MultiModalStation.java
  src/main/java/org/opentripplanner/transit/model/site/MultiModalStationBuilder.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/StopModel.java
  src/main/java/org/opentripplanner/transit/service/StopModelIndex.java
  src/main/java/org/opentripplanner/transit/service/TransitService.java
  src/test/java/org/opentripplanner/netex/NetexBundleSmokeTest.java
  src/test/java/org/opentripplanner/transit/model/site/GroupOfStationsTest.java
  src/test/java/org/opentripplanner/transit/model/site/MultiModalStationTest.java
Labels: technical debt, bump serialization id, skip changelog

#4327 Convert Pathways to TransitEntity2
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/gtfs/mapping/PathwayMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/PathwayModeMapper.java
  src/main/java/org/opentripplanner/model/OtpTransitService.java
  src/main/java/org/opentripplanner/model/Pathway.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceImpl.java
  src/main/java/org/opentripplanner/routing/edgetype/PathwayEdge.java
  src/main/java/org/opentripplanner/transit/model/site/Pathway.java
  src/main/java/org/opentripplanner/transit/model/site/PathwayBuilder.java
  src/main/java/org/opentripplanner/transit/model/site/PathwayMode.java
  src/test/java/org/opentripplanner/gtfs/mapping/PathwayMapperTest.java
  src/test/java/org/opentripplanner/model/impl/OtpTransitServiceImplTest.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
  src/test/java/org/opentripplanner/routing/edgetype/PathwayEdgeTest.java
  src/test/java/org/opentripplanner/transit/model/site/PathwayTest.java
Labels: technical debt, bump serialization id, skip changelog

#4329 Convert StopTimeKey to TransitEntity2
  src/main/java/org/opentripplanner/model/StopTime.java
  src/main/java/org/opentripplanner/model/StopTimeKey.java
  src/main/java/org/opentripplanner/model/TripTimeOnDate.java
  src/main/java/org/opentripplanner/netex/mapping/NoticeAssignmentMapper.java
  src/main/java/org/opentripplanner/transit/model/timetable/StopTimeKey.java
  src/main/java/org/opentripplanner/transit/model/timetable/StopTimeKeyBuilder.java
  src/test/java/org/opentripplanner/netex/NetexBundleSmokeTest.java
  src/test/java/org/opentripplanner/transit/model/timetable/StopTimeKeyTest.java
Labels: technical debt, bump serialization id, skip changelog

#4322 Explicitly pass feedId to SiriFuzzyTripMatcher instead of guessing
  src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java
  src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
Labels: bug, sandbox, technical debt, skip changelog

#4334 Fix serialization of FlexLocationGroup and GroupOfStations
  src/main/java/org/opentripplanner/transit/model/site/FlexLocationGroupBuilder.java
  src/main/java/org/opentripplanner/transit/model/site/GroupOfStationsBuilder.java
Labels: bug, skip changelog

#4330 Convert FlexTrip to TransitEntity2
  src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/UnscheduledTripTest.java
  src/ext/java/org/opentripplanner/ext/flex/FlexIndex.java
  src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
  src/ext/java/org/opentripplanner/ext/flex/FlexTripsMapper.java
  src/ext/java/org/opentripplanner/ext/flex/trip/FlexTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/FlexTripBuilder.java
  src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTripBuilder.java
  src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTripBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/model/OtpTransitService.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceImpl.java
  src/main/java/org/opentripplanner/transit/service/TransitModel.java
Labels: technical debt, bump serialization id, skip changelog

#4336 Run Norway first in the speed test, don't run for version bumps
  .github/workflows/performance-test.yml
Labels: skip changelog

#4321 Car mode Leg splitting related fixes
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/core/State.java
  src/main/java/org/opentripplanner/routing/core/StateEditor.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/CarSnapshotTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/CarSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/core/StateEditorTest.java
  src/test/resources/portland/portland-central-filtered.osm.pbf
Labels: bug, skip changelog
