Repository opentripplanner/OpenTripPlanner, pull requests merged in 2022-08, with the labels that each got.

#4331 Convert TripOnServiceDate to TransitEntity2
  src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/DatedServiceJourneyQuery.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/DatedServiceJourneyType.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/model/TripOnServiceDate.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapperResult.java
  src/main/java/org/opentripplanner/routing/DatedServiceJourneyHelper.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripOnServiceDate.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripOnServiceDateBuilder.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/TransitModel.java
  src/main/java/org/opentripplanner/transit/service/TransitModelIndex.java
  src/main/java/org/opentripplanner/transit/service/TransitService.java
  src/test/java/org/opentripplanner/netex/mapping/TripPatternMapperTest.java
  src/test/java/org/opentripplanner/transit/model/timetable/TripOnServiceDateTest.java
Labels: technical debt, bump serialization id

#4332 Convert FareAttribute to TransitEntity2
  src/ext-test/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/model/FareAttribute.java
  src/ext/java/org/opentripplanner/ext/fares/model/FareAttributeBuilder.java
  src/main/java/org/opentripplanner/gtfs/mapping/FareAttributeMapper.java
  src/test/java/org/opentripplanner/model/calendar/impl/CalendarServiceDataFactoryImplTest.java
  src/test/java/org/opentripplanner/model/impl/OtpTransitServiceBuilderTest.java
Labels: technical debt, bump serialization id, skip changelog

#4349 Fixed NPE that occurs due to null list returned by the getTripPattern…
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TransitLayer.java
Labels: bug, skip changelog

#4319 Use java.time classes in StopTimesHelper
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLUtils.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLDepartureRowImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
  src/main/java/org/opentripplanner/index/IndexAPI.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReference.java
  src/main/java/org/opentripplanner/routing/DatedServiceJourneyHelper.java
  src/main/java/org/opentripplanner/routing/TripTimesShortHelper.java
  src/main/java/org/opentripplanner/routing/alternativelegs/AlternativeLegs.java
  src/main/java/org/opentripplanner/routing/graphfinder/PatternAtStop.java
  src/main/java/org/opentripplanner/routing/stoptimes/StopTimesHelper.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/TransitService.java
  src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
  src/main/java/org/opentripplanner/updater/vehicle_positions/PollingVehiclePositionUpdater.java
  src/test/java/org/opentripplanner/routing/stoptimes/StopTimesHelperTest.java
  src/test/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSourceTest.java
Labels: technical debt, skip changelog

#4344 Add Atlanta WayPropertySetSource
  src/main/java/org/opentripplanner/graph_builder/module/osm/AtlantaWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetSource.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/AtlantaWayPropertySetSourceTest.java
Labels: new feature, IBI, skip changelog

#4298 Allow filtering out of timeshifted itineraries with same routes and stops
  docs/RouterConfiguration.md
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/groupids/GroupByAllSameStations.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/groupids/GroupBySameRoutesAndStops.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RoutingRequestToFilterChainMapper.java
  src/main/java/org/opentripplanner/routing/api/request/ItineraryFilterParameters.java
  src/main/java/org/opentripplanner/standalone/config/ItineraryFiltersMapper.java
  src/main/java/org/opentripplanner/transit/model/site/StopLocation.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/groupids/GroupBySameRoutesAndStopsTest.java
Labels: improvement, WhereIsMyTransport

#4337 Remove unneeded usage of Guava
  src/ext/java/org/opentripplanner/ext/fares/FaresConfiguration.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessEgressTemplate.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPatternImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/AbstractAzureSiriUpdater.java
  src/main/java/org/opentripplanner/api/common/Message.java
  src/main/java/org/opentripplanner/api/model/ApiPatternDetail.java
  src/main/java/org/opentripplanner/api/parameter/QualifiedModeSet.java
  src/main/java/org/opentripplanner/api/support/SemanticHash.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/graph_builder/module/TripPatternNamer.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderFactory.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/PortlandCustomNamer.java
  src/main/java/org/opentripplanner/index/IndexAPI.java
  src/main/java/org/opentripplanner/model/Timetable.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/model/plan/WalkStep.java
  src/main/java/org/opentripplanner/openstreetmap/OpenStreetMapProvider.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/AStar.java
  src/main/java/org/opentripplanner/routing/algorithm/astar/strategies/EuclideanRemainingWeightHeuristic.java
  src/main/java/org/opentripplanner/routing/core/intersection_model/SimpleIntersectionTraversalCostModel.java
  src/main/java/org/opentripplanner/routing/graphfinder/DirectGraphFinder.java
  src/main/java/org/opentripplanner/standalone/server/OTPWebApplication.java
  src/main/java/org/opentripplanner/transit/model/framework/Deduplicator.java
  src/main/java/org/opentripplanner/transit/model/network/StopPattern.java
  src/main/java/org/opentripplanner/transit/model/network/TripPattern.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripTimes.java
  src/main/java/org/opentripplanner/transit/service/StopModelIndex.java
  src/main/java/org/opentripplanner/transit/service/TransitModel.java
  src/main/java/org/opentripplanner/transit/service/TransitModelIndex.java
  src/main/java/org/opentripplanner/updater/GraphUpdaterManager.java
  src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
  src/main/java/org/opentripplanner/updater/stoptime/TripUpdateGraphWriterRunnable.java
  src/main/java/org/opentripplanner/updater/vehicle_positions/GtfsRealtimeHttpVehiclePositionSource.java
  src/main/java/org/opentripplanner/util/lang/ToStringBuilder.java
  src/main/java/org/opentripplanner/util/resources/ResourceBundleAdaptor.java
  src/test/java/org/opentripplanner/graph_builder/module/linking/LinkingTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/UnroutableTest.java
  src/test/java/org/opentripplanner/model/impl/OtpTransitServiceBuilderLimitPeriodTest.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphPathTest.java
  src/test/java/org/opentripplanner/transit/model/TransitModelArchitectureTest.java
  src/test/java/org/opentripplanner/util/lang/ToStringBuilderTest.java
Labels: technical debt, skip changelog

#4345 Use try-with-resources for GBFS loading, improve logging
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFeedLoader.java
Labels: bug, skip changelog

#4358 Explicitly set timezones for speed test
  test/performance/baden-wuerttemberg/build-config.json
  test/performance/norway/build-config.json
Labels: bug, skip changelog

#4359 Fix init of trip pattern name
  src/main/java/org/opentripplanner/transit/model/network/TripPattern.java
  src/test/java/org/opentripplanner/transit/model/network/TripPatternTest.java
Labels: bug, skip changelog

#4361 Do not try to rename patterns with already existing names
  src/main/java/org/opentripplanner/graph_builder/module/TripPatternNamer.java
Labels: bug, skip changelog

#4342 Fix building of graphs with only FlexStopLocations
  src/main/java/org/opentripplanner/transit/service/StopModel.java
Labels: bug, IBI, skip changelog

#4352 Count stops only once in VehicleToStopHeuristics
  src/ext/java/org/opentripplanner/ext/vehicletostopheuristics/VehicleToStopSkipEdgeStrategy.java
Labels: sandbox, skip changelog

#4328 Add walk safety to way property sets and walkSafetyFactor routing parameter
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/java/org/opentripplanner/ext/reportapi/model/BicyleSafetyReport.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/DefaultRoutingRequestType.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/AtlantaWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/DefaultWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/FinlandWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/GermanyWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/NorwayWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/UKWayPropertySetSource.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayProperties.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertiesBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySet.java
  src/main/java/org/opentripplanner/inspector/TileRendererManager.java
  src/main/java/org/opentripplanner/inspector/WalkSafetyEdgeRenderer.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/Transfer.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/edgetype/NamedArea.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetElevationExtension.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/FinlandWayPropertySetSourceTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/GermanyWayPropertySetSourceTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModuleTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/UnconnectedAreasTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetSourceTest.java
  src/test/java/org/opentripplanner/routing/edgetype/StreetEdgeCostTest.java
Labels: new feature, bump serialization id

#4273 Remove unmaintained custom fare calculators for NYC, Seattle, SF Bay Area, Netherlands
  docs/sandbox/Fares.md
  src/ext-test/java/org/opentripplanner/ext/fares/impl/FaresIntegrationTest.java
  src/ext/java/org/opentripplanner/ext/fares/FaresConfiguration.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DutchFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DutchFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/SeattleFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/SeattleFareServiceImpl.java
Labels: technical debt

#4354 Merge TransitEntity to TransitEntity2
  src/ext/java/org/opentripplanner/ext/fares/model/FareAttribute.java
  src/ext/java/org/opentripplanner/ext/flex/trip/FlexTrip.java
  src/main/java/org/opentripplanner/transit/model/basic/Notice.java
  src/main/java/org/opentripplanner/transit/model/framework/AbstractEntityBuilder.java
  src/main/java/org/opentripplanner/transit/model/framework/TransitEntity.java
  src/main/java/org/opentripplanner/transit/model/framework/TransitEntity2.java
  src/main/java/org/opentripplanner/transit/model/network/GroupOfRoutes.java
  src/main/java/org/opentripplanner/transit/model/network/Route.java
  src/main/java/org/opentripplanner/transit/model/network/TripPattern.java
  src/main/java/org/opentripplanner/transit/model/organization/Agency.java
  src/main/java/org/opentripplanner/transit/model/organization/Branding.java
  src/main/java/org/opentripplanner/transit/model/organization/Operator.java
  src/main/java/org/opentripplanner/transit/model/site/FareZone.java
  src/main/java/org/opentripplanner/transit/model/site/FlexLocationGroup.java
  src/main/java/org/opentripplanner/transit/model/site/FlexStopLocation.java
  src/main/java/org/opentripplanner/transit/model/site/GroupOfStations.java
  src/main/java/org/opentripplanner/transit/model/site/MultiModalStation.java
  src/main/java/org/opentripplanner/transit/model/site/Pathway.java
  src/main/java/org/opentripplanner/transit/model/site/Station.java
  src/main/java/org/opentripplanner/transit/model/site/StationElement.java
  src/main/java/org/opentripplanner/transit/model/timetable/StopTimeKey.java
  src/main/java/org/opentripplanner/transit/model/timetable/Trip.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripOnServiceDate.java
  src/test/java/org/opentripplanner/model/impl/EntityByIdTest.java
  src/test/java/org/opentripplanner/util/lang/ToStringBuilderTest.java
Labels: technical debt, skip changelog

#4360 Otp2 guava
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/ServiceJourneyType.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  src/main/java/org/opentripplanner/graph_builder/module/interlining/InterlineProcessor.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/ItineraryDeletionFlagger.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/LatestDepartureTimeFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/MaxLimitFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/NonTransitGeneralizedCostFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/OtherThanSameLegsMaxGeneralizedCostFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/RemoveBikerentalWithMostlyWalkingFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/RemoveParkAndRideWithMostlyWalkingFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/RemoveTransitIfStreetOnlyIsBetterFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/RemoveWalkOnlyFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/TransitGeneralizedCostFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filter/DeletionFlaggingFilter.java
  src/main/java/org/opentripplanner/standalone/server/OTPWebApplication.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/DeletionFlaggerTestHelper.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/OtherThanSameLegsMaxGeneralizedCostFilterTest.java
Labels: technical debt, skip changelog

#4353 Clean up TripPattern
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPatternImpl.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTripPatternCache.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/JourneyPatternType.java
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryProcessor.java
  src/main/java/org/opentripplanner/gtfs/GenerateTripPatternsOperation.java
  src/main/java/org/opentripplanner/netex/mapping/ServiceLinkMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
  src/main/java/org/opentripplanner/routing/TripTimesShortHelper.java
  src/main/java/org/opentripplanner/routing/alternativelegs/AlternativeLegs.java
  src/main/java/org/opentripplanner/routing/stoptimes/StopTimesHelper.java
  src/main/java/org/opentripplanner/transit/model/network/StopPattern.java
  src/main/java/org/opentripplanner/transit/model/network/TripPattern.java
  src/main/java/org/opentripplanner/transit/model/network/TripPatternBuilder.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/TransitService.java
  src/main/java/org/opentripplanner/updater/GtfsRealtimeFuzzyTripMatcher.java
  src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
  src/main/java/org/opentripplanner/updater/stoptime/TripPatternCache.java
  src/test/java/org/opentripplanner/graph_builder/module/geometry/GeometryProcessorTest.java
  src/test/java/org/opentripplanner/gtfs/GtfsContextBuilder.java
  src/test/java/org/opentripplanner/model/TripPatternTest.java
  src/test/java/org/opentripplanner/netex/NetexBundleSmokeTest.java
  src/test/java/org/opentripplanner/netex/mapping/ServiceLinkMapperTest.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphPathTest.java
  src/test/java/org/opentripplanner/routing/edgetype/loader/GeometryProcessorTest.java
Labels: technical debt, bump serialization id, skip changelog

#4364 Throw RoutingValidationException if origin and destination are the same
  src/main/java/org/opentripplanner/routing/core/TemporaryVerticesContainer.java
  src/test/java/org/opentripplanner/routing/algorithm/StreetModeLinkingTest.java
Labels: bug

#4362 Take allowed modes in VehicleToStopHeuristics into account
  src/ext/java/org/opentripplanner/ext/vehicletostopheuristics/VehicleToStopSkipEdgeStrategy.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
Labels: bug, sandbox, skip changelog

#4363 Improve SIRI updaters
  src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
  src/ext/java/org/opentripplanner/ext/siri/SiriHttpUtils.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETHttpTripUpdateSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriVMHttpTripUpdateSource.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerUpdater.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripIdAndServiceDate.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripOnServiceDate.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/TransitModelIndex.java
  src/main/java/org/opentripplanner/transit/service/TransitService.java
Labels: bug, sandbox, RealTimeUpdate

#4370 Use dedicated fields for services in Graph object
  src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
  src/ext/java/org/opentripplanner/ext/geocoder/LuceneIndex.java
  src/main/java/org/opentripplanner/api/model/ApiRouterInfo.java
  src/main/java/org/opentripplanner/api/resource/BikeRental.java
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/graph_builder/module/StreetLinkerModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingUpdater.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdater.java
  src/test/java/org/opentripplanner/graph_builder/module/VehicleParkingLinkingTest.java
  src/test/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingUpdaterTest.java
Labels: technical debt, bump serialization id, skip changelog

#4367 Add Stop Location index to transit model
  src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeResource.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/FlexAccessEgressAdapter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TransitLayer.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/TransferIndexGenerator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/TransferPointForPatternFactory.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/AccessEgressMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransfersMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerUpdater.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TripPatternMapper.java
  src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
  src/main/java/org/opentripplanner/transit/model/site/FlexLocationGroup.java
  src/main/java/org/opentripplanner/transit/model/site/FlexStopLocation.java
  src/main/java/org/opentripplanner/transit/model/site/Stop.java
  src/main/java/org/opentripplanner/transit/model/site/StopLocation.java
  src/main/java/org/opentripplanner/transit/service/StopModelIndex.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/ConstrainedBoardingSearchTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TestRouteData.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TestTransitCaseData.java
  src/test/java/org/opentripplanner/transit/service/StopIndexMock.java
Labels: technical debt, bump serialization id, skip changelog

#4343 Bugfix for missing realtime problem
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerUpdater.java
Labels: bug, Entur test, skip changelog

#4340 Fix stop time repair for trips with single flex stop
  src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/UnscheduledTripTest.java
  src/main/java/org/opentripplanner/gtfs/RepairStopTimesForEachTripOperation.java
Labels: bug, IBI, skip changelog

#4365 Do not crash Transmodel API when pattern for trip is not found
  docs/sandbox/TransmodelApi.md
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/DatedServiceJourneyType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/ServiceJourneyType.java
  src/main/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReference.java
  src/main/java/org/opentripplanner/routing/TripTimesShortHelper.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/TransitService.java
Labels: bug, improvement, sandbox, Entur test, skip changelog

#4368 Encapsulate StopModelIndex
  src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeResource.java
  src/main/java/org/opentripplanner/graph_builder/linking/FlexLocationAdder.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TransitLayer.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransfersMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerMapper.java
  src/main/java/org/opentripplanner/routing/graphfinder/DirectGraphFinder.java
  src/main/java/org/opentripplanner/routing/impl/TransitAlertServiceImpl.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/StopModel.java
  src/main/java/org/opentripplanner/transit/service/StopModelIndex.java
  src/main/java/org/opentripplanner/transit/service/TransitModel.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerMapperTest.java
  src/test/java/org/opentripplanner/routing/graph/RoutingServiceTest.java
  src/test/java/org/opentripplanner/transit/service/StopModelMock.java
  src/test/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSourceTest.java
Labels: technical debt, skip changelog

#4373 Fix reading of transitGeneralizedCostLimit
  src/main/java/org/opentripplanner/standalone/config/ItineraryFiltersMapper.java
  src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
  src/test/java/org/opentripplanner/standalone/config/NodeAdapterTest.java
Labels: bug, Entur test, skip changelog

#4374 Otp2 patch ci test
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
  src/main/java/org/opentripplanner/transit/service/StopModel.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/support/AssertSpeedTestSetup.java
Labels: bug, technical debt, skip changelog

#4376 Remove unused build parameters
  docs/BuildConfiguration.md
  docs/Netex-Norway.md
  docs/examples/entur/build-config.json
  docs/examples/skanetrafiken/build-config.json
  src/main/java/org/opentripplanner/graph_builder/model/GtfsBundle.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/test/java/org/opentripplanner/standalone/config/BuildConfigTest.java
  src/test/resources/portland/build-config.json
  test/performance/norway/build-config.json
Labels: skip changelog

#4380 debug-client: display street notes
  src/client/js/otp/modules/planner/ItinerariesWidget.js
Labels: improvement, skip changelog

#4369 Create RoutingTripPattern and move constrained transfers to transit layer
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/SlackProvider.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TransitLayer.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TripPatternForDate.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TripPatternWithRaptorStopIndexes.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/ConstrainedTransfersForPatterns.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/TransferIndexGenerator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerUpdater.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TripPatternForDateMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TripPatternMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitData.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TransitDataProviderFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripPatternForDates.java
  src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
  src/main/java/org/opentripplanner/transit/model/network/Route.java
  src/main/java/org/opentripplanner/transit/model/network/RoutingTripPattern.java
  src/main/java/org/opentripplanner/transit/model/network/TripPattern.java
  src/main/java/org/opentripplanner/transit/model/network/TripPatternBuilder.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorRoute.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTransitDataProvider.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RangeRaptorWorker.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/ForwardTransitCalculator.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/ReverseTransitCalculator.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/TransitCalculator.java
  src/test/java/org/opentripplanner/OtpArchitectureModules.java
  src/test/java/org/opentripplanner/model/TripPatternTest.java
  src/test/java/org/opentripplanner/model/impl/OtpTransitServiceBuilderTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TripPatternForDateTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/ConstrainedBoardingSearchTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreatorTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TestRouteData.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripPatternWithId.java
  src/test/java/org/opentripplanner/transit/model/TransitModelArchitectureTest.java
  src/test/java/org/opentripplanner/transit/model/_data/TransitModelForTest.java
  src/test/java/org/opentripplanner/transit/model/network/TripPatternTest.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestRoute.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTransitData.java
  src/test/java/org/opentripplanner/updater/vehicle_positions/VehiclePositionsMatcherTest.java
Labels: bug, technical debt, Entur test, bump serialization id, skip changelog

#4379 Correct toString() methods for NearbyStop, TripScheduleWithOffset
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleWithOffset.java
  src/main/java/org/opentripplanner/routing/graphfinder/NearbyStop.java
Labels: bug, skip changelog

#4381 Add custom bike rental data updater (vilkku) as an extension
  src/ext-test/java/org/opentripplanner/ext/vilkkubikerental/VilkkuBikeRentalDataSourceTest.java
  src/ext-test/resources/vilkkubikerental/vilkku.xml
  src/ext/java/org/opentripplanner/ext/vilkkubikerental/VilkkuBikeRentalDataSource.java
  src/ext/java/org/opentripplanner/ext/vilkkubikerental/VilkkuBikeRentalDataSourceParameters.java
  src/main/java/org/opentripplanner/standalone/config/updaters/sources/VehicleRentalSourceFactory.java
  src/main/java/org/opentripplanner/updater/DataSourceType.java
  src/main/java/org/opentripplanner/updater/GenericXmlDataSource.java
Labels: sandbox

#4383 Fix bugs in Transmodel API
  pom.xml
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
Labels: bug, skip changelog

#4375 Cleanup dev-guide and add code conventions
  CODE_CONVENTIONS.md
  docs/DevReleaseChecklist.md
  docs/Developers-Guide.md
  src/main/java/org/opentripplanner/transit/model/framework/FeedScopedId.java
  src/main/java/org/opentripplanner/transit/model/network/GroupOfRoutes.java
  src/main/java/org/opentripplanner/transit/model/network/TripPattern.java
  src/main/java/org/opentripplanner/transit/model/organization/Agency.java
  src/main/java/org/opentripplanner/transit/model/organization/Operator.java
  src/main/java/org/opentripplanner/transit/service/TransitModel.java
  src/main/java/org/opentripplanner/util/lang/AssertUtils.java
  src/main/java/org/opentripplanner/util/lang/ObjectUtils.java
  src/main/java/org/opentripplanner/util/lang/StringUtils.java
  src/test/java/org/opentripplanner/util/lang/AssertUtilsTest.java
  src/test/java/org/opentripplanner/util/lang/ObjectUtilsTest.java
  src/test/java/org/opentripplanner/util/lang/StringUtilsTest.java
Labels: documentation, technical debt

#4386 Add missing bike rental service configuration 'vilkku' to data source factory
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/VehicleRentalDataSourceFactory.java
Labels: skip changelog

#4335 Convert itinerary seconds to Duration
  src/ext/java/org/opentripplanner/ext/fares/impl/TimeBasedVehicleRentalFareService.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLItineraryImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLLegImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripPatternType.java
  src/main/java/org/opentripplanner/api/mapping/ItineraryMapper.java
  src/main/java/org/opentripplanner/api/resource/PlannerResource.java
  src/main/java/org/opentripplanner/model/plan/ItinerariesCalculateLegTotals.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/RemoveParkAndRideWithMostlyWalkingFilter.java
  src/main/java/org/opentripplanner/util/time/TimeUtils.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestIntermediatePlaces.java
  src/test/java/org/opentripplanner/model/plan/ItineraryTest.java
  src/test/java/org/opentripplanner/model/plan/LegTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/SnapshotTestBase.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/model/testcase/CsvFileIO.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/model/testcase/ItineraryResultMapper.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/model/testcase/Result.java
Labels: technical debt, skip changelog

#4385 Improve logging
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
  src/main/java/org/opentripplanner/model/Timetable.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripTimes.java
  src/test/java/org/opentripplanner/routing/trippattern/TripTimesTest.java
Labels: technical debt, skip changelog

#4393 Otp doc update
  CODE_CONVENTIONS.md
  docs/sandbox/SiriUpdator.md
Labels: documentation, skip changelog

#4372 Skip opening hours if no time-zone configured
  src/main/java/org/opentripplanner/common/RepeatingTimePeriod.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderFactory.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/openstreetmap/OSMOpeningHoursParser.java
Labels: bug

#4388 Rename and clean up RepairStopTimesForEachTripOperation
  src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/graph_builder/module/ValidateAndInterpolateStopTimesForEachTrip.java
  src/main/java/org/opentripplanner/netex/NetexModule.java
  src/test/java/org/opentripplanner/gtfs/GtfsContextBuilder.java
Labels: improvement, technical debt, NeTEx

#4404 Digitransit stop vector layer updates
  docs/sandbox/MapboxVectorTilesApi.md
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/DigitransitStopPropertyMapper.java
Labels: improvement, sandbox

#4407 Re-enable copying of submode to trip from route
  src/main/java/org/opentripplanner/transit/model/timetable/Trip.java
  src/test/java/org/opentripplanner/transit/model/timetable/TripTest.java
Labels: Regression, NeTEx

#4387 Sort ConstrainedTransfers after mapping
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TransitLayer.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/ConstrainedTransfersForPatterns.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/TransferIndexGenerator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitData.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/ConstrainedBoardingSearchTest.java
Labels: bug, optimization, Entur test, skip changelog

#4403 Optimize RAPTOR adapter layer
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TripPatternForDate.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripPatternForDates.java
  src/main/java/org/opentripplanner/routing/impl/StreetVertexIndex.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/SystemErrDebugLogger.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/besttimes/BestTimes.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/besttimes/SimpleBestNumberOfTransfers.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/heuristics/HeuristicsAdapter.java
  src/main/java/org/opentripplanner/transit/raptor/service/DebugHeuristics.java
  src/main/java/org/opentripplanner/util/lang/IntUtils.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TestRouteData.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/ResultPrinter.java
Labels: optimization, skip changelog

#4390 Use pattern index instead of route id or agency id for unpreferred cost
  docs/RouterConfiguration.md
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeResource.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/api/DefaultTripPattern.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/api/SlackProvider.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/CostCalculatorFactory.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/DefaultTripSchedule.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/McCostParams.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/McCostParamsBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/PatternCostCalculator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/frequency/FrequencyAlightEvent.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/frequency/FrequencyBoardOrAlightEvent.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/frequency/FrequencyBoardingEvent.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/frequency/TripFrequencyAlightSearch.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/frequency/TripFrequencyBoardSearch.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/McCostParamsMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitData.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripPatternForDates.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleWithOffset.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
  src/main/java/org/opentripplanner/transit/model/network/RoutingTripPattern.java
  src/main/java/org/opentripplanner/transit/model/network/TripPatternBuilder.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTripPattern.java
  src/main/java/org/opentripplanner/transit/service/TransitService.java
  src/test/java/org/opentripplanner/OtpArchitectureModules.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/PatternCostCalculatorTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/McCostParamsMapperTest.java
  src/test/java/org/opentripplanner/standalone/config/NodeAdapterTest.java
  src/test/java/org/opentripplanner/transit/model/TransitModelArchitectureTest.java
  src/test/java/org/opentripplanner/transit/model/_data/TransitModelForTest.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestRoute.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTransitData.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTripPattern.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTripSchedule.java
  src/test/java/org/opentripplanner/transit/raptor/moduletests/F02_UnpreferredRouteTest.java
Labels: technical debt

#4398 Allow parsing of legacy leg references
  src/main/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializer.java
  src/test/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializerTest.java
Labels: bug, Entur test, skip changelog

#4409 Clean code
  src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/test/java/org/opentripplanner/util/lang/IntUtilsTest.java
Labels: skip changelog

#4402 Performance improvements for DefaultFareServiceImpl
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceImpl.java
  src/main/java/org/opentripplanner/transit/model/site/RegularStop.java
  src/main/java/org/opentripplanner/transit/model/site/StopLocation.java
Labels: sandbox, optimization

#4413 doc: Document why unused parameters in Raptor API should NOT be deleted.
  src/main/java/org/opentripplanner/transit/raptor/api/response/StopArrivals.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/internalapi/Heuristics.java
Labels: technical debt, skip changelog

#4406 Improve limits in ValidateAndInterpolateStopTimesForEachTrip
  src/main/java/org/opentripplanner/graph_builder/module/ValidateAndInterpolateStopTimesForEachTrip.java
Labels: improvement, Entur test, skip changelog

#4397 Do not crash if PageCursorFactory can't be created
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RoutingResponseMapper.java
Labels: bug, Entur test, skip changelog

#4356 Support for Route longName translations
  src/ext-test/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLUtils.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLRouteImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/api/mapping/I18NStringMapper.java
  src/main/java/org/opentripplanner/api/mapping/LegMapper.java
  src/main/java/org/opentripplanner/api/mapping/PlaceMapper.java
  src/main/java/org/opentripplanner/api/mapping/RouteMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/RouteMapper.java
  src/main/java/org/opentripplanner/netex/mapping/RouteMapper.java
  src/main/java/org/opentripplanner/transit/model/network/Route.java
  src/main/java/org/opentripplanner/transit/model/network/RouteBuilder.java
  src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
  src/test/java/org/opentripplanner/gtfs/mapping/FareRuleMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/FrequencyMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/RouteMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/StopTimesMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/TransferMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/RouteMapperTest.java
  src/test/java/org/opentripplanner/transit/model/network/RouteTest.java
Labels: improvement, GTFS, bump serialization id, skip changelog

#4412 Clean up street routing
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLstepImpl.java
  src/main/java/org/opentripplanner/api/mapping/LegMapper.java
  src/main/java/org/opentripplanner/api/mapping/WalkStepMapper.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/model/plan/StreetLeg.java
  src/main/java/org/opentripplanner/model/plan/StreetLegBuilder.java
  src/main/java/org/opentripplanner/model/plan/WalkStep.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapper.java
  src/main/java/org/opentripplanner/routing/core/StateEditor.java
  src/main/java/org/opentripplanner/routing/edgetype/AreaEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/AreaEdgeList.java
  src/main/java/org/opentripplanner/routing/edgetype/ElevatorAlightEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/ElevatorBoardEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/ElevatorHopEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/FreeEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/NamedArea.java
  src/main/java/org/opentripplanner/routing/edgetype/PathwayEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/SimpleEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetTransitEntityLink.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetVehicleParkingLink.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetVehicleRentalLink.java
  src/main/java/org/opentripplanner/routing/edgetype/TemporaryPartialStreetEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/VehicleParkingEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/VehicleRentalEdge.java
  src/main/java/org/opentripplanner/routing/graph/Edge.java
  src/main/java/org/opentripplanner/routing/spt/ShortestPathTree.java
  src/test/java/org/opentripplanner/routing/edgetype/TemporaryPartialStreetEdgeTest.java
Labels: optimization, technical debt, Entur test, skip changelog

#4416 Update heuristic profile name in performanceTimers
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/performance/PerformanceTimersForRaptor.java
  src/main/java/org/opentripplanner/transit/raptor/api/debug/RaptorTimers.java
  src/main/java/org/opentripplanner/transit/raptor/service/HeuristicSearchTask.java
Labels: Regression, Entur test, skip changelog

#4411 Otp2 fix updater config
  docs/OTP2-MigrationGuide.md
  src/ext-test/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandlerTest.java
  src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriVMUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriVMUpdaterParameters.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/AbstractAzureSiriUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java
  src/ext/java/org/opentripplanner/ext/vehiclerentalservicedirectory/VehicleRentalServiceDirectoryFetcher.java
  src/ext/java/org/opentripplanner/ext/vilkkubikerental/VilkkuBikeRentalDataSource.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/standalone/OTPMain.java
  src/main/java/org/opentripplanner/standalone/config/UpdatersConfig.java
  src/main/java/org/opentripplanner/standalone/config/updaters/SiriVMUpdaterConfig.java
  src/main/java/org/opentripplanner/standalone/config/updaters/WebsocketGtfsRealtimeUpdaterConfig.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/TransitEditorService.java
  src/main/java/org/opentripplanner/transit/service/TransitModel.java
  src/main/java/org/opentripplanner/updater/GraphUpdater.java
  src/main/java/org/opentripplanner/updater/GraphUpdaterConfigurator.java
  src/main/java/org/opentripplanner/updater/PollingGraphUpdater.java
  src/main/java/org/opentripplanner/updater/TimetableSnapshotSourceParameters.java
  src/main/java/org/opentripplanner/updater/UpdatersParameters.java
  src/main/java/org/opentripplanner/updater/alerts/GtfsRealtimeAlertsUpdater.java
  src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
  src/main/java/org/opentripplanner/updater/stoptime/MqttGtfsRealtimeUpdater.java
  src/main/java/org/opentripplanner/updater/stoptime/PollingStoptimeUpdater.java
  src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
  src/main/java/org/opentripplanner/updater/stoptime/TripUpdateGraphWriterRunnable.java
  src/main/java/org/opentripplanner/updater/stoptime/WebsocketGtfsRealtimeUpdater.java
  src/main/java/org/opentripplanner/updater/stoptime/WebsocketGtfsRealtimeUpdaterParameters.java
  src/main/java/org/opentripplanner/updater/street_notes/WFSNotePollingGraphUpdater.java
  src/main/java/org/opentripplanner/updater/street_notes/WinkkiPollingGraphUpdater.java
  src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingUpdater.java
  src/main/java/org/opentripplanner/updater/vehicle_positions/PollingVehiclePositionUpdater.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdater.java
  src/test/java/org/opentripplanner/GtfsTest.java
  src/test/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSourceTest.java
  src/test/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingUpdaterTest.java
Labels: technical debt, skip changelog

#4420 Documentation updates and fixes
  docs/BuildConfiguration.md
  docs/RouterConfiguration.md
  src/test/java/org/opentripplanner/standalone/config/RouterConfigTest.java
Labels: documentation, skip changelog

#4415 Avoid creating unneeded objects in RAPTOR
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/RaptorTransferIndex.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/ConstrainedBoardingSearch.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitData.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RangeRaptorWorker.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/McStopArrivals.java
Labels: optimization, Entur test, skip changelog
