Repository opentripplanner/OpenTripPlanner, pull requests merged in 2022-04, with the labels that each got.

#4053 Remove the Sandbox example, there are plenty of others [changelog skip]
  docs/Configuration.md
  docs/SandboxExtension.md
  docs/sandbox/Examples.md
  src/ext-test/java/org/opentripplanner/ext/examples/statistics/api/resource/GraphStatisticsResourceTest.java
  src/ext/java/org/opentripplanner/ext/examples/statistics/api/model/GraphStatistics.java
  src/ext/java/org/opentripplanner/ext/examples/statistics/api/model/StatisticsGraphQLSchemaFactory.java
  src/ext/java/org/opentripplanner/ext/examples/statistics/api/resource/GraphStatisticsResource.java
  src/main/java/org/opentripplanner/api/configuration/APIEndpoints.java
  src/main/java/org/opentripplanner/util/OTPFeature.java
Labels: technical debt

#4062 Add GBFS form factors to GraphQL API
  docs/sandbox/LegacyGraphQLApi.md
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLUtils.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLRentalVehicleImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLRentalVehicleTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/graphql-codegen.yml
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/routing/vehicle_rental/RentalVehicleType.java
Labels: IBI test, IBI

#4064 Fix problem with time points [changelog skip]
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
Labels: Skanetrafiken

#4057 Remove unused dependencies [changelog skip]
  pom.xml
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
Labels: technical debt

#4056 Map to ApiTripTimesShort in REST API response [changelog skip]
  src/main/java/org/opentripplanner/index/IndexAPI.java
Labels: Regression

#4054 Remove TraversalRequirements and use exactly same method in StreetEdge [changelog skip]
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/routing/core/TraversalRequirements.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
Labels: technical debt

#4060 Optimise TripPatternForDates.getTripSchedule(int) - TripScheduleWithOffset [changelog skip]
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripPatternForDates.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleWithOffset.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TestRouteData.java
Labels: optimization

#4068 Add Geocoder API for debug client searches
  docs/SandboxExtension.md
  docs/sandbox/GeocoderAPI.md
  pom.xml
  src/client/js/otp/core/GeocoderBuiltin.js
  src/client/js/otp/core/IndexApi.js
  src/ext/java/org/opentripplanner/ext/geocoder/GeocoderResource.java
  src/ext/java/org/opentripplanner/ext/geocoder/LuceneIndex.java
  src/main/java/org/opentripplanner/api/configuration/APIEndpoints.java
  src/main/java/org/opentripplanner/model/GroupOfStations.java
  src/main/java/org/opentripplanner/model/MultiModalStation.java
  src/main/java/org/opentripplanner/model/StopCollection.java
  src/main/java/org/opentripplanner/netex/mapping/GroupOfStationsMapper.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/standalone/server/Router.java
  src/main/java/org/opentripplanner/util/OTPFeature.java
Labels: sandbox, Regression

#4074 Make language nullable in MultilingualString, as it is not set in NonLocalizedString [changelog skip]
  docs/sandbox/TransmodelApi.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/MultilingualStringType.java
Labels: bug, Entur test

#4065 Link platforms also against railway=platform
  src/main/java/org/opentripplanner/openstreetmap/model/OSMNode.java
Labels: improvement

#4046 Consider Wheelchair boarding/alightning when routing from or to directly to a stop
  pom.xml
  src/main/java/org/opentripplanner/model/Stop.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TripPatternWithRaptorStopIndexes.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TransitDataProviderFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripPatternForDates.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreatorTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TestRouteData.java
  src/test/resources/mmri/2b/stops.txt
Labels: Regression, Skanetrafiken

#4076 Use maven plugin to compile GTFS-RT library [changelog skip]
  pom.xml
  src/main/java/com/google/transit/realtime/GtfsRealtime.java
  src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
  src/main/proto/gtfs-realtime.proto
  src/test/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSourceTest.java
Labels: technical debt

#4071 Add an implementation for fetching alternative legs
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStoptimeImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/TripTimeShortHelper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
  src/main/java/org/opentripplanner/api/mapping/TripTimeMapper.java
  src/main/java/org/opentripplanner/model/TripTimeOnDate.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
  src/main/java/org/opentripplanner/model/plan/legreference/LegReference.java
  src/main/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializer.java
  src/main/java/org/opentripplanner/model/plan/legreference/LegReferenceType.java
  src/main/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReference.java
  src/main/java/org/opentripplanner/routing/alternativelegs/AlternativeLegs.java
  src/main/java/org/opentripplanner/routing/alternativelegs/AlternativeLegsFilter.java
  src/main/java/org/opentripplanner/routing/stoptimes/StopTimesHelper.java
  src/test/java/org/opentripplanner/GtfsTest.java
  src/test/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializerTest.java
  src/test/java/org/opentripplanner/routing/stoptimes/AlternativeLegsTest.java
Labels: new feature, Entur, Entur test

#4069 Refactor trip search [changelog skip]
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TripSchedule.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/ConstrainedBoardingSearch.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripPatternForDates.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleAlightSearch.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleBoardSearch.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleSearchFactory.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripSearchTimetable.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTimeTable.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTripScheduleBoardOrAlightEvent.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTripScheduleSearch.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RangeRaptorWorker.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/ForwardTransitCalculator.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/ReverseTransitCalculator.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripAssert.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleAlightSearchTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleBoardSearchTest.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestRoute.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTripSearchTimetable.java
Labels: technical debt

#4051 Group/filter on first/last trip in itineraries
  docs/RouterConfiguration.md
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filter/SameFirstOrLastTripFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/groupids/GroupBySameFirstOrLastTrip.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RoutingRequestToFilterChainMapper.java
  src/main/java/org/opentripplanner/routing/api/request/ItineraryFilterParameters.java
  src/main/java/org/opentripplanner/standalone/config/ItineraryFiltersMapper.java
  src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filter/SameFirstOrLastTripFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/groupids/GroupBySameFirstOrLastTripTest.java
Labels: new feature, Skanetrafiken

#4072 Shortcut in ParetoCheck add/check for performance [changelog skip]
  src/main/java/org/opentripplanner/transit/raptor/util/paretoset/ParetoSet.java
Labels: improvement, optimization

#4073 Remove self-referring DatedServiceJourneyRefs [changelog skip]
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
Labels: bug, Entur test, NeTEx

#4082 Reactivate GTFS-RT tests [changelog skip]
  README.md
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/model/calendar/ServiceDate.java
  src/main/java/org/opentripplanner/model/calendar/impl/CalendarServiceDataFactoryImpl.java
  src/main/java/org/opentripplanner/updater/stoptime/PollingStoptimeUpdater.java
  src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/model/TimetableSnapshotTest.java
  src/test/java/org/opentripplanner/model/TimetableTest.java
  src/test/java/org/opentripplanner/model/calendar/impl/CalendarServiceDataFactoryImplTest.java
  src/test/java/org/opentripplanner/routing/algorithm/AStarTest.java
  src/test/java/org/opentripplanner/routing/algorithm/FaresTest.java
  src/test/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSourceTest.java
Labels: improvement

#4081 Update prettier formatter documentation [changelog skip]
  docs/Codestyle.md
  docs/images/ExternalToolDialog.png
Labels: documentation

#4085 Clean up PolylineEncoder & EncodedPolylineBean [changelog skip]
  src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLGeometryImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/PointsOnLinkType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/JourneyPatternType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/ServiceJourneyType.java
  src/main/java/org/opentripplanner/api/mapping/LegMapper.java
  src/main/java/org/opentripplanner/api/model/ApiLeg.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
  src/main/java/org/opentripplanner/index/IndexAPI.java
  src/main/java/org/opentripplanner/util/PolylineEncoder.java
  src/main/java/org/opentripplanner/util/model/EncodedPolyline.java
  src/main/java/org/opentripplanner/util/model/EncodedPolylineBean.java
  src/test/java/org/opentripplanner/routing/street/BarrierRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/BicycleRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/CarRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/SplitEdgeTurnRestrictionsTest.java
  src/test/java/org/opentripplanner/util/PolylineEncoderTest.java
  src/test/java/org/opentripplanner/util/model/TestEncodedPolylineBean.java
Labels: technical debt

#4084 Convert Legs to Java 8 time classes [changelog skip]
  src/ext/java/org/opentripplanner/ext/flex/FlexibleTransitLeg.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLItineraryImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLLegImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPlaceImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripPatternType.java
  src/main/java/org/opentripplanner/api/mapping/ItineraryMapper.java
  src/main/java/org/opentripplanner/api/mapping/LegMapper.java
  src/main/java/org/opentripplanner/api/mapping/PlaceMapper.java
  src/main/java/org/opentripplanner/model/base/ToStringBuilder.java
  src/main/java/org/opentripplanner/model/plan/FrequencyTransitLeg.java
  src/main/java/org/opentripplanner/model/plan/ItinerariesCalculateLegTotals.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
  src/main/java/org/opentripplanner/model/plan/StopArrival.java
  src/main/java/org/opentripplanner/model/plan/StreetLeg.java
  src/main/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReference.java
  src/main/java/org/opentripplanner/routing/alertpatch/TransitAlert.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/LatestDepartureTimeFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/AlertToLegMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/alternativelegs/AlternativeLegs.java
  src/main/java/org/opentripplanner/routing/core/State.java
  src/main/java/org/opentripplanner/routing/core/StateData.java
  src/main/java/org/opentripplanner/routing/core/StateEditor.java
  src/main/java/org/opentripplanner/routing/fares/impl/RideMapper.java
  src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
  src/main/java/org/opentripplanner/transit/raptor/util/PathStringBuilder.java
  src/main/java/org/opentripplanner/util/time/RelativeTime.java
  src/main/java/org/opentripplanner/util/time/TimeUtils.java
  src/test/java/org/opentripplanner/GtfsTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestIntermediatePlaces.java
  src/test/java/org/opentripplanner/model/base/ToStringBuilderTest.java
  src/test/java/org/opentripplanner/model/plan/ItineraryTest.java
  src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
  src/test/java/org/opentripplanner/routing/algorithm/FaresTest.java
  src/test/java/org/opentripplanner/routing/algorithm/TestDominanceFunction.java
  src/test/java/org/opentripplanner/routing/core/TraverseResultTest.java
  src/test/java/org/opentripplanner/routing/edgetype/PlainStreetEdgeTest.java
  src/test/java/org/opentripplanner/transit/raptor/speed_test/model/testcase/ItineraryResultMapper.java
  src/test/java/org/opentripplanner/util/time/TimeUtilsTest.java
Labels: technical debt

#4080 Refactor, explicit slackIndex on RaptorTripPattern [changelog skip]
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/SlackProvider.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripPatternForDates.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/MinSafeTransferTimeCalculator.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGenerator.java
  src/main/java/org/opentripplanner/transit/raptor/api/path/PathBuilderLeg.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/Flyweight.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorSlackProvider.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTransitDataProvider.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTripPattern.java
  src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTripScheduleSearch.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RangeRaptorWorker.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/SlackProvider.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/MultiCriteriaRoutingStrategy.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/SearchContext.java
  src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/SlackProviderAdapter.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGeneratorTest.java
  src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTripPattern.java
  src/test/java/org/opentripplanner/transit/raptor/rangeraptor/transit/SlackProviderAdapterTest.java
Labels: technical debt

#4089 Fix time shifting bug in flex direct router [changelog skip]
  src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessTemplate.java
Labels: bug, sandbox

#4075 Added SIRI trip matching for DatedServiceJourneyId [changelog skip]
  src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java
  src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
Labels: improvement, NeTEx, Skanetrafiken

#4093 Fix problem with submode filter
  src/main/java/org/opentripplanner/model/modes/AllowedTransitMode.java
  src/test/java/org/opentripplanner/model/modes/AllowedTransitModeTest.java
Labels: Skanetrafiken

#4088 Make maxWheelchairSlope not a hard cut-off, but apply a cost instead
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/ItinerariesHelper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectStreetRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/Transfer.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRequestTransferCache.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/core/RoutingContext.java
  src/main/java/org/opentripplanner/routing/edgetype/PathwayEdge.java
  src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
  src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
Labels: improvement

#4094 Improve logging of GTFS-RT updates [changelog skip]
  src/main/java/org/opentripplanner/updater/stoptime/GtfsRealtimeHttpTripUpdateSource.java
  src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
  src/test/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSourceTest.java
Labels: improvement

#4092 Only crash build if none of the transit data sets have active data [changelog skip]
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
  src/main/java/org/opentripplanner/model/OtpTransitService.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceImpl.java
  src/main/java/org/opentripplanner/netex/NetexModule.java
  src/test/java/org/opentripplanner/model/impl/OtpTransitServiceImplTest.java
Labels: improvement

#4099 Fix generalized cost of flex direct legs [changelog skip]
  src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/comparator/SortOrderComparatorTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/MaxLimitFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/RemoveTransitIfStreetOnlyIsBetterFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/RemoveWalkOnlyFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/TransitGeneralizedCostFilterTest.java
Labels: bug

#4066 Infer vehicle positions service day [changelog skip]
  src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/updater/vehicle_positions/PollingVehiclePositionUpdater.java
  src/main/java/org/opentripplanner/updater/vehicle_positions/VehiclePositionPatternMatcher.java
  src/test/java/org/opentripplanner/routing/street/BarrierRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/BicycleRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/CarRoutingTest.java
  src/test/java/org/opentripplanner/routing/street/SplitEdgeTurnRestrictionsTest.java
  src/test/java/org/opentripplanner/test/support/PolylineAssert.java
  src/test/java/org/opentripplanner/test/support/VariableArgumentsProvider.java
  src/test/java/org/opentripplanner/test/support/VariableSource.java
  src/test/java/org/opentripplanner/updater/vehicle_positions/VehiclePositionsMatcherTest.java
Labels: improvement, IBI test

#4109 Use correct routing request when traversing transfers [changelog skip]
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
Labels: bug

#4108 Fix: Hot fix to avoid crash during routing in optimized transfers [changelog skip]
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/OptimizeTransferService.java
Labels: bug

#4111 How about turning off the default build reports generation feature [changelog skip]
  pom.xml
Labels: technical debt

#4104 Enable overriding maxDirectStreetDuration per mode
  docs/OTP2-MigrationGuide.md
  docs/RouterConfiguration.md
  docs/examples/entur/router-config.json
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/DefaultRoutingRequestType.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectStreetRouter.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
  src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
  src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
  src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
  src/test/java/org/opentripplanner/standalone/config/NodeAdapterTest.java
Labels: new feature, Entur test

#4117 Preserve language in SIRI/GTFS-RT alert messages
  src/ext-test/java/org/opentripplanner/ext/vectortiles/VehicleParkingsLayerTest.java
  src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkToVehicleParkingMapper.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/parkapi/ParkAPIUpdater.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/NoteProperties.java
  src/main/java/org/opentripplanner/netex/mapping/StationMapper.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
  src/main/java/org/opentripplanner/updater/alerts/AlertsUpdateHandler.java
  src/main/java/org/opentripplanner/util/TranslatedString.java
  src/main/java/org/opentripplanner/util/TranslationHelper.java
  src/test/java/org/opentripplanner/util/TranslatedStringTest.java
Labels: improvement

#4079 Use board/aligh cost only for transits
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/StopIndexForRaptor.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/DefaultCostCalculator.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/StopPriorityCostCalculator.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/DefaultCostCalculatorTest.java
  src/test/java/org/opentripplanner/transit/raptor/_data/api/TestPathBuilderTest.java
Labels: bug, Skanetrafiken

#4038 Improve SIRI realtime performance by reducing stopPattern duplicates
  src/ext-test/java/org/opentripplanner/ext/siri/TimeTableHelperTest.java
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/model/TripIdAndServiceDate.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerUpdater.java
Labels: optimization, Entur test, Skanetrafiken, RealTimeUpdate

#4128 Expose datedServiceJourney from EstimatedCall [changelog skip]
  docs/sandbox/TransmodelApi.md
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
  src/main/java/org/opentripplanner/routing/DatedServiceJourneyHelper.java
  src/main/java/org/opentripplanner/routing/RoutingService.java
  src/main/java/org/opentripplanner/routing/graph/GraphIndex.java
Labels: new feature, sandbox

#4122 Read headsign for frequency-only patterns in vector tiles API [changelog skip]
  docs/sandbox/MapboxVectorTilesApi.md
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/DigitransitStopPropertyMapper.java
  src/main/java/org/opentripplanner/model/Timetable.java
  src/main/java/org/opentripplanner/model/TripPattern.java
Labels: bug, sandbox
