Repository opentripplanner/OpenTripPlanner, pull requests merged in 2023-01, with the labels that each got.

#4692 Remove micrometer-jersey2 module
  pom.xml
  src/main/java/org/opentripplanner/standalone/server/OTPWebApplication.java
Labels: technical debt, skip changelog

#4694 Remove NYC fare service
  docs/sandbox/Fares.md
  src/ext/java/org/opentripplanner/ext/fares/FaresConfiguration.java
  src/ext/java/org/opentripplanner/ext/fares/impl/NycFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/NycFareServiceImpl.java
Labels: sandbox, technical debt

#4676 Annotation to make graphql resolver execution async
  docs/Configuration.md
  docs/sandbox/LegacyGraphQLApi.md
  src/ext-test/java/org/opentripplanner/ext/legacygraphqlapi/GraphQLIndexTest.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/IntrospectionTypeWiring.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/framework/application/OTPFeature.java
Labels: sandbox, skip changelog, bbnavi

#4693 Upgrade dependencies to take newest GTFS Flex spec into account
  pom.xml
Labels: technical debt, IBI

#4684 Configuration of additional HTTP headers for GTFS-RT updaters
  docs/RouterConfiguration.md
  docs/UpdaterConfig.md
  docs/examples/ibi/atlanta/router-config.json
  docs/sandbox/VehicleParking.md
  src/main/java/org/opentripplanner/framework/collection/MapUtils.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/UpdatersConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/GtfsRealtimeAlertsUpdaterConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/PollingTripUpdaterConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/VehiclePositionsUpdaterConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/VehicleRentalUpdaterConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/WebsocketGtfsRealtimeUpdaterConfig.java
  src/main/java/org/opentripplanner/updater/alert/GtfsRealtimeAlertsUpdater.java
  src/main/java/org/opentripplanner/updater/alert/GtfsRealtimeAlertsUpdaterParameters.java
  src/main/java/org/opentripplanner/updater/trip/GtfsRealtimeHttpTripUpdateSource.java
  src/main/java/org/opentripplanner/updater/trip/PollingTripUpdaterParameters.java
  src/main/java/org/opentripplanner/updater/vehicle_position/GtfsRealtimeHttpVehiclePositionSource.java
  src/main/java/org/opentripplanner/updater/vehicle_position/PollingVehiclePositionUpdater.java
  src/main/java/org/opentripplanner/updater/vehicle_position/VehiclePositionsUpdaterParameters.java
  src/test/java/org/opentripplanner/framework/collection/MapUtilsTest.java
  src/test/java/org/opentripplanner/generate/doc/UpdaterConfigDocTest.java
  src/test/java/org/opentripplanner/generate/doc/framework/DocBuilder.java
  src/test/java/org/opentripplanner/updater/vehicle_position/VehiclePositionParsingTest.java
  src/test/resources/standalone/config/router-config.json
Labels: new feature, IBI

#4703 Minor adjustments to finland walk safety
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/FinlandMapper.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/FinlandMapperTest.java
Labels: skip changelog

#4667 GTFS-RT extension to add completely new routes
  docs/sandbox/ActuatorAPI.md
  src/ext/java/org/opentripplanner/ext/siri/AddedTripHelper.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  src/main/java/org/opentripplanner/framework/io/HttpUtils.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/gtfs/mapping/PickDropMapper.java
  src/main/java/org/opentripplanner/model/Timetable.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/model/UpdateError.java
  src/main/java/org/opentripplanner/model/UpdateSuccess.java
  src/main/java/org/opentripplanner/transit/model/framework/Result.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/TransitModel.java
  src/main/java/org/opentripplanner/transit/service/TransitService.java
  src/main/java/org/opentripplanner/updater/UpdateResult.java
  src/main/java/org/opentripplanner/updater/trip/AddedRoute.java
  src/main/java/org/opentripplanner/updater/trip/AddedStopTime.java
  src/main/java/org/opentripplanner/updater/trip/GtfsRealtimeHttpTripUpdateSource.java
  src/main/java/org/opentripplanner/updater/trip/MqttGtfsRealtimeUpdater.java
  src/main/java/org/opentripplanner/updater/trip/PollingTripUpdater.java
  src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
  src/main/java/org/opentripplanner/updater/trip/TripUpdateGraphWriterRunnable.java
  src/main/java/org/opentripplanner/updater/trip/UpdateResult.java
  src/main/java/org/opentripplanner/updater/trip/WebsocketGtfsRealtimeUpdater.java
  src/main/java/org/opentripplanner/updater/trip/metrics/BatchTripUpdateMetrics.java
  src/main/java/org/opentripplanner/updater/trip/metrics/StreamingTripUpdateMetrics.java
  src/main/java/org/opentripplanner/updater/trip/metrics/TripUpdateMetrics.java
  src/main/proto/mfdz-realtime-extensions.proto
  src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java
  src/test/java/org/opentripplanner/updater/trip/TripUpdateBuilder.java
Labels: RealTimeUpdate, bbnavi

#4705 Pretty-print all JSON examples in docs
  doc-templates/Flex.md
  docs/BuildConfiguration.md
  docs/RouterConfiguration.md
  docs/sandbox/Flex.md
  docs/sandbox/VehicleParking.md
  src/test/java/org/opentripplanner/generate/doc/BuildConfigurationDocTest.java
  src/test/java/org/opentripplanner/generate/doc/ConfigurationDocTest.java
  src/test/java/org/opentripplanner/generate/doc/FlexConfigurationDocTest.java
  src/test/java/org/opentripplanner/generate/doc/RouteRequestDocTest.java
  src/test/java/org/opentripplanner/generate/doc/RouterConfigurationDocTest.java
  src/test/java/org/opentripplanner/generate/doc/UpdaterConfigDocTest.java
  src/test/java/org/opentripplanner/generate/doc/VehicleParkingDocTest.java
  src/test/java/org/opentripplanner/generate/doc/framework/DocBuilder.java
  src/test/java/org/opentripplanner/generate/doc/framework/JsonExampleBuilder.java
  src/test/java/org/opentripplanner/generate/doc/framework/TemplateUtil.java
Labels: documentation, skip changelog

#4657 New filter API
  src/ext-test/java/org/opentripplanner/ext/fares/impl/FaresIntegrationTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/FilterInputType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/ModeAndSubModeInputType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/ModeInputType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/SelectInputType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
  src/ext/java/org/opentripplanner/ext/vehicletostopheuristics/VehicleToStopSkipEdgeStrategy.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/api/parameter/QualifiedModeSet.java
  src/main/java/org/opentripplanner/api/resource/PlannerResource.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/model/modes/AllowAllModesFilter.java
  src/main/java/org/opentripplanner/model/modes/AllowMainAndSubModeFilter.java
  src/main/java/org/opentripplanner/model/modes/AllowMainAndSubModesFilter.java
  src/main/java/org/opentripplanner/model/modes/AllowMainModeFilter.java
  src/main/java/org/opentripplanner/model/modes/AllowMainModesFilter.java
  src/main/java/org/opentripplanner/model/modes/AllowTransitModeFilter.java
  src/main/java/org/opentripplanner/model/modes/FilterCollection.java
  src/main/java/org/opentripplanner/model/modes/FilterFactory.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RouteRequestTransitDataProviderFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TransitDataProviderFilter.java
  src/main/java/org/opentripplanner/routing/api/request/RequestModes.java
  src/main/java/org/opentripplanner/routing/api/request/RequestModesBuilder.java
  src/main/java/org/opentripplanner/routing/api/request/RouteRequest.java
  src/main/java/org/opentripplanner/routing/api/request/request/JourneyRequest.java
  src/main/java/org/opentripplanner/routing/api/request/request/TransitRequest.java
  src/main/java/org/opentripplanner/routing/api/request/request/filter/AllowAllTransitFilter.java
  src/main/java/org/opentripplanner/routing/api/request/request/filter/SelectRequest.java
  src/main/java/org/opentripplanner/routing/api/request/request/filter/TransitFilter.java
  src/main/java/org/opentripplanner/routing/api/request/request/filter/TransitFilterRequest.java
  src/test/java/org/opentripplanner/GtfsTest.java
  src/test/java/org/opentripplanner/api/parameter/QualifiedModeSetTest.java
  src/test/java/org/opentripplanner/filter/ExcludeAllTransitFilter.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestIntermediatePlaces.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TriangleInequalityTest.java
  src/test/java/org/opentripplanner/model/modes/AllowAllModesFilterTest.java
  src/test/java/org/opentripplanner/model/modes/AllowMainAndSubModeFilterTest.java
  src/test/java/org/opentripplanner/model/modes/AllowMainAndSubModesFilterTest.java
  src/test/java/org/opentripplanner/model/modes/AllowMainModeFilterTest.java
  src/test/java/org/opentripplanner/model/modes/AllowMainModesFilterTest.java
  src/test/java/org/opentripplanner/model/modes/FilterFactoryTest.java
  src/test/java/org/opentripplanner/routing/algorithm/FilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/TestBanning.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/BikeRentalSnapshotTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/CarSnapshotTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/ElevationSnapshotTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/SnapshotTestBase.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/TransitSnapshotTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/router/FilterTransitWhenDirectModeIsEmptyTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreatorTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RouteRequestTransitDataProviderFilterTest.java
Labels: new feature, Skanetrafiken

#4731 Merge @Tag("docs") and @OnlyIfDocsExist into @GeneratesDocumentation
  src/test/java/org/opentripplanner/generate/doc/BuildConfigurationDocTest.java
  src/test/java/org/opentripplanner/generate/doc/ConfigurationDocTest.java
  src/test/java/org/opentripplanner/generate/doc/FlexConfigurationDocTest.java
  src/test/java/org/opentripplanner/generate/doc/RouteRequestDocTest.java
  src/test/java/org/opentripplanner/generate/doc/RouterConfigurationDocTest.java
  src/test/java/org/opentripplanner/generate/doc/UpdaterConfigDocTest.java
  src/test/java/org/opentripplanner/generate/doc/VehicleParkingDocTest.java
  src/test/java/org/opentripplanner/generate/doc/framework/DocsTestConstants.java
  src/test/java/org/opentripplanner/generate/doc/framework/GeneratesDocumentation.java
  src/test/java/org/opentripplanner/standalone/config/ExampleConfigTest.java
Labels: documentation, technical debt, skip changelog

#4696 Refactor of wayproperty.specifier.Condition
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWay.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/WayPropertySet.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/specifier/BestMatchSpecifier.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/specifier/Condition.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/specifier/ExactMatchSpecifier.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/specifier/OsmSpecifier.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/DefaultMapperTest.java
  src/test/java/org/opentripplanner/openstreetmap/wayproperty/WayPropertySetTest.java
  src/test/java/org/opentripplanner/openstreetmap/wayproperty/specifier/BestMatchSpecifierTest.java
  src/test/java/org/opentripplanner/openstreetmap/wayproperty/specifier/ConditionTest.java
  src/test/java/org/opentripplanner/openstreetmap/wayproperty/specifier/ExactMatchSpecifierTest.java
  src/test/java/org/opentripplanner/openstreetmap/wayproperty/specifier/OsmSpecifierTest.java
  src/test/java/org/opentripplanner/openstreetmap/wayproperty/specifier/SpecifierTest.java
  src/test/java/org/opentripplanner/openstreetmap/wayproperty/specifier/WayTestData.java
Labels: improvement

#4749 Configure renovate to be less noisy
  renovate.json5
Labels: improvement, skip changelog

#4750 Bugfix: do not add elements to immutable list
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
Labels: skip changelog

#4751 Make the SpeedIntegrationTest run in isolation with respect to OTPFeatures
  src/main/java/org/opentripplanner/standalone/config/ConfigModel.java
  src/test/java/org/opentripplanner/transit/speed_test/SpeedIntegrationTest.java
  src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
Labels: technical debt, skip changelog

#4689 Add next legs search to LegacyGraphQL API
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLLegImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/graphql-codegen.yml
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/routing/alternativelegs/AlternativeLegs.java
Labels: improvement, sandbox, skip changelog

#4754 Set default value when mode parameter is null
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationModule.java
  src/test/java/org/opentripplanner/api/common/PlannerResourceTest.java
Labels: bug, skip changelog

#4729 Added contact email for Siri Azure Updater sandbox module
  docs/sandbox/SiriAzureUpdater.md
Labels: documentation, sandbox, skip changelog

#4757 fix: relaxGeneralizedCostAtDestination leaks Raptor internal NOT_SET
  docs/RouteRequest.md
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
  src/main/java/org/opentripplanner/api/common/RequestToPreferencesMapper.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/raptor/api/request/SearchParams.java
  src/main/java/org/opentripplanner/raptor/api/request/SearchParamsBuilder.java
  src/main/java/org/opentripplanner/raptor/rangeraptor/path/configure/PathConfig.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RaptorRequestMapper.java
  src/main/java/org/opentripplanner/routing/api/request/framework/Units.java
  src/main/java/org/opentripplanner/routing/api/request/preference/RaptorPreferences.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  src/test/java/org/opentripplanner/raptor/util/paretoset/ParetoSetTest.java
  src/test/java/org/opentripplanner/routing/api/request/framework/UnitsTest.java
  src/test/java/org/opentripplanner/routing/api/request/preference/RaptorPreferencesTest.java
Labels: skip changelog

#4756 Norway mapper walk safety
  .gitignore
  src/main/java/org/opentripplanner/framework/functional/FunctionUtils.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/FinlandMapper.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/NorwayMapper.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/WayPropertySet.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/specifier/LogicalOrSpecifier.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/NorwayMapperTest.java
Labels: improvement, skip changelog

#4761 docs: Add transitGeneralizedCostLimit fields in documentation
  docs/RouteRequest.md
  docs/RouterConfiguration.md
  src/main/java/org/opentripplanner/standalone/config/routerequest/ItineraryFiltersConfig.java
  src/test/resources/standalone/config/router-config.json
Labels: documentation, skip changelog

#4699 Cleanup usage of SIRI DatedServiceJourneyId vs. ServiceJourneyId
  src/ext/java/org/opentripplanner/ext/siri/EntityResolver.java
  src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTripPatternCache.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriVMUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/AbstractAzureSiriUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
Labels: bug, sandbox, technical debt, RealTimeUpdate

#4758 Do not return a leg from a leg reference, if trip does not exist on date
  src/main/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReference.java
Labels: bug

#4755 Expose more data from SIRI-SX messages in the Transmodel API
  src/ext-test/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLstepImplTest.java
  src/ext-test/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandlerTest.java
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLAgencyImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLAlertImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLFeedImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPatternImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLRouteImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLstepImpl.java
  src/ext/java/org/opentripplanner/ext/siri/AffectsMapper.java
  src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/ValidityPeriodType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/sx/AffectsType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/sx/PtSituationElementType.java
  src/main/java/org/opentripplanner/api/mapping/AlertMapper.java
  src/main/java/org/opentripplanner/routing/alertpatch/EntityKey.java
  src/main/java/org/opentripplanner/routing/alertpatch/EntitySelector.java
  src/main/java/org/opentripplanner/routing/alertpatch/TransitAlert.java
  src/main/java/org/opentripplanner/routing/alertpatch/TransitAlertBuilder.java
  src/main/java/org/opentripplanner/routing/impl/DelegatingTransitAlertServiceImpl.java
  src/main/java/org/opentripplanner/routing/impl/TransitAlertServiceImpl.java
  src/main/java/org/opentripplanner/routing/services/TransitAlertService.java
  src/main/java/org/opentripplanner/updater/alert/AlertsUpdateHandler.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filter/TransitAlertFilterTest.java
  src/test/java/org/opentripplanner/updater/alert/AlertsUpdateHandlerTest.java
Labels: improvement, technical debt, Entur test

#4763 Exclude transit modes in APIs when there is only non-transit ones
  src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/model/modes/ExcludeAllTransitFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/api/request/request/TransitRequest.java
  src/main/java/org/opentripplanner/routing/api/request/request/filter/TransitFilterRequest.java
  src/test/java/org/opentripplanner/api/common/PlannerResourceTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestIntermediatePlaces.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TriangleInequalityTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/BikeRentalSnapshotTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/CarSnapshotTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/ElevationSnapshotTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/TransitSnapshotTest.java
  src/test/java/org/opentripplanner/transit/speed_test/SpeedTestRequest.java
  src/test/java/org/opentripplanner/transit/speed_test/model/testcase/TestCaseDefinition.java
  src/test/java/org/opentripplanner/transit/speed_test/model/testcase/io/TestCaseDefinitionCsvFile.java
Labels: bug, skip changelog

#4753 Add more module tests to Raptor for all relevant profiles
  src/test/java/org/opentripplanner/raptor/moduletests/A01_SingeRouteTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/A02_SingeRouteRestrictionsTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/A04_BoardingTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/B01_AccessTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/B02_EgressTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/B03_AccessEgressTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/B04_AccessEgressBoardingTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/B10_FlexAccessTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/B11_FlexEgressTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/C01_TransferBoardAndAlightSlackTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/C02_BoardAndAlightSlackWithFlexAccessEgressTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/C03_OnStreetTransfersTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/E01_GuaranteedTransferTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/E02_NotAllowedConstrainedTransferTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/E11_GuaranteedTransferWithFlexAccessTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/F01_TransitModeReluctanceTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/support/RaptorModuleTestCase.java
  src/test/java/org/opentripplanner/raptor/moduletests/support/RaptorModuleTestCaseBuilder.java
  src/test/java/org/opentripplanner/raptor/moduletests/support/RaptorModuleTestConfig.java
  src/test/java/org/opentripplanner/raptor/moduletests/support/RaptorModuleTestConfigSetBuilder.java
Labels: technical debt, skip changelog

#4767 Fix direct transfer analyzer
  src/ext/java/org/opentripplanner/ext/transferanalyzer/DirectTransferAnalyzer.java
  src/ext/java/org/opentripplanner/ext/transferanalyzer/annotations/TransferCouldNotBeRouted.java
  src/ext/java/org/opentripplanner/ext/transferanalyzer/annotations/TransferRoutingDistanceTooLong.java
  src/main/java/org/opentripplanner/graph_builder/issue/api/DataImportIssue.java
  src/main/java/org/opentripplanner/graph_builder/issues/HopSpeedSlow.java
  src/main/java/org/opentripplanner/graph_builder/issues/HopZeroDistance.java
  src/main/java/org/opentripplanner/graph_builder/issues/HopZeroTime.java
  src/main/java/org/opentripplanner/graph_builder/issues/InterliningTeleport.java
  src/main/java/org/opentripplanner/graph_builder/issues/RepeatedStops.java
Labels: bug, improvement

#4775 Move from javax.inject.Singleton to jakarta.inject.Singleton
  src/ext/java/org/opentripplanner/ext/datastore/gs/GsDataSourceModule.java
  src/main/java/org/opentripplanner/datastore/configure/DataStoreModule.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilderDataSources.java
  src/main/java/org/opentripplanner/graph_builder/issue/service/DefaultDataImportIssueStore.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderFactory.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  src/main/java/org/opentripplanner/routing/api/request/RoutingService.java
  src/main/java/org/opentripplanner/service/worldenvelope/internal/DefaultWorldEnvelopeRepository.java
  src/main/java/org/opentripplanner/standalone/config/configure/ConfigModule.java
  src/main/java/org/opentripplanner/standalone/config/configure/LoadConfigModule.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationFactory.java
  src/main/java/org/opentripplanner/standalone/configure/LoadApplicationFactory.java
Labels: technical debt, skip changelog

#4759 Add support for deleted trips & including real-time cancelations in trip search
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
  src/main/java/org/opentripplanner/model/TripTimeOnDate.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TripPatternForDateMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RouteRequestTransitDataProviderFilter.java
  src/main/java/org/opentripplanner/routing/api/request/preference/TransitPreferences.java
  src/main/java/org/opentripplanner/routing/stoptimes/StopTimesHelper.java
  src/main/java/org/opentripplanner/transit/model/timetable/RealTimeState.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripTimes.java
  src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
  src/main/proto/gtfs-realtime.proto
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RouteRequestTransitDataProviderFilterTest.java
  src/test/java/org/opentripplanner/routing/api/request/preference/TransitPreferencesTest.java
  src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java
Labels: new feature, bump serialization id

#4774 Add deprecation tags, improve docs, update GraphiQL
  docs/RouteRequest.md
  docs/sandbox/LegacyGraphQLApi.md
  src/client/legacygraphql/graphiql/index.html
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
Labels: skip changelog

#4782 Make Transmodel API accept timezones without colons
  pom.xml
  src/ext-test/java/org/opentripplanner/ext/transmodelapi/model/scalars/DateTimeScalarFactoryTest.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/scalars/DateTimeScalarFactory.java
Labels: bug, Entur test, skip changelog

#4770 Improve logging of Modes and SelectFilter with modes
  src/main/java/org/opentripplanner/routing/api/request/request/filter/SelectRequest.java
  src/main/java/org/opentripplanner/transit/model/basic/MainAndSubMode.java
  src/test/java/org/opentripplanner/routing/api/request/request/filter/SelectRequestTest.java
  src/test/java/org/opentripplanner/transit/model/basic/MainAndSubModeTest.java
Labels: improvement, skip changelog
