Repository opentripplanner/OpenTripPlanner, pull requests merged in 2023-06, with the labels that each got.

#5155 Otp2 fix max direct duration for mode
  src/ext-test/java/org/opentripplanner/ext/transmodelapi/mapping/TripRequestMapperTest.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/PreferencesMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/preferences/BikePreferencesMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/preferences/ItineraryFilterPreferencesMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/preferences/StreetPreferencesMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/preferences/TransferPreferencesMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/preferences/TransitPreferencesMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/preferences/WalkPreferencesMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/TransportModeSlack.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/StreetModeDurationInputType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
  src/main/java/org/opentripplanner/routing/api/request/preference/StreetPreferences.java
Labels: bug, skip changelog

#5145 Remove San Francisco and vehicle rental fare calculators
  docs/sandbox/Fares.md
  src/ext/java/org/opentripplanner/ext/fares/FaresConfiguration.java
  src/ext/java/org/opentripplanner/ext/fares/impl/SFBayFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/SFBayFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/TimeBasedVehicleRentalFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/TimeBasedVehicleRentalFareServiceFactory.java
Labels: technical debt

#5147 Remove batch query from Transmodel API
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelAPI.java
Labels: technical debt

#5159 Fix nullable absolute direction in GTFS GraphQL API
  src/ext-test/java/org/opentripplanner/ext/legacygraphqlapi/GraphQLIntegrationTest.java
  src/ext-test/resources/legacygraphqlapi/expectations/walk-steps.json
  src/ext-test/resources/legacygraphqlapi/queries/walk-steps.graphql
  src/ext/graphql/transmodelapi/.graphqlconfig
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLstepImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/PathGuidanceType.java
  src/main/java/org/opentripplanner/api/mapping/WalkStepMapper.java
  src/main/java/org/opentripplanner/model/plan/WalkStep.java
  src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
  src/test/java/org/opentripplanner/model/plan/WalkStepTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapperTest.java
  src/test/java/org/opentripplanner/street/search/state/TestStateBuilder.java
Labels: bug, IBI

#5161 Fix error in flex validation
  src/main/java/org/opentripplanner/netex/support/stoptime/AbstractStopTimeAdaptor.java
  src/main/java/org/opentripplanner/netex/validation/ServiceJourneyNonIncreasingPassingTime.java
  src/test/java/org/opentripplanner/netex/mapping/NetexTestDataSample.java
  src/test/java/org/opentripplanner/netex/validation/ServiceJourneyNonIncreasingPassingTimeTest.java
Labels: bug, Entur test, NeTEx

#5162 Check service dates instead of service ids for block id transfers
  src/main/java/org/opentripplanner/graph_builder/module/interlining/InterlineProcessor.java
  src/main/java/org/opentripplanner/gtfs/graphbuilder/GtfsModule.java
  src/main/java/org/opentripplanner/model/calendar/CalendarServiceData.java
  src/test/java/org/opentripplanner/graph_builder/module/interlining/InterlineProcessorTest.java
Labels: improvement, GTFS, Digitransit test

#5168 Improve updater log messages
  src/ext/java/org/opentripplanner/ext/siri/ModifiedTripBuilder.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFeedLoader.java
Labels: improvement, technical debt, Entur test

#5167 Add support for mapping NeTEx operating day in operating period
  src/main/java/org/opentripplanner/netex/mapping/calendar/DayTypeAssignmentMapper.java
  src/test/java/org/opentripplanner/netex/NetexTestDataSupport.java
  src/test/java/org/opentripplanner/netex/mapping/calendar/DayTypeAssignmentMapperTest.java
Labels: new feature, Entur test, NeTEx

#5169 Relax validity check on flex trip with null duration
  src/ext-test/java/org/opentripplanner/ext/flex/FlexPathDurationsTest.java
  src/ext/java/org/opentripplanner/ext/flex/FlexPathDurations.java
  src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/FlexPath.java
Labels: bug, Entur test

#5175 Log unexpected vehicle type in GBFS update
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsStationStatusMapper.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsVehicleRentalDataSource.java
Labels: bug, Entur test, RealTimeUpdate

#5164 Validate to/from in routing request
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/main/java/org/opentripplanner/api/resource/PlannerResource.java
  src/main/java/org/opentripplanner/routing/api/request/RouteRequest.java
  src/main/java/org/opentripplanner/routing/error/RoutingValidationException.java
  src/main/java/org/opentripplanner/routing/service/DefaultRoutingService.java
  src/test/java/org/opentripplanner/routing/core/RouteRequestTest.java
Labels: bug, Entur test

#5165 Changing default value for earlyStartSec
  docs/RouterConfiguration.md
  docs/examples/entur/router-config.json
  docs/sandbox/SiriUpdater.md
  src/ext-test/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandlerTest.java
  src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java
  src/ext/java/org/opentripplanner/ext/siri/SiriHttpUtils.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETHttpTripUpdateSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdaterParameters.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriHelper.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdaterParameters.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java
  src/main/java/org/opentripplanner/framework/time/DurationUtils.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/SiriETUpdaterConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/SiriSXUpdaterConfig.java
  src/test/java/org/opentripplanner/framework/time/DurationUtilsTest.java
  src/test/resources/standalone/config/router-config.json
Labels: Entur test, RealTimeUpdate

#5153 Add GTFS stop sequence to GTFS GraphQL API
  docs/RouterConfiguration.md
  src/ext-test/java/org/opentripplanner/ext/legacygraphqlapi/GraphQLIntegrationTest.java
  src/ext-test/resources/legacygraphqlapi/expectations/patterns.json
  src/ext-test/resources/legacygraphqlapi/expectations/plan-stop-positions.json
  src/ext-test/resources/legacygraphqlapi/queries/patterns.graphql
  src/ext-test/resources/legacygraphqlapi/queries/plan-stop-positions.graphql
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPlaceImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStoptimeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/graphql-codegen.yml
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/model/StopPosition.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/model/TripTimeOnDate.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/ServerConfig.java
  src/test/java/org/opentripplanner/model/TripTimeOnDateTest.java
  src/test/java/org/opentripplanner/transit/model/_data/TransitModelForTest.java
Labels: new feature, IBI

#5182 Reduce log severity for non-optimized transfers
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/OptimizeTransferService.java
Labels: improvement, technical debt, skip changelog

#5184 Improve vehicle rental service directory error handling
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java
  src/ext/java/org/opentripplanner/ext/vehiclerentalservicedirectory/api/VehicleRentalServiceDirectoryFetcherParameters.java
  src/main/java/org/opentripplanner/framework/io/HttpUtils.java
  src/main/java/org/opentripplanner/updater/alert/GtfsRealtimeAlertsUpdater.java
Labels: bug, technical debt, Entur test, skip changelog

#5135 Remove walk leg in a stay seated transfer
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
Labels: bug, Digitransit test

#5186 Rename OSM constanspeed tag mapper and derive it from finland tag mapper
  docs/BuildConfiguration.md
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/ConstantSpeedMapper.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/OsmTagMapperSource.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/OsmTagMapperTest.java
Labels: skip changelog, HSL

#5144 Add elevation profiles to Transmodel API
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/ElevationProfileStepType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/PathGuidanceType.java
  src/main/java/org/opentripplanner/model/plan/ElevationProfile.java
Labels: skip changelog

#5183 Add support for taxi mode
  src/client/images/mode/taxi.png
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/main/java/org/opentripplanner/netex/mapping/TransportModeMapper.java
  src/test/java/org/opentripplanner/netex/mapping/TransportModeMapperTest.java
Labels: improvement, Entur test, NeTEx

#5179 Fix bike triangle in Transmodel API
  src/ext-test/java/org/opentripplanner/ext/legacygraphqlapi/mapping/RouteRequestMapperTest.java
  src/ext-test/java/org/opentripplanner/ext/transmodelapi/mapping/TripRequestMapperTest.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/preferences/BikePreferencesMapper.java
  src/main/java/org/opentripplanner/routing/core/BicycleOptimizeType.java
Labels: bug, sandbox

#5193 Add "language" argument to Quay and StopPlace types in transmodel api and deprecate "lang" argument
  src/ext-test/java/org/opentripplanner/ext/transmodelapi/support/GqlUtilTest.java
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/support/GqlUtil.java
Labels: sandbox, skip changelog

#5166 Bug fixes in stop area relation processing
  docs/StopAreas.md
  mkdocs.yml
  src/main/java/org/opentripplanner/graph_builder/issues/PublicTransportRelationSkipped.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmDatabase.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilderTest.java
  src/test/resources/org/opentripplanner/graph_builder/module/osm/stopareas.pbf
Labels: bug, improvement

#5191 Allow underscores in GTFS feed IDs
  src/main/java/org/opentripplanner/graph_builder/module/GtfsFeedId.java
  src/main/java/org/opentripplanner/gtfs/graphbuilder/GtfsBundle.java
  src/main/java/org/opentripplanner/gtfs/graphbuilder/GtfsFeedParameters.java
  src/test/java/org/opentripplanner/graph_builder/module/FakeGraph.java
  src/test/java/org/opentripplanner/graph_builder/module/GtfsFeedIdTest.java
  src/test/java/org/opentripplanner/graph_builder/module/linking/LinkingTest.java
  src/test/java/org/opentripplanner/gtfs/GtfsContextBuilder.java
  src/test/resources/org/opentripplanner/graph_builder/module/addTransitMultipleLines.gtfs.zip
Labels: GTFS, technical debt, IBI

#5189 Allow timeout exception to propagate to Transmodel GraphQL error handling
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLUtils.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/support/OtpExecutionResult.java
  src/main/java/org/opentripplanner/astar/AStar.java
  src/main/java/org/opentripplanner/framework/application/OTPRequestTimeoutException.java
  src/main/java/org/opentripplanner/framework/time/TimeUtils.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/AccessEgressRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectFlexRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectStreetRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/FlexAccessEgressRouter.java
  src/main/java/org/opentripplanner/routing/api/response/RoutingErrorCode.java
  src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
  src/main/java/org/opentripplanner/routing/service/DefaultRoutingService.java
  src/main/resources/logback.xml
Labels: bug, Entur test, skip changelog

#5209 Area vertex linking improvements
  src/main/java/org/opentripplanner/routing/linking/VertexLinker.java
  src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
  src/test/java/org/opentripplanner/graph_builder/linking/LinkStopToPlatformTest.java
Labels: bug, improvement, optimization

#4922 Allow multiple FlexibleAreas in a FlexibleStopPlace
  pom.xml
  src/main/java/org/opentripplanner/netex/mapping/FlexStopsMapper.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/transit/model/site/RegularStop.java
  src/test/java/org/opentripplanner/netex/mapping/FlexStopsMapperTest.java
Labels: bug, improvement, Entur test

#5207 Preemptively make a GraphQL FareProduct an interface
  src/ext-test/java/org/opentripplanner/ext/fares/impl/AtlantaFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
  src/ext-test/resources/legacygraphqlapi/expectations/plan-fares.json
  src/ext-test/resources/legacygraphqlapi/expectations/plan.json
  src/ext-test/resources/legacygraphqlapi/queries/plan-fares.graphql
  src/ext-test/resources/legacygraphqlapi/queries/plan.graphql
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLDefaultFareProductImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLFareProductTypeResolver.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/model/fare/FareProduct.java
  src/main/java/org/opentripplanner/model/fare/ItineraryFares.java
  src/main/java/org/opentripplanner/routing/core/FareComponent.java
  src/main/java/org/opentripplanner/routing/core/FareType.java
Labels: improvement, IBI

#5212 Prevent NPE in vehicle position matching
  pom.xml
  src/main/java/org/opentripplanner/model/Timetable.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/updater/vehicle_position/VehiclePositionPatternMatcher.java
  src/test/java/org/opentripplanner/updater/vehicle_position/VehiclePositionsMatcherTest.java
Labels: bug, IBI, RealTimeUpdate

#5205 Empty stop_headsign will fall back to trip_headsign
  src/main/java/org/opentripplanner/transit/model/timetable/TripTimes.java
  src/test/java/org/opentripplanner/transit/model/timetable/TripTimesTest.java
Labels: bug, GTFS
