Repository opentripplanner/OpenTripPlanner, pull requests merged in 2023-11, with the labels that each got.

#5450 Create the NumItinerariesFilter and the associated NumItinerariesFilterResults to limit itineraries based on the numItineraries parameter.
  src/main/java/org/opentripplanner/model/plan/SortOrder.java
  src/main/java/org/opentripplanner/model/plan/pagecursor/PageCursorFactory.java
  src/main/java/org/opentripplanner/model/plan/pagecursor/PageCursorFactoryParameters.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ListSection.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/MaxLimitFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/NumItinerariesFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/NumItinerariesFilterResults.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RouteRequestToFilterChainMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RoutingResponseMapper.java
  src/main/java/org/opentripplanner/routing/api/request/RouteRequest.java
  src/test/java/org/opentripplanner/model/plan/pagecursor/PageCursorFactoryTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/MaxLimitFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/NumItinerariesFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/RoutingResponseMapperTest.java
Labels: improvement, skip changelog

#5475 Add logging of siri errors to SiriAzureETUpdater
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdaterParameters.java
  src/main/java/org/opentripplanner/updater/spi/ResultLogger.java
Labels: sandbox, skip changelog

#5278 Calculate CO₂ emissions of itineraries
  doc-templates/Emissions.md
  docs/BuildConfiguration.md
  docs/Configuration.md
  docs/sandbox/Emissions.md
  src/ext-test/java/org/opentripplanner/ext/emissions/Co2EmissionsDataReaderTest.java
  src/ext-test/java/org/opentripplanner/ext/emissions/EmissionsTest.java
  src/ext-test/java/org/opentripplanner/ext/transmodelapi/mapping/TripRequestMapperTest.java
  src/ext-test/resources/org/opentripplanner/ext/emissions/emissions-invalid-test-gtfs/emissions.txt
  src/ext-test/resources/org/opentripplanner/ext/emissions/emissions-invalid-test-gtfs/feed_info.txt
  src/ext-test/resources/org/opentripplanner/ext/emissions/emissions-test-gtfs.zip
  src/ext-test/resources/org/opentripplanner/ext/emissions/emissions-test-gtfs/emissions.txt
  src/ext-test/resources/org/opentripplanner/ext/emissions/emissions-test-gtfs/feed_info.txt
  src/ext/java/org/opentripplanner/ext/emissions/Co2EmissionsDataReader.java
  src/ext/java/org/opentripplanner/ext/emissions/DefaultEmissionsService.java
  src/ext/java/org/opentripplanner/ext/emissions/EmissionsConfig.java
  src/ext/java/org/opentripplanner/ext/emissions/EmissionsDataModel.java
  src/ext/java/org/opentripplanner/ext/emissions/EmissionsFilter.java
  src/ext/java/org/opentripplanner/ext/emissions/EmissionsModule.java
  src/ext/java/org/opentripplanner/ext/emissions/EmissionsService.java
  src/ext/java/org/opentripplanner/ext/emissions/EmissionsServiceModule.java
  src/main/java/org/opentripplanner/api/mapping/ItineraryMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/GraphQLScalars.java
  src/main/java/org/opentripplanner/apis/gtfs/GtfsGraphQLIndex.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/ItineraryImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/graphql-codegen.yml
  src/main/java/org/opentripplanner/framework/application/OTPFeature.java
  src/main/java/org/opentripplanner/framework/model/Grams.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderFactory.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  src/main/java/org/opentripplanner/model/plan/Emissions.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RouteRequestToFilterChainMapper.java
  src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
  src/main/java/org/opentripplanner/standalone/OTPMain.java
  src/main/java/org/opentripplanner/standalone/api/OtpServerRequestContext.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationFactory.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationModule.java
  src/main/java/org/opentripplanner/standalone/configure/LoadApplication.java
  src/main/java/org/opentripplanner/standalone/configure/LoadApplicationFactory.java
  src/main/java/org/opentripplanner/standalone/server/DefaultServerRequestContext.java
  src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
  src/test/java/org/opentripplanner/TestServerContext.java
  src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
  src/test/java/org/opentripplanner/generate/doc/BuildConfigurationDocTest.java
  src/test/java/org/opentripplanner/generate/doc/EmissionsConfigurationDocTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainTest.java
  src/test/java/org/opentripplanner/routing/graph/GraphSerializationTest.java
  src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/plan-extended.json
  src/test/resources/org/opentripplanner/apis/gtfs/queries/plan-extended.graphql
  src/test/resources/standalone/config/build-config.json
Labels: new feature, sandbox, bump serialization id

#5469 Orca Fixes Part 2
  src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
  src/main/java/org/opentripplanner/transit/model/basic/Money.java
  src/test/java/org/opentripplanner/routing/core/MoneyTest.java
Labels: sandbox, IBI, skip changelog

#5466 Update NeTEx Java Model 2.0.15
  pom.xml
  src/main/java/org/opentripplanner/netex/loader/parser/ServiceCalendarFrameParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/ServiceFrameParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/SiteFrameParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/TimeTableFrameParser.java
  src/main/java/org/opentripplanner/netex/mapping/GroupOfStationsMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopAndStationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopPlaceTypeMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TransportModeMapper.java
  src/main/java/org/opentripplanner/netex/mapping/calendar/DayTypeAssignmentMapper.java
  src/main/java/org/opentripplanner/netex/support/JAXBUtils.java
  src/test/java/org/opentripplanner/netex/NetexTestDataSupport.java
  src/test/java/org/opentripplanner/netex/loader/parser/ServiceCalendarFrameParserTest.java
  src/test/java/org/opentripplanner/netex/loader/parser/SiteFrameParserTest.java
  src/test/java/org/opentripplanner/netex/mapping/RouteMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/StationMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/StopAndStationMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/StopPlaceTypeMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/TransportModeMapperTest.java
Labels: Entur test

#5421 Migrate to Java 21
  .github/workflows/cibuild.yml
  .github/workflows/performance-test.yml
  docs/Basic-Tutorial.md
  docs/Getting-OTP.md
  docs/Version-Comparison.md
  pom.xml
Labels: improvement

#5468 Add Roadmap setup docs
  docs/Roadmap.md
  docs/images/roadmap-1.png
  docs/images/roadmap-2.png
  docs/images/roadmap-3.png
  docs/images/roadmap-4.png
  docs/images/roadmap-5.png
  docs/images/roadmap-6.png
  docs/images/roadmap-7.png
  mkdocs.yml
Labels: documentation, Roadmap

#5462 Convert stateful predicate `distinctByKey` into a list method
  src/ext/java/org/opentripplanner/ext/geocoder/LuceneIndex.java
  src/ext/java/org/opentripplanner/ext/geocoder/StopClusterMapper.java
  src/main/java/org/opentripplanner/framework/collection/ListUtils.java
  src/main/java/org/opentripplanner/framework/lang/PredicateUtils.java
  src/main/java/org/opentripplanner/routing/graphfinder/StopFinderTraverseVisitor.java
  src/test/java/org/opentripplanner/framework/collection/ListUtilsTest.java
  src/test/java/org/opentripplanner/framework/lang/PredicateUtilsTest.java
Labels: technical debt, skip changelog

#5484 Improve graph builder start up
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/service/worldenvelope/model/WorldEnvelopeBuilder.java
  src/test/java/org/opentripplanner/graph_builder/module/geometry/CalculateWorldEnvelopeModuleTest.java
Labels: improvement, technical debt, skip changelog

#5489 Add support for park and ride itineraries when calculating CO2 emissions
  src/ext-test/java/org/opentripplanner/ext/emissions/EmissionsTest.java
  src/ext/java/org/opentripplanner/ext/emissions/EmissionsFilter.java
Labels: sandbox, skip changelog

#5348 Interpolate increasing stop times for GTFS-RT cancelled trips
  src/main/java/org/opentripplanner/model/Timetable.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripTimes.java
  src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
  src/test/java/org/opentripplanner/model/TimetableSnapshotTest.java
  src/test/java/org/opentripplanner/model/TimetableTest.java
  src/test/java/org/opentripplanner/transit/model/timetable/TripTimesTest.java
  src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java
  src/test/java/org/opentripplanner/updater/trip/TripUpdateBuilder.java
Labels: RealTimeUpdate

#5433 Remove itineraries outside the search window in arriveBy search
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/OutsideSearchWindowFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RouteRequestToFilterChainMapper.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/OutsideSearchWindowFilterTest.java
Labels: bug

#5492 Expose `numberOfTransfers` in GTFS GraphQL API
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/ItineraryImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
  src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/plan-extended.json
  src/test/resources/org/opentripplanner/apis/gtfs/queries/plan-extended.graphql
Labels: improvement, skip changelog

#5504 Allow early creation of StopModelBuilder
  src/main/java/org/opentripplanner/transit/service/StopModel.java
  src/main/java/org/opentripplanner/transit/service/StopModelBuilder.java
  src/test/java/org/opentripplanner/routing/graph/GraphSerializationTest.java
Labels: bug, bump serialization id, skip changelog

#5502 Make `feedId` required for realtime updaters
  docs/BuildConfiguration.md
  docs/RouterConfiguration.md
  docs/UpdaterConfig.md
  docs/sandbox/VehicleParking.md
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/GtfsRealtimeAlertsUpdaterConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/MqttGtfsRealtimeUpdaterConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/PollingTripUpdaterConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/VehicleParkingUpdaterConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/WebsocketGtfsRealtimeUpdaterConfig.java
  src/test/resources/standalone/config/build-config.json
  src/test/resources/standalone/config/router-config.json
Labels: bug

#5508 Fix serialization of `AtomicInteger`
  src/main/java/org/opentripplanner/routing/graph/kryosupport/AtomicIntegerSerializer.java
  src/main/java/org/opentripplanner/routing/graph/kryosupport/KryoBuilder.java
Labels: bug, bump serialization id

#5503 Improve linking of fixed stops used by flex trips
  src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  src/main/java/org/opentripplanner/graph_builder/module/StreetLinkerModule.java
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/routing/graph/index/StreetIndex.java
  src/main/java/org/opentripplanner/street/model/vertex/StreetVertex.java
  src/main/java/org/opentripplanner/street/model/vertex/TransitStopVertex.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/_support/geometry/Coordinates.java
  src/test/java/org/opentripplanner/graph_builder/module/StreetLinkerModuleTest.java
  src/test/java/org/opentripplanner/graph_builder/module/TestStreetLinkerModule.java
  src/test/java/org/opentripplanner/graph_builder/module/VehicleParkingLinkingTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/UnconnectedAreasTest.java
  src/test/java/org/opentripplanner/routing/TestHalfEdges.java
  src/test/java/org/opentripplanner/routing/algorithm/StreetModeLinkingTest.java
  src/test/java/org/opentripplanner/routing/linking/LinkStopToPlatformTest.java
  src/test/java/org/opentripplanner/routing/vehicle_parking/VehicleParkingTestGraphData.java
  src/test/java/org/opentripplanner/routing/vehicle_parking/VehicleParkingTestUtil.java
  src/test/java/org/opentripplanner/street/model/_data/StreetModelForTest.java
  src/test/java/org/opentripplanner/transit/model/_data/TransitModelForTest.java
Labels: bug

#5511 Fix transfer of zoneId in `ScheduledTransitLegBuilder`
  src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
  src/main/java/org/opentripplanner/model/plan/ScheduledTransitLegBuilder.java
  src/test/java/org/opentripplanner/model/plan/ScheduledTransitLegBuilderTest.java
Labels: bug, skip changelog

#5436 Keep min transfer filter is not local to group-by-filters
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/SystemNoticeType.java
  src/main/java/org/opentripplanner/api/mapping/SystemNoticeMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/SystemNoticeImpl.java
  src/main/java/org/opentripplanner/framework/collection/CollectionUtils.java
  src/main/java/org/opentripplanner/model/SystemNotice.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/RoutingErrorsAttacher.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filter/RemoveDeletionFlagForLeastTransfersItinerary.java
  src/test/java/org/opentripplanner/framework/collection/CollectionUtilsTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/DeleteResultHandlerTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filter/GroupByFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/ElevationSnapshotTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/ElevationSnapshotTest.snap
Labels: bug, Entur

#5458 Add paging deduplication when cropping.
  src/main/java/org/opentripplanner/model/plan/pagecursor/ItineraryPageCut.java
  src/main/java/org/opentripplanner/model/plan/pagecursor/PageCursor.java
  src/main/java/org/opentripplanner/model/plan/pagecursor/PageCursorFactory.java
  src/main/java/org/opentripplanner/model/plan/pagecursor/PageCursorFactoryParameters.java
  src/main/java/org/opentripplanner/model/plan/pagecursor/PageCursorSerializer.java
  src/main/java/org/opentripplanner/model/plan/pagecursor/PagingDeduplicationSection.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/NumItinerariesFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/NumItinerariesFilterResults.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/PagingDuplicateFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RouteRequestToFilterChainMapper.java
  src/test/java/org/opentripplanner/model/plan/pagecursor/PageCursorFactoryTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/DeleteResultHandlerTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/PagingDuplicateFilterTest.java
Labels: bug, improvement

#5517 Fix flex egress stop index
  src/ext-test/java/org/opentripplanner/ext/flex/trip/UnscheduledTripTest.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexEgressTemplate.java
  src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
Labels: bug, Entur test, skip changelog

#5518 Check transport mode when mapping GroupStops
  src/main/java/org/opentripplanner/netex/mapping/FlexStopsMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TransportModeMapper.java
  src/test/java/org/opentripplanner/netex/mapping/FlexStopsMapperTest.java
Labels: improvement, NeTEx

#5522 Fix small bug in time-travel logging
  src/main/java/org/opentripplanner/raptor/rangeraptor/standard/MinTravelDurationRoutingStrategy.java
Labels: bug, skip changelog

#5519 Code cleanup paging filter
  src/main/java/org/opentripplanner/framework/tostring/MultiLineToStringBuilder.java
  src/main/java/org/opentripplanner/framework/tostring/ToStringBuilder.java
  src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
  src/main/java/org/opentripplanner/model/plan/StreetLeg.java
  src/main/java/org/opentripplanner/model/plan/pagecursor/PageCursor.java
  src/main/java/org/opentripplanner/model/plan/pagecursor/PageCursorFactory.java
  src/main/java/org/opentripplanner/model/plan/pagecursor/PageCursorInput.java
  src/main/java/org/opentripplanner/raptor/RaptorService.java
  src/main/java/org/opentripplanner/raptor/api/model/RaptorAccessEgress.java
  src/main/java/org/opentripplanner/raptor/api/request/SearchParams.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/NumItinerariesFilterResults.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/PagingFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RoutingResponseMapper.java
  src/main/java/org/opentripplanner/routing/api/request/RouteRequest.java
  src/main/java/org/opentripplanner/routing/service/DefaultRoutingService.java
  src/main/resources/logback.xml
  src/test/java/org/opentripplanner/framework/tostring/MultiLineToStringBuilderTest.java
  src/test/java/org/opentripplanner/model/plan/pagecursor/PageCursorFactoryTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/PagingFilterTest.java
Labels: technical debt, skip changelog

#5437 Cleanup trip times - Part A
  src/ext-test/java/org/opentripplanner/ext/emissions/EmissionsTest.java
  src/ext-test/java/org/opentripplanner/ext/realtimeresolver/RealtimeResolverTest.java
  src/ext-test/java/org/opentripplanner/ext/siri/ModifiedTripBuilderTest.java
  src/ext-test/java/org/opentripplanner/ext/siri/TimetableHelperTest.java
  src/ext/java/org/opentripplanner/ext/siri/AddedTripBuilder.java
  src/ext/java/org/opentripplanner/ext/siri/ModifiedTripBuilder.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/main/java/org/opentripplanner/framework/lang/IntUtils.java
  src/main/java/org/opentripplanner/graph_builder/module/TimeZoneAdjusterModule.java
  src/main/java/org/opentripplanner/gtfs/GenerateTripPatternsOperation.java
  src/main/java/org/opentripplanner/model/Timetable.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
  src/main/java/org/opentripplanner/transit/model/framework/Deduplicator.java
  src/main/java/org/opentripplanner/transit/model/framework/DeduplicatorNoop.java
  src/main/java/org/opentripplanner/transit/model/framework/DeduplicatorService.java
  src/main/java/org/opentripplanner/transit/model/timetable/ScheduledTripTimes.java
  src/main/java/org/opentripplanner/transit/model/timetable/ScheduledTripTimesBuilder.java
  src/main/java/org/opentripplanner/transit/model/timetable/StopTimeToScheduledTripTimesMapper.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripTimes.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripTimesFactory.java
  src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
  src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
  src/test/java/org/opentripplanner/gtfs/interlining/InterlineProcessorTest.java
  src/test/java/org/opentripplanner/model/TripTimeOnDateTest.java
  src/test/java/org/opentripplanner/model/impl/OtpTransitServiceBuilderLimitPeriodTest.java
  src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
  src/test/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReferenceTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TripPatternForDateTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TripPatternForDateMapperTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreatorTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RouteRequestTransitDataProviderFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TestRouteData.java
  src/test/java/org/opentripplanner/routing/trippattern/FrequencyEntryTest.java
  src/test/java/org/opentripplanner/transit/model/timetable/TripTimesTest.java
  src/test/java/org/opentripplanner/updater/vehicle_position/RealtimeVehicleMatcherTest.java
Labels: technical debt, bump serialization id

#5516 Transfer cost limit
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/Transfer.java
  src/test/java/org/opentripplanner/_support/geometry/Coordinates.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TransferTest.java
Labels: bug, IBI

#5520 Fix missed trip when arrive-by search-window is off by one minute
  src/main/java/org/opentripplanner/raptor/rangeraptor/transit/RaptorSearchWindowCalculator.java
  src/test/java/org/opentripplanner/raptor/rangeraptor/transit/RaptorSearchWindowCalculatorTest.java
Labels: bug, Entur test

#5515 Token serializer for paging and Leg.ID
  src/main/java/org/opentripplanner/framework/lang/ObjectUtils.java
  src/main/java/org/opentripplanner/framework/token/Deserializer.java
  src/main/java/org/opentripplanner/framework/token/FieldDefinition.java
  src/main/java/org/opentripplanner/framework/token/Serializer.java
  src/main/java/org/opentripplanner/framework/token/Token.java
  src/main/java/org/opentripplanner/framework/token/TokenBuilder.java
  src/main/java/org/opentripplanner/framework/token/TokenDefinition.java
  src/main/java/org/opentripplanner/framework/token/TokenDefinitionBuilder.java
  src/main/java/org/opentripplanner/framework/token/TokenSchema.java
  src/main/java/org/opentripplanner/framework/token/TokenType.java
  src/main/java/org/opentripplanner/framework/token/package.md
  src/test/java/org/opentripplanner/framework/lang/ObjectUtilsTest.java
  src/test/java/org/opentripplanner/framework/token/AdvancedTokenSchemaTest.java
  src/test/java/org/opentripplanner/framework/token/TokenSchemaConstants.java
  src/test/java/org/opentripplanner/framework/token/TokenSchemaTest.java
Labels: improvement, skip changelog

#5529 Use American English [ci skip]
  CODE_CONVENTIONS.md
Labels: documentation, skip changelog

#5523 Remove `matchBusRoutesToStreets`
  docs/BuildConfiguration.md
  docs/examples/entur/build-config.json
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderFactory.java
  src/main/java/org/opentripplanner/graph_builder/module/map/BusRouteStreetMatcher.java
  src/main/java/org/opentripplanner/graph_builder/module/map/EndMatchState.java
  src/main/java/org/opentripplanner/graph_builder/module/map/LinearIterator.java
  src/main/java/org/opentripplanner/graph_builder/module/map/MatchState.java
  src/main/java/org/opentripplanner/graph_builder/module/map/MidblockMatchState.java
  src/main/java/org/opentripplanner/graph_builder/module/map/StreetMatcher.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/main/java/org/opentripplanner/transit/model/network/TripPattern.java
  src/test/java/org/opentripplanner/graph_builder/module/map/StreetMatcherTest.java
  test/performance/norway/build-config.json
Labels: technical debt
