Repository opentripplanner/OpenTripPlanner, pull requests merged in 2023-10, with the labels that each got.

#5320 Transmodel GraphQL API for pass-through searches
  src/ext-test/java/org/opentripplanner/ext/transmodelapi/mapping/TripRequestMapperTest.java
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/PassThroughLocationMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/TransitIdMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/TripRequestMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/PassThroughPointInputType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/ViaLocationInputType.java
  src/main/java/org/opentripplanner/raptor/api/request/PassThroughPoint.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RaptorRequestMapper.java
  src/main/java/org/opentripplanner/routing/api/request/PassThroughPoint.java
  src/main/java/org/opentripplanner/routing/api/request/RouteRequest.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/TransitService.java
  src/test/java/org/opentripplanner/raptor/api/request/PassThroughPointTest.java
  src/test/java/org/opentripplanner/raptor/api/request/PassThroughPointsTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/J01_PassThroughTest.java
  src/test/java/org/opentripplanner/raptor/rangeraptor/multicriteria/passthrough/BitSetPassThroughPointsServiceTest.java
Labels: sandbox

#5394 Log Java version info at startup
  src/main/java/org/opentripplanner/standalone/OtpStartupInfo.java
Labels: improvement, skip changelog

#5323 Fix flex access itinerary mapping
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapperTest.java
Labels: bug, Entur test, skip changelog

#5389 Don't crash interline processing if no service data
  src/main/java/org/opentripplanner/graph_builder/module/interlining/InterlineProcessor.java
  src/main/java/org/opentripplanner/model/calendar/CalendarServiceData.java
Labels: skip changelog

#5397 Fix IBI fare calculators
  src/ext-test/java/org/opentripplanner/ext/fares/FaresFilterTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/AtlantaFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/HSLFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/FaresToItineraryMapper.java
  src/ext/java/org/opentripplanner/ext/fares/impl/AtlantaFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/HSLFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/HSLFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
  src/main/java/org/opentripplanner/model/fare/ItineraryFares.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/ElevationSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
Labels: bug, IBI, skip changelog

#5379 Fix check for OSM relation members not being present in the extract
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmDatabase.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OsmDatabaseTest.java
  src/test/java/org/opentripplanner/openstreetmap/model/BicycleNetworkRelationsTest.java
  src/test/resources/org/opentripplanner/graph_builder/module/osm/brenner-invalid-relation-reference.osm.pbf
  src/test/resources/org/opentripplanner/graph_builder/module/osm/ehningen-minimal.osm.pbf
Labels: bug

#5409 Update service bus dependencies
  pom.xml
Labels: skip changelog

#5293 Add a configurable limit for the search window
  docs/RouterConfiguration.md
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TransitTuningParameters.java
  src/main/java/org/opentripplanner/routing/api/request/RouteRequest.java
  src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/TransitRoutingConfig.java
  src/test/java/org/opentripplanner/routing/core/RouteRequestTest.java
  src/test/java/org/opentripplanner/standalone/config/RouterConfigDocTest.java
  src/test/java/org/opentripplanner/standalone/config/RouterConfigTest.java
Labels: improvement, config change

#5416 Update ORCA model fares October 2023
  src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFaresData.java
Labels: sandbox, skip changelog

#5419 Make Money serializable
  src/main/java/org/opentripplanner/transit/model/basic/Money.java
  src/test/java/org/opentripplanner/routing/core/MoneyTest.java
Labels: bug, bump serialization id, skip changelog

#5408 Fix fare calculation for combined interlined legs
  src/ext-test/java/org/opentripplanner/ext/fares/impl/CombinedInterlinedLegsFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/impl/CombinedInterlinedTransitLeg.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareService.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
Labels: bug, sandbox, IBI

#5420 Fix board slack list mapping in Transmodel API
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/preferences/TransitPreferencesMapper.java
Labels: bug, Regression

#5417 Fix flexible quay querying in Transmodel API
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
Labels: bug

#5415 Fix Transmodel GraphQL query with empty quay id
  src/main/java/org/opentripplanner/transit/service/StopModel.java
  src/test/java/org/opentripplanner/transit/service/StopModelTest.java
Labels: improvement, skip changelog

#5407 Add validation for scheduled transit leg reference
  src/main/java/org/opentripplanner/model/plan/legreference/LegReference.java
  src/main/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReference.java
  src/test/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReferenceTest.java
Labels: bug, skip changelog

#5426 Fix ORCA cross-agency fares
  src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
Labels: bug, sandbox, IBI, skip changelog

#5414 Fix stop times helper when requesting zero departure
  src/main/java/org/opentripplanner/routing/stoptimes/StopTimesHelper.java
  src/test/java/org/opentripplanner/routing/stoptimes/StopTimesHelperTest.java
Labels: improvement, skip changelog

#5403 Add validation for missing calls in SIRI update
  src/ext-test/java/org/opentripplanner/ext/siri/AddedTripBuilderTest.java
  src/ext/java/org/opentripplanner/ext/siri/AddedTripBuilder.java
Labels: bug, Entur test, RealTimeUpdate

#5372 Import Occupancy Status from GTFS-RT Vehicle Positions
  docs/RouterConfiguration.md
  docs/UpdaterConfig.md
  src/ext-test/java/org/opentripplanner/ext/transmodelapi/mapping/TripRequestMapperTest.java
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/siri/mapper/OccupancyMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/OccupancyStatusMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
  src/main/java/org/opentripplanner/apis/gtfs/GraphQLRequestContext.java
  src/main/java/org/opentripplanner/apis/gtfs/GtfsGraphQLIndex.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/PatternImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/StopRelationshipImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/TripImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/TripOccupancyImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/VehiclePositionImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLTypes.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/graphql-codegen.yml
  src/main/java/org/opentripplanner/apis/gtfs/model/TripOccupancy.java
  src/main/java/org/opentripplanner/service/realtimevehicles/RealtimeVehicleRepository.java
  src/main/java/org/opentripplanner/service/realtimevehicles/RealtimeVehicleService.java
  src/main/java/org/opentripplanner/service/realtimevehicles/configure/RealtimeVehicleRepositoryModule.java
  src/main/java/org/opentripplanner/service/realtimevehicles/configure/RealtimeVehicleServiceModule.java
  src/main/java/org/opentripplanner/service/realtimevehicles/internal/DefaultRealtimeVehicleService.java
  src/main/java/org/opentripplanner/service/realtimevehicles/model/RealtimeVehicle.java
  src/main/java/org/opentripplanner/service/realtimevehicles/model/RealtimeVehicleBuilder.java
  src/main/java/org/opentripplanner/service/vehiclepositions/VehiclePositionRepository.java
  src/main/java/org/opentripplanner/service/vehiclepositions/VehiclePositionService.java
  src/main/java/org/opentripplanner/service/vehiclepositions/configure/VehiclePositionsRepositoryModule.java
  src/main/java/org/opentripplanner/service/vehiclepositions/configure/VehiclePositionsServiceModule.java
  src/main/java/org/opentripplanner/service/vehiclepositions/internal/DefaultVehiclePositionService.java
  src/main/java/org/opentripplanner/service/vehiclepositions/model/RealtimeVehiclePosition.java
  src/main/java/org/opentripplanner/service/vehiclepositions/model/RealtimeVehiclePositionBuilder.java
  src/main/java/org/opentripplanner/standalone/api/OtpServerRequestContext.java
  src/main/java/org/opentripplanner/standalone/config/framework/json/OtpVersion.java
  src/main/java/org/opentripplanner/standalone/config/framework/json/ParameterBuilder.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/VehiclePositionsUpdaterConfig.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationFactory.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationModule.java
  src/main/java/org/opentripplanner/standalone/server/DefaultServerRequestContext.java
  src/main/java/org/opentripplanner/transit/model/timetable/OccupancyStatus.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripTimes.java
  src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
  src/main/java/org/opentripplanner/updater/vehicle_position/PollingVehiclePositionUpdater.java
  src/main/java/org/opentripplanner/updater/vehicle_position/RealtimeVehiclePatternMatcher.java
  src/main/java/org/opentripplanner/updater/vehicle_position/VehiclePositionUpdaterRunnable.java
  src/main/java/org/opentripplanner/updater/vehicle_position/VehiclePositionsUpdaterParameters.java
  src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
  src/test/java/org/opentripplanner/TestServerContext.java
  src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
  src/test/java/org/opentripplanner/apis/gtfs/mapping/RouteRequestMapperTest.java
  src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
  src/test/java/org/opentripplanner/updater/vehicle_position/RealtimeVehicleMatcherTest.java
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/patterns.json
  src/test/resources/org/opentripplanner/apis/gtfs/queries/patterns.graphql
  src/test/resources/standalone/config/router-config.json
Labels: RealTimeUpdate

#5401 Improve geocoding fuzziness, remove street corners
  docs/sandbox/GeocoderAPI.md
  src/ext-test/java/org/opentripplanner/ext/geocoder/EnglishNgramAnalyzerTest.java
  src/ext-test/java/org/opentripplanner/ext/geocoder/LuceneIndexTest.java
  src/ext/java/org/opentripplanner/ext/geocoder/EnglishNGramAnalyzer.java
  src/ext/java/org/opentripplanner/ext/geocoder/GeocoderResource.java
  src/ext/java/org/opentripplanner/ext/geocoder/LuceneIndex.java
  src/ext/java/org/opentripplanner/ext/geocoder/StopClusterMapper.java
  src/main/java/org/opentripplanner/framework/geometry/WgsCoordinate.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
  src/test/java/org/opentripplanner/framework/geometry/WgsCoordinateTest.java
Labels: improvement, sandbox, IBI, skip changelog

#5376 Allow multiple zones in an unscheduled flex trip
  src/ext-test/java/org/opentripplanner/ext/flex/GtfsFlexTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/trip/UnscheduledTripTest.java
  src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
  src/ext/java/org/opentripplanner/ext/flex/README.md
  src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessEgressTemplate.java
  src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
  src/main/java/org/opentripplanner/model/StopTime.java
Labels: improvement

#5445 Fix type in Roadmap epic template
  .github/ISSUE_TEMPLATE/roadmap_epic.md
Labels: documentation, skip changelog

#5428 Filter out null, empty and blank elements when mapping feed-scoped ids
  src/ext-test/java/org/opentripplanner/ext/transmodelapi/mapping/TransitIdMapperTest.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/FilterMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/SelectRequestMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/TransitIdMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/TripRequestMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/JourneyWhiteListed.java
Labels: improvement, Entur test

#5440 Validate stop id in Transit leg reference
  src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
  src/main/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializer.java
  src/main/java/org/opentripplanner/model/plan/legreference/LegReferenceType.java
  src/main/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReference.java
  src/test/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializerTest.java
  src/test/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReferenceTest.java
  src/test/java/org/opentripplanner/routing/stoptimes/AlternativeLegsTest.java
Labels: improvement

#5449 Clean up fare attribute, remove non-standard senior and youth prices
  src/ext-test/java/org/opentripplanner/ext/fares/impl/FareModelForTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/HSLFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/HSLFareService.java
  src/ext/java/org/opentripplanner/ext/fares/model/FareAttribute.java
  src/ext/java/org/opentripplanner/ext/fares/model/FareAttributeBuilder.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/TicketTypeImpl.java
  src/main/java/org/opentripplanner/gtfs/mapping/FareAttributeMapper.java
  src/test/java/org/opentripplanner/gtfs/mapping/FareAttributeMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/FareRuleMapperTest.java
Labels: sandbox, technical debt, IBI, bump serialization id, skip changelog

#5425 Add available types and spaces to `VehicleRentalStation`
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/VehicleRentalStationImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/graphql-codegen.yml
  src/main/java/org/opentripplanner/service/vehiclerental/model/RentalVehicleEntityCounts.java
  src/main/java/org/opentripplanner/service/vehiclerental/model/RentalVehicleTypeCount.java
  src/main/java/org/opentripplanner/service/vehiclerental/model/VehicleRentalStation.java
  src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
  src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
  src/test/java/org/opentripplanner/service/vehiclerental/internal/DefaultVehicleRentalServiceTest.java
  src/test/java/org/opentripplanner/service/vehiclerental/model/TestVehicleRentalStationBuilder.java
  src/test/java/org/opentripplanner/street/search/state/TestStateBuilder.java
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/vehicle-rental-station.json
  src/test/resources/org/opentripplanner/apis/gtfs/queries/vehicle-rental-station.graphql
Labels: improvement

#5411 Make vehicleRentalStation query optionally accept id without feed
  docs/Configuration.md
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/QueryTypeImpl.java
  src/main/java/org/opentripplanner/framework/application/OTPFeature.java
Labels: Vehicle rental

#5457 Add stricter validation for flex areas
  src/main/java/org/opentripplanner/netex/mapping/FlexStopsMapper.java
  src/main/java/org/opentripplanner/netex/mapping/OpenGisMapper.java
  src/test/java/org/opentripplanner/netex/mapping/FlexStopsMapperTest.java
Labels: improvement

#5439 Remove HTTPS handling and its documentation
  docs/Basic-Tutorial.md
  docs/Security.md
  mkdocs.yml
  src/main/java/org/opentripplanner/standalone/config/CommandLineParameters.java
  src/main/java/org/opentripplanner/standalone/server/GrizzlyServer.java
  src/test/java/org/opentripplanner/standalone/config/CommandLineParametersTest.java
Labels: technical debt

#5455 Add support for DSJ in transit leg reference
  src/ext/java/org/opentripplanner/ext/realtimeresolver/RealtimeResolver.java
  src/main/java/org/opentripplanner/model/plan/FrequencyTransitLeg.java
  src/main/java/org/opentripplanner/model/plan/FrequencyTransitLegBuilder.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
  src/main/java/org/opentripplanner/model/plan/ScheduledTransitLegBuilder.java
  src/main/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializer.java
  src/main/java/org/opentripplanner/model/plan/legreference/LegReferenceType.java
  src/main/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReference.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/alternativelegs/AlternativeLegs.java
  src/test/java/org/opentripplanner/model/plan/ScheduledTransitLegTest.java
  src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
  src/test/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializerTest.java
  src/test/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReferenceTest.java
  src/test/java/org/opentripplanner/routing/stoptimes/AlternativeLegsTest.java
Labels: improvement

#5454 Remove redundant Link fares
  src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFaresData.java
Labels: sandbox, skip changelog

#5443 Ignore negative travel-times in Raptor
  src/main/java/org/opentripplanner/raptor/rangeraptor/standard/ArrivalTimeRoutingStrategy.java
  src/main/java/org/opentripplanner/raptor/rangeraptor/standard/MinTravelDurationRoutingStrategy.java
Labels: improvement, technical debt, Entur test

#5446 Fix sort order bug in optimized transfers
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/Transfer.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/costfilter/MinCostPathTailFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/passthrough/PassThroughPathTailFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizePathDomainService.java
  src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransitPathLegSelector.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizePathDomainServiceTest.java
Labels: bug

#5460 Siri file loader
  docs/sandbox/SiriUpdater.md
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/EstimatedTimetableSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETHttpTripUpdateSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriFileLoader.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriHttpLoader.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriLoader.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
  src/main/java/org/opentripplanner/framework/time/CountdownTimer.java
  src/main/java/org/opentripplanner/framework/tostring/ToStringBuilder.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/SiriETUpdaterConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/SiriSXUpdaterConfig.java
  src/test/java/org/opentripplanner/framework/time/CountdownTimerTest.java
  src/test/java/org/opentripplanner/framework/tostring/ToStringBuilderTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/groupids/GroupByDistanceTest.java
Labels: improvement, sandbox

#5459 Run OTP with one key push in interactive OTP launcher
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/MainView.java
  src/ext/java/org/opentripplanner/ext/interactivelauncher/views/StartOtpButtonView.java
Labels: sandbox, skip changelog
