Repository opentripplanner/OpenTripPlanner, pull requests merged in 2023-04, with the labels that each got.

#4802 Product Overview page
  docs/Product-Overview.md
  mkdocs.yml
Labels: skip changelog

#5027 Fix staySeated transfers in RealtimeResolver
  src/ext-test/java/org/opentripplanner/ext/realtimeresolver/RealtimeResolverTest.java
  src/ext/java/org/opentripplanner/ext/realtimeresolver/RealtimeResolver.java
  src/main/java/org/opentripplanner/transit/model/network/TripPatternBuilder.java
Labels: sandbox, skip changelog

#5013 Use a more human-readable value for rental vehicle's name
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFreeVehicleStatusMapper.java
  src/test/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFreeVehicleStatusMapperTest.java
Labels: improvement, skip changelog

#5028 Fix banning of route and agency in GraphQL API
  src/ext-test/java/org/opentripplanner/ext/legacygraphqlapi/mapping/RouteRequestMapperTest.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/mapping/RouteRequestMapper.java
  src/main/java/org/opentripplanner/model/modes/ExcludeAllTransitFilter.java
Labels: bug, sandbox, skip changelog

#5016 Make maxTransferDuration a Duration
  docs/BuildConfiguration.md
  docs/OTP2-MigrationGuide.md
  docs/examples/entur/build-config.json
  docs/examples/skanetrafiken/build-config.json
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  test/performance/skanetrafiken/build-config.json
Labels: bump serialization id, skip changelog, config change

#5004 Bugs related to DST and service date
  src/ext-test/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTripTest.java
  src/ext-test/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandlerTest.java
  src/ext/java/org/opentripplanner/ext/siri/EntityResolver.java
  src/main/java/org/opentripplanner/framework/time/ServiceDateUtils.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
  src/test/java/org/opentripplanner/framework/time/ServiceDateUtilsTest.java
Labels: bug

#5007 Fix validation of running period for NeTEx flexible lines
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TripPatternForDate.java
Labels: bug

#5026 Change documentation enums from underscore to kebab case
  docs/BuildConfiguration.md
  docs/UpdaterConfig.md
  docs/sandbox/SiriUpdater.md
  docs/sandbox/VehicleParking.md
  src/main/java/org/opentripplanner/standalone/config/framework/json/EnumMapper.java
  src/main/java/org/opentripplanner/standalone/config/framework/json/NodeInfo.java
Labels: documentation, skip changelog

#5023 JSON logging
  docs/Logging.md
  docs/Troubleshooting-Routing.md
  mkdocs.yml
  pom.xml
  src/main/resources/logback.xml
Labels: improvement

#5024 Add allowOverloading parameter to GBFS updaters and fix use of it in routing
  docs/UpdaterConfig.md
  docs/sandbox/SmooveBikeRental.md
  src/ext-test/java/org/opentripplanner/ext/smoovebikerental/SmooveBikeRentalDataSourceTest.java
  src/ext-test/java/org/opentripplanner/ext/vilkkubikerental/VilkkuBikeRentalDataSourceTest.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLBikeRentalStationImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLVehicleRentalStationImpl.java
  src/ext/java/org/opentripplanner/ext/smoovebikerental/SmooveBikeRentalDataSource.java
  src/ext/java/org/opentripplanner/ext/smoovebikerental/SmooveBikeRentalDataSourceParameters.java
  src/ext/java/org/opentripplanner/ext/vehiclerentalservicedirectory/VehicleRentalServiceDirectoryFetcher.java
  src/ext/java/org/opentripplanner/ext/vilkkubikerental/VilkkuBikeRentalDataSource.java
  src/ext/java/org/opentripplanner/ext/vilkkubikerental/VilkkuBikeRentalDataSourceParameters.java
  src/main/java/org/opentripplanner/service/vehiclerental/model/VehicleRentalPlace.java
  src/main/java/org/opentripplanner/service/vehiclerental/model/VehicleRentalStation.java
  src/main/java/org/opentripplanner/service/vehiclerental/model/VehicleRentalVehicle.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/sources/VehicleRentalSourceFactory.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsStationInformationMapper.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsVehicleRentalDataSource.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/params/GbfsVehicleRentalDataSourceParameters.java
  src/test/java/org/opentripplanner/street/model/edge/VehicleParkingEdgeTest.java
  src/test/java/org/opentripplanner/street/model/edge/VehicleRentalEdgeTest.java
  src/test/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsVehicleRentalDataSourceTest.java
Labels: bug, new feature, Digitransit test

#5043 Fix typo
  CONTRIBUTING.md
Labels: skip changelog

#5021 Fix precedence rules for NeTEx flexible line booking information
  src/main/java/org/opentripplanner/netex/mapping/BookingInfoMapper.java
  src/test/java/org/opentripplanner/netex/mapping/BookingInfoMapperTest.java
Labels: bug, Entur test, NeTEx

#5044 Deduplicate lang string
  src/client/i18n/de.po
  src/client/i18n/en.po
  src/client/i18n/es.po
  src/client/i18n/fr.po
  src/client/i18n/hu.po
  src/client/i18n/it.po
  src/client/i18n/no.po
  src/client/i18n/pl.po
  src/client/i18n/pt.po
  src/client/i18n/sl.po
Labels: documentation, skip changelog

#5035 Use HttpHeaders class for GTFS-RT, cleanup
  docs/UpdaterConfig.md
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETHttpTripUpdateSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/GtfsRealtimeAlertsUpdaterConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/PollingTripUpdaterConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/VehiclePositionsUpdaterConfig.java
  src/main/java/org/opentripplanner/updater/alert/GtfsRealtimeAlertsUpdater.java
  src/main/java/org/opentripplanner/updater/alert/GtfsRealtimeAlertsUpdaterParameters.java
  src/main/java/org/opentripplanner/updater/spi/GenericJsonDataSource.java
  src/main/java/org/opentripplanner/updater/spi/HttpHeaders.java
  src/main/java/org/opentripplanner/updater/trip/GtfsRealtimeFileTripUpdateSource.java
  src/main/java/org/opentripplanner/updater/trip/GtfsRealtimeTripUpdateSource.java
  src/main/java/org/opentripplanner/updater/trip/PollingTripUpdater.java
  src/main/java/org/opentripplanner/updater/trip/PollingTripUpdaterParameters.java
  src/main/java/org/opentripplanner/updater/trip/TripUpdateSource.java
  src/main/java/org/opentripplanner/updater/vehicle_position/GtfsRealtimeHttpVehiclePositionSource.java
  src/main/java/org/opentripplanner/updater/vehicle_position/PollingVehiclePositionUpdater.java
  src/main/java/org/opentripplanner/updater/vehicle_position/VehiclePositionSource.java
  src/main/java/org/opentripplanner/updater/vehicle_position/VehiclePositionsUpdaterParameters.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFeedLoader.java
  src/test/java/org/opentripplanner/updater/spi/HttpHeadersTest.java
  src/test/java/org/opentripplanner/updater/trip/GtfsRealtimeTripUpdateSourceTest.java
  src/test/java/org/opentripplanner/updater/vehicle_position/VehiclePositionParsingTest.java
  src/test/resources/gtfs-rt/trip-updates/septa.pbf
  src/test/resources/gtfs-rt/vehicle-positions/king-county-metro-1.pb
  src/test/resources/gtfs-rt/vehicle-positions/king-county-metro-2.pb
Labels: technical debt, skip changelog

#5036 Add documentation for timetable updater config, use duration
  docs/RouterConfiguration.md
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/UpdatersConfig.java
  src/main/java/org/opentripplanner/updater/TimetableSnapshotSourceParameters.java
  src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
  src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java
  src/test/resources/standalone/config/router-config.json
Labels: documentation, technical debt, bump serialization id, skip changelog, config change

#5030 Log results of Siri-ET updates
  src/ext-test/java/org/opentripplanner/ext/siri/TimetableHelperTest.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  src/main/java/org/opentripplanner/updater/spi/ResultLogger.java
  src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
  src/main/java/org/opentripplanner/updater/vehicle_position/VehiclePositionPatternMatcher.java
Labels: skip changelog

#5049 Add 'config' parameter to REST API
  docs/Configuration.md
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/framework/application/OTPFeature.java
Labels: improvement, Entur test, OTP Debug UI

#5050 Improve GTFS-RT feed debugging for invalid arrival/departure time
  src/main/java/org/opentripplanner/model/Timetable.java
  src/test/java/org/opentripplanner/model/TimetableTest.java
  src/test/java/org/opentripplanner/updater/trip/TripUpdateBuilder.java
Labels: improvement, RealTimeUpdate, skip changelog

#5039 Fix transferCacheRequests when custom streetRoutingTimeout is set
  src/main/java/org/opentripplanner/routing/api/request/preference/StreetPreferences.java
  src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  src/test/java/org/opentripplanner/standalone/config/RouterConfigTest.java
Labels: bug, Digitransit test

#5068 Add example URL for travel isochrones docs [ci skip]
  docs/sandbox/TravelTime.md
Labels: documentation, skip changelog

#5069 Generate static documentation for GTFS GraphQL API
  .github/workflows/cibuild.yml
  magidoc.mjs
Labels: documentation, IBI

#5019 Create a valid area even when it has too many vertices
  docs/BuildConfiguration.md
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/graph_builder/module/FakeGraph.java
  src/test/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModuleTest.java
  src/test/java/org/opentripplanner/graph_builder/module/islandpruning/AdaptivePruningTest.java
  src/test/java/org/opentripplanner/graph_builder/module/islandpruning/PruneNoThruIslandsTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModuleTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/PlatformLinkerTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TriangleInequalityTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/UnconnectedAreasTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/UnroutableTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilderTest.java
  src/test/resources/org/opentripplanner/graph_builder/module/osm/lund-station-sweden.osm.pbf
Labels: bug, Digitransit test

#5057 Constant speed street routing
  docs/BuildConfiguration.md
  docs/RouteRequest.md
  src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/ConstantSpeedMapper.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/OsmTagMapper.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/OsmTagMapperSource.java
  src/main/java/org/opentripplanner/street/search/intersection_model/IntersectionTraversalCalculator.java
  src/main/java/org/opentripplanner/street/search/intersection_model/IntersectionTraversalModel.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/OsmTagMapperTest.java
Labels: new feature

#5054 Remove dependency from to UpdateResult from TripTimes
  src/ext-test/java/org/opentripplanner/ext/siri/AddedTripBuilderTest.java
  src/ext-test/java/org/opentripplanner/ext/siri/ModifiedTripBuilderTest.java
  src/ext/java/org/opentripplanner/ext/siri/AddedTripBuilder.java
  src/ext/java/org/opentripplanner/ext/siri/ModifiedTripBuilder.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/main/java/org/opentripplanner/model/Timetable.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripTimes.java
  src/main/java/org/opentripplanner/transit/model/timetable/ValidationError.java
  src/main/java/org/opentripplanner/updater/spi/ResultLogger.java
  src/main/java/org/opentripplanner/updater/spi/TripTimesValidationMapper.java
  src/main/java/org/opentripplanner/updater/spi/UpdateError.java
  src/main/java/org/opentripplanner/updater/spi/UpdateResult.java
  src/main/java/org/opentripplanner/updater/spi/UpdateSuccess.java
  src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
  src/main/java/org/opentripplanner/updater/trip/metrics/BatchTripUpdateMetrics.java
  src/main/java/org/opentripplanner/updater/trip/metrics/StreamingTripUpdateMetrics.java
  src/main/java/org/opentripplanner/updater/vehicle_position/VehiclePositionPatternMatcher.java
  src/test/java/org/opentripplanner/model/TimetableSnapshotTest.java
  src/test/java/org/opentripplanner/model/TimetableTest.java
  src/test/java/org/opentripplanner/routing/trippattern/TripTimesTest.java
  src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java
Labels: technical debt, RealTimeUpdate, skip changelog

#5072 Introduce builder for OSM module, rename types
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderFactory.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/ElevatorProcessor.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmDatabase.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmFilter.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModuleBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/parameters/OsmProcessingParameters.java
  src/main/java/org/opentripplanner/openstreetmap/OpenStreetMapParser.java
  src/main/java/org/opentripplanner/openstreetmap/OsmProvider.java
  src/main/java/org/opentripplanner/openstreetmap/api/OSMProvider.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
  src/main/java/org/opentripplanner/openstreetmap/spi/OSMDatabase.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/graph_builder/module/FakeGraph.java
  src/test/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModuleTest.java
  src/test/java/org/opentripplanner/graph_builder/module/islandpruning/AdaptivePruningTest.java
  src/test/java/org/opentripplanner/graph_builder/module/islandpruning/PruneNoThruIslandsTest.java
  src/test/java/org/opentripplanner/graph_builder/module/islandpruning/TestCustomNamer.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapParserTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OsmModuleTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/PlatformLinkerTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TriangleInequalityTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/UnconnectedAreasTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/UnroutableTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilderTest.java
  src/test/java/org/opentripplanner/openstreetmap/model/BicycleNetworkRelationsTest.java
  src/test/java/org/opentripplanner/openstreetmap/model/OSMWayTest.java
  src/test/java/org/opentripplanner/street/model/vertex/BarrierVertexTest.java
Labels: technical debt, skip changelog

#5056 Use structured log markers for realtime update results
  pom.xml
  src/main/java/org/opentripplanner/updater/spi/ResultLogger.java
Labels: improvement, RealTimeUpdate, skip changelog
