Repository opentripplanner/OpenTripPlanner, pull requests merged in 2023-02, with the labels that each got.

#4741 GBFS geofencing zones - part 1
  doc-templates/UpdaterConfig.md
  docs/RouterConfiguration.md
  docs/UpdaterConfig.md
  docs/examples/ibi/portland/build-config.json
  docs/examples/ibi/portland/router-config.json
  src/client/index.html
  src/client/js/otp/layers/GeofencingZonesLayer.js
  src/client/js/otp/modules/multimodal/MultimodalPlannerModule.js
  src/client/style.css
  src/ext/java/org/opentripplanner/ext/smoovebikerental/SmooveBikeRentalDataSource.java
  src/ext/java/org/opentripplanner/ext/vehiclerentalservicedirectory/VehicleRentalServiceDirectoryFetcher.java
  src/ext/java/org/opentripplanner/ext/vilkkubikerental/VilkkuBikeRentalDataSource.java
  src/main/java/org/opentripplanner/api/resource/GraphInspectorVectorTileResource.java
  src/main/java/org/opentripplanner/framework/geometry/GeometryUtils.java
  src/main/java/org/opentripplanner/inspector/vector/geofencing/GeofencingZonesLayerBuilder.java
  src/main/java/org/opentripplanner/inspector/vector/geofencing/GeofencingZonesPropertyMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapper.java
  src/main/java/org/opentripplanner/routing/linking/VertexLinker.java
  src/main/java/org/opentripplanner/routing/vehicle_rental/GeofencingZone.java
  src/main/java/org/opentripplanner/routing/vehicle_rental/VehicleRentalService.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/sources/VehicleRentalSourceFactory.java
  src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
  src/main/java/org/opentripplanner/street/model/edge/TemporaryPartialStreetEdge.java
  src/main/java/org/opentripplanner/street/model/vertex/RentalRestrictionExtension.java
  src/main/java/org/opentripplanner/street/model/vertex/Vertex.java
  src/main/java/org/opentripplanner/street/search/state/State.java
  src/main/java/org/opentripplanner/street/search/state/StateData.java
  src/main/java/org/opentripplanner/street/search/state/StateEditor.java
  src/main/java/org/opentripplanner/street/search/strategy/DominanceFunctions.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/GeofencingVertexUpdater.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdater.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsGeofencingZoneMapper.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsVehicleRentalDataSource.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/VehicleRentalDataSourceFactory.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/VehicleRentalDatasource.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/params/GbfsVehicleRentalDataSourceParameters.java
  src/test/java/org/opentripplanner/framework/FrameworkArchitectureTest.java
  src/test/java/org/opentripplanner/framework/geometry/GeometryUtilsTest.java
  src/test/java/org/opentripplanner/generate/doc/UpdaterConfigDocTest.java
  src/test/java/org/opentripplanner/street/model/_data/StreetModelForTest.java
  src/test/java/org/opentripplanner/street/model/edge/RentalRestrictionExtensionTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeCostTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeWheelchairCostTest.java
  src/test/java/org/opentripplanner/street/search/state/StateEditorTest.java
  src/test/java/org/opentripplanner/street/search/strategy/DominanceFunctionTest.java
  src/test/java/org/opentripplanner/updater/vehicle_rental/GeofencingVertexUpdaterTest.java
  src/test/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFeedLoaderTest.java
  src/test/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsVehicleRentalDataSourceTest.java
  src/test/resources/gbfs/tieroslo/gbfs.json
  src/test/resources/gbfs/tieroslo/geofencing_zones.json
  src/test/resources/gbfs/tieroslo/system_information.json
  src/test/resources/standalone/config/router-config.json
  test/performance/norway/speed-test-config.json
Labels: new feature, IBI, bump serialization id

#4776 Remove sub-services from routing service
  src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  src/ext-test/java/org/opentripplanner/ext/legacygraphqlapi/GraphQLApiTest.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLRequestContext.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPatternImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelRequestContext.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/support/GqlUtil.java
  src/main/java/org/opentripplanner/routing/RoutingService.java
  src/main/java/org/opentripplanner/routing/api/RoutingService.java
  src/main/java/org/opentripplanner/routing/service/DefaultRoutingService.java
  src/main/java/org/opentripplanner/standalone/api/OtpServerRequestContext.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationModule.java
  src/main/java/org/opentripplanner/standalone/server/DefaultServerRequestContext.java
  src/main/java/org/opentripplanner/updater/GraphUpdaterManager.java
  src/test/java/org/opentripplanner/api/common/PlannerResourceTest.java
  src/test/java/org/opentripplanner/routing/graph/DefaultRoutingServiceTest.java
Labels: technical debt, IBI, skip changelog

#4773 Add ORCA Fares support with Fare by Leg
  docs/sandbox/Fares.md
  src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/FaresConfiguration.java
  src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFaresData.java
  src/ext/java/org/opentripplanner/ext/fares/model/RiderCategory.java
  src/main/java/org/opentripplanner/api/mapping/FareMapper.java
  src/main/java/org/opentripplanner/routing/core/ItineraryFares.java
  src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
Labels: sandbox, IBI, bump serialization id

#4793 Expose original trip pattern in pattern
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPatternImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
Labels: sandbox, skip changelog

#4804 Fix NPE in ORCA fare calculator
  src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
Labels: bug, sandbox, IBI, skip changelog

#4787 Fix TPoint generation for real-time generated patterns
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/TransferIndexGenerator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerUpdater.java
Labels: bug, Entur test

#4807 Do not override network name in the vehicle rental service directory service
  src/ext/java/org/opentripplanner/ext/vehiclerentalservicedirectory/VehicleRentalServiceDirectoryFetcher.java
Labels: bug, sandbox, Vehicle rental

#4800 Replace 'developer mailing list' with 'Gitter chat' in doc
  ISSUE_TEMPLATE
  README.md
  docs/Developers-Guide.md
  docs/Localization.md
Labels: documentation, skip changelog

#4797 Refactor GTFS-RT tests to use fixed service date
  src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
  src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java
  src/test/java/org/opentripplanner/updater/trip/TripUpdateBuilder.java
Labels: technical debt, skip changelog

#4801 Small cleanup ItineraryListFilterChainBuilder
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java
Labels: technical debt, skip changelog

#4784 Refactor vehicle position service into separate module
  .github/workflows/cibuild.yml
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLRequestContext.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPatternImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopRelationshipImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLVehiclePositionImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/graphql-codegen.yml
  src/main/java/org/opentripplanner/routing/graph/Graph.java
  src/main/java/org/opentripplanner/routing/services/RealtimeVehiclePositionService.java
  src/main/java/org/opentripplanner/service/vehiclepositions/VehiclePositionRepository.java
  src/main/java/org/opentripplanner/service/vehiclepositions/VehiclePositionService.java
  src/main/java/org/opentripplanner/service/vehiclepositions/configure/VehiclePositionsRepositoryModule.java
  src/main/java/org/opentripplanner/service/vehiclepositions/configure/VehiclePositionsServiceModule.java
  src/main/java/org/opentripplanner/service/vehiclepositions/internal/DefaultVehiclePositionService.java
  src/main/java/org/opentripplanner/service/vehiclepositions/model/RealtimeVehiclePosition.java
  src/main/java/org/opentripplanner/service/vehiclepositions/model/RealtimeVehiclePositionBuilder.java
  src/main/java/org/opentripplanner/standalone/api/OtpServerRequestContext.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationFactory.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationModule.java
  src/main/java/org/opentripplanner/standalone/server/DefaultServerRequestContext.java
  src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
  src/main/java/org/opentripplanner/updater/vehicle_position/PollingVehiclePositionUpdater.java
  src/main/java/org/opentripplanner/updater/vehicle_position/VehiclePositionPatternMatcher.java
  src/test/java/org/opentripplanner/TestServerContext.java
  src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
  src/test/java/org/opentripplanner/updater/vehicle_position/VehiclePositionsMatcherTest.java
Labels: technical debt, skip changelog

#4822 Fix windows CI build by specifying resource encoding
  pom.xml
  src/main/resources/Message_de.properties
  src/main/resources/internals_hu.properties
  src/test/java/org/opentripplanner/framework/i18n/LocalizedStringTest.java
  src/test/java/org/opentripplanner/framework/resources/ResourceBundleSingletonTest.java
Labels: bug, skip changelog

#4833 Update Azure updaters
  docs/sandbox/SiriAzureUpdater.md
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java
Labels: sandbox, Skanetrafiken, RealTimeUpdate, skip changelog

#4806 Improve resiliency of the Transmodel API
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/PlanPlaceType.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/TripPlanMapper.java
Labels: improvement, Entur

#4809 Update GBFS support to v2.3
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLUtils.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLRentalVehicleTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/vehicle_rental/RentalVehicleType.java
  src/main/java/org/opentripplanner/street/model/edge/VehicleRentalEdge.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFeedLoader.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFreeVehicleStatusMapper.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsGeofencingZoneMapper.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsStationInformationMapper.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsStationStatusMapper.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsSystemInformationMapper.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsVehicleRentalDataSource.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsVehicleTypeMapper.java
  src/test/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFeedLoaderTest.java
Labels: technical debt, Entur test, Vehicle rental

#4819 Add documentation for unpreferred agencies and routes
  docs/RouteRequest.md
  docs/RouterConfiguration.md
  src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  src/test/resources/standalone/config/router-config.json
Labels: documentation, skip changelog

#4839 Introduce separate build step for windows
  .github/workflows/cibuild.yml
  pom.xml
Labels: technical debt, skip changelog

#4820 Use TripPatterns for filtering
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTripPatternCache.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/FilterMapper.java
  src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeResource.java
  src/ext/java/org/opentripplanner/ext/vehicletostopheuristics/VehicleToStopSkipEdgeStrategy.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/gtfs/GenerateTripPatternsOperation.java
  src/main/java/org/opentripplanner/model/modes/AllowTransitModeFilter.java
  src/main/java/org/opentripplanner/model/modes/ExcludeAllTransitFilter.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RouteRequestTransitDataProviderFilter.java
  src/main/java/org/opentripplanner/routing/api/request/request/filter/AllowAllTransitFilter.java
  src/main/java/org/opentripplanner/routing/api/request/request/filter/SelectRequest.java
  src/main/java/org/opentripplanner/routing/api/request/request/filter/TransitFilter.java
  src/main/java/org/opentripplanner/routing/api/request/request/filter/TransitFilterRequest.java
  src/main/java/org/opentripplanner/transit/model/network/TripPattern.java
  src/main/java/org/opentripplanner/transit/model/network/TripPatternBuilder.java
  src/main/java/org/opentripplanner/updater/trip/TripPatternCache.java
  src/test/java/org/opentripplanner/routing/algorithm/FilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/TestBanning.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/SnapshotTestBase.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RouteRequestTransitDataProviderFilterTest.java
  src/test/java/org/opentripplanner/transit/model/_data/TransitModelForTest.java
Labels: bug, Entur, optimization, Entur test, bump serialization id

#4798 Add Fares V2 distance-based computation
  pom.xml
  src/ext-test/java/org/opentripplanner/ext/fares/impl/GtfsFaresV2ServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/impl/GtfsFaresV2Service.java
  src/ext/java/org/opentripplanner/ext/fares/model/Distance.java
  src/ext/java/org/opentripplanner/ext/fares/model/FareDistance.java
  src/ext/java/org/opentripplanner/ext/fares/model/FareLegRule.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/main/java/org/opentripplanner/gtfs/mapping/FareLegRuleMapper.java
  src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
  src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
Labels: new feature, bump serialization id

#4834 Make sure that we do not return realtime snapshot that is null
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
Labels: Skanetrafiken, RealTimeUpdate, skip changelog

#4835 properly decode cp437 names in zip files
  pom.xml
  src/main/java/org/opentripplanner/datastore/file/ZipFileDataSource.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/datastore/file/ZipFileDataSourceTest.java
  src/test/resources/umlaut-cp437.zip
  src/test/resources/umlaut-utf8-no-efs.zip
  src/test/resources/umlaut-utf8.zip
Labels: technical debt, skip changelog

#4842 Add leg alerts to GraphQL API
  .github/workflows/cibuild.yml
  src/ext-test/java/org/opentripplanner/ext/legacygraphqlapi/GraphQLApiTest.java
  src/ext-test/java/org/opentripplanner/ext/legacygraphqlapi/GraphQLIntegrationTest.java
  src/ext-test/java/org/opentripplanner/ext/legacygraphqlapi/TestRoutingService.java
  src/ext-test/resources/legacygraphqlapi/expectations/plan.json
  src/ext-test/resources/legacygraphqlapi/expectations/stops.json
  src/ext-test/resources/legacygraphqlapi/queries/plan.graphql
  src/ext-test/resources/legacygraphqlapi/queries/stops.graphql
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLAPI.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLRequestContext.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLAgencyImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLAlertImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLDepartureRowImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLFeedImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLLegImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPatternImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLRouteImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLRouteTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLfareComponentImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLserviceTimeRangeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/graphql-codegen.yml
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/mapping/LegacyGraphQLCauseMapper.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/mapping/LegacyGraphQLEffectMapper.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/mapping/LegacyGraphQLSeverityMapper.java
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/test/java/org/opentripplanner/model/plan/PlanTestConstants.java
Labels: sandbox, skip changelog

#4846 Remove all edges from stop vertex in island pruning
  src/main/java/org/opentripplanner/graph_builder/module/islandpruning/PruneIslands.java
Labels: bug

#4812 Filter functionality for GroupOfLines/GroupOfRoutes + TransmodelAPI m…
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/SelectRequestMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/SelectInputType.java
  src/main/java/org/opentripplanner/routing/api/request/request/filter/SelectRequest.java
  src/main/java/org/opentripplanner/transit/model/network/RouteBuilder.java
  src/test/java/org/opentripplanner/routing/algorithm/FilterTest.java
  src/test/java/org/opentripplanner/transit/model/_data/TransitModelForTest.java
Labels: new feature, bump serialization id

#4831 Apply bike safety multiplier to cyclestreets and bicycle roads
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/DefaultMapper.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/GermanyMapperTest.java
Labels: skip changelog

#4843 Add docs for presentations related to OTP
  docs/Presentations.md
  mkdocs.yml
Labels: documentation, skip changelog

#4845 Use headsign from the original pattern in a realtime added pattern if the stop sequence is unchanged
  src/main/java/org/opentripplanner/transit/model/network/TripPattern.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripTimes.java
  src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java
  src/test/resources/testagency/trips.txt
Labels: improvement, RealTimeUpdate

#4840 Remove usage of apache commons
  src/ext-test/java/org/opentripplanner/ext/datastore/gs/GsIntegrationTest.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriVMUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/AbstractAzureSiriUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/ValidityPeriodType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/sx/PtSituationElementType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/sx/ValidityPeriod.java
  src/main/java/org/opentripplanner/datastore/api/DataSource.java
  src/main/java/org/opentripplanner/datastore/file/DirectoryDataSource.java
  src/main/java/org/opentripplanner/datastore/file/ZipStreamDataSourceDecorator.java
  src/main/java/org/opentripplanner/framework/text/FileSizeToTextConverter.java
  src/main/java/org/opentripplanner/framework/text/HexString.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/Ring.java
  src/main/java/org/opentripplanner/netex/loader/FileEntry.java
  src/main/java/org/opentripplanner/standalone/config/framework/file/ConfigFileLoader.java
  src/main/java/org/opentripplanner/standalone/config/framework/file/IncludeFileDirective.java
  src/main/java/org/opentripplanner/standalone/server/EtagRequestFilter.java
  src/test/java/org/opentripplanner/datastore/DataStoreArchitectureTest.java
  src/test/java/org/opentripplanner/datastore/OtpDataStoreTest.java
  src/test/java/org/opentripplanner/datastore/base/ByteArrayDataSourceTest.java
  src/test/java/org/opentripplanner/datastore/file/DirectoryDataSourceTest.java
  src/test/java/org/opentripplanner/datastore/file/FileDataSourceTest.java
  src/test/java/org/opentripplanner/datastore/file/ZipFileDataSourceTest.java
  src/test/java/org/opentripplanner/datastore/file/ZipStreamDataSourceDecoratorTest.java
  src/test/java/org/opentripplanner/framework/text/FileSizeToTextConverterTest.java
  src/test/java/org/opentripplanner/framework/text/HexStringTest.java
  src/test/java/org/opentripplanner/standalone/config/OtpConfigLoaderTest.java
  src/test/java/org/opentripplanner/standalone/config/framework/file/ConfigFileLoaderTest.java
  src/test/java/org/opentripplanner/standalone/config/framework/file/IncludeFileDirectiveTest.java
Labels: technical debt

#4821 Remove RouteMatcher
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/FilterMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/SelectRequestMapper.java
  src/main/java/org/opentripplanner/routing/api/request/request/filter/SelectRequest.java
  src/main/java/org/opentripplanner/routing/core/RouteMatcher.java
  src/test/java/org/opentripplanner/GtfsTest.java
  src/test/java/org/opentripplanner/routing/algorithm/FilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/TestBanning.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RouteRequestTransitDataProviderFilterTest.java
  src/test/java/org/opentripplanner/routing/core/RouteMatcherTest.java
Labels: technical debt

#4854 Fix docker commands in Container-Image.md
  docs/Container-Image.md
Labels: documentation, skip changelog

#4852 Improve boarding location linking on platforms
  src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  src/main/java/org/opentripplanner/inspector/raster/AreaEdgeRenderer.java
  src/main/java/org/opentripplanner/inspector/raster/TileRendererManager.java
  src/main/java/org/opentripplanner/street/model/edge/AreaEdgeList.java
  src/test/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModuleTest.java
Labels: improvement, OTP Debug UI

#4848 Return scooter rental legs with correct mode
  src/ext/java/org/opentripplanner/ext/dataoverlay/DataOverlayStreetEdgeCostExtension.java
  src/main/java/org/opentripplanner/routing/vehicle_rental/RentalVehicleType.java
  src/main/java/org/opentripplanner/street/model/StreetTraversalPermission.java
  src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
  src/main/java/org/opentripplanner/street/search/TraverseMode.java
  src/main/java/org/opentripplanner/street/search/intersection_model/SimpleIntersectionTraversalCalculator.java
  src/test/java/org/opentripplanner/street/model/edge/RentalRestrictionExtensionTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeRentalTraversalTest.java
Labels: bug, IBI, skip changelog, Vehicle rental

#4864 Fix handling of nullable route names in ORCA fare calculator
  src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
Labels: bug, sandbox, IBI, skip changelog

#4860 Remove unused files
  src/ext-test/java/org/opentripplanner/ext/legacygraphqlapi/TestHeaders.java
  src/main/java/org/opentripplanner/graph_builder/module/extra_elevation_data/ElevationPoint.java
  src/test/resources/scripts/test.groovy
  src/test/resources/scripts/test.py
Labels: technical debt, skip changelog

#4875 Fix mapping of nullable URL in StreetNote
  src/ext-test/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLstepImplTest.java
  src/ext-test/java/org/opentripplanner/ext/legacygraphqlapi/mapping/StreetNoteMapperTest.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLstepImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/mapping/StreetNoteMapper.java
  src/main/java/org/opentripplanner/routing/alertpatch/TransitAlert.java
Labels: bug, sandbox, IBI, skip changelog

#4810 Always check allowed modes in VehicleRentalEdge
  src/main/java/org/opentripplanner/street/model/edge/VehicleRentalEdge.java
Labels: bug, Vehicle rental

#4863 Improve support for EPIP NeTex profile
  src/main/java/org/opentripplanner/netex/index/NetexEntityIndex.java
  src/main/java/org/opentripplanner/netex/index/api/NetexEntityIndexReadOnlyView.java
  src/main/java/org/opentripplanner/netex/loader/parser/ServiceCalendarFrameParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/ServiceFrameParser.java
  src/main/java/org/opentripplanner/netex/mapping/GroupOfStationsMapper.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/RouteMapper.java
  src/main/java/org/opentripplanner/netex/mapping/ServiceLinkMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripCalendarBuilder.java
  src/main/java/org/opentripplanner/netex/mapping/TripMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
  src/main/java/org/opentripplanner/netex/mapping/calendar/DayTypeAssignmentMapper.java
  src/main/java/org/opentripplanner/netex/validation/JourneyPatternSJMismatch.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/netex/NetexEpipBundleSmokeTest.java
  src/test/java/org/opentripplanner/netex/NetexNordicBundleSmokeTest.java
  src/test/java/org/opentripplanner/netex/NetexTestDataSupport.java
  src/test/java/org/opentripplanner/netex/mapping/NetexTestDataSample.java
  src/test/java/org/opentripplanner/netex/mapping/TripCalendarBuilderTest.java
  src/test/java/org/opentripplanner/netex/mapping/TripMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/calendar/DayTypeAssignmentMapperTest.java
  src/test/resources/netex/epip/build-config.json
  src/test/resources/netex/epip/netex_epip_minimal.zip
  src/test/resources/netex/nordic/build-config.json
  src/test/resources/netex/nordic/netex_minimal.zip
Labels: improvement
