Repository opentripplanner/OpenTripPlanner, pull requests merged in 2023-05, with the labels that each got.

#5075 Document Siri-SX updaters, use records for config
  doc-templates/SiriUpdater.md
  doc-templates/UpdaterConfig.md
  docs/RouterConfiguration.md
  docs/UpdaterConfig.md
  docs/sandbox/SiriUpdater.md
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdaterParameters.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/SiriSXUpdaterConfig.java
  src/test/java/org/opentripplanner/generate/doc/SiriConfigDocTest.java
  src/test/java/org/opentripplanner/generate/doc/UpdaterConfigDocTest.java
  src/test/resources/standalone/config/router-config.json
Labels: documentation, sandbox, skip changelog

#4942 Add performance test for Hamburg
  .github/workflows/performance-test.yml
  test/performance/README.md
  test/performance/hamburg/build-config.json
  test/performance/hamburg/generate_test_cases.py
  test/performance/hamburg/speed-test-config.json
  test/performance/hamburg/travelSearch-expected-results.csv
  test/performance/hamburg/travelSearch.csv
Labels: skip changelog

#5047 Configure HTTP WebServer Transaction timeouts
  docs/RouteRequest.md
  docs/RouterConfiguration.md
  docs/examples/entur/router-config.json
  docs/examples/ibi/portland/router-config.json
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLUtils.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraph.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/support/OTPProcessingTimeoutGraphQLException.java
  src/main/java/org/opentripplanner/api/common/Message.java
  src/main/java/org/opentripplanner/api/common/OTPExceptionMapper.java
  src/main/java/org/opentripplanner/api/resource/PlannerResource.java
  src/main/java/org/opentripplanner/framework/application/OTPRequestTimeoutException.java
  src/main/java/org/opentripplanner/framework/concurrent/InterruptibleExecutor.java
  src/main/java/org/opentripplanner/framework/http/OtpHttpStatus.java
  src/main/java/org/opentripplanner/raptor/rangeraptor/DefaultRangeRaptorWorker.java
  src/main/java/org/opentripplanner/raptor/service/RangeRaptorDynamicSearch.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/api/response/RoutingErrorCode.java
  src/main/java/org/opentripplanner/routing/error/RoutingValidationException.java
  src/main/java/org/opentripplanner/standalone/OTPMain.java
  src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
  src/main/java/org/opentripplanner/standalone/config/framework/json/OtpVersion.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/ServerConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  src/main/java/org/opentripplanner/standalone/config/sandbox/TransmodelAPIConfig.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationModule.java
  src/main/java/org/opentripplanner/standalone/server/GrizzlyServer.java
  src/main/java/org/opentripplanner/standalone/server/MetricsLogging.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/resources/Message.properties
  src/main/resources/Message_de.properties
  src/main/resources/Message_es.properties
  src/main/resources/Message_fr.properties
  src/main/resources/Message_hu.properties
  src/main/resources/Message_nl.properties
  src/test/java/org/opentripplanner/TestServerContext.java
  src/test/java/org/opentripplanner/standalone/config/OtpConfigLoaderTest.java
  src/test/java/org/opentripplanner/standalone/config/RouterConfigTest.java
  src/test/java/org/opentripplanner/standalone/config/routerconfig/ServerConfigTest.java
  src/test/resources/standalone/config/router-config.json
Labels: new feature, technical debt

#5079 Remove request log file
  docs/Logging.md
  docs/RouterConfiguration.md
  src/main/java/org/opentripplanner/api/resource/PlannerResource.java
  src/main/java/org/opentripplanner/standalone/OTPMain.java
  src/main/java/org/opentripplanner/standalone/api/OtpServerRequestContext.java
  src/main/java/org/opentripplanner/standalone/config/package.md
  src/main/java/org/opentripplanner/standalone/config/routerconfig/ServerConfig.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationModule.java
  src/main/java/org/opentripplanner/standalone/configure/RequestLoggerFactory.java
  src/main/java/org/opentripplanner/standalone/server/DefaultServerRequestContext.java
  src/test/java/org/opentripplanner/TestServerContext.java
  src/test/java/org/opentripplanner/standalone/config/OtpConfigLoaderTest.java
  src/test/java/org/opentripplanner/standalone/config/routerconfig/ServerConfigTest.java
  src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
Labels: bump serialization id, skip changelog

#5084 Add deduplicated "stop clusters" to geocoding sandbox API
  docs/sandbox/GeocoderAPI.md
  src/ext-test/java/org/opentripplanner/ext/geocoder/LuceneIndexTest.java
  src/ext/java/org/opentripplanner/ext/geocoder/GeocoderResource.java
  src/ext/java/org/opentripplanner/ext/geocoder/LuceneIndex.java
  src/ext/java/org/opentripplanner/ext/geocoder/StopCluster.java
  src/ext/java/org/opentripplanner/ext/geocoder/StopClusters.java
Labels: sandbox, IBI

#5063 Fix flex timeshift
  src/ext-test/java/org/opentripplanner/ext/flex/FlexPathDurationsTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/trip/UnscheduledTripTest.java
  src/ext-test/java/org/opentripplanner/ext/transmodelapi/model/EnumTypesTest.java
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/flex/Flex.svg
  src/ext/java/org/opentripplanner/ext/flex/FlexAccessEgress.java
  src/ext/java/org/opentripplanner/ext/flex/FlexPathDurations.java
  src/ext/java/org/opentripplanner/ext/flex/edgetype/FlexTripEdge.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessEgressTemplate.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessTemplate.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexEgressTemplate.java
  src/ext/java/org/opentripplanner/ext/flex/trip/FlexTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/StopTimeWindow.java
  src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/main/java/org/opentripplanner/framework/lang/IntRange.java
  src/main/java/org/opentripplanner/framework/time/TimeUtils.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/FlexAccessEgressAdapter.java
  src/test/java/org/opentripplanner/framework/lang/IntRangeTest.java
  src/test/java/org/opentripplanner/framework/time/TimeUtilsTest.java
  src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
Labels: bug, Entur test, bump serialization id

#5108 Fix logging of stacktraces for polling graph updater
  src/main/java/org/opentripplanner/updater/spi/PollingGraphUpdater.java
  src/main/java/org/opentripplanner/updater/trip/GtfsRealtimeTripUpdateSource.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdater.java
Labels: bug, skip changelog, bbnavi

#4841 Make A*'s traverse method return array of states
  src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  src/ext/java/org/opentripplanner/ext/flex/edgetype/FlexTripEdge.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessEgressTemplate.java
  src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessTemplate.java
  src/main/java/org/opentripplanner/astar/AStar.java
  src/main/java/org/opentripplanner/astar/spi/AStarEdge.java
  src/main/java/org/opentripplanner/astar/spi/AStarState.java
  src/main/java/org/opentripplanner/graph_builder/module/islandpruning/PruneIslands.java
  src/main/java/org/opentripplanner/graph_builder/module/map/MatchState.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/Transfer.java
  src/main/java/org/opentripplanner/service/vehiclerental/street/StreetVehicleRentalLink.java
  src/main/java/org/opentripplanner/service/vehiclerental/street/VehicleRentalEdge.java
  src/main/java/org/opentripplanner/street/model/edge/Edge.java
  src/main/java/org/opentripplanner/street/model/edge/ElevatorAlightEdge.java
  src/main/java/org/opentripplanner/street/model/edge/ElevatorBoardEdge.java
  src/main/java/org/opentripplanner/street/model/edge/ElevatorHopEdge.java
  src/main/java/org/opentripplanner/street/model/edge/FreeEdge.java
  src/main/java/org/opentripplanner/street/model/edge/PathwayEdge.java
  src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
  src/main/java/org/opentripplanner/street/model/edge/StreetTransitEntityLink.java
  src/main/java/org/opentripplanner/street/model/edge/StreetVehicleParkingLink.java
  src/main/java/org/opentripplanner/street/model/edge/TemporaryFreeEdge.java
  src/main/java/org/opentripplanner/street/model/edge/VehicleParkingEdge.java
  src/main/java/org/opentripplanner/street/search/state/EdgeTraverser.java
  src/main/java/org/opentripplanner/street/search/state/State.java
  src/main/java/org/opentripplanner/street/search/state/StateEditor.java
  src/test/java/org/opentripplanner/graph_builder/module/map/StreetMatcherTest.java
  src/test/java/org/opentripplanner/routing/TestHalfEdges.java
  src/test/java/org/opentripplanner/routing/graph/SimpleConcreteEdge.java
  src/test/java/org/opentripplanner/routing/graph/TemporaryConcreteEdge.java
  src/test/java/org/opentripplanner/street/model/edge/ElevatorHopEdgeTest.java
  src/test/java/org/opentripplanner/street/model/edge/PathwayEdgeTest.java
  src/test/java/org/opentripplanner/street/model/edge/RentalRestrictionExtensionTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeCostTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeGeofencingTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeRentalTraversalTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeWheelchairCostTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetTransitEntityLinkTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetVehicleParkingLinkTest.java
  src/test/java/org/opentripplanner/street/model/edge/TemporaryPartialStreetEdgeTest.java
  src/test/java/org/opentripplanner/street/model/edge/VehicleParkingEdgeTest.java
  src/test/java/org/opentripplanner/street/model/edge/VehicleParkingPreferredTagsTest.java
  src/test/java/org/opentripplanner/street/model/edge/VehicleRentalEdgeTest.java
  src/test/java/org/opentripplanner/street/search/state/TraverseResultTest.java
Labels: technical debt, bump serialization id, skip changelog

#5090 Use correct GTFS sequence number in vehicle position matcher
  src/main/java/org/opentripplanner/model/Timetable.java
  src/main/java/org/opentripplanner/model/plan/FrequencyTransitLeg.java
  src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripTimes.java
  src/main/java/org/opentripplanner/updater/vehicle_position/VehiclePositionPatternMatcher.java
  src/test/java/org/opentripplanner/routing/trippattern/TripTimesTest.java
  src/test/java/org/opentripplanner/updater/vehicle_position/VehiclePositionsMatcherTest.java
Labels: bug, RealTimeUpdate

#5102 Allow switching between GTFS and Transmodel APIs in GraphiQL
  src/client/graphiql/index.html
Labels: documentation, OTP Debug UI, skip changelog

#5104 Fix SIRI ET PubSub updater shutdown
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
Labels: bug, RealTimeUpdate

#5096 OSM: Break out of processing a malformed level map
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmDatabase.java
Labels: bug

#5111 Improve changelog update stability
  .github/workflows/post-merge.yml
Labels: skip changelog

#5118 Create unique SIRI-ET PubSub subscription
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
Labels: bug

#5123 fix: PageCursor decode of JS "null" (as String)
  src/main/java/org/opentripplanner/framework/lang/StringUtils.java
  src/main/java/org/opentripplanner/model/plan/pagecursor/PageCursorSerializer.java
  src/main/java/org/opentripplanner/netex/mapping/OperatorToAgencyMapper.java
  src/main/java/org/opentripplanner/updater/vehicle_position/VehiclePositionPatternMatcher.java
  src/test/java/org/opentripplanner/framework/lang/StringUtilsTest.java
Labels: improvement, skip changelog

#5119 fix: Log warnings in child nodes
  src/main/java/org/opentripplanner/standalone/config/framework/json/NodeAdapter.java
  src/main/java/org/opentripplanner/standalone/config/framework/json/ParameterBuilder.java
  src/test/java/org/opentripplanner/standalone/config/framework/json/NodeAdapterTest.java
Labels: bug, skip changelog

#5089 Rename bikeRental options to vehicleRental
  docs/RouteRequest.md
  docs/RouterConfiguration.md
  docs/UpdaterConfig.md
  docs/examples/entur/router-config.json
  docs/examples/ibi/atlanta/router-config.json
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/routing/api/request/preference/VehicleRentalPreferences.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/sources/VehicleRentalSourceFactory.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/VehicleRentalConfig.java
  src/test/resources/standalone/config/router-config.json
Labels: config change

#5055 Mapping for maxDirectDuration in Transmodel API
  src/ext-test/java/org/opentripplanner/ext/transmodelapi/mapping/TripRequestMapperTest.java
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/PreferencesMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/StreetModeDurationInputType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
  src/main/java/org/opentripplanner/routing/api/request/preference/StreetPreferences.java
Labels: sandbox, Skanetrafiken, skip changelog

#5124 Cleanup threads and error handling
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelAPI.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraph.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/support/GraphQLToWebResponseMapper.java
  src/main/java/org/opentripplanner/framework/concurrent/OtpRequestThreadFactory.java
  src/main/java/org/opentripplanner/raptor/configure/RaptorConfig.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/java/org/opentripplanner/standalone/OTPMain.java
  src/main/java/org/opentripplanner/standalone/OtpStartupInfo.java
  src/main/java/org/opentripplanner/standalone/server/GrizzlyServer.java
  src/main/java/org/opentripplanner/updater/GraphUpdaterManager.java
  src/main/resources/logback.xml
  src/test/java/org/opentripplanner/OtpArchitectureModules.java
  src/test/java/org/opentripplanner/raptor/RaptorArchitectureTest.java
  src/test/resources/logback.xml
Labels: improvement, skip changelog

#5100 Fare sandbox cleanup, remove MultipleFareService
  docs/sandbox/Fares.md
  src/ext-test/java/org/opentripplanner/ext/fares/FaresFilterTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/AtlantaFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/CombinedInterlinedLegsFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/FareModelForTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/FaresIntegrationTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/GtfsFaresV2ServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/HSLFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/MultipleFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/model/FareProductTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTripTest.java
  src/ext-test/java/org/opentripplanner/ext/legacygraphqlapi/GraphQLIntegrationTest.java
  src/ext-test/java/org/opentripplanner/ext/ridehailing/RideHailingFilterTest.java
  src/ext/java/org/opentripplanner/ext/fares/FaresConfiguration.java
  src/ext/java/org/opentripplanner/ext/fares/FaresFilter.java
  src/ext/java/org/opentripplanner/ext/fares/impl/AddingMultipleFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/AtlantaFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/GtfsFaresService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/GtfsFaresV2Service.java
  src/ext/java/org/opentripplanner/ext/fares/impl/HSLFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/MultipleFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/NoopFareServiceFactory.java
  src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFaresData.java
  src/ext/java/org/opentripplanner/ext/fares/impl/SFBayFareServiceImpl.java
  src/ext/java/org/opentripplanner/ext/fares/impl/TimeBasedVehicleRentalFareService.java
  src/ext/java/org/opentripplanner/ext/fares/model/Distance.java
  src/ext/java/org/opentripplanner/ext/fares/model/FareDistance.java
  src/ext/java/org/opentripplanner/ext/fares/model/FareLegRule.java
  src/ext/java/org/opentripplanner/ext/fares/model/FareRuleSet.java
  src/ext/java/org/opentripplanner/ext/fares/model/FareRulesData.java
  src/ext/java/org/opentripplanner/ext/fares/model/FareTransferRule.java
  src/ext/java/org/opentripplanner/ext/fares/model/LegProducts.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLMoneyImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLfareComponentImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLfareImpl.java
  src/ext/java/org/opentripplanner/ext/ridehailing/service/uber/UberService.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/bikely/BikelyUpdater.java
  src/main/java/org/opentripplanner/api/mapping/FareMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/FareLegRuleMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/FareProductMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/FareTransferRuleMapper.java
  src/main/java/org/opentripplanner/model/fare/FareProduct.java
  src/main/java/org/opentripplanner/model/fare/ItineraryFares.java
  src/main/java/org/opentripplanner/routing/fares/FareService.java
  src/main/java/org/opentripplanner/transit/model/basic/Money.java
  src/test/java/org/opentripplanner/api/mapping/FareMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/FareProductMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/FareTransferRuleMapperTest.java
  src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
  src/test/java/org/opentripplanner/routing/core/ItineraryFaresTest.java
  src/test/java/org/opentripplanner/routing/core/MoneyTest.java
Labels: sandbox, technical debt, IBI

#5081 Add validation of NeTEX timetabled passing times
  src/main/java/org/opentripplanner/netex/index/hierarchy/AbstractHierarchicalMap.java
  src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java
  src/main/java/org/opentripplanner/netex/support/ServiceJourneyHelper.java
  src/main/java/org/opentripplanner/netex/support/ServiceJourneyInfo.java
  src/main/java/org/opentripplanner/netex/support/stoptime/AbstractStopTimeAdaptor.java
  src/main/java/org/opentripplanner/netex/support/stoptime/AreaStopTimeAdaptor.java
  src/main/java/org/opentripplanner/netex/support/stoptime/RegularStopTimeAdaptor.java
  src/main/java/org/opentripplanner/netex/support/stoptime/StopTimeAdaptor.java
  src/main/java/org/opentripplanner/netex/validation/AbstractHMapValidationRule.java
  src/main/java/org/opentripplanner/netex/validation/ServiceJourneyNonIncreasingPassingTime.java
  src/main/java/org/opentripplanner/netex/validation/Validator.java
  src/test/java/org/opentripplanner/netex/mapping/NetexTestDataSample.java
  src/test/java/org/opentripplanner/netex/validation/ServiceJourneyNonIncreasingPassingTimeTest.java
Labels: Entur test, NeTEx

#5058 Ride hailing improvements
  docs/RouterConfiguration.md
  docs/examples/ibi/portland/router-config.json
  docs/sandbox/RideHailing.md
  src/ext-test/java/org/opentripplanner/ext/ridehailing/FailingRideHailingService.java
  src/ext-test/java/org/opentripplanner/ext/ridehailing/RideHailingAccessAdapterTest.java
  src/ext-test/java/org/opentripplanner/ext/ridehailing/RideHailingAccessShifterTest.java
  src/ext-test/java/org/opentripplanner/ext/ridehailing/RideHailingFilterTest.java
  src/ext-test/java/org/opentripplanner/ext/ridehailing/TestRideHailingService.java
  src/ext-test/java/org/opentripplanner/ext/ridehailing/configure/RideHailingServicesModuleTest.java
  src/ext-test/java/org/opentripplanner/ext/ridehailing/service/uber/UberServiceTest.java
  src/ext/java/org/opentripplanner/ext/ridehailing/CachingRideHailingService.java
  src/ext/java/org/opentripplanner/ext/ridehailing/RideHailingAccessAdapter.java
  src/ext/java/org/opentripplanner/ext/ridehailing/RideHailingAccessShifter.java
  src/ext/java/org/opentripplanner/ext/ridehailing/RideHailingFilter.java
  src/ext/java/org/opentripplanner/ext/ridehailing/RideHailingService.java
  src/ext/java/org/opentripplanner/ext/ridehailing/RideHailingServiceParameters.java
  src/ext/java/org/opentripplanner/ext/ridehailing/model/ArrivalTime.java
  src/ext/java/org/opentripplanner/ext/ridehailing/model/Ride.java
  src/ext/java/org/opentripplanner/ext/ridehailing/model/RideEstimate.java
  src/ext/java/org/opentripplanner/ext/ridehailing/model/RideEstimateRequest.java
  src/ext/java/org/opentripplanner/ext/ridehailing/service/uber/UberService.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RouteRequestToFilterChainMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/graph/index/StreetIndex.java
  src/main/java/org/opentripplanner/routing/services/notes/StreetNotesService.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/services/UberConfig.java
  src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
  src/main/java/org/opentripplanner/street/search/TraverseMode.java
  src/main/java/org/opentripplanner/street/search/intersection_model/SimpleIntersectionTraversalCalculator.java
  src/main/java/org/opentripplanner/street/search/state/State.java
  src/main/java/org/opentripplanner/street/search/strategy/DominanceFunctions.java
  src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/DefaultAccessEgressTest.java
  src/test/java/org/opentripplanner/standalone/config/services/RideHailingServicesConfigTest.java
  src/test/java/org/opentripplanner/street/search/state/StateTest.java
  src/test/java/org/opentripplanner/street/search/state/TestStateBuilder.java
  src/test/resources/standalone/config/router-config.json
Labels: improvement, IBI, skip changelog

#5142 Remove broken Jersey tracing configuration
  src/main/java/org/opentripplanner/standalone/server/OTPWebApplication.java
Labels: technical debt

#5138 Add example JSON to route request documentation, move configuration to top level in menu
  doc-templates/RouteRequest.md
  docs/RouteRequest.md
  mkdocs.yml
  src/test/java/org/opentripplanner/generate/doc/RouteRequestDocTest.java
  src/test/java/org/opentripplanner/generate/doc/framework/JsonExampleBuilder.java
  src/test/java/org/opentripplanner/generate/doc/framework/TemplateUtil.java
Labels: documentation, skip changelog

#5139 Remove unused code
  src/main/java/org/opentripplanner/framework/io/XmlDataListDownloader.java
  src/main/java/org/opentripplanner/routing/linking/VertexLinker.java
  src/main/java/org/opentripplanner/transit/model/basic/EntityNotFoundException.java
  src/main/java/org/opentripplanner/updater/trip/GtfsRealtimeTripUpdateSource.java
  src/test/java/org/opentripplanner/framework/io/XmlDataListDownloaderTest.java
  src/test/resources/xml/test-data.xml
Labels: technical debt, skip changelog

#5136 Add stay seated test
  docs/RouteRequest.md
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/InterchangeType.java
  src/main/java/org/opentripplanner/graph_builder/module/interlining/InterlineProcessor.java
  src/main/java/org/opentripplanner/gtfs/mapping/TransferMapper.java
  src/main/java/org/opentripplanner/model/TripStopTimes.java
  src/main/java/org/opentripplanner/model/transfer/TransferConstraint.java
  src/main/java/org/opentripplanner/model/transfer/TransferPriority.java
  src/main/java/org/opentripplanner/netex/mapping/TransferMapper.java
  src/main/java/org/opentripplanner/raptor/api/request/DynamicSearchWindowCoefficients.java
  src/main/java/org/opentripplanner/routing/api/request/RouteRequest.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
  src/test/java/org/opentripplanner/model/transfer/ConstrainedTransferTest.java
  src/test/java/org/opentripplanner/model/transfer/TransferConstraintTest.java
  src/test/java/org/opentripplanner/model/transfer/TransferServiceTest.java
  src/test/java/org/opentripplanner/raptor/_data/transit/TestTransitData.java
  src/test/java/org/opentripplanner/raptor/api/path/PathTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/E01_StaySeatedTransferTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/E02_GuaranteedWalkTransferTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/E03_NotAllowedConstrainedTransferTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/ConstrainedBoardingSearchTest.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizePathDomainServiceConstrainedTest.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TestTransferBuilder.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGeneratorTest.java
Labels: technical debt, skip changelog

#5107 Add documentation about flex booking info, cleanup deprecated fields
  .github/workflows/cibuild.yml
  src/ext/resources/legacygraphqlapi/schema.graphqls
Labels: documentation, IBI, skip changelog

#5130 Graceful timeout error handling
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelAPI.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraph.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/support/AbortOnTimeoutExecutionStrategy.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/support/GraphQLToWebResponseMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/support/OtpExecutionResult.java
  src/main/java/org/opentripplanner/api/common/OTPExceptionMapper.java
  src/main/java/org/opentripplanner/api/resource/PlannerResource.java
  src/main/java/org/opentripplanner/framework/application/OTPRequestTimeoutException.java
  src/main/java/org/opentripplanner/framework/logging/ProgressTracker.java
  src/main/java/org/opentripplanner/framework/time/TimeUtils.java
  src/main/resources/logback.xml
Labels: bug, improvement, Entur test

#5137 Don't return null from StreetEdge#traverse
  src/main/java/org/opentripplanner/astar/AStar.java
  src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
  src/main/java/org/opentripplanner/street/search/state/State.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeGeofencingTest.java
Labels: bug, IBI, skip changelog

#5141 Fix vertex removal race condition
  src/ext/java/org/opentripplanner/ext/flex/edgetype/FlexTripEdge.java
  src/main/java/org/opentripplanner/graph_builder/module/GraphCoherencyCheckerModule.java
  src/main/java/org/opentripplanner/routing/graph/index/StreetIndex.java
  src/main/java/org/opentripplanner/routing/linking/VertexLinker.java
  src/main/java/org/opentripplanner/street/model/edge/Edge.java
  src/main/java/org/opentripplanner/street/model/vertex/Vertex.java
Labels: bug, technical debt, Entur test, bump serialization id
