Repository opentripplanner/OpenTripPlanner, pull requests merged in 2023-12, with the labels that each got.

#5528 Remove container images that have not been pulled for over a year
  .github/workflows/prune-container-images.yml
Labels: improvement, skip changelog

#5548 Add same submode in alternative legs filter
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/main/java/org/opentripplanner/routing/alternativelegs/AlternativeLegsFilter.java
Labels: improvement

#5552 Fix issue where stop points are sometimes added twice to index
  src/main/java/org/opentripplanner/netex/mapping/GroupNetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TransferMapper.java
Labels: bug

#5557 refactor: Add "-Dps" as alias for -P prettierSkip
  pom.xml
Labels: improvement, skip changelog

#5561 Relax TripTimes validation to [-12h, 20d] to allow support for "Hurtigruten"
  src/main/java/org/opentripplanner/transit/model/timetable/ScheduledTripTimes.java
  src/test/java/org/opentripplanner/transit/model/timetable/ScheduledTripTimesTest.java
Labels: bug, skip changelog

#5514 Improve shutdown logic
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/AbstractAzureSiriUpdater.java
  src/main/java/org/opentripplanner/framework/application/ApplicationShutdownSupport.java
  src/main/java/org/opentripplanner/standalone/OTPMain.java
  src/main/java/org/opentripplanner/standalone/OtpStartupInfo.java
  src/main/java/org/opentripplanner/standalone/server/GrizzlyServer.java
Labels: improvement, technical debt

#5542 Create TripOnServiceDate for new siri realtime servicejourneys
  src/ext-test/java/org/opentripplanner/ext/siri/AddedTripBuilderTest.java
  src/ext/java/org/opentripplanner/ext/siri/AddedTripBuilder.java
  src/ext/java/org/opentripplanner/ext/siri/EntityResolver.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
Labels: bug

#5569 Emissions data validation and reporting improvements
  src/ext-test/java/org/opentripplanner/ext/emissions/EmissionsModuleTest.java
  src/ext-test/resources/org/opentripplanner/ext/emissions/emissions-test-gtfs.zip
  src/ext-test/resources/org/opentripplanner/ext/emissions/emissions-test-gtfs/emissions.txt
  src/ext/java/org/opentripplanner/ext/emissions/Co2EmissionsDataReader.java
  src/ext/java/org/opentripplanner/ext/emissions/EmissionsModule.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
Labels: bug, sandbox, skip changelog

#5568 Orca Fares: No senior discount for cash payments
  src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
Labels: sandbox, IBI, skip changelog

#5565 Use TRIP_NOT_FOUND when Siri journey cannot be resolved
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETHttpTripUpdateSource.java
Labels: skip changelog

#5521 Create own parking preferences for bike and car in the internal model
  docs/RouteRequest.md
  docs/RouterConfiguration.md
  docs/examples/entur/router-config.json
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/DefaultRouteRequestType.java
  src/main/java/org/opentripplanner/api/common/RequestToPreferencesMapper.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/RouteRequestMapper.java
  src/main/java/org/opentripplanner/model/plan/Place.java
  src/main/java/org/opentripplanner/routing/api/request/preference/BikePreferences.java
  src/main/java/org/opentripplanner/routing/api/request/preference/CarPreferences.java
  src/main/java/org/opentripplanner/routing/api/request/preference/RoutingPreferences.java
  src/main/java/org/opentripplanner/routing/api/request/preference/VehicleParkingPreferences.java
  src/main/java/org/opentripplanner/routing/api/request/preference/filter/VehicleParkingFilter.java
  src/main/java/org/opentripplanner/routing/api/request/preference/filter/VehicleParkingSelect.java
  src/main/java/org/opentripplanner/routing/api/request/request/JourneyRequest.java
  src/main/java/org/opentripplanner/routing/api/request/request/VehicleParkingRequest.java
  src/main/java/org/opentripplanner/routing/api/request/request/filter/VehicleParkingFilterRequest.java
  src/main/java/org/opentripplanner/routing/vehicle_parking/VehicleParking.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  src/main/java/org/opentripplanner/street/model/edge/StreetVehicleParkingLink.java
  src/main/java/org/opentripplanner/street/model/edge/VehicleParkingEdge.java
  src/main/java/org/opentripplanner/street/search/request/StreetSearchRequest.java
  src/main/java/org/opentripplanner/street/search/request/StreetSearchRequestBuilder.java
  src/main/java/org/opentripplanner/street/search/request/StreetSearchRequestMapper.java
  src/test/java/org/opentripplanner/apis/gtfs/mapping/RouteRequestMapperTest.java
  src/test/java/org/opentripplanner/routing/api/request/preference/BikePreferencesTest.java
  src/test/java/org/opentripplanner/routing/api/request/preference/CarPreferencesTest.java
  src/test/java/org/opentripplanner/routing/api/request/preference/VehicleParkingPreferencesTest.java
  src/test/java/org/opentripplanner/street/integration/ParkAndRideTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetVehicleParkingLinkTest.java
  src/test/java/org/opentripplanner/street/model/edge/VehicleParkingEdgeTest.java
  src/test/java/org/opentripplanner/street/model/edge/VehicleParkingPreferredTagsTest.java
  src/test/resources/standalone/config/router-config.json
Labels: improvement, bump serialization id, config change

#5564 GTFS Flex spec update: separate columns for `location_id`, `location_group_id`
  pom.xml
  src/main/java/org/opentripplanner/gtfs/mapping/LocationGroupMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/StopTimeMapper.java
  src/test/java/org/opentripplanner/gtfs/mapping/StopTimeMapperTest.java
Labels: improvement, IBI

#5579 Include images into vite build process so urls are transformed correctly
  client-next/src/components/ItineraryList/ItineraryHeaderLegContent.tsx
  client-next/src/components/MapView/NavigationMarkers.tsx
  client-next/src/components/SearchBar/SearchBar.tsx
  client-next/src/static/img/marker-flag-end-shadowed.png
  client-next/src/static/img/marker-flag-start-shadowed.png
  client-next/src/static/img/mode/air.png
  client-next/src/static/img/mode/bicycle.png
  client-next/src/static/img/mode/bus.png
  client-next/src/static/img/mode/cableway.png
  client-next/src/static/img/mode/car.png
  client-next/src/static/img/mode/coach.png
  client-next/src/static/img/mode/foot.png
  client-next/src/static/img/mode/funicular.png
  client-next/src/static/img/mode/metro.png
  client-next/src/static/img/mode/monorail.png
  client-next/src/static/img/mode/rail.png
  client-next/src/static/img/mode/taxi.png
  client-next/src/static/img/mode/tram.png
  client-next/src/static/img/mode/trolleybus.png
  client-next/src/static/img/mode/water.png
  client-next/src/static/img/otp-logo.svg
Labels: improvement, skip changelog

#5570 Report NO_TRANSIT_CONNECTION when search-window is set.
  src/main/java/org/opentripplanner/apis/transmodel/model/EnumTypes.java
  src/main/java/org/opentripplanner/raptor/RaptorService.java
  src/main/java/org/opentripplanner/raptor/api/response/RaptorResponse.java
  src/main/java/org/opentripplanner/raptor/rangeraptor/standard/heuristics/HeuristicsAdapter.java
  src/main/java/org/opentripplanner/raptor/service/RangeRaptorDynamicSearch.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
Labels: bug

#5588 Warn if routing is empty and there are no errors in the result
  src/main/java/org/opentripplanner/routing/service/DefaultRoutingService.java
Labels: bug, skip changelog
