Repository opentripplanner/OpenTripPlanner, pull requests merged in 2023-07, with the labels that each got.

#5213 Refactor HTTP client
  src/ext/java/org/opentripplanner/ext/ridehailing/service/uber/UberService.java
  src/ext/java/org/opentripplanner/ext/siri/SiriHttpUtils.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETHttpTripUpdateSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriHttpLoader.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/AbstractAzureSiriUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslFacilitiesDownloader.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslHubsDownloader.java
  src/ext/java/org/opentripplanner/ext/vehiclerentalservicedirectory/VehicleRentalServiceDirectoryFetcher.java
  src/main/java/org/opentripplanner/datastore/https/HttpsDataSourceRepository.java
  src/main/java/org/opentripplanner/datastore/https/HttpsFileDataSource.java
  src/main/java/org/opentripplanner/framework/io/HttpUtils.java
  src/main/java/org/opentripplanner/framework/io/JsonDataListDownloader.java
  src/main/java/org/opentripplanner/framework/io/OtpHttpClient.java
  src/main/java/org/opentripplanner/framework/io/OtpHttpClientException.java
  src/main/java/org/opentripplanner/updater/alert/GtfsRealtimeAlertsUpdater.java
  src/main/java/org/opentripplanner/updater/trip/GtfsRealtimeTripUpdateSource.java
  src/main/java/org/opentripplanner/updater/vehicle_position/GtfsRealtimeHttpVehiclePositionSource.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFeedLoader.java
  src/test/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFeedLoaderTest.java
Labels: technical debt, Entur test

#5217 Fix fare leg rule mapper, introduce builder
  src/ext-test/java/org/opentripplanner/ext/fares/impl/GtfsFaresV2ServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/impl/GtfsFaresV2Service.java
  src/ext/java/org/opentripplanner/ext/fares/model/Distance.java
  src/ext/java/org/opentripplanner/ext/fares/model/FareLegRule.java
  src/ext/java/org/opentripplanner/ext/fares/model/FareLegRuleBuilder.java
  src/main/java/org/opentripplanner/datastore/https/HttpsDataSourceRepository.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModule.java
  src/main/java/org/opentripplanner/gtfs/mapping/FareLegRuleMapper.java
  src/main/java/org/opentripplanner/updater/vehicle_position/VehiclePositionPatternMatcher.java
  src/test/java/org/opentripplanner/gtfs/mapping/FareLegRuleMapperTest.java
  src/test/java/org/opentripplanner/transit/model/timetable/TripTimesTest.java
Labels: bug, technical debt, skip changelog

#5046 Add escalator reluctance parameter
  docs/RouteRequest.md
  docs/RouterConfiguration.md
  src/main/java/org/opentripplanner/graph_builder/module/osm/ElevatorProcessor.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/EscalatorProcessor.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModule.java
  src/main/java/org/opentripplanner/inspector/raster/TraversalPermissionsEdgeRenderer.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWay.java
  src/main/java/org/opentripplanner/routing/api/request/preference/WalkPreferences.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  src/main/java/org/opentripplanner/street/model/edge/EscalatorEdge.java
  src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
  src/main/resources/WayProperties.properties
  src/main/resources/WayProperties_de.properties
  src/main/resources/WayProperties_fi.properties
  src/test/java/org/opentripplanner/street/model/edge/EscalatorEdgeTest.java
  src/test/resources/standalone/config/router-config.json
Labels: new feature

#5228 Upgrade to Apache HTTP Client 5
  pom.xml
  src/ext/java/org/opentripplanner/ext/actuator/ActuatorAPI.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java
  src/main/java/org/opentripplanner/datastore/https/HttpsDataSourceMetadata.java
  src/main/java/org/opentripplanner/datastore/https/HttpsDataSourceRepository.java
  src/main/java/org/opentripplanner/framework/io/OtpHttpClient.java
  src/main/java/org/opentripplanner/standalone/server/EtagRequestFilter.java
  src/main/java/org/opentripplanner/updater/spi/PollingGraphUpdater.java
  src/main/resources/logback.xml
  src/test/java/org/opentripplanner/datastore/DataStoreArchitectureTest.java
  src/test/java/org/opentripplanner/datastore/https/HttpsDataSourceRepositoryTest.java
  src/test/java/org/opentripplanner/datastore/https/HttpsFileDataSourceTest.java
  src/test/java/org/opentripplanner/framework/FrameworkArchitectureTest.java
Labels: technical debt

#5229 Update error code documentation, restructure config docs
  docs/RouteRequest.md
  docs/archive/RoutingModes.md
  mkdocs.yml
  src/ext-test/java/org/opentripplanner/ext/gtfsgraphqlapi/mapping/RouteRequestMapperTest.java
  src/ext/resources/gtfsgraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/routing/api/request/request/filter/SelectRequest.java
  src/test/java/org/opentripplanner/generate/doc/RouteRequestDocTest.java
Labels: documentation, IBI, skip changelog

#5237 Fix duplicate publishing of speed test data
  src/test/java/org/opentripplanner/transit/speed_test/model/timer/MeterRegistrySetup.java
  src/test/java/org/opentripplanner/transit/speed_test/model/timer/SpeedTestTimer.java
Labels: bug

#5240 Provide default implementation for checkInputs()
  src/ext/java/org/opentripplanner/ext/dataoverlay/EdgeUpdaterModule.java
  src/ext/java/org/opentripplanner/ext/flex/FlexLocationsToStreetEdgesMapper.java
  src/ext/java/org/opentripplanner/ext/transferanalyzer/DirectTransferAnalyzer.java
  src/main/java/org/opentripplanner/graph_builder/issue/report/DataImportIssueReporter.java
  src/main/java/org/opentripplanner/graph_builder/model/GraphBuilderModule.java
  src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
  src/main/java/org/opentripplanner/graph_builder/module/GraphCoherencyCheckerModule.java
  src/main/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModule.java
  src/main/java/org/opentripplanner/graph_builder/module/StreetLinkerModule.java
  src/main/java/org/opentripplanner/graph_builder/module/TimeZoneAdjusterModule.java
  src/main/java/org/opentripplanner/graph_builder/module/TripPatternNamer.java
  src/main/java/org/opentripplanner/graph_builder/module/geometry/CalculateWorldEnvelopeModule.java
  src/main/java/org/opentripplanner/graph_builder/module/islandpruning/PruneIslands.java
  src/main/java/org/opentripplanner/graph_builder/module/map/BusRouteStreetMatcher.java
Labels: technical debt, skip changelog

#5233 Flex build time and memory optimization for large zones
  .github/workflows/cibuild.yml
  src/ext-test/java/org/opentripplanner/ext/flex/AreaStopsToVerticesMapperTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  src/ext/java/org/opentripplanner/ext/flex/AreaStopsToVerticesMapper.java
  src/ext/java/org/opentripplanner/ext/flex/FlexLocationsToStreetEdgesMapper.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderFactory.java
  src/main/java/org/opentripplanner/routing/linking/FlexLocationAdder.java
  src/main/java/org/opentripplanner/street/model/vertex/StreetVertex.java
  src/test/java/org/opentripplanner/_support/geometry/Coordinates.java
  src/test/java/org/opentripplanner/_support/geometry/Polygons.java
  src/test/java/org/opentripplanner/street/model/_data/StreetModelForTest.java
  src/test/java/org/opentripplanner/street/model/vertex/OsmVertexTest.java
Labels: optimization, technical debt, IBI

#5242 Fix pathway traversal time calculation when none is supplied
  src/main/java/org/opentripplanner/street/model/edge/PathwayEdge.java
  src/test/java/org/opentripplanner/street/model/edge/PathwayEdgeTest.java
Labels: bug

#5250 Remove unused code
  src/main/java/org/opentripplanner/gtfs/MockGtfs.java
  src/test/java/org/opentripplanner/gtfs/GtfsContext.java
Labels: technical debt, skip changelog

#5192 Improve error handling in TransmodelGraph
  src/ext-test/java/org/opentripplanner/ext/transmodelapi/support/ExecutionResultMapperTest.java
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/GraphQLUtils.java
  src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/generated/GraphQLTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelAPI.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraph.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/support/AbortOnTimeoutExecutionStrategy.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/support/ExecutionResultMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/support/GraphQLToWebResponseMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/support/OTPProcessingTimeoutGraphQLException.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/support/OtpExecutionResult.java
  src/ext/resources/gtfsgraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/api/common/OTPExceptionMapper.java
  src/main/java/org/opentripplanner/api/mapping/PlannerErrorMapper.java
  src/main/java/org/opentripplanner/api/model/error/PlannerError.java
  src/main/java/org/opentripplanner/api/resource/PlannerResource.java
  src/main/java/org/opentripplanner/framework/http/OtpHttpStatus.java
  src/main/java/org/opentripplanner/routing/api/response/RoutingErrorCode.java
Labels: improvement, sandbox, technical debt

#5243 Replace `walkDistance` with `streetDistance` in TransmodelAPI
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripPatternType.java
Labels: improvement, sandbox, skip changelog

#5246 Remove name from vertex constructor chain
  src/ext-test/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTripTest.java
  src/main/java/org/opentripplanner/routing/vehicle_parking/VehicleParkingEntrance.java
  src/main/java/org/opentripplanner/service/vehiclerental/street/VehicleRentalPlaceVertex.java
  src/main/java/org/opentripplanner/street/model/vertex/ElevatorOffboardVertex.java
  src/main/java/org/opentripplanner/street/model/vertex/ElevatorOnboardVertex.java
  src/main/java/org/opentripplanner/street/model/vertex/IntersectionVertex.java
  src/main/java/org/opentripplanner/street/model/vertex/LabelledIntersectionVertex.java
  src/main/java/org/opentripplanner/street/model/vertex/OsmBoardingLocationVertex.java
  src/main/java/org/opentripplanner/street/model/vertex/OsmVertex.java
  src/main/java/org/opentripplanner/street/model/vertex/SplitterVertex.java
  src/main/java/org/opentripplanner/street/model/vertex/StationElementVertex.java
  src/main/java/org/opentripplanner/street/model/vertex/StreetLocation.java
  src/main/java/org/opentripplanner/street/model/vertex/StreetVertex.java
  src/main/java/org/opentripplanner/street/model/vertex/TransitStopVertex.java
  src/main/java/org/opentripplanner/street/model/vertex/VehicleParkingEntranceVertex.java
  src/main/java/org/opentripplanner/street/model/vertex/Vertex.java
  src/main/java/org/opentripplanner/street/model/vertex/VertexFactory.java
  src/test/java/org/opentripplanner/graph_builder/linking/LinkStopToPlatformTest.java
  src/test/java/org/opentripplanner/graph_builder/module/geometry/CalculateWorldEnvelopeModuleTest.java
  src/test/java/org/opentripplanner/street/model/_data/StreetModelForTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeTest.java
  src/test/java/org/opentripplanner/street/model/vertex/IntersectionVertexTest.java
  src/test/java/org/opentripplanner/street/model/vertex/SimpleVertex.java
  src/test/java/org/opentripplanner/street/model/vertex/TemporaryVertexDisposeTest.java
  src/test/java/org/opentripplanner/street/search/intersection_model/SimpleIntersectionTraversalCalculatorTest.java
Labels: optimization, technical debt, bump serialization id, skip changelog

#5256 Insert escalators into graph after construction
  src/main/java/org/opentripplanner/graph_builder/module/osm/EscalatorProcessor.java
  src/main/java/org/opentripplanner/street/model/edge/EscalatorEdge.java
  src/test/java/org/opentripplanner/street/model/edge/ElevatorHopEdgeTest.java
  src/test/java/org/opentripplanner/street/model/edge/EscalatorEdgeTest.java
  src/test/java/org/opentripplanner/street/model/edge/PathwayEdgeTest.java
Labels: bug, bump serialization id, skip changelog

#5251 Fix content type of vector tiles 404
  src/main/java/org/opentripplanner/framework/io/HttpUtils.java
  src/main/java/org/opentripplanner/inspector/vector/VectorTileResponseFactory.java
  src/test/java/org/opentripplanner/inspector/vector/VectorTileResponseFactoryTest.java
Labels: bug, skip changelog

#5260 Disable nynorsk money tests
  src/test/java/org/opentripplanner/routing/core/MoneyTest.java
Labels: Regression, Entur test, skip changelog

#5262 Fix SIRI SX retry logic
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETHttpTripUpdateSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriHttpLoader.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
Labels: bug, Entur test, RealTimeUpdate

#5258 Remove migration guide, introduce GraphQL tutorial
  doc-templates/Configuration.md
  doc-templates/GraphQL-Tutorial.md
  docs/Apis-Data-Sources.md
  docs/Apis.md
  docs/Changelog.md
  docs/Configuration.md
  docs/Data-Sources.md
  docs/GraphQL-Tutorial.md
  docs/OTP2-MigrationGuide.md
  docs/Version-Comparison.md
  docs/images/graphiql-autocomplete.png
  docs/images/graphiql-documentation.png
  docs/index.md
  mkdocs.yml
  src/ext-test/resources/gtfsgraphqlapi/expectations/plan-extended.json
  src/ext-test/resources/gtfsgraphqlapi/expectations/plan.json
  src/ext-test/resources/gtfsgraphqlapi/queries/plan-extended.graphql
  src/ext-test/resources/gtfsgraphqlapi/queries/plan.graphql
  src/test/java/org/opentripplanner/generate/doc/GraphQLTutorialDocTest.java
  src/test/java/org/opentripplanner/generate/doc/framework/TemplateUtil.java
Labels: documentation, skip changelog

#5254 Configure scheduled thread pool for polling updaters
  src/main/java/org/opentripplanner/standalone/server/MetricsLogging.java
  src/main/java/org/opentripplanner/updater/GraphUpdaterManager.java
  src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
  src/main/java/org/opentripplanner/updater/spi/PollingGraphUpdater.java
  src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdater.java
  src/test/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingUpdaterTest.java
  src/test/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdaterTest.java
Labels: technical debt, RealTimeUpdate, skip changelog
