Repository opentripplanner/OpenTripPlanner, pull requests merged in 2023-09, with the labels that each got.

#5350 Exclude OBA's slf4j-simple
  pom.xml
Labels: technical debt, skip changelog

#5328 Refactor tag handling during OSM parsing
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/mapper/AffectsMapper.java
  src/main/java/org/opentripplanner/graph_builder/issues/TooManyAreasInRelation.java
  src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryProcessor.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/ElevatorProcessor.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmDatabase.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmFilter.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  src/main/java/org/opentripplanner/gtfs/mapping/TransferMapper.java
  src/main/java/org/opentripplanner/model/plan/pagecursor/PageCursorSerializer.java
  src/main/java/org/opentripplanner/netex/mapping/NoticeAssignmentMapper.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMNode.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMRelation.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMRelationMember.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWay.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/specifier/Condition.java
  src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  src/main/java/org/opentripplanner/standalone/config/framework/json/ParameterBuilder.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapParserTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilderTest.java
  src/test/java/org/opentripplanner/openstreetmap/model/BicycleNetworkRelationsTest.java
  src/test/java/org/opentripplanner/openstreetmap/model/OSMWayTest.java
  src/test/java/org/opentripplanner/openstreetmap/model/OSMWithTagsTest.java
  src/test/java/org/opentripplanner/openstreetmap/wayproperty/specifier/WayTestData.java
Labels: technical debt, skip changelog

#5349 Gracefully handle nullable fields in TransitAlert
  src/ext-test/java/org/opentripplanner/ext/gtfsgraphqlapi/GraphQLIntegrationTest.java
  src/ext-test/java/org/opentripplanner/ext/gtfsgraphqlapi/mapping/StreetNoteMapperTest.java
  src/ext-test/resources/gtfsgraphqlapi/expectations/alerts.json
  src/ext-test/resources/gtfsgraphqlapi/queries/alerts.graphql
  src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/datafetchers/AlertImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/sx/PtSituationElementType.java
  src/main/java/org/opentripplanner/api/mapping/AlertMapper.java
  src/main/java/org/opentripplanner/routing/alertpatch/TransitAlert.java
  src/main/java/org/opentripplanner/routing/alertpatch/TransitAlertBuilder.java
  src/test/java/org/opentripplanner/_support/text/I18NStrings.java
  src/test/java/org/opentripplanner/updater/alert/AlertsUpdateHandlerTest.java
Labels: technical debt

#5355 Remove ice roads from Finland routing
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/FinlandMapper.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/FinlandMapperTest.java
Labels: skip changelog, HSL

#5284 Consider feed id in HSL fare service
  src/ext-test/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/FareModelForTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/HSLFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/HSLFareServiceImpl.java
  src/test/java/org/opentripplanner/transit/model/_data/TransitModelForTest.java
Labels: sandbox, skip changelog

#5357 Fix race condition in GtfsModuleTest
  src/test/java/org/opentripplanner/graph_builder/module/GtfsModuleTest.java
Labels: technical debt, skip changelog

#5341 Remove banDiscouragedCycling and banDiscouragedWalking
  docs/BuildConfiguration.md
  docs/examples/entur/build-config.json
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmFilter.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModuleBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/parameters/OsmProcessingParameters.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/DefaultMapper.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/DefaultMapperTest.java
  test/performance/norway/build-config.json
Labels: technical debt, bump serialization id, config change

#5363 Add ID to mapper error messages
  src/main/java/org/opentripplanner/gtfs/mapping/StationMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/StopMapper.java
Labels: GTFS, technical debt, skip changelog, NVBW

#5358 Refactor OSM permissions
  src/ext-test/java/org/opentripplanner/ext/gtfsgraphqlapi/GraphQLIntegrationTest.java
  src/ext/java/org/opentripplanner/ext/reportapi/model/BicycleSafetyReport.java
  src/main/java/org/opentripplanner/graph_builder/issues/ConflictingBikeTags.java
  src/main/java/org/opentripplanner/graph_builder/issues/DisconnectedOsmNode.java
  src/main/java/org/opentripplanner/graph_builder/issues/InvalidOsmGeometry.java
  src/main/java/org/opentripplanner/graph_builder/issues/InvalidVehicleParkingCapacity.java
  src/main/java/org/opentripplanner/graph_builder/issues/LevelAmbiguous.java
  src/main/java/org/opentripplanner/graph_builder/issues/ParkAndRideUnlinked.java
  src/main/java/org/opentripplanner/graph_builder/issues/StreetCarSpeedZero.java
  src/main/java/org/opentripplanner/graph_builder/issues/TurnRestrictionUnknown.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/Area.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/AreaTooComplicated.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/ElevatorProcessor.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmDatabase.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmFilter.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/ParkingProcessor.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/SafetyValueNormalizer.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/UnconnectedArea.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/VertexGenerator.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMNode.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMRelation.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWay.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/NorwayMapper.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/MixinPropertiesBuilder.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/SafetyFeatures.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/WayProperties.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/WayPropertiesBuilder.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/WayPropertySet.java
  src/main/java/org/opentripplanner/street/model/StreetTraversalPermission.java
  src/main/java/org/opentripplanner/transit/service/TransitModel.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OsmModuleTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilderTest.java
  src/test/java/org/opentripplanner/openstreetmap/model/OSMNodeTest.java
  src/test/java/org/opentripplanner/openstreetmap/model/OSMWayTest.java
  src/test/java/org/opentripplanner/openstreetmap/model/OSMWithTagsTest.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/DefaultMapperTest.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/FinlandMapperTest.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/GermanyMapperTest.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/NorwayMapperTest.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/OsmTagMapperTest.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/PortlandMapperTest.java
  src/test/java/org/opentripplanner/openstreetmap/wayproperty/WayPropertySetTest.java
  src/test/java/org/opentripplanner/street/model/vertex/BarrierVertexTest.java
  src/test/resources/org/opentripplanner/graph_builder/module/osm/wendlingen-bahnhof.osm.pbf
Labels: technical debt, skip changelog

#5361 Fix rental scooter access
  .gitignore
  src/main/java/org/opentripplanner/astar/spi/AStarEdge.java
  src/main/java/org/opentripplanner/street/model/edge/StreetTransitEntityLink.java
  src/main/java/org/opentripplanner/street/search/state/State.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/AccessEgressPenaltyDecoratorTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/DefaultAccessEgressTest.java
  src/test/java/org/opentripplanner/service/vehiclerental/model/TestFreeFloatingRentalVehicleBuilder.java
  src/test/java/org/opentripplanner/service/vehiclerental/model/TestVehicleRentalStationBuilder.java
  src/test/java/org/opentripplanner/street/model/edge/StreetTransitEntityLinkTest.java
  src/test/java/org/opentripplanner/street/search/state/StateTest.java
  src/test/java/org/opentripplanner/street/search/state/TestStateBuilder.java
Labels: bug, Vehicle rental

#5367 Fix issue with null headers in HSL park updater
  src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkUpdater.java
  src/main/java/org/opentripplanner/framework/io/JsonDataListDownloader.java
Labels: bug, sandbox, skip changelog

#5368 Fix value mapping for bikesAllowed in GTFS GraphQL API
  docs/GraphQL-Tutorial.md
  src/ext-test/java/org/opentripplanner/ext/gtfsgraphqlapi/mapping/BikesAllowedMapperTest.java
  src/ext-test/resources/gtfsgraphqlapi/expectations/routes.json
  src/ext-test/resources/gtfsgraphqlapi/queries/routes.graphql
  src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/datafetchers/RouteImpl.java
  src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/datafetchers/TripImpl.java
  src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/generated/GraphQLDataFetchers.java
  src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/generated/graphql-codegen.yml
  src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/mapping/BikesAllowedMapper.java
Labels: bug

#5375 Improve logging message for negative travel time
  src/main/java/org/opentripplanner/raptor/rangeraptor/transit/RaptorSearchWindowCalculator.java
Labels: skip changelog

#5329 Fix filtering of rental vehicle in vehicle station BBox search
  src/main/java/org/opentripplanner/service/vehiclerental/VehicleRentalService.java
  src/main/java/org/opentripplanner/service/vehiclerental/internal/DefaultVehicleRentalService.java
  src/test/java/org/opentripplanner/service/vehiclerental/internal/DefaultVehicleRentalServiceTest.java
  src/test/java/org/opentripplanner/service/vehiclerental/model/TestFreeFloatingRentalVehicleBuilder.java
  src/test/java/org/opentripplanner/service/vehiclerental/model/TestVehicleRentalStationBuilder.java
Labels: bug, Entur test, skip changelog, Vehicle rental

#5373 Minor performance fixes
  src/ext/java/org/opentripplanner/ext/siri/SiriTripPatternCache.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslFacilitiesDownloader.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslHubToVehicleParkingGroupMapper.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslHubsDownloader.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkToVehicleParkingMapper.java
  src/main/java/org/opentripplanner/framework/geometry/GeometryUtils.java
  src/main/java/org/opentripplanner/framework/io/JsonDataListDownloader.java
  src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryProcessor.java
  src/main/java/org/opentripplanner/graph_builder/module/islandpruning/PruneIslands.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/AreaGroup.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/Ring.java
  src/main/java/org/opentripplanner/inspector/raster/NoThruTrafficEdgeRenderer.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMLevel.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/WayPropertySet.java
  src/main/java/org/opentripplanner/standalone/config/CommandLineParameters.java
  src/test/java/org/opentripplanner/astar/model/BinHeapTest.java
Labels: technical debt, skip changelog

#5383 Fix barrier vertex pruning test
  src/main/java/org/opentripplanner/openstreetmap/model/OSMNode.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OsmModuleTest.java
Labels: bug, skip changelog

#5359 Add checklist item for GitHub maintenance in release checklist
  docs/ReleaseChecklist.md
Labels: release management, documentation, skip changelog
