Repository opentripplanner/OpenTripPlanner, pull requests merged in 2023-08, with the labels that each got.

#5261 Fix filtering by submode
  src/main/java/org/opentripplanner/routing/api/request/request/filter/SelectRequest.java
  src/main/java/org/opentripplanner/routing/api/request/request/filter/TransitFilterRequest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RouteRequestTransitDataProviderFilterTest.java
  src/test/java/org/opentripplanner/transit/model/_data/TransitModelForTest.java
Labels: bug, Entur test

#5283 Adding minor notes to Container-Image.md doc file
  docs/Container-Image.md
Labels: documentation, skip changelog

#5264 Limit retry attempts in SIRI-SX updater
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
  src/main/java/org/opentripplanner/framework/retry/OtpRetry.java
  src/main/java/org/opentripplanner/framework/retry/OtpRetryBuilder.java
  src/main/java/org/opentripplanner/framework/retry/OtpRetryException.java
  src/test/java/org/opentripplanner/framework/retry/OtpRetryTest.java
Labels: improvement, Entur test, RealTimeUpdate, skip changelog

#5263 Add illustrations to fare docs, upgrade GraphiQL
  .github/workflows/cibuild.yml
  src/client/graphiql/index.html
  src/ext/resources/gtfsgraphqlapi/schema.graphqls
Labels: documentation, IBI, skip changelog

#5290 Add leg.headsign to GTFS GraphQL API
  src/ext-test/java/org/opentripplanner/ext/gtfsgraphqlapi/GraphQLIntegrationTest.java
  src/ext-test/resources/gtfsgraphqlapi/expectations/patterns.json
  src/ext-test/resources/gtfsgraphqlapi/expectations/plan-extended.json
  src/ext-test/resources/gtfsgraphqlapi/queries/patterns.graphql
  src/ext-test/resources/gtfsgraphqlapi/queries/plan-extended.graphql
  src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/datafetchers/LegImpl.java
  src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/generated/GraphQLDataFetchers.java
  src/ext/resources/gtfsgraphqlapi/schema.graphqls
  src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
  src/test/java/org/opentripplanner/transit/model/_data/TransitModelForTest.java
Labels: IBI

#5277 Return client error for invalid Transmodel query JSON format
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelAPI.java
Labels: improvement

#5253 Validate missing intermediate location in via requests
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/ViaLocationMapper.java
  src/main/java/org/opentripplanner/api/common/Message.java
  src/main/java/org/opentripplanner/api/mapping/PlannerErrorMapper.java
  src/main/java/org/opentripplanner/routing/api/request/ViaLocation.java
  src/main/resources/Message.properties
  src/main/resources/Message_de.properties
  src/main/resources/Message_es.properties
  src/main/resources/Message_fr.properties
  src/main/resources/Message_hu.properties
  src/main/resources/Message_nl.properties
Labels: bug, Entur test

#5274 Refactor copy properties from parent edge to split edge
  src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/MissingElevationHandler.java
  src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
  src/main/java/org/opentripplanner/street/model/edge/StreetEdgeBuilder.java
  src/main/java/org/opentripplanner/street/model/edge/StreetElevationExtension.java
  src/main/java/org/opentripplanner/street/model/edge/StreetElevationExtensionBuilder.java
  src/test/java/org/opentripplanner/graph_builder/module/ned/MissingElevationHandlerTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeWheelchairCostTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetElevationExtensionBuilderTest.java
Labels: technical debt, skip changelog

#5285 Improve walk step narrative for entering/exiting stations and signposted pathways
  src/client/images/directions/enter_station.png
  src/client/images/directions/exit_station.png
  src/client/images/directions/follow_signs.png
  src/ext-test/java/org/opentripplanner/ext/gtfsgraphqlapi/GraphQLIntegrationTest.java
  src/ext-test/java/org/opentripplanner/ext/gtfsgraphqlapi/mapping/DirectionMapperTest.java
  src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/datafetchers/stepImpl.java
  src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/generated/GraphQLTypes.java
  src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/mapping/DirectionMapper.java
  src/ext/resources/gtfsgraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/api/mapping/RelativeDirectionMapper.java
  src/main/java/org/opentripplanner/api/model/ApiRelativeDirection.java
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/gtfs/mapping/PathwayMapper.java
  src/main/java/org/opentripplanner/model/plan/RelativeDirection.java
  src/main/java/org/opentripplanner/model/plan/WalkStep.java
  src/main/java/org/opentripplanner/model/plan/WalkStepBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapper.java
  src/main/java/org/opentripplanner/routing/services/notes/StreetNotesService.java
  src/main/java/org/opentripplanner/street/model/edge/PathwayEdge.java
  src/main/java/org/opentripplanner/street/model/edge/StreetTransitEntityLink.java
  src/main/java/org/opentripplanner/street/model/edge/StreetTransitEntranceLink.java
  src/main/java/org/opentripplanner/street/search/state/State.java
  src/main/java/org/opentripplanner/street/search/state/StateEditor.java
  src/main/java/org/opentripplanner/transit/model/site/Pathway.java
  src/main/java/org/opentripplanner/transit/model/site/PathwayBuilder.java
  src/test/java/org/opentripplanner/model/plan/WalkStepTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapperTest.java
  src/test/java/org/opentripplanner/street/model/_data/StreetModelForTest.java
  src/test/java/org/opentripplanner/street/model/edge/PathwayEdgeTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetTransitEntranceLinkTest.java
  src/test/java/org/opentripplanner/street/search/state/TestStateBuilder.java
  src/test/java/org/opentripplanner/transit/model/site/PathwayTest.java
Labels: improvement, technical debt, IBI, bump serialization id

#5292 Map CoercingParseValueException
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraph.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/support/ExecutionResultMapper.java
  src/main/java/org/opentripplanner/api/common/OTPExceptionMapper.java
Labels: Regression, skip changelog

#5304 Add support for decimal numbers in the constant part of a linear function
  src/main/java/org/opentripplanner/routing/api/request/framework/LinearFunctionSerialization.java
  src/test/java/org/opentripplanner/routing/api/request/framework/LinearFunctionSerializationTest.java
  src/test/java/org/opentripplanner/test/support/TestTableParser.java
Labels: bug, Entur test, skip changelog

#5310 Fix walk board cost comparison and add escalatorReluctance to hash
  src/main/java/org/opentripplanner/routing/api/request/preference/WalkPreferences.java
  src/test/java/org/opentripplanner/routing/api/request/preference/ImmutablePreferencesAsserts.java
  src/test/java/org/opentripplanner/routing/api/request/preference/WalkPreferencesTest.java
Labels: bug

#5314 Fix concurrent modification exception in vehicle rental service
  src/main/java/org/opentripplanner/service/vehiclerental/internal/DefaultVehicleRentalService.java
Labels: bug, skip changelog, Vehicle rental

#5271 Generate RoutingMode documentation from StreetMode and TransportMode enumerations
  doc-templates/RoutingModes.md
  docs/RoutingModes.md
  docs/archive/RoutingModes.md
  mkdocs.yml
  src/main/java/org/opentripplanner/routing/api/request/StreetMode.java
  src/main/java/org/opentripplanner/transit/model/basic/TransitMode.java
  src/test/java/org/opentripplanner/OtpArchitectureModules.java
  src/test/java/org/opentripplanner/generate/doc/RoutingModeDocTest.java
Labels: documentation, skip changelog

#5296 Map mismatched input exception
  src/main/java/org/opentripplanner/api/common/OTPExceptionMapper.java
Labels: improvement, skip changelog

#5214 Stop count limit for access/egress routing and new accessEgress configuration object
  docs/RouteRequest.md
  docs/RouterConfiguration.md
  docs/examples/entur/router-config.json
  src/ext-test/java/org/opentripplanner/ext/transmodelapi/mapping/TripRequestMapperTest.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/preferences/StreetPreferencesMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
  src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeResource.java
  src/main/java/org/opentripplanner/astar/strategy/MaxCountSkipEdgeStrategy.java
  src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/AccessEgressRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectFlexRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/FlexAccessEgressRouter.java
  src/main/java/org/opentripplanner/routing/api/request/preference/AccessEgressPreferences.java
  src/main/java/org/opentripplanner/routing/api/request/preference/StreetPreferences.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  src/test/java/org/opentripplanner/astar/strategy/MaxCountSkipEdgeStrategyTest.java
  src/test/java/org/opentripplanner/routing/api/request/preference/StreetPreferencesTest.java
  src/test/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfigTest.java
  src/test/java/org/opentripplanner/street/search/state/TestStateBuilder.java
  src/test/resources/speedtest/travelSearch-expected-results-bd.csv
  src/test/resources/standalone/config/router-config.json
Labels: improvement, optimization, config change

#5297 Refactor SIRI-ET PubSub updater
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/main/java/org/opentripplanner/updater/GraphUpdaterManager.java
Labels: technical debt, RealTimeUpdate, skip changelog

#5303 Remove pathway id from REST API
  src/ext-test/java/org/opentripplanner/ext/gtfsgraphqlapi/GraphQLIntegrationTest.java
  src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/datafetchers/stepImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/PathGuidanceType.java
  src/main/java/org/opentripplanner/api/mapping/LegMapper.java
  src/main/java/org/opentripplanner/api/mapping/WalkStepMapper.java
  src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/model/plan/StreetLeg.java
  src/main/java/org/opentripplanner/model/plan/StreetLegBuilder.java
  src/main/java/org/opentripplanner/model/plan/WalkStep.java
  src/main/java/org/opentripplanner/model/plan/WalkStepBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapper.java
  src/main/java/org/opentripplanner/street/model/edge/ElevatorHopEdge.java
  src/main/java/org/opentripplanner/street/model/edge/PathwayEdge.java
  src/test/java/org/opentripplanner/model/plan/WalkStepTest.java
  src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapperTest.java
  src/test/java/org/opentripplanner/street/model/edge/PathwayEdgeTest.java
  src/test/java/org/opentripplanner/street/search/state/TestStateBuilder.java
Labels: technical debt

#5316 Rename FeedScopeId.parseId to FeedScopedId.parse
  src/ext/java/org/opentripplanner/ext/geocoder/LuceneIndex.java
  src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/datafetchers/QueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/datafetchers/StopImpl.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/TransitIdMapper.java
  src/main/java/org/opentripplanner/api/common/LocationStringParser.java
  src/main/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializer.java
  src/main/java/org/opentripplanner/routing/api/request/request/TransitRequest.java
  src/main/java/org/opentripplanner/routing/api/request/request/filter/SelectRequest.java
  src/main/java/org/opentripplanner/routing/graphfinder/PatternAtStop.java
  src/main/java/org/opentripplanner/standalone/config/framework/json/ParameterBuilder.java
  src/main/java/org/opentripplanner/transit/model/framework/FeedScopedId.java
  src/test/java/org/opentripplanner/routing/algorithm/FilterTest.java
  src/test/java/org/opentripplanner/transit/model/network/RouteTest.java
  src/test/java/org/opentripplanner/transit/model/timetable/TripTest.java
Labels: technical debt, skip changelog

#5305 Remove Winkki street note updater
  pom.xml
  src/main/java/org/opentripplanner/routing/services/notes/DynamicStreetNotesSource.java
  src/main/java/org/opentripplanner/routing/services/notes/StreetNoteModel.java
  src/main/java/org/opentripplanner/routing/services/notes/StreetNotesService.java
  src/main/java/org/opentripplanner/routing/services/notes/StreetNotesSource.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/UpdatersConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/WFSNotePollingGraphUpdaterConfig.java
  src/main/java/org/opentripplanner/updater/UpdatersParameters.java
  src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
  src/main/java/org/opentripplanner/updater/street_note/WFSNotePollingGraphUpdater.java
  src/main/java/org/opentripplanner/updater/street_note/WFSNotePollingGraphUpdaterParameters.java
  src/main/java/org/opentripplanner/updater/street_note/WinkkiPollingGraphUpdater.java
Labels: technical debt

#5319 Extend stop area relation linking to include bus stop and platform nodes
  docs/BoardingLocations.md
  docs/StopAreas.md
  src/main/java/org/opentripplanner/graph_builder/module/islandpruning/PruneIslands.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmDatabase.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  src/main/java/org/opentripplanner/inspector/raster/AreaEdgeRenderer.java
  src/main/java/org/opentripplanner/openstreetmap/OpenStreetMapParser.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMMemberType.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMRelationMember.java
  src/main/java/org/opentripplanner/routing/linking/VertexLinker.java
  src/main/java/org/opentripplanner/street/model/edge/AreaEdgeList.java
  src/test/java/org/opentripplanner/graph_builder/linking/LinkStopToPlatformTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilderTest.java
  src/test/resources/org/opentripplanner/graph_builder/module/osm/stopareas.pbf
Labels: bug, bump serialization id

#5315 Retry on failed SIRI-ET Pubsub subscription creation
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
  src/main/java/org/opentripplanner/framework/retry/OtpRetry.java
  src/test/java/org/opentripplanner/framework/retry/OtpRetryTest.java
Labels: bug, Entur test, RealTimeUpdate, skip changelog

#5321 Document in-station navigation
  docs/In-Station-Navigation.md
  docs/RouteRequest.md
  docs/images/boarding-schwabstrasse.png
  docs/images/exiting-oesterfeld.png
  docs/images/transfer-oslo-1.png
  docs/images/transfer-oslo-2.png
  docs/images/transfer-suedkreuz.png
  mkdocs.yml
  src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
Labels: documentation, NVBW

#5336 Parse NeTEx Resource frame without organisation
  src/main/java/org/opentripplanner/netex/loader/parser/ResourceFrameParser.java
  src/test/java/org/opentripplanner/netex/loader/parser/ResourceFrameParserTest.java
Labels: bug, Entur test, skip changelog

#5268 Add access/egress penalty transmodel api
  docs/RouteRequest.md
  docs/RouterConfiguration.md
  docs/examples/entur/router-config.json
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/interactivelauncher/DebugLoggingSupport.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/preferences/StreetPreferencesMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/PenaltyForStreetModeType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/ItineraryFiltersInputType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/scalars/DoubleFunction.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/scalars/DoubleFunctionFactory.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/support/GqlUtil.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/framework/time/DurationUtils.java
  src/test/java/org/opentripplanner/framework/time/DurationUtilsTest.java
  src/test/java/org/opentripplanner/routing/api/request/preference/TransitPreferencesTest.java
  src/test/resources/standalone/config/router-config.json
Labels: new feature, Entur, Entur test

#5307 Return valid response when stop id is missing in Transmodel query
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
Labels: bug, sandbox, Entur test, skip changelog

#5335 Map GraphQL UnknowOperationException as bad request
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraph.java
Labels: bug, skip changelog

#5317 Move "Topic descriptions" to top level
  docs/System-Requirements.md
  mkdocs.yml
  src/ext/resources/gtfsgraphqlapi/schema.graphqls
Labels: documentation, skip changelog
