Repository opentripplanner/OpenTripPlanner, pull requests merged in 2023-03, with the labels that each got.

#4851 Include cancelled stops when including cancelled trips in trip search
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/BoardAlight.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RouteRequestTransitDataProviderFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TransitDataProviderFilter.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreatorTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RouteRequestTransitDataProviderFilterTest.java
Labels: improvement, Entur test

#4921 Revert "Improve support for EPIP NeTex profile"
  src/main/java/org/opentripplanner/netex/index/NetexEntityIndex.java
  src/main/java/org/opentripplanner/netex/index/api/NetexEntityIndexReadOnlyView.java
  src/main/java/org/opentripplanner/netex/loader/parser/ServiceCalendarFrameParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/ServiceFrameParser.java
  src/main/java/org/opentripplanner/netex/mapping/GroupOfStationsMapper.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/RouteMapper.java
  src/main/java/org/opentripplanner/netex/mapping/ServiceLinkMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripCalendarBuilder.java
  src/main/java/org/opentripplanner/netex/mapping/TripMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
  src/main/java/org/opentripplanner/netex/mapping/calendar/DayTypeAssignmentMapper.java
  src/main/java/org/opentripplanner/netex/validation/JourneyPatternSJMismatch.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/netex/NetexBundleSmokeTest.java
  src/test/java/org/opentripplanner/netex/NetexEpipBundleSmokeTest.java
  src/test/java/org/opentripplanner/netex/NetexTestDataSupport.java
  src/test/java/org/opentripplanner/netex/mapping/NetexTestDataSample.java
  src/test/java/org/opentripplanner/netex/mapping/TripCalendarBuilderTest.java
  src/test/java/org/opentripplanner/netex/mapping/TripMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/calendar/DayTypeAssignmentMapperTest.java
  src/test/resources/netex/build-config.json
  src/test/resources/netex/epip/build-config.json
  src/test/resources/netex/epip/netex_epip_minimal.zip
  src/test/resources/netex/netex_minimal.zip
Labels: skip changelog

#4916 Take nullable route short name into account in Atlanta fare calculator
  src/ext-test/java/org/opentripplanner/ext/fares/impl/AtlantaFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/impl/AtlantaFareService.java
Labels: bug, sandbox, IBI, skip changelog

#4920 Fix NPE in alert header usage
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLAlertImpl.java
Labels: bug, sandbox, RealTimeUpdate, skip changelog, Digitransit test

#4919 Ignore UnrestrictedPublicTransportAreas that do not contain regular stops
  src/main/java/org/opentripplanner/netex/mapping/FlexStopsMapper.java
  src/main/java/org/opentripplanner/transit/model/site/GroupStop.java
  src/test/java/org/opentripplanner/netex/mapping/FlexStopsMapperTest.java
Labels: bug

#4805 GBFS geofencing zones - part 2: backwards search
  .github/workflows/cibuild.yml
  src/main/java/org/opentripplanner/routing/linking/VertexLinker.java
  src/main/java/org/opentripplanner/service/vehiclerental/street/BusinessAreaBorder.java
  src/main/java/org/opentripplanner/service/vehiclerental/street/CompositeRentalRestrictionExtension.java
  src/main/java/org/opentripplanner/service/vehiclerental/street/GeofencingZoneExtension.java
  src/main/java/org/opentripplanner/service/vehiclerental/street/NoRestriction.java
  src/main/java/org/opentripplanner/street/model/RentalRestrictionExtension.java
  src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
  src/main/java/org/opentripplanner/street/model/vertex/TemporaryStreetLocation.java
  src/main/java/org/opentripplanner/street/model/vertex/Vertex.java
  src/main/java/org/opentripplanner/street/search/state/State.java
  src/main/java/org/opentripplanner/street/search/state/StateData.java
  src/main/java/org/opentripplanner/street/search/state/StateEditor.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeGeofencingTest.java
  src/test/java/org/opentripplanner/street/model/vertex/RentalRestrictionExtensionTest.java
  src/test/java/org/opentripplanner/street/search/state/StateEditorTest.java
  src/test/java/org/opentripplanner/street/search/state/StateTest.java
  src/test/java/org/opentripplanner/street/search/state/TraverseResultTest.java
  src/test/java/org/opentripplanner/street/search/strategy/DominanceFunctionTest.java
Labels: new feature, IBI, bump serialization id, Vehicle rental

#4924 Return 404 when a requested vector tile layer cannot be found
  src/main/java/org/opentripplanner/inspector/vector/VectorTileResponseFactory.java
  src/test/java/org/opentripplanner/inspector/vector/VectorTileResponseFactoryTest.java
Labels: improvement, IBI, bbnavi, HSL

#4927 fix: banned lines filter incorrectly mapped
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/FilterMapper.java
Labels: bug, Entur test, skip changelog

#4905 Use UnscheduledTrip for flex trips with one scheduled and one unscheduled stop.
  src/ext-test/java/org/opentripplanner/ext/flex/FlexTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/UnscheduledTripTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTripTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/trip/UnscheduledTripTest.java
  src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
  src/main/java/org/opentripplanner/model/StopTime.java
Labels: improvement, sandbox

#4923 Remove deprecation annotation from viaTrip query field
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/ViaTripQuery.java
Labels: documentation, sandbox

#4930 Validate missing transit data before building transit graph
  src/main/java/org/opentripplanner/graph_builder/GraphBuilderDataSources.java
Labels: bug

#4929 Split maven CI build into two steps to avoid timeouts
  .github/workflows/cibuild.yml
Labels: technical debt, skip changelog

#4909 Fix alerts query severity, cause and effects filters in Legacy GraphQL API
  docs/sandbox/LegacyGraphQLApi.md
  src/ext-test/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImplTest.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLUtils.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
Labels: bug, sandbox, skip changelog, Digitransit test

#4938 feat: make documentation release independent
  docs/Basic-Tutorial.md
Labels: documentation, skip changelog

#4906 Improve travel time API
  docs/sandbox/TravelTime.md
  src/ext/java/org/opentripplanner/ext/traveltime/IsochroneRenderer.java
  src/ext/java/org/opentripplanner/ext/traveltime/PostTransitSkipEdgeStrategy.java
  src/ext/java/org/opentripplanner/ext/traveltime/RasterRenderer.java
  src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeRequest.java
  src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeResource.java
  src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeStateData.java
  src/main/java/org/opentripplanner/raptor/api/request/SearchParams.java
  src/main/java/org/opentripplanner/raptor/api/request/SearchParamsBuilder.java
  src/main/java/org/opentripplanner/street/search/TemporaryVerticesContainer.java
  src/main/java/org/opentripplanner/street/search/state/StateData.java
Labels: bug, improvement, sandbox, skip changelog

#4944 Replace Mockito with concrete implementations where not used in test
  src/test/java/org/opentripplanner/graph_builder/module/ned/MissingElevationHandlerTest.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filter/TransitAlertFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TripPatternForDateTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RouteRequestTransitDataProviderFilterTest.java
  src/test/java/org/opentripplanner/updater/alert/AlertsUpdateHandlerTest.java
Labels: technical debt, skip changelog

#4865 Refactor SIRI-ET updaters
  src/ext-test/java/org/opentripplanner/ext/siri/AddedTripBuilderTest.java
  src/ext-test/java/org/opentripplanner/ext/siri/AddedTripHelperTest.java
  src/ext-test/java/org/opentripplanner/ext/siri/ModifiedTripBuilderTest.java
  src/ext-test/java/org/opentripplanner/ext/siri/TestCall.java
  src/ext-test/java/org/opentripplanner/ext/siri/TimeTableHelperTest.java
  src/ext-test/java/org/opentripplanner/ext/siri/mapper/PickDropMapperTest.java
  src/ext/java/org/opentripplanner/ext/siri/AddedTripBuilder.java
  src/ext/java/org/opentripplanner/ext/siri/AddedTripHelper.java
  src/ext/java/org/opentripplanner/ext/siri/CallWrapper.java
  src/ext/java/org/opentripplanner/ext/siri/DebugString.java
  src/ext/java/org/opentripplanner/ext/siri/EntityResolver.java
  src/ext/java/org/opentripplanner/ext/siri/Mode.java
  src/ext/java/org/opentripplanner/ext/siri/ModifiedTripBuilder.java
  src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java
  src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
  src/ext/java/org/opentripplanner/ext/siri/SiriSeverityMapper.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTransportModeMapper.java
  src/ext/java/org/opentripplanner/ext/siri/SiriTripPatternCache.java
  src/ext/java/org/opentripplanner/ext/siri/TimeForStop.java
  src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
  src/ext/java/org/opentripplanner/ext/siri/TripAndPattern.java
  src/ext/java/org/opentripplanner/ext/siri/TripTimesAndStopPattern.java
  src/ext/java/org/opentripplanner/ext/siri/TripUpdate.java
  src/ext/java/org/opentripplanner/ext/siri/mapper/AffectsMapper.java
  src/ext/java/org/opentripplanner/ext/siri/mapper/OccupancyMapper.java
  src/ext/java/org/opentripplanner/ext/siri/mapper/PickDropMapper.java
  src/ext/java/org/opentripplanner/ext/siri/mapper/SiriSeverityMapper.java
  src/ext/java/org/opentripplanner/ext/siri/mapper/SiriTransportModeMapper.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETHttpTripUpdateSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriVMHttpTripUpdateSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriVMUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriVMUpdaterParameters.java
  src/ext/java/org/opentripplanner/ext/siri/updater/VehicleMonitoringSource.java
  src/main/java/org/opentripplanner/model/UpdateError.java
  src/main/java/org/opentripplanner/model/UpdateSuccess.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/UpdatersConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/SiriVMUpdaterConfig.java
  src/main/java/org/opentripplanner/transit/model/network/StopPattern.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripTimes.java
  src/main/java/org/opentripplanner/updater/UpdatersParameters.java
  src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
  src/test/java/org/opentripplanner/transit/model/_data/TransitModelForTest.java
Labels: bug, sandbox, Entur, technical debt, RealTimeUpdate

#4947 Only log warning in GBFS updater if failed to fetch auto-discovery file
  src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFeedLoader.java
Labels: skip changelog

#4948 Separating config of projectName for Pubsub topic/subscription
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdaterParameters.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/SiriETGooglePubsubUpdaterConfig.java
Labels: sandbox, skip changelog

#4945 Generate lists instead of iterables for types in the Legacy GraphQL API
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLUtils.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLAgencyImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLFeedImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLLegImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPatternImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLRouteImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/graphql-codegen.yml
Labels: improvement, sandbox, skip changelog

#4937 Add documentation about system requirements and suggestions
  docs/Basic-Tutorial.md
  docs/System-Requirements.md
  mkdocs.yml
Labels: documentation

#4956 Add areas to documentation example for preparing osm data [ci skip]
  docs/Preparing-OSM.md
Labels: documentation, skip changelog

#4925 Fix Netex EPIP implementation bug
  .prettierrc.yml
  src/main/java/org/opentripplanner/netex/index/NetexEntityIndex.java
  src/main/java/org/opentripplanner/netex/index/api/NetexEntityIndexReadOnlyView.java
  src/main/java/org/opentripplanner/netex/loader/parser/ServiceCalendarFrameParser.java
  src/main/java/org/opentripplanner/netex/loader/parser/ServiceFrameParser.java
  src/main/java/org/opentripplanner/netex/mapping/GroupOfStationsMapper.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/RouteMapper.java
  src/main/java/org/opentripplanner/netex/mapping/ServiceLinkMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StationMapper.java
  src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripCalendarBuilder.java
  src/main/java/org/opentripplanner/netex/mapping/TripMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
  src/main/java/org/opentripplanner/netex/mapping/calendar/DayTypeAssignmentMapper.java
  src/main/java/org/opentripplanner/netex/package.md
  src/main/java/org/opentripplanner/netex/validation/JourneyPatternSJMismatch.java
  src/test/java/org/opentripplanner/ConstantsForTests.java
  src/test/java/org/opentripplanner/netex/NetexEpipBundleSmokeTest.java
  src/test/java/org/opentripplanner/netex/NetexNordicBundleSmokeTest.java
  src/test/java/org/opentripplanner/netex/NetexTestDataSupport.java
  src/test/java/org/opentripplanner/netex/mapping/NetexTestDataSample.java
  src/test/java/org/opentripplanner/netex/mapping/TripCalendarBuilderTest.java
  src/test/java/org/opentripplanner/netex/mapping/TripMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/calendar/DayTypeAssignmentMapperTest.java
  src/test/resources/netex/epip/build-config.json
  src/test/resources/netex/epip/netex_epip_minimal.zip
  src/test/resources/netex/nordic/build-config.json
  src/test/resources/netex/nordic/netex_minimal.zip
Labels: bug, NeTEx, skip changelog

#4959 Update Configuration.md [ci skip]
  doc-templates/Configuration.md
  doc-templates/UpdaterConfig.md
  docs/Configuration.md
  docs/UpdaterConfig.md
Labels: documentation, skip changelog

#4888 Adding support for SIRI SX-messages tagged on DatedServiceJourney
  src/ext-test/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandlerTest.java
  src/ext/java/org/opentripplanner/ext/siri/EntityResolver.java
  src/ext/java/org/opentripplanner/ext/siri/mapper/AffectsMapper.java
Labels: sandbox, RealTimeUpdate

#4934 Fix initial A* state of car rental
  src/main/java/org/opentripplanner/street/search/state/StateData.java
  src/test/java/org/opentripplanner/street/search/state/StateTest.java
Labels: bug, Vehicle rental

#4966 Remove check for (now optional) ENV-variable for GCP Authentication
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
Labels: sandbox, RealTimeUpdate

#4976 Use different logic in smoove updater to tell if the station is on
  src/ext-test/resources/smoovebikerental/smoove.json
  src/ext/java/org/opentripplanner/ext/smoovebikerental/SmooveBikeRentalDataSource.java
Labels: improvement, sandbox, skip changelog

#4936 Optimal walking routes when walking starts or ends in an area
  src/main/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModule.java
  src/main/java/org/opentripplanner/graph_builder/module/islandpruning/PruneIslands.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/linking/FlexLocationAdder.java
  src/main/java/org/opentripplanner/routing/linking/VertexLinker.java
  src/main/java/org/opentripplanner/street/model/edge/AreaEdge.java
  src/main/java/org/opentripplanner/street/model/edge/AreaEdgeList.java
  src/main/java/org/opentripplanner/street/model/vertex/Vertex.java
  src/test/java/org/opentripplanner/graph_builder/linking/LinkStopToPlatformTest.java
Labels: improvement, bump serialization id, Digitransit test

#4981 Remove unconnected walking areas from graph
  src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
Labels: bug

#4982 Update GraphQL-docs
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
Labels: sandbox, skip changelog

#4974 Ignore default values in WheelchairPreferences#toString()
  docs/RouteRequest.md
  docs/RouterConfiguration.md
  src/main/java/org/opentripplanner/routing/api/request/preference/AccessibilityPreferences.java
  src/main/java/org/opentripplanner/routing/api/request/preference/WheelchairPreferences.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/WheelchairConfig.java
  src/test/java/org/opentripplanner/routing/api/request/WheelchairPreferencesTest.java
  src/test/resources/standalone/config/router-config.json
Labels: skip changelog

#4868 Filter out duplicate-like legs in alternative legs
  src/ext/resources/legacygraphqlapi/schema.graphqls
  src/main/java/org/opentripplanner/routing/alternativelegs/AlternativeLegs.java
  src/test/java/org/opentripplanner/model/impl/OtpTransitServiceBuilderTest.java
  src/test/java/org/opentripplanner/model/impl/OtpTransitServiceImplTest.java
  src/test/java/org/opentripplanner/routing/stoptimes/AlternativeLegsTest.java
  src/test/resources/testagency/routes.txt
  src/test/resources/testagency/stop_times.txt
  src/test/resources/testagency/stops.txt
  src/test/resources/testagency/trips.txt
Labels: bug, improvement, Digitransit test

#4991 Speed test profiles
  .github/workflows/performance-test.yml
Labels: skip changelog

#4992 Improve error logging
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/main/java/org/opentripplanner/model/plan/pagecursor/PageCursorSerializer.java
  src/test/java/org/opentripplanner/model/plan/pagecursor/PageCursorTest.java
Labels: technical debt, skip changelog

#4993 Identify which terminal is the problem when throwing an exception
  src/main/java/org/opentripplanner/gtfs/mapping/StopMapper.java
Labels: improvement, GTFS, skip changelog

#4994 Fix prettier node download for CI
  .github/workflows/cibuild.yml
Labels: skip changelog

#4971 Use accept-language header locale instead of default routing request locale
  docs/sandbox/LegacyGraphQLApi.md
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLUtils.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLAlertImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLBikeParkImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLCarParkImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPatternImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPlaceImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLRouteImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStoptimeImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLVehicleParkingImpl.java
  src/ext/java/org/opentripplanner/ext/legacygraphqlapi/mapping/RouteRequestMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLUtils.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/ViaRequestMapper.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/PathGuidanceType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/PlanPlaceType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
  src/main/java/org/opentripplanner/framework/graphql/GraphQLUtils.java
  src/test/java/org/opentripplanner/framework/graphql/GraphQLUtilsTest.java
Labels: bug, sandbox, skip changelog, Digitransit test

#4963 Validate the number of service links mapped to a JourneyPattern
  src/main/java/org/opentripplanner/netex/mapping/ServiceLinkMapper.java
  src/test/java/org/opentripplanner/netex/mapping/ServiceLinkMapperTest.java
Labels: improvement

#4975 Add checks for configuring AccessibilityPreferences
  src/main/java/org/opentripplanner/standalone/config/routerequest/WheelchairConfig.java
  src/test/java/org/opentripplanner/standalone/config/routerequest/WheelchairConfigTest.java
Labels: skip changelog, config change

#4998 Make sure the default streetRoutingTimeout is used
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
  src/main/java/org/opentripplanner/astar/AStar.java
  src/main/java/org/opentripplanner/astar/AStarBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectStreetRouter.java
  src/main/java/org/opentripplanner/routing/api/request/preference/StreetPreferences.java
  src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
  src/main/java/org/opentripplanner/standalone/api/OtpServerRequestContext.java
  src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationModule.java
  src/main/java/org/opentripplanner/standalone/server/DefaultServerRequestContext.java
  src/main/java/org/opentripplanner/street/search/StreetSearchBuilder.java
  src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java
  src/test/java/org/opentripplanner/TestServerContext.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModuleTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TestIntermediatePlaces.java
  src/test/java/org/opentripplanner/routing/api/request/preference/StreetPreferencesTest.java
  src/test/java/org/opentripplanner/standalone/config/RouterConfigTest.java
  src/test/java/org/opentripplanner/street/integration/BarrierRoutingTest.java
  src/test/java/org/opentripplanner/street/integration/BicycleRoutingTest.java
  src/test/java/org/opentripplanner/street/integration/CarRoutingTest.java
  src/test/java/org/opentripplanner/street/integration/SplitEdgeTurnRestrictionsTest.java
  src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
Labels: bug, technical debt, Entur test, bump serialization id

#4861 Validate service date for SCHEDULED updates
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TripPatternForDate.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerUpdater.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripTimes.java
  src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
  src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java
Labels: bug, RealTimeUpdate, Digitransit test

#4985 Azure updater bugfix
  docs/sandbox/SiriAzureUpdater.md
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java
Labels: sandbox, Skanetrafiken, RealTimeUpdate, skip changelog

#4983 Allow OTP to start when unexpected enum values is encountered in config.
  docs/RouterConfiguration.md
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/main/java/org/opentripplanner/standalone/config/OtpConfig.java
  src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
  src/main/java/org/opentripplanner/standalone/config/framework/json/NodeAdapter.java
  src/main/java/org/opentripplanner/standalone/config/framework/json/ParameterBuilder.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/TransitRoutingConfig.java
  src/test/java/org/opentripplanner/standalone/config/BuildConfigTest.java
  src/test/java/org/opentripplanner/standalone/config/ExampleConfigTest.java
  src/test/java/org/opentripplanner/standalone/config/RouterConfigTest.java
  src/test/java/org/opentripplanner/standalone/config/framework/json/NodeAdapterTest.java
  src/test/java/org/opentripplanner/standalone/config/sandbox/DataOverlayConfigMapperTest.java
  src/test/java/org/opentripplanner/transit/speed_test/options/SpeedTestConfig.java
Labels: bug

#5001 Avoid changing already non-routable stops when cancelling stops in realtime
  src/ext-test/java/org/opentripplanner/ext/siri/mapper/PickDropMapperTest.java
  src/ext/java/org/opentripplanner/ext/siri/AddedTripBuilder.java
  src/ext/java/org/opentripplanner/ext/siri/ModifiedTripBuilder.java
  src/ext/java/org/opentripplanner/ext/siri/mapper/PickDropMapper.java
  src/main/java/org/opentripplanner/transit/model/network/StopPattern.java
Labels: bug, RealTimeUpdate, skip changelog

#4986 fix: Catch RoutingValidationException for ViaRoutingResponse
  src/ext/graphql/transmodelapi/schema.graphql
  src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
  src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
Labels: sandbox, skip changelog

#4987 Catch and log exceptions when generating transfers
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/TransferIndexGenerator.java
Labels: Skanetrafiken

#5008 Remove the word 'legacy' from path of GraphQL explorer (GraphiQL)
  docs/sandbox/LegacyGraphQLApi.md
  src/client/graphiql/index.html
  src/client/legacygraphql/graphiql/index.html
Labels: documentation, skip changelog
