Repository opentripplanner/OpenTripPlanner, pull requests merged in 2024-06, with the labels that each got.

#5856 Small clean up of flex duration factor/offset
  src/ext-test/java/org/opentripplanner/ext/flex/flexpathcalculator/FlexPathTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/trip/FlexTripsMapperTest.java
  src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/FlexPath.java
  src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/TimePenaltyCalculator.java
  src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
  src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
  src/main/java/org/opentripplanner/gtfs/mapping/TripMapper.java
  src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
  src/main/java/org/opentripplanner/routing/api/request/framework/TimePenalty.java
  src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java
Labels: technical debt, skip changelog

#5879 Rework clustering logic for sandbox geocoder
  src/ext-test/java/org/opentripplanner/ext/geocoder/LuceneIndexTest.java
  src/ext/java/org/opentripplanner/ext/geocoder/LuceneIndex.java
  src/ext/java/org/opentripplanner/ext/geocoder/LuceneStopCluster.java
  src/ext/java/org/opentripplanner/ext/geocoder/StopCluster.java
  src/ext/java/org/opentripplanner/ext/geocoder/StopClusterMapper.java
  src/main/java/org/opentripplanner/framework/collection/ListUtils.java
  src/test/java/org/opentripplanner/framework/collection/ListUtilsTest.java
Labels: sandbox, IBI, skip changelog

#5877 Add nicer assertions to SiriTimetableSnapshotSourceTest
  src/ext-test/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSourceTest.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripTimesStringBuilder.java
Labels: RealTimeUpdate, skip changelog

#5871 Introduce module tests for GTFS-RT
  src/ext-test/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSourceTest.java
  src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
  src/main/java/org/opentripplanner/transit/model/timetable/TripTimes.java
  src/test/java/org/opentripplanner/updater/trip/RealtimeTestEnvironment.java
  src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java
  src/test/java/org/opentripplanner/updater/trip/moduletests/cancellation/CancellationDeletionTest.java
  src/test/java/org/opentripplanner/updater/trip/moduletests/delay/DelayedTest.java
  src/test/java/org/opentripplanner/updater/trip/moduletests/delay/SkippedTest.java
  src/test/java/org/opentripplanner/updater/trip/moduletests/rejection/InvalidInputTest.java
Labels: RealTimeUpdate, skip changelog

#5891 Fix parsing of GBFS feeds
  pom.xml
  src/test/resources/gbfs/lillestrombysykkel/gbfs.json
Labels: bug

#5867 Fix SIRI update travel back in time
  src/ext-test/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSourceTest.java
  src/ext/java/org/opentripplanner/ext/siri/AddedTripBuilder.java
  src/main/java/org/opentripplanner/transit/model/timetable/RealTimeTripTimes.java
Labels: bug, Entur test, RealTimeUpdate

#5894 fix: ensure connsolidated transit leg carries over fare
  src/ext-test/java/org/opentripplanner/ext/stopconsolidation/DecorateConsolidatedStopNamesTest.java
  src/ext/java/org/opentripplanner/ext/stopconsolidation/model/ConsolidatedStopLeg.java
Labels: sandbox, skip changelog

#5883 Limit result size and execution time in TransModel GraphQL API
  docs/RouterConfiguration.md
  src/main/java/org/opentripplanner/apis/transmodel/MaxFieldsInResultInstrumentation.java
  src/main/java/org/opentripplanner/apis/transmodel/OTPRequestTimeoutInstrumentation.java
  src/main/java/org/opentripplanner/apis/transmodel/TransmodelAPI.java
  src/main/java/org/opentripplanner/apis/transmodel/TransmodelAPIParameters.java
  src/main/java/org/opentripplanner/apis/transmodel/TransmodelGraph.java
  src/main/java/org/opentripplanner/standalone/config/sandbox/TransmodelAPIConfig.java
Labels: Entur test

#5726 Fix real-time added patterns persistence with DIFFERENTIAL updates
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
  src/test/java/org/opentripplanner/updater/trip/RealtimeTestEnvironment.java
  src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java
  src/test/java/org/opentripplanner/updater/trip/moduletests/cancellation/CancellationDeletionTest.java
  src/test/java/org/opentripplanner/updater/trip/moduletests/delay/SkippedTest.java
Labels: bug, RealTimeUpdate, Digitransit test

#5185 Add plan query that follows the relay connection specification
  .github/workflows/cibuild.yml
  pom.xml
  src/ext/java/org/opentripplanner/ext/actuator/MicrometerGraphQLInstrumentation.java
  src/main/java/org/opentripplanner/apis/gtfs/GraphQLScalars.java
  src/main/java/org/opentripplanner/apis/gtfs/GtfsGraphQLIndex.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/PlanConnectionImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/QueryTypeImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLTypes.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/graphql-codegen.yml
  src/main/java/org/opentripplanner/apis/gtfs/generated/package.json
  src/main/java/org/opentripplanner/apis/gtfs/generated/yarn.lock
  src/main/java/org/opentripplanner/apis/gtfs/mapping/TransitModeMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/AccessModeMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/ArgumentUtils.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/BicyclePreferencesMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/CarPreferencesMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/DirectModeMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/EgressModeMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/ItineraryFilterDebugProfileMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/LegacyRouteRequestMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/ModePreferencesMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/OptimizationTypeMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/RouteRequestMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/ScooterPreferencesMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/TransferModeMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/TransitPreferencesMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/VehicleOptimizationTypeMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/WalkPreferencesMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/model/PlanPageInfo.java
  src/main/java/org/opentripplanner/apis/transmodel/support/AbortOnTimeoutExecutionStrategy.java
  src/main/java/org/opentripplanner/framework/collection/CollectionUtils.java
  src/main/java/org/opentripplanner/framework/graphql/GraphQLUtils.java
  src/main/java/org/opentripplanner/framework/time/DurationUtils.java
  src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
  src/test/java/org/opentripplanner/apis/gtfs/CoordinateValueScalarTest.java
  src/test/java/org/opentripplanner/apis/gtfs/CostScalarTest.java
  src/test/java/org/opentripplanner/apis/gtfs/RatioScalarTest.java
  src/test/java/org/opentripplanner/apis/gtfs/ReluctanceScalarTest.java
  src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/LegacyRouteRequestMapperTest.java
  src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/RouteRequestMapperAccessibilityTest.java
  src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/RouteRequestMapperBicycleTest.java
  src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/RouteRequestMapperCarTest.java
  src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/RouteRequestMapperModesTest.java
  src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/RouteRequestMapperScooterTest.java
  src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/RouteRequestMapperTest.java
  src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/RouteRequestMapperTransitTest.java
  src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/RouteRequestMapperWalkTest.java
  src/test/java/org/opentripplanner/framework/graphql/GraphQLUtilsTest.java
  src/test/java/org/opentripplanner/framework/time/DurationUtilsTest.java
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/planConnection.json
  src/test/resources/org/opentripplanner/apis/gtfs/queries/planConnection.graphql
Labels: new feature

#5893 Remove unused Siri code
  src/ext/java/org/opentripplanner/ext/siri/SiriTripPatternCache.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriHelper.java
Labels: technical debt, RealTimeUpdate, skip changelog

#5890 Remove TravelTime API
  docs/Analysis.md
  docs/Configuration.md
  docs/sandbox/TravelTime.md
  mkdocs.yml
  src/ext/java/org/opentripplanner/ext/traveltime/IsochroneData.java
  src/ext/java/org/opentripplanner/ext/traveltime/IsochroneRenderer.java
  src/ext/java/org/opentripplanner/ext/traveltime/IsolineMetric.java
  src/ext/java/org/opentripplanner/ext/traveltime/PostTransitSkipEdgeStrategy.java
  src/ext/java/org/opentripplanner/ext/traveltime/RasterRenderer.java
  src/ext/java/org/opentripplanner/ext/traveltime/SampleGridRenderer.java
  src/ext/java/org/opentripplanner/ext/traveltime/SampleGridSPTVisitor.java
  src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeRequest.java
  src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeResource.java
  src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeStateData.java
  src/ext/java/org/opentripplanner/ext/traveltime/WTWD.java
  src/ext/java/org/opentripplanner/ext/traveltime/WTWDAccumulativeMetric.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/AccumulativeGridSampler.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/AccumulativeMetric.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/DelaunayEdge.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/DelaunayIsolineBuilder.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/DelaunayPoint.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/DelaunayTriangulation.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/IsolineBuilder.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/SparseMatrix.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/SparseMatrixZSampleGrid.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/ZMetric.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/ZSampleGrid.java
  src/ext/java/org/opentripplanner/ext/traveltime/geometry/ZSamplePoint.java
  src/ext/java/org/opentripplanner/ext/traveltime/spt/SPTVisitor.java
  src/ext/java/org/opentripplanner/ext/traveltime/spt/SPTWalker.java
  src/main/java/org/opentripplanner/apis/APIEndpoints.java
  src/main/java/org/opentripplanner/framework/application/OTPFeature.java
  src/main/java/org/opentripplanner/raptor/api/request/SearchParams.java
  src/main/java/org/opentripplanner/raptor/api/request/SearchParamsBuilder.java
  src/main/java/org/opentripplanner/street/search/state/StateData.java
Labels: sandbox, technical debt, config change

#5882 Extract timetable manager for realtime trip updates
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotManager.java
  src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
  src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotManagerTest.java
  src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java
Labels: technical debt, RealTimeUpdate, skip changelog

#5892 Use enum instead of boolean for real time update semantics
  src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/EstimatedTimetableSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETHttpTripUpdateSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  src/main/java/org/opentripplanner/updater/trip/GtfsRealtimeTripUpdateSource.java
  src/main/java/org/opentripplanner/updater/trip/MqttGtfsRealtimeUpdater.java
  src/main/java/org/opentripplanner/updater/trip/PollingTripUpdater.java
  src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
  src/main/java/org/opentripplanner/updater/trip/TripUpdateGraphWriterRunnable.java
  src/main/java/org/opentripplanner/updater/trip/UpdateIncrementality.java
  src/test/java/org/opentripplanner/GtfsTest.java
  src/test/java/org/opentripplanner/updater/trip/RealtimeTestEnvironment.java
  src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java
  src/test/java/org/opentripplanner/updater/trip/moduletests/cancellation/CancellationDeletionTest.java
  src/test/java/org/opentripplanner/updater/trip/moduletests/delay/SkippedTest.java
Labels: technical debt, RealTimeUpdate, skip changelog

#5908 Improve cancellation of large response in TransModel API
  src/ext/java/org/opentripplanner/ext/restapi/resources/PlannerResource.java
  src/main/java/org/opentripplanner/api/common/Message.java
  src/main/java/org/opentripplanner/apis/transmodel/MaxFieldsInResultInstrumentation.java
  src/main/java/org/opentripplanner/apis/transmodel/ResponseTooLargeException.java
  src/main/java/org/opentripplanner/apis/transmodel/TransmodelGraph.java
  src/main/java/org/opentripplanner/apis/transmodel/support/AbortOnUnprocessableRequestExecutionStrategy.java
  src/main/java/org/opentripplanner/apis/transmodel/support/ExecutionResultMapper.java
  src/main/resources/Message.properties
  src/main/resources/Message_de.properties
  src/main/resources/Message_es.properties
  src/main/resources/Message_fr.properties
  src/main/resources/Message_hu.properties
  src/main/resources/Message_nl.properties
  src/test/java/org/opentripplanner/apis/transmodel/support/ExecutionResultMapperTest.java
Labels: improvement, Entur test

#5906 Refactor NearbyStopsFinder to follow strategy pattern
  src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
  src/main/java/org/opentripplanner/graph_builder/module/nearbystops/MinMap.java
  src/main/java/org/opentripplanner/graph_builder/module/nearbystops/NearbyStopFinder.java
  src/main/java/org/opentripplanner/graph_builder/module/nearbystops/PatternConsideringNearbyStopFinder.java
  src/main/java/org/opentripplanner/graph_builder/module/nearbystops/StraightLineNearbyStopFinder.java
  src/main/java/org/opentripplanner/graph_builder/module/nearbystops/StreetNearbyStopFinder.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/AccessEgressRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectFlexRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/FlexAccessEgressRouter.java
  src/test/java/org/opentripplanner/astar/strategy/MaxCountSkipEdgeStrategyTest.java
Labels: technical debt, skip changelog

#5918 Prettify leg view in debug client
  client-next/.env
  client-next/.env.development
  client-next/src/components/ItineraryList/ItineraryLegDetails.tsx
  client-next/src/components/ItineraryList/LegTime.tsx
  client-next/src/components/MapView/LayerControl.tsx
  client-next/src/hooks/useTripQueryVariables.ts
  client-next/src/screens/App.tsx
  client-next/src/style.css
  client-next/src/util/getColorForMode.ts
  src/main/java/org/opentripplanner/apis/vectortiles/DebugStyleSpec.java
  src/test/resources/org/opentripplanner/apis/vectortiles/style.json
Labels: OTP Debug UI, skip changelog

#5922 fix(orca-fares): allow senior fares with cash
  src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
  src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
Labels: sandbox, IBI, skip changelog

#5904 Refactor SIRI-ET updaters
  src/ext/java/org/opentripplanner/ext/siri/updater/AsyncEstimatedTimetableProcessor.java
  src/ext/java/org/opentripplanner/ext/siri/updater/AsyncEstimatedTimetableSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/EstimatedTimetableHandler.java
  src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/google/GooglePubsubEstimatedTimetableSource.java
  src/ext/java/org/opentripplanner/ext/siri/updater/google/SiriETGooglePubsubUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/google/SiriETGooglePubsubUpdaterParameters.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/UpdatersConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/SiriETGooglePubsubUpdaterConfig.java
  src/main/java/org/opentripplanner/updater/UpdatersParameters.java
  src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
  src/test/java/org/opentripplanner/updater/trip/RealtimeTestEnvironment.java
Labels: improvement, RealTimeUpdate

#5926 Update magidoc
  .github/workflows/cibuild.yml
  .github/workflows/performance-test.yml
  magidoc.mjs
Labels: skip changelog

#5928 Add back GraphQL data fetcher error logging
  src/main/java/org/opentripplanner/apis/gtfs/GtfsGraphQLIndex.java
  src/main/java/org/opentripplanner/apis/support/graphql/LoggingDataFetcherExceptionHandler.java
  src/main/java/org/opentripplanner/apis/transmodel/TransmodelGraph.java
  src/main/java/org/opentripplanner/apis/transmodel/support/AbortOnUnprocessableRequestExecutionStrategy.java
  src/main/resources/logback.xml
Labels: bug, skip changelog

#5930 Fix Javadoc of `TimetableSnapshotManager.snapshot`
  src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotManager.java
Labels: documentation, skip changelog
