Repository opentripplanner/OpenTripPlanner, pull requests merged in 2024-12, with the labels that each got.

#6274 Avoid NullPointerException in GTFS GraphQL API
  application/src/ext/java/org/opentripplanner/ext/restapi/mapping/BookingInfoMapper.java
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/BookingInfoImpl.java
  application/src/main/java/org/opentripplanner/transit/model/timetable/booking/BookingInfo.java
  application/src/main/java/org/opentripplanner/transit/model/timetable/booking/RoutingBookingInfo.java
  application/src/test/java/org/opentripplanner/apis/gtfs/datafetchers/BookingInfoImplTest.java
  application/src/test/java/org/opentripplanner/netex/mapping/BookingInfoMapperTest.java
  application/src/test/java/org/opentripplanner/transit/model/timetable/booking/BookingInfoTest.java
Labels: Bug, Skip Changelog

#6288 Make `motorroad=yes` car-only
  application/src/main/java/org/opentripplanner/osm/tagmapping/FinlandMapper.java
  application/src/main/java/org/opentripplanner/osm/tagmapping/OsmTagMapper.java
  application/src/test/java/org/opentripplanner/osm/tagmapping/FinlandMapperTest.java
  application/src/test/java/org/opentripplanner/osm/tagmapping/OsmTagMapperTest.java
  doc/user/osm/Finland.md
  doc/user/osm/Germany.md
  doc/user/osm/OsmTag.md
  doc/user/osm/UK.md
Labels: Bug

#6267 Split the shaded jar out of application
  application/pom.xml
  pom.xml
  raptor/pom.xml
  shaded-jar/pom.xml
  utils/pom.xml
Labels: Technical Debt, Skip Changelog

#6281 Add decision record for analysis and design documentation
  ARCHITECTURE.md
  DEVELOPMENT_DECISION_RECORDS.md
  doc/dev/decisionrecords/AnalysesAndDesign.md
  doc/dev/images/DomainModelNotation.svg
Labels: Documentation, Technical Debt

#6298 Switch GTFS flex `safe_duration_offset` back to seconds
  application/src/main/java/org/opentripplanner/gtfs/mapping/TripMapper.java
  application/src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java
Labels: Improvement, GTFS

#6282 Remove unused GtfsGraphQlApiRentalStationFuzzyMatching feature
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/QueryTypeImpl.java
  application/src/main/java/org/opentripplanner/framework/application/OTPFeature.java
  doc/user/Configuration.md
Labels: Technical Debt

#6310 Fix references to the shaded jar for performance tests and in doc
  .github/workflows/performance-test.yml
  README.md
  doc/user/Getting-OTP.md
Labels: Technical Debt, Skip Changelog

#6320 Renovate/major react monorepo
  client/package-lock.json
  client/package.json
Labels: Skip Changelog

#6268 Better escalator duration control: specific duration from OSM duration tag, default speed from build-config.json
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/EscalatorProcessor.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModule.java
  application/src/main/java/org/opentripplanner/inspector/vector/edge/EdgePropertyMapper.java
  application/src/main/java/org/opentripplanner/osm/model/OsmWay.java
  application/src/main/java/org/opentripplanner/osm/model/OsmWithTags.java
  application/src/main/java/org/opentripplanner/routing/api/request/preference/EscalatorPreferences.java
  application/src/main/java/org/opentripplanner/routing/api/request/preference/WalkPreferences.java
  application/src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  application/src/main/java/org/opentripplanner/street/model/edge/EscalatorEdge.java
  application/src/test/java/org/opentripplanner/osm/model/OsmWithTagsTest.java
  application/src/test/java/org/opentripplanner/routing/api/request/preference/WalkPreferencesTest.java
  application/src/test/java/org/opentripplanner/street/model/edge/EscalatorEdgeTest.java
  application/src/test/resources/standalone/config/router-config.json
  doc/user/RouteRequest.md
  doc/user/RouterConfiguration.md
Labels: Improvement, bump serialization id

#6325 Reduce geocode cluster radius
  application/src/ext/java/org/opentripplanner/ext/geocoder/StopClusterMapper.java
Labels: Sandbox, IBI, Skip Changelog

#6330 Add endpoint to download Transmodel GraphQL Schema
  application/src/main/java/org/opentripplanner/apis/transmodel/TransmodelAPI.java
Labels: Improvement, Entur Test, Skip Changelog

#6329 WSF calculate fares from GTFS
  application/src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
  application/src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
  application/src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFaresData.java
  application/src/main/java/org/opentripplanner/transit/model/basic/Money.java
  application/src/test/java/org/opentripplanner/routing/core/MoneyTest.java
Labels: Sandbox, Skip Changelog

#6193 Add relay connection and global object identification specification guidelines to decision records
  DEVELOPMENT_DECISION_RECORDS.md
  doc/dev/decisionrecords/APIGraphQLDesign.md
  doc/dev/decisionrecords/_TEMPLATE.md
Labels: Skip Changelog, Developer Decision Record

#6321 Improve "bogus name" handling when setting StreetEdge's name during postprocessing
  application/src/main/java/org/opentripplanner/street/model/edge/Edge.java
  application/src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/naming/SidewalkNamerTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapperTest.java
  application/src/test/java/org/opentripplanner/street/model/edge/StreetEdgeTest.java
Labels: Improvement, Skip Changelog

#6308 Use WCAG recommendation to fill in GTFS route text color if it is missing
  application/src/main/java/org/opentripplanner/gtfs/graphbuilder/GtfsModule.java
  client/src/util/generateTextColor.ts
  utils/src/main/java/org/opentripplanner/utils/color/Brightness.java
  utils/src/main/java/org/opentripplanner/utils/color/ColorUtils.java
  utils/src/test/java/org/opentripplanner/utils/color/ColorUtilsTest.java
Labels: Improvement, GTFS

#6293 Enable mode-specific transfers by storing mode information in transfers
  application/src/ext/java/org/opentripplanner/ext/flex/FlexIndex.java
  application/src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
  application/src/main/java/org/opentripplanner/api/parameter/QualifiedModeSet.java
  application/src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
  application/src/main/java/org/opentripplanner/model/PathTransfer.java
  application/src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  application/src/main/java/org/opentripplanner/routing/algorithm/mapping/StreetModeToTransferTraverseModeMapper.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/RaptorTransferIndex.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/Transfer.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransfersMapper.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerMapper.java
  application/src/main/java/org/opentripplanner/transit/service/TimetableRepository.java
  application/src/test/java/org/opentripplanner/graph_builder/module/DirectTransferGeneratorTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapperTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TransferTest.java
Labels: Improvement, bump serialization id

#6302 Add default penalty to all car API modes
  application/src/main/java/org/opentripplanner/routing/api/request/preference/AccessEgressPreferences.java
  application/src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
  application/src/test/java/org/opentripplanner/routing/api/request/preference/StreetPreferencesTest.java
  doc/user/RouteRequest.md
Labels: Bug, Entur Test

#6336 Show generalized cost in debug UI
  client/src/components/ItineraryList/ItineraryDetails.tsx
  client/src/components/ItineraryList/ItineraryLegDetails.tsx
  client/src/static/query/tripQuery.tsx
  client/src/style.css
  client/src/util/formatDuration.ts
Labels: OTP Debug UI, Skip Changelog

#6311 Make flex linking work together with boarding locations
  application/src/main/java/org/opentripplanner/graph_builder/module/StreetLinkerModule.java
  application/src/main/java/org/opentripplanner/street/model/vertex/TransitStopVertex.java
  application/src/test/java/org/opentripplanner/graph_builder/module/StreetLinkerModuleTest.java
Labels: Bug, IBI

#6344 Fix test failure when building OTP in a path with special characters
  application/src/test/java/org/opentripplanner/test/support/ResourceLoader.java
Labels: Bug, Skip Changelog

#6303 Add fallback name for corridors
  application/src/main/java/org/opentripplanner/osm/tagmapping/OsmTagMapper.java
  application/src/main/resources/WayProperties.properties
  application/src/main/resources/WayProperties_de.properties
  application/src/main/resources/WayProperties_fi.properties
  application/src/main/resources/WayProperties_fr.properties
  application/src/main/resources/WayProperties_hu.properties
  application/src/main/resources/WayProperties_nl.properties
  application/src/main/resources/WayProperties_no.properties
  application/src/main/resources/WayProperties_sv.properties
  application/src/test/java/org/opentripplanner/osm/tagmapping/OsmTagMapperTest.java
Labels: Improvement, IBI
