Repository opentripplanner/OpenTripPlanner, pull requests merged in 2024-01, with the labels that each got.

#5586 Fix preference cost comparisons
  src/main/java/org/opentripplanner/routing/api/request/preference/BikePreferences.java
  src/main/java/org/opentripplanner/routing/api/request/preference/TransitPreferences.java
  src/main/java/org/opentripplanner/routing/api/request/preference/VehicleRentalPreferences.java
Labels: bug

#5587 Report and throw away trip-times which fail sanity check
  src/main/java/org/opentripplanner/framework/error/DefaultOtpError.java
  src/main/java/org/opentripplanner/framework/error/OtpError.java
  src/main/java/org/opentripplanner/transit/model/timetable/ScheduledTripTimes.java
  src/test/java/org/opentripplanner/transit/model/timetable/ScheduledTripTimesTest.java
Labels: bug, Entur test

#5591 Consider escalator edges in island pruning
  src/main/java/org/opentripplanner/graph_builder/module/islandpruning/PruneIslands.java
  src/test/java/org/opentripplanner/graph_builder/module/islandpruning/AdaptivePruningTest.java
  src/test/java/org/opentripplanner/graph_builder/module/islandpruning/EscalatorPruningTest.java
  src/test/java/org/opentripplanner/graph_builder/module/islandpruning/IslandPruningUtils.java
  src/test/java/org/opentripplanner/graph_builder/module/islandpruning/PruneNoThruIslandsTest.java
  src/test/resources/org/opentripplanner/graph_builder/module/islandpruning/matinkyla-escalator.pbf
Labels: bug

#5562 Create own rental preferences for bike and car in the internal model
  src/main/java/org/opentripplanner/api/common/RequestToPreferencesMapper.java
  src/main/java/org/opentripplanner/api/common/RoutingResource.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/RouteRequestMapper.java
  src/main/java/org/opentripplanner/apis/transmodel/mapping/PreferencesMapper.java
  src/main/java/org/opentripplanner/apis/transmodel/mapping/TripRequestMapper.java
  src/main/java/org/opentripplanner/apis/transmodel/mapping/preferences/BikePreferencesMapper.java
  src/main/java/org/opentripplanner/apis/transmodel/mapping/preferences/CarPreferencesMapper.java
  src/main/java/org/opentripplanner/apis/transmodel/mapping/preferences/ItineraryFilterPreferencesMapper.java
  src/main/java/org/opentripplanner/apis/transmodel/mapping/preferences/RentalPreferencesMapper.java
  src/main/java/org/opentripplanner/apis/transmodel/model/DefaultRouteRequestType.java
  src/main/java/org/opentripplanner/apis/transmodel/model/plan/TripQuery.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/api/request/preference/BikePreferences.java
  src/main/java/org/opentripplanner/routing/api/request/preference/CarPreferences.java
  src/main/java/org/opentripplanner/routing/api/request/preference/RoutingPreferences.java
  src/main/java/org/opentripplanner/routing/api/request/preference/VehicleRentalPreferences.java
  src/main/java/org/opentripplanner/routing/api/request/request/JourneyRequest.java
  src/main/java/org/opentripplanner/routing/api/request/request/StreetRequest.java
  src/main/java/org/opentripplanner/routing/api/request/request/VehicleRentalRequest.java
  src/main/java/org/opentripplanner/service/vehiclerental/model/VehicleRentalPlace.java
  src/main/java/org/opentripplanner/service/vehiclerental/street/StreetVehicleRentalLink.java
  src/main/java/org/opentripplanner/service/vehiclerental/street/VehicleRentalEdge.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/VehicleRentalConfig.java
  src/main/java/org/opentripplanner/street/model/edge/StreetTransitEntityLink.java
  src/main/java/org/opentripplanner/street/model/edge/TemporaryFreeEdge.java
  src/main/java/org/opentripplanner/street/search/request/StreetSearchRequest.java
  src/main/java/org/opentripplanner/street/search/request/StreetSearchRequestBuilder.java
  src/main/java/org/opentripplanner/street/search/request/StreetSearchRequestMapper.java
  src/main/java/org/opentripplanner/street/search/state/State.java
  src/main/java/org/opentripplanner/street/search/state/StateData.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/BikeRentalSnapshotTest.java
  src/test/java/org/opentripplanner/routing/api/request/preference/BikePreferencesTest.java
  src/test/java/org/opentripplanner/routing/api/request/preference/CarPreferencesTest.java
  src/test/java/org/opentripplanner/routing/api/request/preference/VehicleRentalPreferencesTest.java
  src/test/java/org/opentripplanner/routing/core/RoutingPreferencesTest.java
  src/test/java/org/opentripplanner/street/integration/BikeRentalTest.java
  src/test/java/org/opentripplanner/street/model/edge/VehicleRentalEdgeTest.java
Labels: improvement, bump serialization id

#5571 Report issue for duplicate journey patterns in NeTEx
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapperResult.java
  src/test/java/org/opentripplanner/netex/mapping/TripPatternMapperTest.java
Labels: improvement, NeTEx, skip changelog

#5597 doc: mention protomaps in basic tutorial
  docs/Basic-Tutorial.md
Labels: documentation, skip changelog

#5592 Adding situation-version to TransmodelGraphQL API
  src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java
  src/main/java/org/opentripplanner/apis/transmodel/model/siri/sx/PtSituationElementType.java
  src/main/java/org/opentripplanner/routing/alertpatch/TransitAlert.java
  src/main/java/org/opentripplanner/routing/alertpatch/TransitAlertBuilder.java
  src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
Labels: RealTimeUpdate

#5578 Deploy new debug client to a CDN
  .github/workflows/cibuild.yml
  .github/workflows/debug-client.yml
  .github/workflows/post-merge.yml
  .gitignore
  client-next/README.md
  client-next/vite.config.ts
Labels: improvement, skip changelog

#5605 Fix high walk reluctance leading to zero egress results for rental searches
  pom.xml
  src/main/java/org/opentripplanner/astar/model/BinHeap.java
  src/main/java/org/opentripplanner/astar/model/ShortestPathTree.java
  src/main/java/org/opentripplanner/astar/strategy/MaxCountSkipEdgeStrategy.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/street/search/StreetSearchBuilder.java
  src/main/java/org/opentripplanner/street/search/strategy/EuclideanRemainingWeightHeuristic.java
  src/test/java/org/opentripplanner/astar/strategy/MaxCountSkipEdgeStrategyTest.java
  src/test/java/org/opentripplanner/street/search/state/TestStateBuilder.java
Labels: bug, IBI

#5614 Update dev meeting calendar instructions [ci skip]
  docs/Developers-Guide.md
Labels: documentation, skip changelog

#5615 Improve: Pin all dependencies, past and future in debug client
  client-next/.npmrc
  client-next/package-lock.json
  client-next/package.json
Labels: OTP Debug UI, skip changelog

#5604 Remove GTFS-RT websocket updater
  doc-templates/UpdaterConfig.md
  docs/RouterConfiguration.md
  docs/UpdaterConfig.md
  docs/sandbox/SiriUpdater.md
  pom.xml
  src/main/java/org/opentripplanner/standalone/config/routerconfig/UpdatersConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/WebsocketGtfsRealtimeUpdaterConfig.java
  src/main/java/org/opentripplanner/updater/UpdatersParameters.java
  src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
  src/main/java/org/opentripplanner/updater/trip/WebsocketGtfsRealtimeUpdater.java
  src/main/java/org/opentripplanner/updater/trip/WebsocketGtfsRealtimeUpdaterParameters.java
  src/test/resources/standalone/config/router-config.json
Labels: technical debt, bump serialization id

#5602 Add stop layer to new Debug UI
  client-next/.env
  client-next/.env.development
  client-next/src/components/MapView/GeometryPropertyPopup.tsx
  client-next/src/components/MapView/MapView.tsx
  client-next/src/components/MapView/mapStyle.ts
  docs/Configuration.md
  src/main/java/org/opentripplanner/apis/APIEndpoints.java
  src/main/java/org/opentripplanner/apis/vectortiles/DebugStyleSpec.java
  src/main/java/org/opentripplanner/apis/vectortiles/GraphInspectorVectorTileResource.java
  src/main/java/org/opentripplanner/apis/vectortiles/model/LayerParams.java
  src/main/java/org/opentripplanner/apis/vectortiles/model/LayerStyleBuilder.java
  src/main/java/org/opentripplanner/apis/vectortiles/model/LayerType.java
  src/main/java/org/opentripplanner/apis/vectortiles/model/StyleSpec.java
  src/main/java/org/opentripplanner/apis/vectortiles/model/TileSource.java
  src/main/java/org/opentripplanner/framework/application/OTPFeature.java
  src/main/java/org/opentripplanner/framework/io/HttpUtils.java
  src/main/java/org/opentripplanner/inspector/vector/AreaStopsLayerBuilder.java
  src/main/java/org/opentripplanner/inspector/vector/DebugClientAreaStopPropertyMapper.java
  src/main/java/org/opentripplanner/inspector/vector/KeyValue.java
  src/main/java/org/opentripplanner/inspector/vector/geofencing/GeofencingZonesLayerBuilder.java
  src/main/java/org/opentripplanner/inspector/vector/stop/StopLayerBuilder.java
  src/main/java/org/opentripplanner/inspector/vector/stop/StopLocationPropertyMapper.java
  src/main/java/org/opentripplanner/standalone/server/GrizzlyServer.java
  src/test/java/org/opentripplanner/apis/vectortiles/DebugStyleSpecTest.java
  src/test/java/org/opentripplanner/inspector/vector/stop/AreaStopLayerBuilderTest.java
  src/test/java/org/opentripplanner/test/support/JsonAssertions.java
  src/test/java/org/opentripplanner/test/support/ResourceLoader.java
  src/test/resources/org/opentripplanner/apis/vectortiles/style.json
Labels: OTP Debug UI

#5618 Add documentation about MQTT updater [ci skip]
  doc-templates/UpdaterConfig.md
  docs/RouterConfiguration.md
  docs/UpdaterConfig.md
  docs/sandbox/SiriUpdater.md
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/MqttGtfsRealtimeUpdaterConfig.java
  src/test/resources/standalone/config/router-config.json
Labels: documentation, skip changelog

#4652 Use fallback timezone if no transit data is loaded
  src/ext/java/org/opentripplanner/ext/restapi/resources/RoutingResource.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/RouteRequestMapper.java
  src/main/java/org/opentripplanner/framework/logging/Throttle.java
  src/main/java/org/opentripplanner/framework/time/ZoneIdFallback.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/service/DefaultRoutingService.java
  src/test/java/org/opentripplanner/framework/FrameworkArchitectureTest.java
  src/test/java/org/opentripplanner/framework/time/ZoneIdFallbackTest.java
Labels: bug

#5581 Add new path for GTFS GraphQL API, remove batch feature
  docs/apis/GTFS-GraphQL-API.md
  magidoc.mjs
  src/client/graphiql/index.html
  src/main/java/org/opentripplanner/apis/APIEndpoints.java
  src/main/java/org/opentripplanner/apis/gtfs/GtfsGraphQLAPI.java
  src/main/java/org/opentripplanner/framework/graphql/GraphQLResponseSerializer.java
Labels: improvement, technical debt

#5624 Switchable debug tiles for new UI
  client-next/package-lock.json
  client-next/package.json
  client-next/src/components/MapView/ContextMenuPopup.tsx
  client-next/src/components/MapView/GeometryPropertyPopup.tsx
  client-next/src/components/MapView/LayerControl.tsx
  client-next/src/components/MapView/MapView.tsx
  client-next/src/components/MapView/useMapDoubleClick.ts
  client-next/src/style.css
  src/main/java/org/opentripplanner/apis/vectortiles/DebugStyleSpec.java
  src/main/java/org/opentripplanner/apis/vectortiles/GraphInspectorVectorTileResource.java
  src/main/java/org/opentripplanner/apis/vectortiles/model/LayerParams.java
  src/main/java/org/opentripplanner/apis/vectortiles/model/LayerStyleBuilder.java
  src/main/java/org/opentripplanner/apis/vectortiles/model/LayerType.java
  src/main/java/org/opentripplanner/apis/vectortiles/model/StyleBuilder.java
  src/main/java/org/opentripplanner/apis/vectortiles/model/StyleSpec.java
  src/main/java/org/opentripplanner/apis/vectortiles/model/TileSource.java
  src/main/java/org/opentripplanner/apis/vectortiles/model/VectorSourceLayer.java
  src/main/java/org/opentripplanner/apis/vectortiles/model/ZoomDependentNumber.java
  src/main/java/org/opentripplanner/inspector/vector/edge/EdgeLayerBuilder.java
  src/main/java/org/opentripplanner/inspector/vector/edge/EdgePropertyMapper.java
  src/main/java/org/opentripplanner/inspector/vector/vertex/VertexLayerBuilder.java
  src/main/java/org/opentripplanner/inspector/vector/vertex/VertexPropertyMapper.java
  src/test/java/org/opentripplanner/apis/vectortiles/DebugStyleSpecTest.java
  src/test/resources/org/opentripplanner/apis/vectortiles/style.json
Labels: OTP Debug UI, skip changelog

#5582 Restructure walk/bicycle/car preferences in router-config.json
  docs/RouteRequest.md
  docs/RouterConfiguration.md
  docs/examples/entur/router-config.json
  docs/examples/ibi/atlanta/router-config.json
  docs/examples/ibi/portland/router-config.json
  docs/examples/skanetrafiken/router-config.json
  src/ext/java/org/opentripplanner/ext/restapi/mapping/LegacyBicycleOptimizeType.java
  src/ext/java/org/opentripplanner/ext/restapi/resources/RequestToPreferencesMapper.java
  src/ext/java/org/opentripplanner/ext/restapi/resources/RoutingResource.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/OptimizationTypeMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/RouteRequestMapper.java
  src/main/java/org/opentripplanner/apis/transmodel/mapping/preferences/BikePreferencesMapper.java
  src/main/java/org/opentripplanner/apis/transmodel/model/DefaultRouteRequestType.java
  src/main/java/org/opentripplanner/apis/transmodel/model/EnumTypes.java
  src/main/java/org/opentripplanner/routing/api/request/preference/BikePreferences.java
  src/main/java/org/opentripplanner/routing/api/request/preference/CarPreferences.java
  src/main/java/org/opentripplanner/routing/api/request/preference/RoutingPreferences.java
  src/main/java/org/opentripplanner/routing/api/request/preference/TimeSlopeSafetyTriangle.java
  src/main/java/org/opentripplanner/routing/api/request/preference/VehicleParkingPreferences.java
  src/main/java/org/opentripplanner/routing/api/request/preference/VehicleRentalPreferences.java
  src/main/java/org/opentripplanner/routing/api/request/preference/VehicleWalkingPreferences.java
  src/main/java/org/opentripplanner/routing/core/BicycleOptimizeType.java
  src/main/java/org/opentripplanner/service/vehiclerental/street/VehicleRentalEdge.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/TriangleOptimizationConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/VehicleParkingConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/VehicleRentalConfig.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/VehicleWalkingConfig.java
  src/main/java/org/opentripplanner/street/model/edge/BikeWalkableEdge.java
  src/main/java/org/opentripplanner/street/model/edge/CarPickupableEdge.java
  src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
  src/main/java/org/opentripplanner/street/model/edge/StreetEdgeReluctanceCalculator.java
  src/main/java/org/opentripplanner/street/model/edge/StreetTransitEntityLink.java
  src/main/java/org/opentripplanner/street/model/edge/TemporaryFreeEdge.java
  src/main/java/org/opentripplanner/street/model/edge/VehicleParkingEdge.java
  src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java
  src/test/java/org/opentripplanner/apis/gtfs/mapping/RouteRequestMapperTest.java
  src/test/java/org/opentripplanner/apis/transmodel/mapping/TripRequestMapperTest.java
  src/test/java/org/opentripplanner/apis/transmodel/mapping/preferences/BikePreferencesMapperTest.java
  src/test/java/org/opentripplanner/routing/api/request/preference/BikePreferencesTest.java
  src/test/java/org/opentripplanner/routing/api/request/preference/CarPreferencesTest.java
  src/test/java/org/opentripplanner/routing/api/request/preference/VehicleParkingPreferencesTest.java
  src/test/java/org/opentripplanner/routing/api/request/preference/VehicleRentalPreferencesTest.java
  src/test/java/org/opentripplanner/routing/api/request/preference/VehicleWalkingPreferencesTest.java
  src/test/java/org/opentripplanner/street/integration/BarrierRoutingTest.java
  src/test/java/org/opentripplanner/street/integration/BicycleRoutingTest.java
  src/test/java/org/opentripplanner/street/integration/BikeRentalTest.java
  src/test/java/org/opentripplanner/street/integration/BikeWalkingTest.java
  src/test/java/org/opentripplanner/street/integration/ParkAndRideTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeCostTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetVehicleParkingLinkTest.java
  src/test/java/org/opentripplanner/street/model/edge/VehicleParkingPreferredTagsTest.java
  src/test/resources/standalone/config/router-config.json
  test/performance/norway/speed-test-config.json
  test/performance/skanetrafiken/speed-test-config.json
  test/performance/switzerland/speed-test-config.json
Labels: improvement, bump serialization id, config change

#5629 Revert REST API spelling change of real-time
  src/ext/java/org/opentripplanner/ext/restapi/mapping/TripTimeMapper.java
  src/ext/java/org/opentripplanner/ext/restapi/model/ApiTripTimeShort.java
  src/ext/java/org/opentripplanner/ext/restapi/model/ApiVehicleParkingWithEntrance.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/CarSnapshotTest.snap
Labels: bug, sandbox, IBI

#5626 Transit group report
  docs/sandbox/ReportApi.md
  src/ext/java/org/opentripplanner/ext/reportapi/model/TransitGroupPriorityReport.java
  src/ext/java/org/opentripplanner/ext/reportapi/resource/ReportResource.java
  src/main/java/org/opentripplanner/framework/logging/Throttle.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/PriorityGroupConfigurator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
  src/test/java/org/opentripplanner/framework/logging/ThrottleTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/PriorityGroupConfiguratorTest.java
Labels: improvement, sandbox, skip changelog

#5613 Remove `FareComponent`
  src/ext-test/java/org/opentripplanner/ext/fares/impl/CombinedInterlinedLegsFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/FareModelForTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/FaresIntegrationTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/HSLFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/restapi/mapping/FareMapperTest.java
  src/ext-test/resources/org/opentripplanner/ext/fares/impl/farecomponents.gtfs.zip
  src/ext/java/org/opentripplanner/ext/fares/FaresToItineraryMapper.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFaresData.java
  src/ext/java/org/opentripplanner/ext/fares/model/FareRuleSet.java
  src/ext/java/org/opentripplanner/ext/restapi/mapping/FareMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/GtfsGraphQLIndex.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/ItineraryImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/fareComponentImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/fareImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/graphql-codegen.yml
  src/main/java/org/opentripplanner/model/fare/ItineraryFares.java
  src/main/java/org/opentripplanner/routing/core/FareComponent.java
  src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/ElevationSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/plan-fares.json
Labels: technical debt, IBI, bump serialization id, HSL

#5637 Change Transmodel API path to `/otp/transmodel/v3`
  docs/apis/TransmodelApi.md
  src/client/graphiql/index.html
  src/main/java/org/opentripplanner/apis/APIEndpoints.java
  src/main/java/org/opentripplanner/apis/transmodel/TransmodelAPI.java
Labels: technical debt

#5625 Add flexibleArea to GroupStop Quays
  src/ext/java/org/opentripplanner/ext/flex/FlexIndex.java
  src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
  src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
  src/main/java/org/opentripplanner/apis/transmodel/model/stop/QuayType.java
  src/main/java/org/opentripplanner/apis/transmodel/model/stop/StopTypeMapper.java
  src/main/java/org/opentripplanner/graph_builder/module/StreetLinkerModule.java
  src/main/java/org/opentripplanner/netex/mapping/FlexStopsMapper.java
  src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  src/main/java/org/opentripplanner/transit/model/site/AreaStop.java
  src/main/java/org/opentripplanner/transit/model/site/GroupStop.java
  src/main/java/org/opentripplanner/transit/model/site/GroupStopBuilder.java
  src/main/java/org/opentripplanner/transit/model/site/RegularStop.java
  src/main/java/org/opentripplanner/transit/model/site/StopLocation.java
  src/main/java/org/opentripplanner/transit/model/site/StopType.java
  src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
  src/test/java/org/opentripplanner/gtfs/mapping/StopTimeMapperTest.java
  src/test/java/org/opentripplanner/netex/mapping/FlexStopsMapperTest.java
  src/test/java/org/opentripplanner/transit/model/site/GroupStopTest.java
Labels: improvement, bump serialization id

#5646 Log trip and pattern id when negative trip-times occurs in routing.
  src/main/java/org/opentripplanner/framework/lang/ObjectUtils.java
  src/main/java/org/opentripplanner/framework/tostring/ToStringBuilder.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleWithOffset.java
  src/main/java/org/opentripplanner/transit/model/network/RoutingTripPattern.java
  src/test/java/org/opentripplanner/framework/lang/ObjectUtilsTest.java
  src/test/java/org/opentripplanner/framework/tostring/ToStringBuilderTest.java
Labels: bug, technical debt, Entur test, skip changelog

#5638 Pass-through should override transit-group-priority
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RaptorRequestMapper.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RaptorRequestMapperTest.java
Labels: bug, Entur test
