Repository opentripplanner/OpenTripPlanner, pull requests merged in 2024-04, with the labels that each got.

#5773 Correct order for x,y when constructing JTS coordinates in tests
  src/ext-test/java/org/opentripplanner/ext/flex/AreaStopsToVerticesMapperTest.java
  src/test/java/org/opentripplanner/_support/geometry/Coordinates.java
  src/test/java/org/opentripplanner/_support/geometry/Polygons.java
  src/test/java/org/opentripplanner/framework/geometry/WgsCoordinateTest.java
  src/test/java/org/opentripplanner/graph_builder/module/StreetLinkerModuleTest.java
  src/test/java/org/opentripplanner/routing/core/TemporaryVerticesContainerTest.java
  src/test/java/org/opentripplanner/street/model/_data/StreetModelForTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeTest.java
  src/test/java/org/opentripplanner/updater/vehicle_rental/GeofencingVertexUpdaterTest.java
Labels: technical debt, skip changelog

#5785 Remove dependency on org.json-simple
  pom.xml
  src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/TestTransitService.java
  src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/stations/DigitransitStationPropertyMapperTest.java
  src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/stops/RealtimeStopsLayerTest.java
  src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/stops/StopsLayerTest.java
  src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/VehicleParkingGroupsLayerTest.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/stations/DigitransitStationPropertyMapper.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/DigitransitStopPropertyMapper.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/DigitransitVehicleParkingGroupPropertyMapper.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/StadtnaviVehicleParkingPropertyMapper.java
Labels: sandbox, technical debt, skip changelog

#5797 Upgrade Codecov action and use token [ci skip]
  .github/workflows/cibuild.yml
  .github/workflows/performance-test.yml
Labels: skip changelog

#5769 Parking updater for NOI Open Data Hub
  doc-templates/VehicleParking.md
  docs/RouterConfiguration.md
  docs/UpdaterConfig.md
  docs/sandbox/VehicleParking.md
  docs/sandbox/siri/SiriAzureUpdater.md
  docs/sandbox/siri/SiriUpdater.md
  src/ext-test/java/org/opentripplanner/ext/vehicleparking/noi/NoiUpdaterTest.java
  src/ext-test/resources/org/opentripplanner/ext/vehicleparking/noi/stations.json
  src/ext/java/org/opentripplanner/ext/vehicleparking/noi/NoiUpdater.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/noi/NoiUpdaterParameters.java
  src/main/java/org/opentripplanner/routing/vehicle_parking/VehicleParking.java
  src/main/java/org/opentripplanner/standalone/config/framework/json/OtpVersion.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/VehicleParkingUpdaterConfig.java
  src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingDataSourceFactory.java
  src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingSourceType.java
  src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingUpdater.java
  src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
  src/test/java/org/opentripplanner/graph_builder/module/VehicleParkingLinkingTest.java
  src/test/java/org/opentripplanner/routing/vehicle_parking/VehicleParkingHelperTest.java
  src/test/java/org/opentripplanner/routing/vehicle_parking/VehicleParkingTestUtil.java
  src/test/java/org/opentripplanner/street/model/_data/StreetModelForTest.java
  src/test/java/org/opentripplanner/street/model/edge/VehicleParkingEdgeTest.java
  src/test/java/org/opentripplanner/street/model/edge/VehicleParkingPreferredTagsTest.java
  src/test/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingUpdaterTest.java
  src/test/resources/standalone/config/router-config.json
Labels: sandbox, skip changelog

#5790 Discourage instead of ban cycling on use_sidepath ways and do the same for walking on foot=use_sidepath
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWay.java
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/DefaultMapper.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/FinlandMapper.java
  src/test/java/org/opentripplanner/openstreetmap/model/OSMWayTest.java
  src/test/java/org/opentripplanner/openstreetmap/model/OSMWithTagsTest.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/DefaultMapperTest.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/FinlandMapperTest.java
  src/test/java/org/opentripplanner/openstreetmap/wayproperty/WayPropertySetTest.java
Labels: improvement

#5779 Overwrite default WALK directMode when it is not set in the request, but modes is set
  src/main/java/org/opentripplanner/apis/transmodel/mapping/RequestModesMapper.java
  src/test/java/org/opentripplanner/apis/transmodel/mapping/RequestModesMapperTest.java
Labels: Entur test

#5784 Improve handling of invalid leg reference
  src/main/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializer.java
  src/test/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializerTest.java
Labels: improvement, Entur test, skip changelog

#5786 Move expensive `WGS84_XY` constant setup into ElevationModule
  src/main/java/org/opentripplanner/framework/geometry/GeometryUtils.java
  src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
Labels: technical debt, skip changelog

#5794 Fix trip duplication in Graph Builder DSJ mapping
  src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
  src/test/java/org/opentripplanner/netex/mapping/NetexTestDataSample.java
  src/test/java/org/opentripplanner/netex/mapping/TripPatternMapperTest.java
Labels: bug, Entur test, NeTEx

#5801 Implement `hashCode` for `Money` class
  src/main/java/org/opentripplanner/transit/model/basic/Money.java
  src/test/java/org/opentripplanner/routing/core/MoneyTest.java
Labels: bug, technical debt, skip changelog

#5808 Fix DebugUi doc [ci skip]
  docs/Frontends.md
Labels: documentation, skip changelog

#5676 Optionally abort startup when unknown configuration parameters were detected
  docs/Migrating-Configuration.md
  mkdocs.yml
  src/main/java/org/opentripplanner/standalone/OTPMain.java
  src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  src/main/java/org/opentripplanner/standalone/config/CommandLineParameters.java
  src/main/java/org/opentripplanner/standalone/config/ConfigModel.java
  src/main/java/org/opentripplanner/standalone/config/OtpConfig.java
  src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
  src/main/java/org/opentripplanner/standalone/config/framework/json/NodeAdapter.java
  src/main/java/org/opentripplanner/standalone/config/framework/json/ParameterBuilder.java
  src/test/java/org/opentripplanner/standalone/config/framework/json/NodeAdapterTest.java
Labels: new feature, IBI

#5783 Fix bug in heuristics cost calculation for egress legs
  src/main/java/org/opentripplanner/raptor/rangeraptor/standard/heuristics/HeuristicsAdapter.java
  src/main/java/org/opentripplanner/raptor/spi/RaptorCostCalculator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/DefaultCostCalculator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/PatternCostCalculator.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/WheelchairCostCalculator.java
  src/test/java/org/opentripplanner/raptor/_data/RaptorTestConstants.java
  src/test/java/org/opentripplanner/raptor/_data/transit/TestTransitData.java
  src/test/java/org/opentripplanner/raptor/moduletests/B05_EgressStopTransferCostTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/DefaultCostCalculatorTest.java
Labels: bug, Skanetrafiken
