Repository opentripplanner/OpenTripPlanner, pull requests merged in 2024-03, with the labels that each got.

#5708 Fix Bikely vehicle parking updater
  docs/sandbox/VehicleParking.md
  src/ext-test/java/org/opentripplanner/ext/vehicleparking/bikely/BikelyUpdaterTest.java
  src/ext-test/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkUpdaterTest.java
  src/ext-test/java/org/opentripplanner/ext/vehicleparking/parkapi/ParkAPIUpdaterTest.java
  src/ext-test/resources/org/opentripplanner/ext/vehicleparking/bikely/bikely.json
  src/ext-test/resources/org/opentripplanner/ext/vehicleparking/hslpark/facilities.json
  src/ext-test/resources/org/opentripplanner/ext/vehicleparking/hslpark/hubs.json
  src/ext-test/resources/org/opentripplanner/ext/vehicleparking/hslpark/utilizations.json
  src/ext-test/resources/org/opentripplanner/ext/vehicleparking/parkapi/herrenberg.json
  src/ext-test/resources/org/opentripplanner/ext/vehicleparking/parkapi/parkapi-reutlingen.json
  src/ext-test/resources/vehicleparking/bikely/bikely.json
  src/ext/java/org/opentripplanner/ext/vehicleparking/bikely/BikelyUpdater.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/bikely/BikelyUpdaterParameters.java
  src/main/java/org/opentripplanner/framework/io/OtpHttpClient.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/VehicleParkingUpdaterConfig.java
Labels: sandbox, skip changelog

#5705 Avoid cumulative real-time updates
  src/ext/java/org/opentripplanner/ext/siri/ModifiedTripBuilder.java
  src/ext/java/org/opentripplanner/ext/siri/mapper/PickDropMapper.java
  src/ext/java/org/opentripplanner/ext/stopconsolidation/StopConsolidationModule.java
  src/main/java/org/opentripplanner/framework/lang/MemEfficientArrayBuilder.java
  src/main/java/org/opentripplanner/transit/model/network/StopPattern.java
  src/main/java/org/opentripplanner/transit/model/network/TripPattern.java
  src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
  src/test/java/org/opentripplanner/framework/lang/MemEfficientArrayBuilderTest.java
  src/test/java/org/opentripplanner/model/TripPatternTest.java
  src/test/java/org/opentripplanner/netex/mapping/ServiceLinkMapperTest.java
  src/test/java/org/opentripplanner/transit/model/_data/TransitModelForTest.java
Labels: bug, RealTimeUpdate, Digitransit test

#5715 Fix time penalty
  src/main/java/org/opentripplanner/raptor/api/model/AbstractAccessEgressDecorator.java
  src/main/java/org/opentripplanner/raptor/api/model/RaptorAccessEgress.java
  src/main/java/org/opentripplanner/raptor/api/model/RaptorConstants.java
  src/main/java/org/opentripplanner/raptor/api/path/RaptorPath.java
  src/main/java/org/opentripplanner/raptor/api/request/SearchParams.java
  src/main/java/org/opentripplanner/raptor/api/request/SearchParamsBuilder.java
  src/main/java/org/opentripplanner/raptor/path/Path.java
  src/main/java/org/opentripplanner/raptor/path/PathBuilderLeg.java
  src/main/java/org/opentripplanner/raptor/rangeraptor/DefaultRangeRaptorWorker.java
  src/main/java/org/opentripplanner/raptor/rangeraptor/context/SearchContext.java
  src/main/java/org/opentripplanner/raptor/rangeraptor/multicriteria/McStopArrivals.java
  src/main/java/org/opentripplanner/raptor/rangeraptor/path/DestinationArrivalPaths.java
  src/main/java/org/opentripplanner/raptor/rangeraptor/path/PathParetoSetComparators.java
  src/main/java/org/opentripplanner/raptor/rangeraptor/path/configure/PathConfig.java
  src/main/java/org/opentripplanner/raptor/rangeraptor/transit/AccessPaths.java
  src/main/java/org/opentripplanner/raptor/rangeraptor/transit/AccessWithPenalty.java
  src/main/java/org/opentripplanner/raptor/rangeraptor/transit/EgressPaths.java
  src/main/java/org/opentripplanner/raptor/rangeraptor/transit/EgressWithPenalty.java
  src/main/java/org/opentripplanner/raptor/rangeraptor/transit/ForwardRaptorTransitCalculator.java
  src/main/java/org/opentripplanner/raptor/rangeraptor/transit/RaptorTransitCalculator.java
  src/main/java/org/opentripplanner/raptor/rangeraptor/transit/ReverseRaptorTransitCalculator.java
  src/main/java/org/opentripplanner/raptor/spi/UnknownPath.java
  src/main/java/org/opentripplanner/raptor/util/IntIterators.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/AccessEgresses.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/DefaultAccessEgress.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/FlexAccessEgressAdapter.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RaptorRequestMapper.java
  src/test/java/org/opentripplanner/raptor/_data/RaptorTestConstants.java
  src/test/java/org/opentripplanner/raptor/_data/api/TestRaptorPath.java
  src/test/java/org/opentripplanner/raptor/_data/transit/TestAccessEgress.java
  src/test/java/org/opentripplanner/raptor/api/path/RaptorPathTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/J01_SearchWindowAccessSlack.java
  src/test/java/org/opentripplanner/raptor/moduletests/L01_TimePenaltyAccessTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/L01_TimePenaltyEgressTest.java
  src/test/java/org/opentripplanner/raptor/moduletests/support/ExpectedList.java
  src/test/java/org/opentripplanner/raptor/rangeraptor/transit/AccessPathsTest.java
  src/test/java/org/opentripplanner/raptor/rangeraptor/transit/AccessWithPenaltyTest.java
  src/test/java/org/opentripplanner/raptor/rangeraptor/transit/EgressWithPenaltyTest.java
  src/test/java/org/opentripplanner/raptor/rangeraptor/transit/ForwardRaptorTransitCalculatorTest.java
  src/test/java/org/opentripplanner/raptor/rangeraptor/transit/ReverseRaptorTransitCalculatorTest.java
  src/test/java/org/opentripplanner/raptor/util/IntIteratorsTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapperTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/AccessEgressPenaltyDecoratorTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/AccessEgressesTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/DefaultAccessEgressTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RaptorRequestMapperTest.java
Labels: bug, improvement, Entur test, bump serialization id

#5723 Migrate from VariableSource to MethodSource
  src/ext-test/java/org/opentripplanner/ext/fares/impl/CombinedInterlinedLegsFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/model/FareProductTest.java
  src/ext-test/java/org/opentripplanner/ext/ridehailing/RideHailingAccessShifterTest.java
  src/test/java/org/opentripplanner/apis/gtfs/mapping/RouteRequestMapperTest.java
  src/test/java/org/opentripplanner/apis/transmodel/mapping/TripRequestMapperTest.java
  src/test/java/org/opentripplanner/apis/transmodel/model/scalars/DateTimeScalarFactoryTest.java
  src/test/java/org/opentripplanner/framework/lang/StringUtilsTest.java
  src/test/java/org/opentripplanner/graph_builder/module/GtfsFeedIdTest.java
  src/test/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModuleTest.java
  src/test/java/org/opentripplanner/gtfs/interlining/InterlineProcessorTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/LocationMapperTest.java
  src/test/java/org/opentripplanner/gtfs/mapping/TransitModeMapperTest.java
  src/test/java/org/opentripplanner/model/plan/PlaceTest.java
  src/test/java/org/opentripplanner/model/plan/RelativeDirectionTest.java
  src/test/java/org/opentripplanner/openstreetmap/OSMOpeningHoursParserTest.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/PortlandMapperTest.java
  src/test/java/org/opentripplanner/openstreetmap/wayproperty/specifier/BestMatchSpecifierTest.java
  src/test/java/org/opentripplanner/openstreetmap/wayproperty/specifier/ConditionTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TripPatternForDateTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/WheelchairCostCalculatorTest.java
  src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RouteRequestTransitDataProviderFilterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGeneratorTest.java
  src/test/java/org/opentripplanner/routing/api/request/WheelchairPreferencesTest.java
  src/test/java/org/opentripplanner/routing/api/request/framework/LinearFunctionSerializationTest.java
  src/test/java/org/opentripplanner/routing/api/request/preference/TimeSlopeSafetyTriangleTest.java
  src/test/java/org/opentripplanner/routing/core/MoneyTest.java
  src/test/java/org/opentripplanner/standalone/config/routerequest/WheelchairConfigTest.java
  src/test/java/org/opentripplanner/standalone/server/EtagRequestFilterTest.java
  src/test/java/org/opentripplanner/standalone/server/RequestTraceFilterTest.java
  src/test/java/org/opentripplanner/street/model/edge/ElevatorHopEdgeTest.java
  src/test/java/org/opentripplanner/street/model/edge/EscalatorEdgeTest.java
  src/test/java/org/opentripplanner/street/model/edge/PathwayEdgeTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeCostTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeRentalTraversalTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeWheelchairCostTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetVehicleParkingLinkTest.java
  src/test/java/org/opentripplanner/street/search/state/StateDataTest.java
  src/test/java/org/opentripplanner/street/search/state/StateTest.java
  src/test/java/org/opentripplanner/test/support/VariableArgumentsProvider.java
  src/test/java/org/opentripplanner/test/support/VariableSource.java
  src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java
  src/test/java/org/opentripplanner/updater/vehicle_position/RealtimeVehicleMatcherTest.java
Labels: technical debt, skip changelog

#5714 Prevent feed id from being used twice
  src/main/java/org/opentripplanner/gtfs/graphbuilder/GtfsModule.java
  src/test/java/org/opentripplanner/graph_builder/module/GtfsModuleTest.java
Labels: GTFS, technical debt, IBI, skip changelog

#5735 Fix error in access filter when access with time-penalty exits
  src/main/java/org/opentripplanner/raptor/rangeraptor/transit/AccessPaths.java
  src/test/java/org/opentripplanner/raptor/rangeraptor/transit/AccessPathsTest.java
Labels: bug, Entur test, skip changelog

#5703 Throw exception when feed ids contain invisible characters
  src/main/java/org/opentripplanner/framework/lang/StringUtils.java
  src/main/java/org/opentripplanner/transit/model/framework/FeedScopedId.java
  src/test/java/org/opentripplanner/framework/lang/StringUtilsTest.java
  src/test/java/org/opentripplanner/transit/model/framework/FeedScopedIdTest.java
Labels: improvement, skip changelog

#5724 Add user agent to HTTP client
  src/main/java/org/opentripplanner/framework/io/OtpHttpClient.java
Labels: improvement, skip changelog

#5731 Fix world envelope builder when crossing Greenwich meridian
  src/main/java/org/opentripplanner/service/worldenvelope/model/WorldEnvelope.java
  src/main/java/org/opentripplanner/service/worldenvelope/model/WorldEnvelopeBuilder.java
  src/test/java/org/opentripplanner/service/worldenvelope/model/WorldEnvelopeTest.java
Labels: bug

#5660 ISO-8601 date time for GTFS API itinerary responses
  docs/apis/GraphQL-Tutorial.md
  magidoc.mjs
  src/ext/java/org/opentripplanner/ext/fares/impl/CombinedInterlinedTransitLeg.java
  src/ext/java/org/opentripplanner/ext/flex/FlexibleTransitLeg.java
  src/ext/java/org/opentripplanner/ext/restapi/mapping/PlaceMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/GraphQLScalars.java
  src/main/java/org/opentripplanner/apis/gtfs/GtfsGraphQLIndex.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/ItineraryImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/LegImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/PlaceImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/graphql-codegen.yml
  src/main/java/org/opentripplanner/apis/transmodel/model/scalars/DateTimeScalarFactory.java
  src/main/java/org/opentripplanner/framework/graphql/scalar/DurationScalarFactory.java
  src/main/java/org/opentripplanner/framework/time/DurationUtils.java
  src/main/java/org/opentripplanner/framework/time/OffsetDateTimeParser.java
  src/main/java/org/opentripplanner/model/plan/FrequencyTransitLeg.java
  src/main/java/org/opentripplanner/model/plan/Leg.java
  src/main/java/org/opentripplanner/model/plan/LegTime.java
  src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
  src/main/java/org/opentripplanner/model/plan/StopArrival.java
  src/main/java/org/opentripplanner/model/plan/StopArrivalMapper.java
  src/main/java/org/opentripplanner/model/plan/StreetLeg.java
  src/main/java/org/opentripplanner/model/plan/UnknownTransitPathLeg.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/AlertToLegMapper.java
  src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
  src/test/java/org/opentripplanner/apis/gtfs/DurationScalarTest.java
  src/test/java/org/opentripplanner/apis/gtfs/GeoJsonScalarTest.java
  src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
  src/test/java/org/opentripplanner/apis/gtfs/OffsetDateTimeScalarTest.java
  src/test/java/org/opentripplanner/framework/time/DurationUtilsTest.java
  src/test/java/org/opentripplanner/framework/time/OffsetDateTimeParserTest.java
  src/test/java/org/opentripplanner/model/plan/ScheduledTransitLegTest.java
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/plan-extended.json
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/plan.json
  src/test/resources/org/opentripplanner/apis/gtfs/queries/plan-extended.graphql
  src/test/resources/org/opentripplanner/apis/gtfs/queries/plan.graphql
Labels: improvement, technical debt

#5741 Adjust SIRI ServiceBus-client parameters to improve performance
  docs/sandbox/siri/SiriAzureUpdater.md
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/AbstractAzureSiriUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureUpdaterParameters.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/azure/SiriAzureUpdaterConfig.java
Labels: sandbox, skip changelog

#5747 Fix skanetrafiken performance test
  .github/workflows/performance-test.yml
  test/performance/skanetrafiken/build-config.json
Labels: Skanetrafiken, skip changelog

#5737 Add script to compile, build, run, call API and test response [ci skip]
  script/Readme.md
  script/run-and-test-otp
Labels: improvement, skip changelog

#5732 Fix street routing on roundabout
  src/main/java/org/opentripplanner/street/model/edge/Edge.java
  src/main/java/org/opentripplanner/street/model/edge/TemporaryPartialStreetEdge.java
  src/test/java/org/opentripplanner/street/integration/WalkRoutingTest.java
  src/test/resources/org/opentripplanner/street/integration/roundabout.osm.pbf
Labels: bug

#5642 Make logging of MQTT realtime updater more uniform
  src/main/java/org/opentripplanner/updater/alert/GtfsRealtimeAlertsUpdater.java
  src/main/java/org/opentripplanner/updater/trip/MqttGtfsRealtimeUpdater.java
Labels: skip changelog

#5760 Fix issues in SiriAzure initialization
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/AbstractAzureSiriUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureInitializationException.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java
  src/main/java/org/opentripplanner/framework/io/OtpHttpClient.java
Labels: sandbox, Skanetrafiken, skip changelog

#5766 Add link to osm.org from new debug client
  client-next/src/components/MapView/GeometryPropertyPopup.tsx
  client-next/src/style.css
Labels: OTP Debug UI, skip changelog

#5764 Expose route sort order in GTFS API
  docs/apis/GraphQL-Tutorial.md
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/RouteImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
  src/main/java/org/opentripplanner/framework/lang/IntUtils.java
  src/main/java/org/opentripplanner/transit/model/network/Route.java
  src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
  src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
  src/test/java/org/opentripplanner/framework/lang/IntUtilsTest.java
  src/test/java/org/opentripplanner/generate/doc/GraphQLTutorialDocTest.java
  src/test/java/org/opentripplanner/transit/model/network/RouteTest.java
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/plan-tutorial.json
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/routes-extended.json
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/routes-tutorial.json
  src/test/resources/org/opentripplanner/apis/gtfs/queries/plan-tutorial.graphql
  src/test/resources/org/opentripplanner/apis/gtfs/queries/routes-extended.graphql
  src/test/resources/org/opentripplanner/apis/gtfs/queries/routes-tutorial.graphql
Labels: improvement, GTFS
