Repository opentripplanner/OpenTripPlanner, pull requests merged in 2024-10, with the labels that each got.

#6099 Add mapper for GTFS GraphQL real time state
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/LegImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/StoptimeImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/graphql-codegen.yml
  src/main/java/org/opentripplanner/apis/gtfs/mapping/RealtimeStateMapper.java
Labels: technical debt, Skip Changelog

#6106 doc: update `NamingConventions.md` reference [ci skip]
  DEVELOPMENT_DECISION_RECORDS.md
  doc/user/Developers-Guide.md
Labels: Documentation, Skip Changelog

#6093 Don't use elevation data directly for ways with cutting=*, location=underground or indoor=yes tags in the default mapper
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/DefaultMapper.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/DefaultMapperTest.java
Labels: improvement

#6105 Add more memory for docker container [ci skip]
  doc/user/Container-Image.md
Labels: Documentation, Skip Changelog

#6098 Remove NOI parking updater
  doc/templates/VehicleParking.md
  doc/user/RouterConfiguration.md
  doc/user/UpdaterConfig.md
  doc/user/sandbox/VehicleParking.md
  doc/user/sandbox/siri/SiriAzureUpdater.md
  doc/user/sandbox/siri/SiriGooglePubSubUpdater.md
  doc/user/sandbox/siri/SiriUpdater.md
  src/ext-test/java/org/opentripplanner/ext/vehicleparking/noi/NoiUpdaterTest.java
  src/ext-test/resources/org/opentripplanner/ext/vehicleparking/noi/stations.json
  src/ext/java/org/opentripplanner/ext/vehicleparking/noi/NoiUpdater.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/noi/NoiUpdaterParameters.java
  src/ext/java/org/opentripplanner/ext/vehicleparking/sirifm/SiriFmUpdaterParameters.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/VehicleParkingUpdaterConfig.java
  src/main/java/org/opentripplanner/updater/vehicle_parking/AvailabilityDatasourceFactory.java
  src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingDataSourceFactory.java
  src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingSourceType.java
  src/test/resources/standalone/config/router-config.json
Labels: Sandbox, Skip Changelog

#6111 Add geometry for `EscalatorEdge`
  src/main/java/org/opentripplanner/street/model/edge/EscalatorEdge.java
  src/test/java/org/opentripplanner/street/model/edge/EscalatorEdgeTest.java
Labels: Skip Changelog

#6110 Un-deprecate GTFS API's `planConnection`, deprecate `plan`
  doc/user/apis/GraphQL-Tutorial.md
  doc/user/css/magidoc-overrides.css
  magidoc.mjs
  src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
  src/test/java/org/opentripplanner/generate/doc/GraphQLTutorialDocTest.java
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/plan-extended.json
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/plan-fares.json
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/plan-stop-positions.json
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/plan-tutorial.json
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/plan.json
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/planConnection-extended.json
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/planConnection-fares.json
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/planConnection-stop-positions.json
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/planConnection-tutorial.json
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/planConnection.json
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/walk-steps.json
  src/test/resources/org/opentripplanner/apis/gtfs/queries/plan-extended.graphql
  src/test/resources/org/opentripplanner/apis/gtfs/queries/plan-fares.graphql
  src/test/resources/org/opentripplanner/apis/gtfs/queries/plan-stop-positions.graphql
  src/test/resources/org/opentripplanner/apis/gtfs/queries/plan-tutorial.graphql
  src/test/resources/org/opentripplanner/apis/gtfs/queries/plan.graphql
  src/test/resources/org/opentripplanner/apis/gtfs/queries/planConnection-extended.graphql
  src/test/resources/org/opentripplanner/apis/gtfs/queries/planConnection-fares.graphql
  src/test/resources/org/opentripplanner/apis/gtfs/queries/planConnection-stop-positions.graphql
  src/test/resources/org/opentripplanner/apis/gtfs/queries/planConnection-tutorial.graphql
  src/test/resources/org/opentripplanner/apis/gtfs/queries/planConnection.graphql
  src/test/resources/org/opentripplanner/apis/gtfs/queries/walk-steps.graphql
Labels: improvement

#6062 Split NeTEx docs into tutorial and profile information
  doc/templates/Netex-Tutorial.md
  doc/user/Frontends.md
  doc/user/Netex-Norway.md
  doc/user/Netex-Tutorial.md
  doc/user/features-explained/Netex-Siri-Compatibility.md
  mkdocs.yml
  src/test/java/org/opentripplanner/generate/doc/NetexTutorialDocTest.java
  src/test/java/org/opentripplanner/generate/doc/framework/DocBuilder.java
  src/test/java/org/opentripplanner/standalone/config/ExampleConfigTest.java
  src/test/resources/standalone/config/netex-tutorial/build-config.json
  src/test/resources/standalone/config/netex-tutorial/router-config.json
Labels: Documentation, Skip Changelog

#6129 Minor cleanup of some OSM classes
  src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/NoteProperties.java
  src/test/java/org/opentripplanner/openstreetmap/model/OSMWithTagsTest.java
Labels: technical debt, Skip Changelog

#6123 debug client: update the map cursor when interactive
  client/src/components/MapView/MapView.tsx
  client/src/components/MapView/NavigationMarkers.tsx
Labels: Skip Changelog

#6124 Timetable snapshot code cleanup
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/StopImpl.java
  src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  src/main/java/org/opentripplanner/routing/stoptimes/StopTimesHelper.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/TransitService.java
  src/main/java/org/opentripplanner/updater/siri/SiriFuzzyTripMatcher.java
  src/main/java/org/opentripplanner/updater/siri/SiriTimetableSnapshotSource.java
  src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotManager.java
  src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
  src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java
  src/test/java/org/opentripplanner/updater/trip/moduletests/delay/SkippedTest.java
Labels: technical debt, RealTimeUpdate, Skip Changelog

#6138 Fix GTFS-Flex duration offset and factor parsing when only one of them is set
  src/main/java/org/opentripplanner/gtfs/mapping/TripMapper.java
  src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java
Labels: Bug, GTFS

#6125 Update code style for ordering things inside classes
  doc/dev/decisionrecords/Codestyle.md
  doc/user/Developers-Guide.md
Labels: Documentation, Skip Changelog

#6140 Make TransitModelIndex more immutable
  src/main/java/org/opentripplanner/netex/NetexModule.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/TransitModel.java
  src/main/java/org/opentripplanner/transit/service/TransitModelIndex.java
  src/test/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReferenceTest.java
  src/test/java/org/opentripplanner/transit/service/TransitModelTest.java
  src/test/java/org/opentripplanner/updater/trip/RealtimeTestEnvironmentBuilder.java
Labels: bump serialization id, Skip Changelog

#6154 Install mkdocs with --break-system-packages
  .github/workflows/cibuild.yml
Labels: Skip Changelog

#6153 Fix duplicated dirty timetables
  application/src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerUpdater.java
  application/src/test/java/org/opentripplanner/model/TimetableSnapshotTest.java
Labels: Bug, Entur Test, Real-Time Update, Skip Changelog

#6166 Add button to swap from/to in debug UI
  client/src/components/SearchBar/SearchBar.tsx
  client/src/components/SearchBar/SwapLocationsButton.tsx
  client/src/static/img/swap.svg
  client/src/style.css
Labels: OTP Debug UI, Skip Changelog

#6162 Fix regression error in passThroughPoints in the Transmodel API
  application/src/main/java/org/opentripplanner/apis/transmodel/mapping/TripViaLocationMapper.java
  application/src/main/java/org/opentripplanner/apis/transmodel/model/plan/ViaLocationInputType.java
  application/src/main/java/org/opentripplanner/routing/api/request/via/PassThroughViaLocation.java
  application/src/main/java/org/opentripplanner/routing/api/request/via/VisitViaLocation.java
  application/src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
  application/src/test/java/org/opentripplanner/apis/transmodel/mapping/TripViaLocationMapperTest.java
Labels: Bug, Regression, Entur Test, Skip Changelog, High Priority

#6175 Update Washington state flex speed test
  .github/workflows/performance-test.yml
  test/performance/washington-state/build-config.json
  test/performance/washington-state/generate_test_cases.py
  test/performance/washington-state/speed-test-config.json
  test/performance/washington-state/travelSearch-expected-results.csv
  test/performance/washington-state/travelSearch.csv
Labels: Skip Changelog

#6141 Clear added patterns in TimetableSnapshot
  application/src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  application/src/test/java/org/opentripplanner/model/TimetableSnapshotTest.java
Labels: Bug, Real-Time Update

#6147 Add @Nullable annotations to Trip and Leg
  application/src/ext/java/org/opentripplanner/ext/fares/impl/CombinedInterlinedTransitLeg.java
  application/src/ext/java/org/opentripplanner/ext/flex/FlexibleTransitLeg.java
  application/src/main/java/org/opentripplanner/model/plan/Leg.java
  application/src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
  application/src/main/java/org/opentripplanner/model/plan/UnknownTransitPathLeg.java
  application/src/main/java/org/opentripplanner/netex/mapping/ServiceLinkMapper.java
  application/src/main/java/org/opentripplanner/transit/model/network/Route.java
  application/src/main/java/org/opentripplanner/transit/model/timetable/Trip.java
  application/src/test/java/org/opentripplanner/GtfsTest.java
Labels: Skip Changelog

#6163 Remove unwanted dependencies in Raptor code
  application/src/main/java/org/opentripplanner/framework/application/OTPRequestTimeoutException.java
  application/src/main/java/org/opentripplanner/raptor/api/request/RaptorEnvironment.java
  application/src/main/java/org/opentripplanner/raptor/api/request/RaptorTuningParameters.java
  application/src/main/java/org/opentripplanner/raptor/api/view/ArrivalView.java
  application/src/main/java/org/opentripplanner/raptor/configure/RaptorConfig.java
  application/src/main/java/org/opentripplanner/raptor/rangeraptor/RangeRaptor.java
  application/src/main/java/org/opentripplanner/raptor/rangeraptor/support/TimeBasedBoardingSupport.java
  application/src/main/java/org/opentripplanner/raptor/service/RangeRaptorDynamicSearch.java
  application/src/main/java/org/opentripplanner/raptor/service/ViaRangeRaptorDynamicSearch.java
  application/src/main/java/org/opentripplanner/raptor/spi/BoardAndAlightTime.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleBoardSearch.java
  application/src/main/java/org/opentripplanner/standalone/config/configure/ConfigModule.java
  application/src/main/java/org/opentripplanner/standalone/config/routerconfig/RaptorEnvironmentFactory.java
  application/src/main/java/org/opentripplanner/standalone/config/routerconfig/TransitRoutingConfig.java
  application/src/test/java/org/opentripplanner/TestServerContext.java
  application/src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
Labels: Technical Debt, Skip Changelog

#6095 Clarify @Nullable and @Nonnull usage [ci skip]
  .gitignore
  application/pom.xml
  application/src/build/templates/package-info-template.java
  application/src/ext/java/org/opentripplanner/ext/datastore/gs/package-info.java
  application/src/ext/java/org/opentripplanner/ext/datastore/gs/package-info.md
  application/src/ext/java/org/opentripplanner/ext/restapi/resources/package-info.java
  application/src/ext/java/org/opentripplanner/ext/restapi/resources/package-info.md
  application/src/main/java/org/opentripplanner/api/parameter/package-info.java
  application/src/main/java/org/opentripplanner/api/parameter/package-info.md
  application/src/main/java/org/opentripplanner/graph_builder/issues/package-info.java
  application/src/main/java/org/opentripplanner/graph_builder/issues/package-info.md
  application/src/main/java/org/opentripplanner/netex/loader/parser/package-info.java
  application/src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/package-info.java
  application/src/main/java/org/opentripplanner/transit/model/package.md
  application/src/main/java/org/opentripplanner/visualizer/package-info.java
  application/src/main/java/org/opentripplanner/visualizer/package-info.md
  application/src/test/java/org/opentripplanner/mmri/MMRI_Testdocument.pdf
  application/src/test/java/org/opentripplanner/mmri/package-info.java
  application/src/test/java/org/opentripplanner/mmri/package-info.md
  doc/dev/decisionrecords/Codestyle.md
Labels: Documentation, Skip Changelog, Developer Decision Record

#6174 Change the NeTEx mapping of "cableway" to GONDOLA
  application/src/main/java/org/opentripplanner/apis/transmodel/model/EnumTypes.java
  application/src/main/java/org/opentripplanner/netex/mapping/StopPlaceTypeMapper.java
  application/src/main/java/org/opentripplanner/netex/mapping/TransportModeMapper.java
  application/src/test/java/org/opentripplanner/netex/mapping/StopPlaceTypeMapperTest.java
  application/src/test/java/org/opentripplanner/netex/mapping/TransportModeMapperTest.java
Labels: Bug, bump serialization id, Skip Changelog

#6101 Add missing transit modes in GTFS GraphQL InputModeWeight
  application/src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLTypes.java
  application/src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
Labels: Skip Changelog

#6179 Allow bike walking through bicycle no thru traffic areas
  application/src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
  application/src/test/java/org/opentripplanner/street/integration/BikeWalkingTest.java
Labels: Improvement

#6184 Generate Java source files from protocol buffer definition files in separate Maven module
  application/pom.xml
  gtfs-realtime-protobuf/pom.xml
  gtfs-realtime-protobuf/src/main/proto/gtfs-realtime.proto
  gtfs-realtime-protobuf/src/main/proto/mfdz-realtime-extensions.proto
  pom.xml
Labels: Technical Debt, Skip Changelog

#6177 Fix race in execution of tests
  application/src/main/java/org/opentripplanner/model/plan/Itinerary.java
  application/src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainTest.java
Labels: Skanetrafiken, Skip Changelog

#6194 Disable protocol upgrades for the HTTP client by default.
  application/src/main/java/org/opentripplanner/framework/io/OtpHttpClient.java
  application/src/main/java/org/opentripplanner/framework/io/OtpHttpClientFactory.java
Labels: Skanetrafiken

#6189 Fix max search-window when paging
  application/src/main/java/org/opentripplanner/apis/transmodel/TransmodelAPI.java
  application/src/main/java/org/opentripplanner/apis/transmodel/TransmodelGraphQLSchema.java
  application/src/main/java/org/opentripplanner/apis/transmodel/model/plan/TripQuery.java
  application/src/main/java/org/opentripplanner/raptor/api/request/DynamicSearchWindowCoefficients.java
  application/src/main/java/org/opentripplanner/routing/algorithm/mapping/PagingServiceFactory.java
  application/src/main/java/org/opentripplanner/routing/api/request/RouteRequest.java
  application/src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
  application/src/main/java/org/opentripplanner/standalone/config/routerconfig/TransitRoutingConfig.java
  application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java
  application/src/main/java/org/opentripplanner/standalone/server/DefaultServerRequestContext.java
  application/src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
  application/src/test/java/org/opentripplanner/apis/transmodel/TransmodelGraphQLSchemaTest.java
  application/src/test/java/org/opentripplanner/routing/core/RouteRequestTest.java
  doc/user/RouterConfiguration.md
Labels: Bug, Documentation, Entur Test

#6119 Make indoor=area and indoor=corridor routable for UK OSM tag mapper
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/OsmDatabase.java
  application/src/main/java/org/opentripplanner/osm/model/OsmWay.java
  application/src/main/java/org/opentripplanner/osm/model/OsmWithTags.java
  application/src/main/java/org/opentripplanner/osm/tagmapping/UKMapper.java
  application/src/test/java/org/opentripplanner/osm/model/OsmWayTest.java
  application/src/test/java/org/opentripplanner/osm/model/OsmWithTagsTest.java
  application/src/test/java/org/opentripplanner/osm/tagmapping/UKMapperTest.java
  application/src/test/java/org/opentripplanner/osm/wayproperty/specifier/WayTestData.java
  doc/user/osm/UK.md
Labels: Improvement
