Repository opentripplanner/OpenTripPlanner, pull requests merged in 2024-02, with the labels that each got.

#5483 Introduce `generalizedCostPlusPenalty` to make cost comparsion fairer
  src/main/java/org/opentripplanner/apis/transmodel/model/framework/PenaltyForStreetModeType.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/main/java/org/opentripplanner/model/plan/ItinerarySortKey.java
  src/main/java/org/opentripplanner/model/plan/paging/cursor/DeduplicationPageCut.java
  src/main/java/org/opentripplanner/model/plan/paging/cursor/PageCursorSerializer.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/transit/RemoveTransitIfStreetOnlyIsBetter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/transit/RemoveTransitIfWalkingIsBetter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/transit/TransitGeneralizedCostFilter.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/transit/group/RemoveOtherThanSameLegsMaxGeneralizedCost.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/framework/sort/SortOnGeneralizedCost.java
  src/main/java/org/opentripplanner/routing/algorithm/filterchain/framework/sort/SortOrderComparator.java
  src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  src/test/java/org/opentripplanner/model/plan/ItineraryTest.java
  src/test/java/org/opentripplanner/raptor/_data/api/TestPathBuilder.java
  src/test/java/org/opentripplanner/raptor/_data/transit/TestAccessEgress.java
  src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/transit/RemoveTransitIfStreetOnlyIsBetterTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapperTest.java
Labels: improvement

#5649 Siri azure updaters: Reduce some log levels
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java
Labels: Skanetrafiken, skip changelog

#5648 Separate walk time from non-transit time
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/ItineraryImpl.java
  src/main/java/org/opentripplanner/apis/transmodel/model/plan/TripPatternType.java
  src/main/java/org/opentripplanner/model/plan/ItinerariesCalculateLegTotals.java
  src/main/java/org/opentripplanner/model/plan/Itinerary.java
  src/test/java/org/opentripplanner/model/plan/ItineraryTest.java
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/plan-extended.json
  src/test/resources/org/opentripplanner/apis/gtfs/queries/plan-extended.graphql
Labels: bug

#5645 Remove "fare"
  src/ext-test/java/org/opentripplanner/ext/fares/FaresFilterTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/AtlantaFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/CombinedInterlinedLegsFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/FaresIntegrationTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/HSLFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
  src/ext-test/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTripTest.java
  src/ext-test/java/org/opentripplanner/ext/restapi/mapping/FareMapperTest.java
  src/ext/java/org/opentripplanner/ext/fares/impl/AtlantaFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareService.java
  src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
  src/ext/java/org/opentripplanner/ext/restapi/mapping/FareMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/GtfsGraphQLIndex.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/ItineraryImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/fareImpl.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
  src/main/java/org/opentripplanner/apis/gtfs/generated/graphql-codegen.yml
  src/main/java/org/opentripplanner/model/fare/FareProduct.java
  src/main/java/org/opentripplanner/model/fare/ItineraryFares.java
  src/main/java/org/opentripplanner/routing/core/FareType.java
  src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
  src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/ElevationSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
  src/test/java/org/opentripplanner/routing/core/ItineraryFaresTest.java
  src/test/resources/org/opentripplanner/apis/gtfs/expectations/plan-fares.json
Labels: sandbox, technical debt, IBI, bump serialization id, HSL

#5651 Refactor GroupStopBuilder addLocation method
  src/main/java/org/opentripplanner/transit/model/site/GroupStopBuilder.java
  src/test/java/org/opentripplanner/transit/model/site/GroupStopTest.java
Labels: bug, bump serialization id

#5634 Add agencies and feed publisher to geocoding result
  docs/apis/Apis.md
  docs/sandbox/GeocoderAPI.md
  src/ext-test/java/org/opentripplanner/ext/geocoder/LuceneIndexTest.java
  src/ext/java/org/opentripplanner/ext/geocoder/GeocoderResource.java
  src/ext/java/org/opentripplanner/ext/geocoder/LuceneIndex.java
  src/ext/java/org/opentripplanner/ext/geocoder/LuceneStopCluster.java
  src/ext/java/org/opentripplanner/ext/geocoder/StopCluster.java
  src/ext/java/org/opentripplanner/ext/geocoder/StopClusterMapper.java
  src/main/java/org/opentripplanner/apis/APIEndpoints.java
  src/test/java/org/opentripplanner/transit/service/DefaultTransitServiceTest.java
Labels: sandbox, IBI, skip changelog

#5650 Rename hopCost/Time -> mountDismountCost/Time in router-config.json
  docs/RouteRequest.md
  src/ext/java/org/opentripplanner/ext/restapi/resources/RequestToPreferencesMapper.java
  src/main/java/org/opentripplanner/apis/gtfs/mapping/RouteRequestMapper.java
  src/main/java/org/opentripplanner/routing/api/request/preference/VehicleWalkingPreferences.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/VehicleWalkingConfig.java
  src/main/java/org/opentripplanner/street/model/edge/BikeWalkableEdge.java
  src/test/java/org/opentripplanner/routing/api/request/preference/VehicleWalkingPreferencesTest.java
  src/test/java/org/opentripplanner/street/integration/BikeWalkingTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeTest.java
Labels: improvement, bump serialization id, skip changelog, config change

#5658 Fix a few typos and improve documentation in the TransitService interface
  src/ext/java/org/opentripplanner/ext/parkAndRideApi/ParkAndRideResource.java
  src/ext/java/org/opentripplanner/ext/restapi/resources/IndexAPI.java
  src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/StopsLayerBuilder.java
  src/main/java/org/opentripplanner/apis/gtfs/datafetchers/QueryTypeImpl.java
  src/main/java/org/opentripplanner/apis/transmodel/TransmodelGraphQLSchema.java
  src/main/java/org/opentripplanner/apis/transmodel/model/stop/StopPlaceType.java
  src/main/java/org/opentripplanner/apis/vectortiles/GraphInspectorVectorTileResource.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/routing/linking/FlexLocationAdder.java
  src/main/java/org/opentripplanner/standalone/api/OtpServerRequestContext.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/StopModel.java
  src/main/java/org/opentripplanner/transit/service/TransitService.java
  src/test/java/org/opentripplanner/apis/gtfs/mapping/RouteRequestMapperTest.java
Labels: skip changelog

#5381 Remove `VehicleToStopHeuristics`
  docs/Configuration.md
  docs/RouteRequest.md
  docs/SandboxExtension.md
  docs/examples/entur/otp-config.json
  docs/sandbox/VehicleToStopHeuristics.md
  mkdocs.yml
  src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  src/ext/java/org/opentripplanner/ext/vehicletostopheuristics/BikeToStopSkipEdgeStrategy.java
  src/ext/java/org/opentripplanner/ext/vehicletostopheuristics/VehicleToStopSkipEdgeStrategy.java
  src/main/java/org/opentripplanner/framework/application/OTPFeature.java
  src/main/java/org/opentripplanner/framework/lang/StringUtils.java
  src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
  src/main/java/org/opentripplanner/routing/api/request/framework/TimeAndCostPenaltyForEnum.java
  src/main/java/org/opentripplanner/routing/api/request/preference/AccessEgressPreferences.java
  src/main/java/org/opentripplanner/standalone/config/framework/json/EnumMapper.java
  src/main/java/org/opentripplanner/standalone/config/framework/json/NodeInfo.java
  src/main/java/org/opentripplanner/standalone/config/framework/json/ParameterBuilder.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
  src/test/java/org/opentripplanner/routing/api/request/preference/StreetPreferencesTest.java
  src/test/java/org/opentripplanner/standalone/config/framework/json/NodeAdapterTest.java
Labels: sandbox, technical debt, config change

#5659 Change the GroupStop's getEncompassingAreaGeometry method to return an empty optional if the group stop is not defined as an area
  src/main/java/org/opentripplanner/transit/model/site/GroupStop.java
Labels: skip changelog

#5653 Improve business logic for consolidated stops
  src/ext-test/java/org/opentripplanner/ext/stopconsolidation/DecorateConsolidatedStopNamesTest.java
  src/ext/java/org/opentripplanner/ext/stopconsolidation/DecorateConsolidatedStopNames.java
  src/ext/java/org/opentripplanner/ext/stopconsolidation/StopConsolidationService.java
  src/ext/java/org/opentripplanner/ext/stopconsolidation/internal/DefaultStopConsolidationService.java
  src/ext/java/org/opentripplanner/ext/stopconsolidation/model/ConsolidatedStopLeg.java
  src/main/java/org/opentripplanner/model/plan/Place.java
Labels: sandbox, IBI, skip changelog

#5675 Set defaults of the modes WALK, even if one and not the others are set
  src/main/java/org/opentripplanner/apis/transmodel/mapping/RequestModesMapper.java
  src/test/java/org/opentripplanner/apis/transmodel/mapping/RequestModesMapperTest.java
Labels: bug

#5674 Reduce flex default access/egress penalty
  docs/RouteRequest.md
  src/main/java/org/opentripplanner/routing/api/request/preference/AccessEgressPreferences.java
  src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
  src/test/java/org/opentripplanner/routing/api/request/preference/StreetPreferencesTest.java
Labels: improvement

#5666 Add GroupStop layer to new debug frontend
  client-next/src/components/MapView/MapView.tsx
  src/main/java/org/opentripplanner/apis/vectortiles/DebugStyleSpec.java
  src/main/java/org/opentripplanner/apis/vectortiles/GraphInspectorVectorTileResource.java
  src/main/java/org/opentripplanner/apis/vectortiles/model/LayerType.java
  src/main/java/org/opentripplanner/inspector/vector/stop/GroupStopLayerBuilder.java
  src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  src/main/java/org/opentripplanner/transit/service/TransitService.java
  src/test/java/org/opentripplanner/apis/vectortiles/DebugStyleSpecTest.java
  src/test/resources/org/opentripplanner/apis/vectortiles/style.json
Labels: improvement, OTP Debug UI

#5673 Allow configuring a custom attribution for vector tiles
  docs/sandbox/MapboxVectorTilesApi.md
  src/ext/java/org/opentripplanner/ext/vectortiles/VectorTilesResource.java
  src/main/java/org/opentripplanner/apis/support/TileJson.java
  src/main/java/org/opentripplanner/framework/io/HttpUtils.java
  src/main/java/org/opentripplanner/standalone/config/routerconfig/VectorTileConfig.java
  src/test/java/org/opentripplanner/apis/support/TileJsonTest.java
  src/test/java/org/opentripplanner/framework/io/HttpUtilsTest.java
Labels: improvement, TriMet, sandbox, IBI, bump serialization id, skip changelog

#5617 Debug UI smoke tests
  .github/workflows/debug-client.yml
  client-next/package-lock.json
  client-next/package.json
  client-next/src/components/ItineraryList/ItineraryList.test.tsx
  client-next/src/components/SearchBar/SearchBar.test.tsx
  client-next/vite.config.ts
Labels: sandbox, OTP Debug UI, skip changelog

#5616 Enable renovate for debug ui, group non-major
  renovate.json5
Labels: sandbox, OTP Debug UI, skip changelog

#5679 Add documentation page about OTP frontends
  docs/Frontends.md
  docs/README-DOCS.txt
  mkdocs.yml
Labels: documentation, skip changelog

#5698 Use NeTEx authority short name if name is not present
  src/main/java/org/opentripplanner/netex/mapping/AuthorityToAgencyMapper.java
  src/main/java/org/opentripplanner/netex/mapping/MultilingualStringMapper.java
  src/main/java/org/opentripplanner/transit/model/organization/Agency.java
  src/test/java/org/opentripplanner/netex/mapping/AuthorityToAgencyMapperTest.java
Labels: NeTEx

#5701 Add Hamburg OSM mapper
  docs/BuildConfiguration.md
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/HamburgMapper.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/OsmTagMapperSource.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/HamburgMapperTest.java
Labels: new feature

#5657 Remove configurable car speed and determine it in graph build
  docs/RouteRequest.md
  docs/RouterConfiguration.md
  docs/examples/entur/router-config.json
  src/main/java/org/opentripplanner/apis/transmodel/model/DefaultRouteRequestType.java
  src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  src/main/java/org/opentripplanner/graph_builder/issues/StreetCarSpeedZero.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderFactory.java
  src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModule.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModuleBuilder.java
  src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  src/main/java/org/opentripplanner/openstreetmap/OsmProvider.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/AtlantaMapper.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/ConstantSpeedMapper.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/DefaultMapper.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/FinlandMapper.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/GermanyMapper.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/HoustonMapper.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/NorwayMapper.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/OsmTagMapper.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/PortlandMapper.java
  src/main/java/org/opentripplanner/openstreetmap/tagmapping/UKMapper.java
  src/main/java/org/opentripplanner/openstreetmap/wayproperty/WayPropertySet.java
  src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectStreetRouter.java
  src/main/java/org/opentripplanner/routing/api/request/preference/CarPreferences.java
  src/main/java/org/opentripplanner/routing/api/request/preference/RoutingPreferences.java
  src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
  src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
  src/main/java/org/opentripplanner/standalone/OTPMain.java
  src/main/java/org/opentripplanner/standalone/api/OtpServerRequestContext.java
  src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationFactory.java
  src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationModule.java
  src/main/java/org/opentripplanner/standalone/configure/LoadApplication.java
  src/main/java/org/opentripplanner/standalone/configure/LoadApplicationFactory.java
  src/main/java/org/opentripplanner/standalone/server/DefaultServerRequestContext.java
  src/main/java/org/opentripplanner/street/model/StreetConstants.java
  src/main/java/org/opentripplanner/street/model/StreetLimitationParameters.java
  src/main/java/org/opentripplanner/street/search/strategy/EuclideanRemainingWeightHeuristic.java
  src/main/java/org/opentripplanner/street/service/DefaultStreetLimitationParametersService.java
  src/main/java/org/opentripplanner/street/service/StreetLimitationParametersService.java
  src/main/java/org/opentripplanner/street/service/StreetLimitationParametersServiceModule.java
  src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
  src/test/java/org/opentripplanner/TestServerContext.java
  src/test/java/org/opentripplanner/apis/transmodel/mapping/TripRequestMapperTest.java
  src/test/java/org/opentripplanner/graph_builder/module/osm/TriangleInequalityTest.java
  src/test/java/org/opentripplanner/openstreetmap/tagmapping/DefaultMapperTest.java
  src/test/java/org/opentripplanner/openstreetmap/wayproperty/WayPropertySetTest.java
  src/test/java/org/opentripplanner/routing/algorithm/TurnCostTest.java
  src/test/java/org/opentripplanner/routing/api/request/preference/CarPreferencesTest.java
  src/test/java/org/opentripplanner/routing/graph/GraphSerializationTest.java
  src/test/java/org/opentripplanner/street/model/TurnRestrictionTest.java
  src/test/java/org/opentripplanner/street/model/edge/StreetEdgeTest.java
  src/test/java/org/opentripplanner/street/service/DefaultStreetLimitationParametersServiceTest.java
  src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
  src/test/resources/standalone/config/router-config.json
Labels: improvement, bump serialization id, config change
