Repository opentripplanner/OpenTripPlanner, pull requests merged in 2025-07, with the labels that each got.

#6716 Make leg's startTime, endTime, serviceDate required
  application/src/ext-test/java/org/opentripplanner/ext/stopconsolidation/model/ConsolidatedStopLegBuilderTest.java
  application/src/main/java/org/opentripplanner/model/plan/leg/ScheduledTransitLeg.java
  application/src/test/java/org/opentripplanner/raptorlegacy/_data/transit/TestTripSchedule.java
Labels: Technical Debt, Skip Changelog

#6724 Reduce graph build memory by gc-ing OsmDatabase early
  application/src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModule.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  application/src/main/java/org/opentripplanner/osm/DefaultOsmProvider.java
Labels: Technical Debt

#6707 Remove unused methods in transit editor
  application/src/main/java/org/opentripplanner/graph_builder/module/AddTransitEntitiesToGraph.java
  application/src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  application/src/main/java/org/opentripplanner/transit/service/TimetableRepository.java
  application/src/main/java/org/opentripplanner/transit/service/TimetableRepositoryIndex.java
  application/src/main/java/org/opentripplanner/transit/service/TransitEditorService.java
  application/src/main/java/org/opentripplanner/transit/service/TransitService.java
  application/src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
  application/src/test/java/org/opentripplanner/routing/graphfinder/PlaceFinderTraverseVisitorTest.java
  application/src/test/resources/org/opentripplanner/apis/gtfs/expectations/routes-extended.json
  application/src/test/resources/org/opentripplanner/apis/gtfs/expectations/routes-tutorial.json
Labels: Technical Debt, bump serialization id, Skip Changelog

#6725 Allow filtering of intermediate stops in GraphQL API
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/LegImpl.java
  application/src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLTypes.java
  application/src/main/java/org/opentripplanner/apis/gtfs/support/filter/StopArrivalByTypeFilter.java
  application/src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
  application/src/test/java/org/opentripplanner/apis/gtfs/datafetchers/BookingInfoImplTest.java
  application/src/test/java/org/opentripplanner/apis/gtfs/datafetchers/DataFetchingSupport.java
  application/src/test/java/org/opentripplanner/apis/gtfs/datafetchers/LegImplTest.java
  application/src/test/java/org/opentripplanner/apis/gtfs/support/filter/StopArrivalByTypeFilterTest.java
  application/src/test/java/org/opentripplanner/model/TripTimeOnDateTest.java
  application/src/test/java/org/opentripplanner/transit/model/_data/TimetableRepositoryForTest.java
  application/src/test/java/org/opentripplanner/updater/trip/TripInput.java
Labels: Improvement, IBI

#6747 Finetune CSS layout of search bar
  client/src/components/SearchBar/AccessSelect.tsx
  client/src/components/SearchBar/DepartureArrivalSelect.tsx
  client/src/components/SearchBar/DirectModeSelect.tsx
  client/src/components/SearchBar/EgressSelect.tsx
  client/src/components/SearchBar/ItineraryFilterDebugSelect.tsx
  client/src/components/SearchBar/MultiSelectDropdown.tsx
  client/src/style.css
Labels: OTP Debug UI, Skip Changelog

#6729 Extract interpolation logic for GTFS-RT trip time updater
  application/src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/MqttGtfsRealtimeUpdaterConfig.java
  application/src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/PollingTripUpdaterConfig.java
  application/src/main/java/org/opentripplanner/transit/model/timetable/RealTimeTripTimesBuilder.java
  application/src/main/java/org/opentripplanner/transit/model/timetable/TimetableValidationError.java
  application/src/main/java/org/opentripplanner/updater/spi/DataValidationExceptionMapper.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/AbstractBackwardsDelayInterpolator.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/BackwardsDelayAlwaysInterpolator.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/BackwardsDelayInterpolator.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/BackwardsDelayPropagationType.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/BackwardsDelayPropagator.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/BackwardsDelayRequiredInterpolator.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/DefaultForwardsDelayInterpolator.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/ForwardsDelayInterpolator.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/ForwardsDelayPropagationType.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/GtfsRealTimeTripUpdateAdapter.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/TripTimesUpdater.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/updater/TripUpdateGraphWriterRunnable.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/updater/http/PollingTripUpdater.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/updater/http/PollingTripUpdaterParameters.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/updater/mqtt/MqttGtfsRealtimeUpdater.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/updater/mqtt/MqttGtfsRealtimeUpdaterParameters.java
  application/src/test/java/org/opentripplanner/GtfsTest.java
  application/src/test/java/org/opentripplanner/transit/model/_data/TimetableRepositoryForTest.java
  application/src/test/java/org/opentripplanner/transit/model/timetable/RealTimeTripTimesTest.java
  application/src/test/java/org/opentripplanner/updater/trip/RealtimeTestEnvironment.java
  application/src/test/java/org/opentripplanner/updater/trip/gtfs/BackwardsDelayAlwaysInterpolatorTest.java
  application/src/test/java/org/opentripplanner/updater/trip/gtfs/BackwardsDelayRequiredInterpolatorTest.java
  application/src/test/java/org/opentripplanner/updater/trip/gtfs/DefaultForwardsDelayInterpolatorTest.java
  application/src/test/java/org/opentripplanner/updater/trip/gtfs/GtfsRealTimeTripUpdateAdapterTest.java
  application/src/test/java/org/opentripplanner/updater/trip/gtfs/LegacyTimetableSnapshotIntegrationTest.java
  application/src/test/java/org/opentripplanner/updater/trip/gtfs/TripTimesUpdaterTest.java
  application/src/test/java/org/opentripplanner/updater/trip/gtfs/updater/http/GtfsRealtimeTripUpdateSourceTest.java
  doc/user/GTFS-RT-Config.md
Labels: Technical Debt, Real-Time Update, bump serialization id
