Repository opentripplanner/OpenTripPlanner, pull requests merged in 2025-03, with the labels that each got.

#6505 Add highway=platform to IsBoardingLocation()
  application/src/main/java/org/opentripplanner/osm/model/OsmEntity.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/BoardingLocationTest.java
  doc/user/BoardingLocations.md
Labels: Skip Changelog

#6484 Fix rounding error in street routing
  application/src/main/java/org/opentripplanner/routing/api/request/RouteRequest.java
  application/src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
  application/src/main/java/org/opentripplanner/street/search/request/StreetSearchRequest.java
  application/src/main/java/org/opentripplanner/street/search/state/State.java
  application/src/test/java/org/opentripplanner/street/integration/WalkRoutingTest.java
Labels: Bug, Entur Test

#6494 Use default max stop count for mode from routing defaults in transfer requests
  application/src/ext/java/org/opentripplanner/ext/dataoverlay/api/DataOverlayParameters.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  application/src/main/java/org/opentripplanner/routing/api/request/framework/DurationForEnum.java
  application/src/main/java/org/opentripplanner/routing/api/request/preference/AccessEgressPreferences.java
  application/src/main/java/org/opentripplanner/routing/api/request/preference/MaxStopCountLimit.java
  application/src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  application/src/test/java/org/opentripplanner/routing/api/request/preference/AccessEgressPreferencesTest.java
  application/src/test/java/org/opentripplanner/routing/api/request/preference/MaxStopCountLimitTest.java
  application/src/test/java/org/opentripplanner/routing/api/request/preference/StreetPreferencesTest.java
Labels: Bug, bump serialization id

#6507 Fix typo in access mode documentation
  application/src/main/java/org/opentripplanner/apis/transmodel/model/plan/ModeInputType.java
  application/src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
Labels: Documentation, Skip Changelog

#6497 Temporarily restore debug layers to classic debug UI and change grouping of safety layers in the new one
  application/src/client/classic-debug/js/otp/core/Map.js
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/BikeSafetyEdgeRenderer.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/EdgeVertexTileRenderer.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/ElevationEdgeRenderer.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/NoThruTrafficEdgeRenderer.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/TileRenderer.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/TileRendererManager.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/TraversalPermissionsEdgeRenderer.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/WalkSafetyEdgeRenderer.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/WheelchairEdgeRenderer.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/api/resource/DebugLayersList.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/api/resource/DebugRasterTileResource.java
  application/src/main/java/org/opentripplanner/apis/vectortiles/DebugStyleSpec.java
  application/src/test/resources/org/opentripplanner/apis/vectortiles/style.json
Labels: Sandbox, Digitransit Test

#6506 Remove Timetable#getTripTimes(index)
  application/src/ext-test/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTripIntegrationTest.java
  application/src/ext-test/java/org/opentripplanner/ext/realtimeresolver/RealtimeResolverTest.java
  application/src/main/java/org/opentripplanner/model/Timetable.java
  application/src/main/java/org/opentripplanner/transit/model/network/TripPattern.java
  application/src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/GtfsRealTimeTripUpdateAdapter.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/TripTimesUpdater.java
  application/src/test/java/org/opentripplanner/apis/transmodel/mapping/TripRequestMapperTest.java
  application/src/test/java/org/opentripplanner/routing/stoptimes/StopTimesHelperTest.java
  application/src/test/java/org/opentripplanner/transit/model/network/grouppriority/TransitGroupPriorityServiceTest.java
  application/src/test/java/org/opentripplanner/updater/trip/gtfs/GtfsRealTimeTripUpdateAdapterTest.java
  application/src/test/java/org/opentripplanner/updater/trip/gtfs/TripTimesUpdaterTest.java
  application/src/test/java/org/opentripplanner/updater/trip/gtfs/moduletests/addition/AddedTest.java
  application/src/test/java/org/opentripplanner/updater/trip/gtfs/moduletests/cancellation/CancellationDeletionTest.java
  application/src/test/java/org/opentripplanner/updater/trip/gtfs/moduletests/delay/DelayedTest.java
  application/src/test/java/org/opentripplanner/updater/trip/gtfs/moduletests/delay/SkippedTest.java
Labels: Technical Debt, Skip Changelog

#6466 Make `StopTimesHelper` package-private, move Javadoc
  application/src/ext/java/org/opentripplanner/ext/restapi/resources/IndexAPI.java
  application/src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/DigitransitRealtimeStopPropertyMapper.java
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/DepartureRowImpl.java
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/StopImpl.java
  application/src/main/java/org/opentripplanner/apis/transmodel/model/EnumTypes.java
  application/src/main/java/org/opentripplanner/apis/transmodel/model/stop/QuayType.java
  application/src/main/java/org/opentripplanner/apis/transmodel/model/stop/StopPlaceType.java
  application/src/main/java/org/opentripplanner/routing/alternativelegs/AlternativeLegs.java
  application/src/main/java/org/opentripplanner/routing/graphfinder/PatternAtStop.java
  application/src/main/java/org/opentripplanner/transit/service/ArrivalDeparture.java
  application/src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  application/src/main/java/org/opentripplanner/transit/service/StopTimesHelper.java
  application/src/main/java/org/opentripplanner/transit/service/TransitService.java
  application/src/main/java/org/opentripplanner/transit/service/TripTimesHelper.java
  application/src/test/java/org/opentripplanner/transit/service/StopTimesHelperTest.java
Labels: Technical Debt, Skip Changelog

#6401 Conditionally wait for previous polling task
  application/src/main/java/org/opentripplanner/updater/alert/siri/SiriSXUpdater.java
  application/src/main/java/org/opentripplanner/updater/spi/PollingGraphUpdater.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/updater/SiriETUpdater.java
  application/src/test/java/org/opentripplanner/updater/spi/PollingGraphUpdaterTest.java
Labels: Improvement, Real-Time Update

#6499 Reject SIRI messages with invalid stops and missing times
  application/src/main/java/org/opentripplanner/updater/spi/UpdateError.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/AddedTripBuilder.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/ModifiedTripBuilder.java
  application/src/test/java/org/opentripplanner/updater/trip/siri/AddedTripBuilderTest.java
  application/src/test/java/org/opentripplanner/updater/trip/siri/ModifiedTripBuilderTest.java
  application/src/test/java/org/opentripplanner/updater/trip/siri/moduletests/InterpolationTest.java
  application/src/test/java/org/opentripplanner/updater/trip/siri/moduletests/cancellation/CancellationTest.java
  application/src/test/java/org/opentripplanner/updater/trip/siri/moduletests/rejection/InvalidCallsTest.java
  application/src/test/java/org/opentripplanner/updater/trip/siri/moduletests/rejection/NegativeTimesTest.java
Labels: Improvement, Real-Time Update

#6513 Add default unknown_producer tag value to the producer tag of the StreamingTripUpdateMetrics
  application/src/main/java/org/opentripplanner/updater/trip/metrics/StreamingTripUpdateMetrics.java
Labels: Bug, Entur Test

#6514 Add edge name for indoor area
  application/src/main/java/org/opentripplanner/osm/tagmapping/OsmTagMapper.java
  application/src/main/resources/WayProperties.properties
  application/src/main/resources/WayProperties_de.properties
  application/src/main/resources/WayProperties_fi.properties
  application/src/main/resources/WayProperties_fr.properties
  application/src/main/resources/WayProperties_hu.properties
  application/src/main/resources/WayProperties_nl.properties
  application/src/main/resources/WayProperties_no.properties
  application/src/main/resources/WayProperties_sv.properties
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/walkablearea/ConcaveHoleTest.java
  application/src/test/java/org/opentripplanner/osm/tagmapping/OsmTagMapperTest.java
Labels: Improvement, Skip Changelog

#6511 Fixes issue where empty ids list was causing errors.
  application/src/main/java/org/opentripplanner/apis/transmodel/TransmodelGraphQLSchema.java
Labels: Entur Test, Skip Changelog

#6490 Add support for coordinate via point in the GTFS GraphQL API
  application/src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLTypes.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/CoordinateMapper.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/LegacyRouteRequestMapper.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/RouteRequestMapper.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/ViaLocationMapper.java
  application/src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
  application/src/test/java/org/opentripplanner/apis/gtfs/SchemaObjectMappersForTests.java
  application/src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/RouteRequestMapperTest.java
  application/src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/ViaLocationMapperTest.java
  application/src/test/resources/org/opentripplanner/apis/gtfs/queries/planConnection-extended.graphql
Labels: Improvement

#6538 Debug client: Improves type safety for query selection fields in components
  client/src/components/ItineraryList/InterchangeInfo.tsx
  client/src/components/ItineraryList/ItineraryDetails.tsx
  client/src/components/ItineraryList/ItineraryHeaderContent.tsx
  client/src/components/ItineraryList/ItineraryHeaderLegContent.tsx
  client/src/components/ItineraryList/ItineraryLegDetails.tsx
  client/src/components/ItineraryList/ItineraryListContainer.tsx
  client/src/components/ItineraryList/useHeaderContentStyleCalculations.ts
  client/src/components/ItineraryList/useHeaderLegContentStyleCalculations.ts
  client/src/hooks/useTripQuery.ts
  client/src/static/query/.gitignore
  client/src/static/query/selector.fragment.graphql
  client/src/static/query/tripQuery.tsx
  client/src/static/query/tripQueryTypes.d.ts
  client/src/util/getColorForLeg.ts
Labels: Improvement, Skip Changelog

#6491 Add `generalizedCostMaxLimit` to page cursor
  application/src/main/java/org/opentripplanner/framework/token/Token.java
  application/src/main/java/org/opentripplanner/framework/token/TokenBuilder.java
  application/src/main/java/org/opentripplanner/model/plan/paging/cursor/PageCursor.java
  application/src/main/java/org/opentripplanner/model/plan/paging/cursor/PageCursorFactory.java
  application/src/main/java/org/opentripplanner/model/plan/paging/cursor/PageCursorSerializer.java
  application/src/test/java/org/opentripplanner/framework/token/AdvancedTokenSchemaTest.java
  application/src/test/java/org/opentripplanner/framework/token/TestTokenSchemaConstants.java
  application/src/test/java/org/opentripplanner/framework/token/TokenSchemaTest.java
  application/src/test/java/org/opentripplanner/model/plan/paging/cursor/PageCursorSerializerTest.java
  application/src/test/java/org/opentripplanner/model/plan/paging/cursor/PageCursorTest.java
Labels: Improvement, Skip Changelog

#6523 Fix removal of old vehicle positions
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/VehiclePositionImpl.java
  application/src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
  application/src/main/java/org/opentripplanner/service/realtimevehicles/RealtimeVehicleRepository.java
  application/src/main/java/org/opentripplanner/service/realtimevehicles/internal/DefaultRealtimeVehicleService.java
  application/src/main/java/org/opentripplanner/updater/vehicle_position/GtfsRealtimeHttpVehiclePositionSource.java
  application/src/main/java/org/opentripplanner/updater/vehicle_position/PollingVehiclePositionUpdater.java
  application/src/main/java/org/opentripplanner/updater/vehicle_position/RealtimeVehiclePatternMatcher.java
  application/src/main/java/org/opentripplanner/updater/vehicle_position/VehiclePositionUpdaterRunnable.java
  application/src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
  application/src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
  application/src/test/java/org/opentripplanner/service/realtimevehicles/internal/DefaultRealtimeVehicleServiceTest.java
  application/src/test/resources/org/opentripplanner/apis/gtfs/expectations/patterns.json
  application/src/test/resources/org/opentripplanner/apis/gtfs/queries/patterns.graphql
Labels: Bug

#6526 Make estimated calls non nullable in the TransModel API
  application/src/main/java/org/opentripplanner/apis/transmodel/model/timetable/DatedServiceJourneyType.java
  application/src/main/java/org/opentripplanner/apis/transmodel/model/timetable/ServiceJourneyType.java
  application/src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
Labels: Entur Test

#6495 Optimize routing time vertex linking with areas
  application/src/main/java/org/opentripplanner/graph_builder/module/StreetLinkerModule.java
  application/src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModule.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModuleBuilder.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  application/src/main/java/org/opentripplanner/routing/linking/VertexLinker.java
  application/src/main/java/org/opentripplanner/standalone/OTPMain.java
  application/src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  application/src/main/java/org/opentripplanner/street/model/StreetConstants.java
  application/src/main/java/org/opentripplanner/street/model/StreetLimitationParameters.java
  application/src/test/java/org/opentripplanner/graph_builder/module/StreetLinkerModuleTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/TestStreetLinkerModule.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/walkablearea/SimpleAreaTest.java
  application/src/test/java/org/opentripplanner/routing/linking/LinkStopToPlatformTest.java
  doc/user/BuildConfiguration.md
Labels: Improvement, bump serialization id

#6549 Fix warnings in SiriAlertsUpdateHandlerTest
  application/src/ext/java/org/opentripplanner/ext/restapi/resources/IndexAPI.java
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/PatternImpl.java
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/RouteImpl.java
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/StopImpl.java
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/TripImpl.java
  application/src/main/java/org/opentripplanner/apis/transmodel/model/timetable/ServiceJourneyType.java
  application/src/main/java/org/opentripplanner/routing/alertpatch/EntitySelector.java
  application/src/main/java/org/opentripplanner/routing/impl/DelegatingTransitAlertServiceImpl.java
  application/src/main/java/org/opentripplanner/routing/impl/TransitAlertServiceImpl.java
  application/src/main/java/org/opentripplanner/routing/services/TransitAlertService.java
  application/src/test/java/org/opentripplanner/updater/alert/siri/SiriAlertsUpdateHandlerTest.java
Labels: Skip Changelog

#6546 Use locale param from plan queries for all translations in the GTFS API if accept-language header is not set
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/BikeRentalStationImpl.java
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/RentalVehicleImpl.java
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/RoutingErrorImpl.java
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/VehicleRentalStationImpl.java
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/stepImpl.java
Labels: Improvement

#6550 Only add accessibility score to itinerary when it's walk-only or transit
  application/src/ext-test/java/org/opentripplanner/ext/accessibilityscore/DecorateWithAccessibilityScoreTest.java
  application/src/ext/java/org/opentripplanner/ext/accessibilityscore/DecorateWithAccessibilityScore.java
Labels: Sandbox, Skip Changelog

#6562 Fix NPE in RoutingWorker after #6535 was merged
  application/src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
Labels: Bug, Entur Test, Skip Changelog

#6539 Fix itinerary cost review
  application/src/ext-test/java/org/opentripplanner/ext/fares/FaresFilterTest.java
  application/src/ext-test/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceTest.java
  application/src/ext-test/java/org/opentripplanner/ext/fares/impl/FaresIntegrationTest.java
  application/src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
  application/src/ext-test/java/org/opentripplanner/ext/realtimeresolver/RealtimeResolverTest.java
  application/src/ext/java/org/opentripplanner/ext/fares/ItineraryFaresDecorator.java
  application/src/ext/java/org/opentripplanner/ext/fares/impl/AtlantaFareService.java
  application/src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareService.java
  application/src/ext/java/org/opentripplanner/ext/fares/impl/GtfsFaresService.java
  application/src/ext/java/org/opentripplanner/ext/fares/impl/GtfsFaresV2Service.java
  application/src/ext/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareService.java
  application/src/ext/java/org/opentripplanner/ext/fares/impl/NoopFareServiceFactory.java
  application/src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
  application/src/main/java/org/opentripplanner/model/fare/ItineraryFare.java
  application/src/main/java/org/opentripplanner/model/plan/Itinerary.java
  application/src/main/java/org/opentripplanner/model/plan/ItineraryBuilder.java
  application/src/main/java/org/opentripplanner/routing/algorithm/RoutingResult.java
  application/src/main/java/org/opentripplanner/routing/fares/FareService.java
  application/src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
  application/src/test/java/org/opentripplanner/routing/core/ItineraryFareTest.java
Labels: Technical Debt, Skip Changelog

#6561 Fix null issue in SiriAzureETUpdaterParameters
  application/src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdaterParameters.java
Labels: Sandbox, Skanetrafiken, Skip Changelog

#6553 do not discard turn restrictions where the turn description and angle do not match, just add an issue
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/TurnRestrictionUnifier.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/TurnRestrictionsTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/_support/RelationBuilder.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/_support/TestOsmProvider.java
  application/src/test/java/org/opentripplanner/test/support/GeoJsonIo.java
Labels: Improvement

#6555 Make `slopeExceededReluctance` example more realistic [ci skip]
  doc/user/Accessibility.md
Labels: Documentation, Skip Changelog

#6551 Take layer configuration into account when computing tilejson min/max zoom
  application/src/ext-test/java/org/opentripplanner/ext/vectortiles/VectorTilesResourceTest.java
  application/src/ext/java/org/opentripplanner/ext/vectortiles/VectorTilesResource.java
  application/src/main/java/org/opentripplanner/apis/support/TileJson.java
  application/src/main/java/org/opentripplanner/apis/vectortiles/GraphInspectorVectorTileResource.java
  application/src/main/java/org/opentripplanner/standalone/config/routerconfig/VectorTileConfig.java
  application/src/test/java/org/opentripplanner/apis/support/TileJsonTest.java
  application/src/test/java/org/opentripplanner/standalone/config/routerconfig/VectorTileConfigTest.java
Labels: Sandbox, Skip Changelog

#6560 Add @Deprecated to methods that are documented as deprecated [ci skip]
  application/src/ext/java/org/opentripplanner/ext/restapi/model/ApiLeg.java
  application/src/main/java/org/opentripplanner/netex/index/api/ReadOnlyHierarchicalVersionMapById.java
  application/src/main/java/org/opentripplanner/routing/api/request/preference/TransferPreferences.java
Labels: Skip Changelog

#6552 Use locale param if one is defined over accept-language header in GTFS APIs
  application/src/main/java/org/opentripplanner/framework/graphql/GraphQLUtils.java
  application/src/test/java/org/opentripplanner/framework/graphql/GraphQLUtilsTest.java
Labels: Improvement

#6544 Add doc for making the first custom release
  script/CUSTOM_RELEASE_README.md
Labels: Documentation, Skip Changelog

#6567 Remove reference to Plannerstack in documentation
  doc/user/Deployments.md
Labels: Documentation, Skip Changelog

#6568 Handle duration tags for elevators in the same way as for escalators
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/ElevatorProcessor.java
  application/src/main/java/org/opentripplanner/osm/model/OsmEntity.java
  application/src/main/java/org/opentripplanner/osm/model/OsmWay.java
  application/src/main/java/org/opentripplanner/street/model/edge/ElevatorHopEdge.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/BoardingLocationTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/ElevatorTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/_support/TestOsmProvider.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/walkablearea/SimpleAreaTest.java
  application/src/test/java/org/opentripplanner/street/model/edge/ElevatorHopEdgeTest.java
Labels: Improvement

#6574 Fix NPEs when processing FaresV2 feeds
  application/src/main/java/org/opentripplanner/gtfs/graphbuilder/GtfsModule.java
  application/src/test/java/org/opentripplanner/gtfs/GtfsContextBuilder.java
  application/src/test/java/org/opentripplanner/gtfs/graphbuilder/GtfsModuleTest.java
Labels: Bug, GTFS, Sandbox, Skip Changelog

#6575 Add unit tests for parsing one-day NeTEx operating periods
  application/src/test/java/org/opentripplanner/netex/mapping/calendar/DayTypeAssignmentMapperTest.java
Labels: NeTEx, Skip Changelog

#6421 Filter flex trips by agency and route
  application/src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  application/src/ext-test/java/org/opentripplanner/ext/flex/filter/FilterMapperTest.java
  application/src/ext-test/java/org/opentripplanner/ext/flex/template/ClosestTripTest.java
  application/src/ext-test/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTripIntegrationTest.java
  application/src/ext/java/org/opentripplanner/ext/flex/FlexIndex.java
  application/src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
  application/src/ext/java/org/opentripplanner/ext/flex/filter/FilterMapper.java
  application/src/ext/java/org/opentripplanner/ext/flex/template/ClosestTrip.java
  application/src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessFactory.java
  application/src/ext/java/org/opentripplanner/ext/flex/template/FlexDirectPathFactory.java
  application/src/ext/java/org/opentripplanner/ext/flex/template/FlexEgressFactory.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectFlexRouter.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/FlexAccessEgressRouter.java
  application/src/main/java/org/opentripplanner/routing/api/request/request/filter/TransitFilterRequest.java
  application/src/main/java/org/opentripplanner/transit/api/model/FilterValues.java
  application/src/main/java/org/opentripplanner/transit/api/model/FilterValuesEmptyIsEverything.java
  application/src/main/java/org/opentripplanner/transit/api/request/TripRequest.java
  application/src/main/java/org/opentripplanner/transit/api/request/TripRequestBuilder.java
  application/src/main/java/org/opentripplanner/transit/model/filter/expr/ExpressionBuilder.java
  application/src/main/java/org/opentripplanner/transit/model/filter/expr/NegationMatcher.java
  application/src/main/java/org/opentripplanner/transit/model/filter/transit/TripMatcherFactory.java
  application/src/test/java/org/opentripplanner/transit/model/filter/transit/TripMatcherFactoryTest.java
Labels: Improvement, Sandbox
