Repository opentripplanner/OpenTripPlanner, pull requests merged in 2025-05, with the labels that each got.

#6292 Remove fare service from Graph
  application/src/ext-test/java/org/opentripplanner/ext/fares/impl/FaresIntegrationTest.java
  application/src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  application/src/ext-test/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTripIntegrationTest.java
  application/src/ext-test/java/org/opentripplanner/ext/vectortiles/VectorTilesResourceTest.java
  application/src/ext/java/org/opentripplanner/ext/fares/FaresConfiguration.java
  application/src/ext/java/org/opentripplanner/ext/fares/configure/FareModule.java
  application/src/main/java/org/opentripplanner/apis/gtfs/GraphQLRequestContext.java
  application/src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  application/src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderFactory.java
  application/src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  application/src/main/java/org/opentripplanner/gtfs/graphbuilder/GtfsModule.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
  application/src/main/java/org/opentripplanner/routing/algorithm/mapping/RouteRequestToFilterChainMapper.java
  application/src/main/java/org/opentripplanner/routing/fares/FareService.java
  application/src/main/java/org/opentripplanner/routing/graph/Graph.java
  application/src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
  application/src/main/java/org/opentripplanner/standalone/OTPMain.java
  application/src/main/java/org/opentripplanner/standalone/api/OtpServerRequestContext.java
  application/src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java
  application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationFactory.java
  application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationModule.java
  application/src/main/java/org/opentripplanner/standalone/configure/LoadApplication.java
  application/src/main/java/org/opentripplanner/standalone/configure/LoadApplicationFactory.java
  application/src/main/java/org/opentripplanner/standalone/server/DefaultServerRequestContext.java
  application/src/test/java/org/opentripplanner/ConstantsForTests.java
  application/src/test/java/org/opentripplanner/GtfsTest.java
  application/src/test/java/org/opentripplanner/TestOtpModel.java
  application/src/test/java/org/opentripplanner/TestServerContext.java
  application/src/test/java/org/opentripplanner/apis/transmodel/mapping/TripRequestMapperTest.java
  application/src/test/java/org/opentripplanner/gtfs/graphbuilder/GtfsModuleTest.java
  application/src/test/java/org/opentripplanner/inspector/vector/VectorTileResponseFactoryTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/mapping/SnapshotTestBase.java
  application/src/test/java/org/opentripplanner/routing/graph/GraphSerializationTest.java
  application/src/test/java/org/opentripplanner/standalone/config/BuildConfigTest.java
  application/src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
Labels: Technical Debt, bump serialization id, Skip Changelog

#6630 Fix transfer for rental modes in deprecated `plan` query
  application/src/main/java/org/opentripplanner/api/parameter/QualifiedModeSet.java
  application/src/test/java/org/opentripplanner/api/parameter/QualifiedModeSetTest.java
Labels: Bug

#6611 Find best route in presence of turn restrictions
  application/src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
  application/src/main/java/org/opentripplanner/graph_builder/module/TurnRestrictionModule.java
  application/src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderFactory.java
  application/src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/OsmDatabase.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModule.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/TurnRestrictionTag.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/TurnRestrictionUnifier.java
  application/src/main/java/org/opentripplanner/service/osminfo/OsmInfoGraphBuildRepository.java
  application/src/main/java/org/opentripplanner/service/osminfo/internal/DefaultOsmInfoGraphBuildRepository.java
  application/src/main/java/org/opentripplanner/street/model/RepeatingTimePeriod.java
  application/src/main/java/org/opentripplanner/street/model/TurnRestriction.java
  application/src/main/java/org/opentripplanner/street/model/edge/Edge.java
  application/src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
  application/src/main/java/org/opentripplanner/street/model/vertex/SubsidiaryVertex.java
  application/src/main/java/org/opentripplanner/street/model/vertex/Vertex.java
  application/src/main/java/org/opentripplanner/street/model/vertex/VertexLabel.java
  application/src/test/java/org/opentripplanner/ConstantsForTests.java
  application/src/test/java/org/opentripplanner/graph_builder/module/TurnRestrictionModuleTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/TurnRestrictionsTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/TurnCostTest.java
  application/src/test/java/org/opentripplanner/street/integration/SplitEdgeTurnRestrictionsTest.java
  application/src/test/java/org/opentripplanner/street/model/TurnRestrictionTest.java
  application/src/test/java/org/opentripplanner/street/model/_data/StreetModelForTest.java
  application/src/test/java/org/opentripplanner/street/model/edge/StreetEdgeSplittingTest.java
  application/src/test/java/org/opentripplanner/street/model/edge/StreetEdgeTest.java
Labels: Bug, bump serialization id

#6643 Add availableUntil to rental vehicles in the GTFS GraphQL API
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/RentalVehicleImpl.java
  application/src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
  application/src/main/java/org/opentripplanner/service/vehiclerental/model/VehicleRentalVehicle.java
  application/src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFreeVehicleStatusMapper.java
  application/src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
  application/src/test/java/org/opentripplanner/service/vehiclerental/model/TestFreeFloatingRentalVehicleBuilder.java
  application/src/test/resources/org/opentripplanner/apis/gtfs/expectations/rental-vehicle.json
  application/src/test/resources/org/opentripplanner/apis/gtfs/queries/rental-vehicle.graphql
Labels: New Feature

#6642 Fixed Siri SX alerts handling with dedicated wrapper
  application/src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java
  application/src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureUpdater.java
Labels: Sandbox, Skanetrafiken, Skip Changelog

#6647 Fix code generation for complex GTFS GraphQL inputs
  application/src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
  application/src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLTypes.java
  application/src/main/java/org/opentripplanner/apis/gtfs/generated/package.json
  application/src/main/java/org/opentripplanner/apis/gtfs/generated/yarn.lock
Labels: Bug, Skip Changelog

#6659 Update path for debug raster tiles
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/api/resource/DebugRasterTileResource.java
  doc/user/sandbox/DebugRasterTiles.md
Labels: Sandbox, Skip Changelog

#6652 Upgrade to GraphiQL 4
  application/src/client/graphiql/index.html
  application/src/client/legacygraphql/graphiql/index.html
Labels: Technical Debt

#6667 Remove unused feature switch
  application/src/main/java/org/opentripplanner/framework/application/OTPFeature.java
  application/src/test/java/org/opentripplanner/framework/application/OTPFeatureTest.java
  doc/user/Configuration.md
Labels: Technical Debt, Skip Changelog

#6663 Deprecate vehicle type in GTFS API
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/StopImpl.java
  application/src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
Labels: Technical Debt

#6474 Add `generalizedCostMaxLimit` field to the `PageCursor` to enable using `RemoveTransitIfStreetOnlyIsBetter` filter with paging
  application/src/main/java/org/opentripplanner/model/plan/paging/cursor/PageCursorFactory.java
  application/src/main/java/org/opentripplanner/model/plan/paging/cursor/PageCursorInput.java
  application/src/main/java/org/opentripplanner/model/plan/paging/cursor/PageCursorSerializer.java
  application/src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
  application/src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChain.java
  application/src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java
  application/src/main/java/org/opentripplanner/routing/algorithm/filterchain/PageCursorInputAggregator.java
  application/src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/system/NumItinerariesFilter.java
  application/src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/system/NumItinerariesFilterResult.java
  application/src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/transit/RemoveTransitIfStreetOnlyIsBetter.java
  application/src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/transit/RemoveTransitIfStreetOnlyIsBetterResult.java
  application/src/main/java/org/opentripplanner/routing/algorithm/filterchain/paging/DefaultPageCursorInput.java
  application/src/main/java/org/opentripplanner/routing/algorithm/mapping/RouteRequestToFilterChainMapper.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/FilterTransitWhenDirectModeIsEmpty.java
  application/src/main/java/org/opentripplanner/routing/api/request/RouteRequest.java
  application/src/main/java/org/opentripplanner/service/paging/PagingService.java
  application/src/test/java/org/opentripplanner/model/plan/paging/cursor/PageCursorFactoryTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/system/NumItinerariesFilterTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/transit/RemoveTransitIfStreetOnlyIsBetterTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/router/FilterTransitWhenDirectModeIsEmptyTest.java
  application/src/test/java/org/opentripplanner/service/paging/TestDriver.java
Labels: Improvement

#6648 Make Google Cloud Storage host configurable
  application/src/ext-test/java/org/opentripplanner/ext/datastore/gs/GsConfigurationDocTest.java
  application/src/ext-test/java/org/opentripplanner/ext/datastore/gs/GsDataSourceRepositoryTest.java
  application/src/ext-test/java/org/opentripplanner/ext/datastore/gs/GsIntegrationTest.java
  application/src/ext-test/resources/org/opentripplanner/ext/datastore/gs/build-config.json
  application/src/ext/java/org/opentripplanner/ext/datastore/gs/GsDataSourceModule.java
  application/src/ext/java/org/opentripplanner/ext/datastore/gs/GsDataSourceRepository.java
  application/src/ext/java/org/opentripplanner/ext/datastore/gs/config/GsConfig.java
  application/src/main/java/org/opentripplanner/datastore/api/GsParameters.java
  application/src/main/java/org/opentripplanner/datastore/api/OtpDataStoreConfig.java
  application/src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
  application/src/test/java/org/opentripplanner/generate/doc/BuildConfigurationDocTest.java
  doc/templates/GoogleCloudStorage.md
  doc/user/BuildConfiguration.md
  doc/user/examples/entur/build-config.json
  doc/user/sandbox/GoogleCloudStorage.md
Labels: Improvement, Sandbox, Skip Changelog

#6672 Upgrade to OBA 7, remove unused fields
  application/pom.xml
  application/src/main/java/org/opentripplanner/gtfs/mapping/StopTimeMapper.java
  application/src/main/java/org/opentripplanner/model/StopTime.java
  application/src/test/java/org/opentripplanner/gtfs/mapping/StopTimeMapperTest.java
Labels: Technical Debt, Skip Changelog

#6656 Fix negative cost in filter
  application/src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/transit/group/RemoveOtherThanSameLegsMaxGeneralizedCost.java
  application/src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
  application/src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/transit/group/RemoveOtherThanSameLegsMaxGeneralizedCostTest.java
Labels: Bug, Skip Changelog
