Repository opentripplanner/OpenTripPlanner, pull requests merged in 2025-06, with the labels that each got.

#6621 Fix issue with paging when going to the next page after initial arrive by search
  application/src/main/java/org/opentripplanner/model/plan/SortOrder.java
  application/src/main/java/org/opentripplanner/model/plan/paging/cursor/PageCursorFactory.java
  application/src/main/java/org/opentripplanner/service/paging/PagingService.java
  application/src/test/java/org/opentripplanner/model/plan/paging/cursor/PageCursorFactoryTest.java
  application/src/test/java/org/opentripplanner/service/paging/PS1_LegacyMetaDataTest.java
  application/src/test/java/org/opentripplanner/service/paging/PS2_ManyParetoOptimalItinerariesTest.java
  application/src/test/java/org/opentripplanner/service/paging/PS3_FewItinerariesOnSearchWindowLimitTest.java
  application/src/test/java/org/opentripplanner/service/paging/PS4_NextPageAfterArriveBySearchTest.java
  application/src/test/java/org/opentripplanner/service/paging/TestPagingModel.java
  application/src/test/java/org/opentripplanner/service/paging/TestPagingUtils.java
Labels: Improvement, HSL

#6629 Unify trip pattern caches for GTFS-RT and SIRI
  application/src/main/java/org/opentripplanner/graph_builder/module/AddTransitEntitiesToGraph.java
  application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java
  application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationFactory.java
  application/src/main/java/org/opentripplanner/transit/configure/TransitModule.java
  application/src/main/java/org/opentripplanner/transit/model/network/TripPattern.java
  application/src/main/java/org/opentripplanner/transit/model/network/TripPatternBuilder.java
  application/src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  application/src/main/java/org/opentripplanner/transit/service/TimetableRepository.java
  application/src/main/java/org/opentripplanner/transit/service/TransitEditorService.java
  application/src/main/java/org/opentripplanner/transit/service/TransitService.java
  application/src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
  application/src/main/java/org/opentripplanner/updater/trip/TripPatternCache.java
  application/src/main/java/org/opentripplanner/updater/trip/TripPatternIdGenerator.java
  application/src/main/java/org/opentripplanner/updater/trip/configure/TripUpdateModule.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/GtfsRealTimeTripUpdateAdapter.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/TripPatternCache.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/SiriRealTimeTripUpdateAdapter.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/SiriTripPatternCache.java
  application/src/test/java/org/opentripplanner/GtfsTest.java
  application/src/test/java/org/opentripplanner/routing/graphfinder/PlaceFinderTraverseVisitorTest.java
  application/src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
  application/src/test/java/org/opentripplanner/updater/trip/RealtimeTestEnvironment.java
  application/src/test/java/org/opentripplanner/updater/trip/gtfs/GtfsRealTimeTripUpdateAdapterTest.java
Labels: Technical Debt, Real-Time Update, Skip Changelog

#6678 Fix route filter application for stations in GTFS API
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/StopImpl.java
  application/src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
  application/src/test/resources/org/opentripplanner/apis/gtfs/expectations/stations.json
  application/src/test/resources/org/opentripplanner/apis/gtfs/queries/stations.graphql
Labels: Bug

#6668 Transit filters for GTFS API's `planConnection`
  application/src/main/java/org/opentripplanner/apis/gtfs/GraphQLUtils.java
  application/src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
  application/src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLTypes.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/FilterMapper.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/ModePreferencesMapper.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/RouteRequestMapper.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/SelectRequestMapper.java
  application/src/main/java/org/opentripplanner/routing/api/request/request/TransitRequest.java
  application/src/main/java/org/opentripplanner/transit/model/framework/FeedScopedId.java
  application/src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
  application/src/test/java/org/opentripplanner/apis/gtfs/GraphQLFormattingTest.java
  application/src/test/java/org/opentripplanner/apis/gtfs/GraphQLUtilsTest.java
  application/src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/FilterMapperTest.java
  application/src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/RouteRequestMapperFiltersTest.java
  application/src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/RouteRequestMapperTransitTest.java
  application/src/test/java/org/opentripplanner/test/support/ResourceLoader.java
  application/src/test/java/org/opentripplanner/transit/model/framework/FeedScopedIdTest.java
  application/src/test/resources/org/opentripplanner/apis/gtfs/queries/planConnection-extended.graphql
  utils/src/main/java/org/opentripplanner/utils/collection/CollectionUtils.java
  utils/src/test/java/org/opentripplanner/utils/collection/CollectionUtilsTest.java
Labels: New Feature

#6680 Add a dictionary document for OTP's terminology
  doc/dev/Dictionary.md
  doc/dev/decisionrecords/NamingConventions.md
Labels: Documentation

#6691 Fix station alert NullPointerExceptions in GTFS GraphQL API
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/StopImpl.java
  application/src/test/resources/org/opentripplanner/apis/gtfs/expectations/stations.json
  application/src/test/resources/org/opentripplanner/apis/gtfs/queries/stations.graphql
Labels: Bug

#6696 Improve error message for null IDs during GTFS mapping
  application/src/main/java/org/opentripplanner/gtfs/mapping/AgencyMapper.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/FareAttributeMapper.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/FareLegRuleMapper.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/FareProductMapper.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/FareTransferRuleMapper.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/IdFactory.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/LocationGroupMapper.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/LocationMapper.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/PathwayMapper.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/RouteMapper.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/ServiceCalendarDateMapper.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/ServiceCalendarMapper.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/ShapePointMapper.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/StationMapper.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/StopMappingWrapper.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/TripMapper.java
  application/src/test/java/org/opentripplanner/gtfs/mapping/FareLegRuleMapperTest.java
  application/src/test/java/org/opentripplanner/gtfs/mapping/GtfsTestData.java
  application/src/test/java/org/opentripplanner/gtfs/mapping/IdFactoryTest.java
  application/src/test/java/org/opentripplanner/gtfs/mapping/LocationMapperTest.java
  application/src/test/java/org/opentripplanner/gtfs/mapping/ServiceCalendarDateMapperTest.java
  application/src/test/java/org/opentripplanner/gtfs/mapping/ServiceCalendarMapperTest.java
  application/src/test/java/org/opentripplanner/gtfs/mapping/ShapePointMapperTest.java
  application/src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java
Labels: Improvement, Skip Changelog

#6695 Fix error message in StreetModeMapper
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/StreetModeMapper.java
  application/src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/StreetModeMapperTest.java
Labels: Bug, Skip Changelog

#6694 Fix initialization bug in DebugRaptor request DTO
  application/src/ext/java/org/opentripplanner/ext/interactivelauncher/debug/raptor/RaptorDebugModel.java
  application/src/main/java/org/opentripplanner/routing/api/request/DebugRaptor.java
  application/src/main/java/org/opentripplanner/routing/api/request/DebugRaptorBuilder.java
  application/src/test/java/org/opentripplanner/routing/api/request/DebugRaptorTest.java
  utils/src/main/java/org/opentripplanner/utils/collection/EnumSetUtils.java
  utils/src/test/java/org/opentripplanner/utils/collection/EnumSetUtilsTest.java
Labels: Bug, Entur Test

#6702 Revert "Unify trip pattern caches for GTFS-RT and SIRI"
  application/src/main/java/org/opentripplanner/graph_builder/module/AddTransitEntitiesToGraph.java
  application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java
  application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationFactory.java
  application/src/main/java/org/opentripplanner/transit/configure/TransitModule.java
  application/src/main/java/org/opentripplanner/transit/model/network/TripPattern.java
  application/src/main/java/org/opentripplanner/transit/model/network/TripPatternBuilder.java
  application/src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  application/src/main/java/org/opentripplanner/transit/service/TimetableRepository.java
  application/src/main/java/org/opentripplanner/transit/service/TransitEditorService.java
  application/src/main/java/org/opentripplanner/transit/service/TransitService.java
  application/src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
  application/src/main/java/org/opentripplanner/updater/trip/TripPatternCache.java
  application/src/main/java/org/opentripplanner/updater/trip/configure/TripUpdateModule.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/GtfsRealTimeTripUpdateAdapter.java
  application/src/main/java/org/opentripplanner/updater/trip/gtfs/TripPatternCache.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/SiriRealTimeTripUpdateAdapter.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/SiriTripPatternCache.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/SiriTripPatternIdGenerator.java
  application/src/test/java/org/opentripplanner/GtfsTest.java
  application/src/test/java/org/opentripplanner/routing/graphfinder/PlaceFinderTraverseVisitorTest.java
  application/src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
  application/src/test/java/org/opentripplanner/updater/trip/RealtimeTestEnvironment.java
  application/src/test/java/org/opentripplanner/updater/trip/gtfs/GtfsRealTimeTripUpdateAdapterTest.java
Labels: Entur Test, Skip Changelog

#6683 Skip new ser-ver-id for --release option (custom-release)
  script/CUSTOM_RELEASE_README.md
  script/custom-release.py
Labels: Bug, Entur Test, Skip Changelog

#6712 Add tracing tags for headers and query parameters to GTFS API
  application/src/main/java/org/opentripplanner/apis/gtfs/GtfsApiParameters.java
  application/src/main/java/org/opentripplanner/apis/gtfs/GtfsGraphQLAPI.java
  application/src/main/java/org/opentripplanner/apis/gtfs/GtfsGraphQLIndex.java
  application/src/main/java/org/opentripplanner/apis/support/TracingUtils.java
  application/src/main/java/org/opentripplanner/apis/transmodel/TransmodelAPI.java
  application/src/main/java/org/opentripplanner/apis/transmodel/TransmodelAPIParameters.java
  application/src/main/java/org/opentripplanner/standalone/api/OtpServerRequestContext.java
  application/src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
  application/src/main/java/org/opentripplanner/standalone/config/sandbox/GtfsApiConfig.java
  application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationModule.java
  application/src/main/java/org/opentripplanner/standalone/server/DefaultServerRequestContext.java
  application/src/test/java/org/opentripplanner/TestServerContext.java
  application/src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
  application/src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
  application/src/test/resources/standalone/config/router-config.json
  doc/user/RouterConfiguration.md
  doc/user/sandbox/ActuatorAPI.md
Labels: GTFS, Sandbox, Config Change, HSL
