Repository opentripplanner/OpenTripPlanner, pull requests merged in 2025-02, with the labels that each got.

#6363 Use SIRI-ET and GTFS-RT TripUpdates at the same time
  .gitignore
  application/src/ext-test/java/org/opentripplanner/ext/geocoder/StopClusterMapperTest.java
  application/src/main/java/org/opentripplanner/model/TimetableSnapshotProvider.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerUpdater.java
  application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java
  application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationFactory.java
  application/src/main/java/org/opentripplanner/transit/configure/TransitModule.java
  application/src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  application/src/main/java/org/opentripplanner/transit/service/TimetableRepository.java
  application/src/main/java/org/opentripplanner/transit/service/TransitEditorService.java
  application/src/main/java/org/opentripplanner/updater/TimetableSnapshotSourceParameters.java
  application/src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
  application/src/main/java/org/opentripplanner/updater/siri/SiriTimetableSnapshotSource.java
  application/src/main/java/org/opentripplanner/updater/spi/TimetableSnapshotFlush.java
  application/src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotManager.java
  application/src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
  application/src/test/java/org/opentripplanner/GtfsTest.java
  application/src/test/java/org/opentripplanner/TestServerContext.java
  application/src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
  application/src/test/java/org/opentripplanner/transit/service/DefaultTransitServiceTest.java
  application/src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
  application/src/test/java/org/opentripplanner/transit/speed_test/TransferCacheTest.java
  application/src/test/java/org/opentripplanner/updater/siri/SiriTimetableSnapshotSourceTest.java
  application/src/test/java/org/opentripplanner/updater/siri/moduletests/rejection/InvalidStopPointRefTest.java
  application/src/test/java/org/opentripplanner/updater/trip/RealtimeTestEnvironment.java
  application/src/test/java/org/opentripplanner/updater/trip/RealtimeTestEnvironmentBuilder.java
  application/src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java
  application/src/test/java/org/opentripplanner/updater/trip/moduletests/addition/AddedTest.java
  application/src/test/java/org/opentripplanner/updater/trip/moduletests/cancellation/CanceledTripTest.java
  application/src/test/java/org/opentripplanner/updater/trip/moduletests/cancellation/CancellationDeletionTest.java
  application/src/test/java/org/opentripplanner/updater/trip/moduletests/delay/DelayedTest.java
  application/src/test/java/org/opentripplanner/updater/trip/moduletests/delay/SkippedTest.java
  application/src/test/java/org/opentripplanner/updater/trip/moduletests/rejection/InvalidInputTest.java
  application/src/test/java/org/opentripplanner/updater/trip/moduletests/rejection/InvalidTripIdTest.java
  doc/dev/design/TimetableSnapshotManager.svg
Labels: Technical Debt, Real-Time Update

#6406 Configure prettier formatting for sandbox code
  .git-blame-ignore-revs
  application/pom.xml
  application/src/ext-test/java/org/opentripplanner/ext/fares/impl/GtfsFaresV2ServiceTest.java
  application/src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
  application/src/ext-test/java/org/opentripplanner/ext/flex/FlexStopTimesForTest.java
  application/src/ext-test/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTripTest.java
  application/src/ext-test/java/org/opentripplanner/ext/flex/trip/UnscheduledTripTest.java
  application/src/ext-test/java/org/opentripplanner/ext/restapi/mapping/EnumMapperTest.java
  application/src/ext-test/java/org/opentripplanner/ext/siri/updater/azure/AbstractAzureSiriUpdaterTest.java
  application/src/ext-test/java/org/opentripplanner/ext/smoovebikerental/SmooveBikeRentalDataSourceTest.java
  application/src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/VehicleParkingsLayerTest.java
  application/src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
  application/src/ext/java/org/opentripplanner/ext/geocoder/StopClusterMapper.java
  application/src/ext/java/org/opentripplanner/ext/parkAndRideApi/ParkAndRideResource.java
  application/src/ext/java/org/opentripplanner/ext/restapi/model/ApiRouterInfo.java
  application/src/ext/java/org/opentripplanner/ext/restapi/resources/IndexAPI.java
  application/src/ext/java/org/opentripplanner/ext/siri/updater/azure/AbstractAzureSiriUpdater.java
  application/src/ext/java/org/opentripplanner/ext/smoovebikerental/SmooveBikeRentalDataSourceParameters.java
  application/src/ext/java/org/opentripplanner/ext/sorlandsbanen/CoachCostCalculator.java
  application/src/ext/java/org/opentripplanner/ext/sorlandsbanen/MergePaths.java
  application/src/ext/java/org/opentripplanner/ext/sorlandsbanen/PathKey.java
  application/src/ext/java/org/opentripplanner/ext/sorlandsbanen/SorlandsbanenNorwayService.java
  application/src/ext/java/org/opentripplanner/ext/stopconsolidation/DecorateConsolidatedStopNames.java
  application/src/ext/java/org/opentripplanner/ext/stopconsolidation/internal/DefaultStopConsolidationService.java
  application/src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/VehicleParkingsLayerBuilder.java
  application/src/ext/java/org/opentripplanner/ext/vehiclerentalservicedirectory/VehicleRentalServiceDirectoryFetcher.java
  pom.xml
Labels: Technical Debt, Skip Changelog

#6413 Add 'boardCost' parameter for cars
  application/src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLTypes.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/CarPreferencesMapper.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/GeneralizedCostParametersMapper.java
  application/src/main/java/org/opentripplanner/routing/api/request/preference/CarPreferences.java
  application/src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  application/src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
  application/src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/RouteRequestMapperCarTest.java
  application/src/test/java/org/opentripplanner/routing/api/request/preference/CarPreferencesTest.java
  application/src/test/resources/standalone/config/router-config.json
  doc/user/RouteRequest.md
  doc/user/RouterConfiguration.md
Labels: Improvement, bump serialization id, Config Change

#6410 Fix processing of one-way boarding locations
  application/src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModule.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/SafetyValueNormalizer.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/StreetEdgePair.java
  application/src/main/java/org/opentripplanner/osm/DefaultOsmProvider.java
  application/src/main/java/org/opentripplanner/osm/OsmParser.java
  application/src/main/java/org/opentripplanner/osm/OsmProvider.java
  application/src/main/java/org/opentripplanner/osm/model/OsmNode.java
  application/src/test/java/org/opentripplanner/ConstantsForTests.java
  application/src/test/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModuleTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/islandpruning/IslandPruningUtils.java
  application/src/test/java/org/opentripplanner/graph_builder/module/linking/LinkingTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/OsmDatabaseTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/OsmModuleTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/OsmParserTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/PlatformLinkerTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/TriangleInequalityTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/UnconnectedAreasTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/UnroutableTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilderTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/BoardingLocationTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/_support/TestOsmProvider.java
  application/src/test/java/org/opentripplanner/osm/wayproperty/specifier/WayTestData.java
Labels: Bug, Technical Debt

#6425 Update suggested machine type for Google Cloud [ci skip]
  doc/user/System-Requirements.md
Labels: Documentation, Skip Changelog

#6397 Allow SIRI's StopPointRef to refer to a NeTEx scheduled stop point
  application/src/main/java/org/opentripplanner/model/OtpTransitService.java
  application/src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
  application/src/main/java/org/opentripplanner/model/impl/OtpTransitServiceImpl.java
  application/src/main/java/org/opentripplanner/netex/NetexModule.java
  application/src/main/java/org/opentripplanner/netex/loader/parser/NetexDocumentParser.java
  application/src/main/java/org/opentripplanner/netex/loader/parser/ServiceFrameParser.java
  application/src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
  application/src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  application/src/main/java/org/opentripplanner/transit/service/TimetableRepository.java
  application/src/main/java/org/opentripplanner/transit/service/TransitService.java
  application/src/main/java/org/opentripplanner/updater/siri/EntityResolver.java
  application/src/test/java/org/opentripplanner/transit/service/TimetableRepositoryTest.java
  application/src/test/java/org/opentripplanner/updater/siri/EntityResolverTest.java
Labels: Real-Time Update, bump serialization id

#6416 Cleanup DefaultServerRequestContext
  application/pom.xml
  application/src/main/java/org/opentripplanner/inspector/raster/TileRendererManager.java
  application/src/main/java/org/opentripplanner/inspector/raster/WheelchairEdgeRenderer.java
  application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationModule.java
  application/src/main/java/org/opentripplanner/standalone/server/DefaultServerRequestContext.java
  application/src/test/java/org/opentripplanner/GtfsTest.java
  application/src/test/java/org/opentripplanner/TestServerContext.java
  application/src/test/java/org/opentripplanner/apis/transmodel/mapping/TripRequestMapperTest.java
  application/src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
  pom.xml
Labels: Technical Debt

#6415 Add support for alert metrics
  application/src/main/java/org/opentripplanner/framework/application/OTPFeature.java
  application/src/main/java/org/opentripplanner/standalone/server/AlertMetrics.java
  application/src/main/java/org/opentripplanner/standalone/server/MetricsLogging.java
  application/src/main/java/org/opentripplanner/transit/service/TimetableRepository.java
  application/src/test/java/org/opentripplanner/GtfsTest.java
  application/src/test/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReferenceTest.java
  application/src/test/java/org/opentripplanner/standalone/server/AlertMetricsTest.java
  doc/user/Configuration.md
Labels: New Feature, Real-Time Update

#6409 Replacing protobuf-format in SIRI-Updater with standard xml
  application/pom.xml
  application/src/main/java/org/opentripplanner/updater/siri/updater/google/GooglePubsubEstimatedTimetableSource.java
Labels: Entur Test

#6434 Add walk and bicycle safety debug layer, remove raster ones
  application/src/main/java/org/opentripplanner/api/resource/GraphInspectorTileResource.java
  application/src/main/java/org/opentripplanner/api/resource/InspectorLayersList.java
  application/src/main/java/org/opentripplanner/apis/APIEndpoints.java
  application/src/main/java/org/opentripplanner/apis/vectortiles/DebugStyleSpec.java
  application/src/main/java/org/opentripplanner/apis/vectortiles/model/StyleBuilder.java
  application/src/main/java/org/opentripplanner/inspector/raster/AreaEdgeRenderer.java
  application/src/main/java/org/opentripplanner/inspector/raster/BikeSafetyEdgeRenderer.java
  application/src/main/java/org/opentripplanner/inspector/raster/DefaultScalarColorPalette.java
  application/src/main/java/org/opentripplanner/inspector/raster/EdgeVertexTileRenderer.java
  application/src/main/java/org/opentripplanner/inspector/raster/ElevationEdgeRenderer.java
  application/src/main/java/org/opentripplanner/inspector/raster/MapTile.java
  application/src/main/java/org/opentripplanner/inspector/raster/NoThruTrafficEdgeRenderer.java
  application/src/main/java/org/opentripplanner/inspector/raster/PathwayEdgeRenderer.java
  application/src/main/java/org/opentripplanner/inspector/raster/ScalarColorPalette.java
  application/src/main/java/org/opentripplanner/inspector/raster/TileRenderer.java
  application/src/main/java/org/opentripplanner/inspector/raster/TileRendererManager.java
  application/src/main/java/org/opentripplanner/inspector/raster/TraversalPermissionsEdgeRenderer.java
  application/src/main/java/org/opentripplanner/inspector/raster/WalkSafetyEdgeRenderer.java
  application/src/main/java/org/opentripplanner/inspector/raster/WheelchairEdgeRenderer.java
  application/src/main/java/org/opentripplanner/inspector/vector/edge/EdgePropertyMapper.java
  application/src/main/java/org/opentripplanner/standalone/api/OtpServerRequestContext.java
  application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationModule.java
  application/src/main/java/org/opentripplanner/standalone/server/DefaultServerRequestContext.java
  application/src/test/java/org/opentripplanner/TestServerContext.java
  application/src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
  application/src/test/resources/org/opentripplanner/apis/vectortiles/style.json
Labels: Technical Debt

#6447 Add maximum slope debug layer
  application/src/main/java/org/opentripplanner/apis/vectortiles/DebugStyleSpec.java
  application/src/main/java/org/opentripplanner/apis/vectortiles/model/StyleBuilder.java
  application/src/main/java/org/opentripplanner/inspector/vector/edge/EdgePropertyMapper.java
  application/src/main/java/org/opentripplanner/inspector/vector/vertex/VertexPropertyMapper.java
  application/src/test/resources/org/opentripplanner/apis/vectortiles/style.json
Labels: Technical Debt

#6438 Rename HSL parking updater to Liipi and update documentation
  application/src/ext-test/java/org/opentripplanner/ext/vehicleparking/liipi/LiipiParkUpdaterTest.java
  application/src/ext-test/resources/org/opentripplanner/ext/vehicleparking/liipi/facilities.json
  application/src/ext-test/resources/org/opentripplanner/ext/vehicleparking/liipi/hubs.json
  application/src/ext-test/resources/org/opentripplanner/ext/vehicleparking/liipi/utilizations.json
  application/src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkUtilizationToPatchMapper.java
  application/src/ext/java/org/opentripplanner/ext/vehicleparking/liipi/LiipiFacilitiesDownloader.java
  application/src/ext/java/org/opentripplanner/ext/vehicleparking/liipi/LiipiHubToVehicleParkingGroupMapper.java
  application/src/ext/java/org/opentripplanner/ext/vehicleparking/liipi/LiipiHubsDownloader.java
  application/src/ext/java/org/opentripplanner/ext/vehicleparking/liipi/LiipiParkPatch.java
  application/src/ext/java/org/opentripplanner/ext/vehicleparking/liipi/LiipiParkToVehicleParkingMapper.java
  application/src/ext/java/org/opentripplanner/ext/vehicleparking/liipi/LiipiParkUpdater.java
  application/src/ext/java/org/opentripplanner/ext/vehicleparking/liipi/LiipiParkUpdaterParameters.java
  application/src/ext/java/org/opentripplanner/ext/vehicleparking/liipi/LiipiParkUtilizationToPatchMapper.java
  application/src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/VehicleParkingUpdaterConfig.java
  application/src/main/java/org/opentripplanner/updater/vehicle_parking/AvailabilityDatasourceFactory.java
  application/src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingDataSourceFactory.java
  application/src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingSourceType.java
  application/src/test/resources/standalone/config/router-config.json
  doc/templates/VehicleParking.md
  doc/user/RouterConfiguration.md
  doc/user/sandbox/VehicleParking.md
Labels: Documentation, bump serialization id, Skip Changelog, Config Change

#6428 Real time components renaming
  application/src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  application/src/ext/java/org/opentripplanner/ext/sorlandsbanen/SorlandsbanenNorwayService.java
  application/src/main/java/org/opentripplanner/model/TimetableSnapshot.java
  application/src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/RaptorTransitData.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/TransferPointForPatternFactory.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/DefaultCostCalculator.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RaptorTransitDataMapper.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RealTimeRaptorTransitDataUpdater.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitData.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TransitDataProviderFilter.java
  application/src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/StopPriorityCostCalculator.java
  application/src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizePathDomainService.java
  application/src/main/java/org/opentripplanner/standalone/config/routerconfig/UpdatersConfig.java
  application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java
  application/src/main/java/org/opentripplanner/standalone/server/MetricsLogging.java
  application/src/main/java/org/opentripplanner/transit/configure/TransitModule.java
  application/src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  application/src/main/java/org/opentripplanner/transit/service/TimetableRepository.java
  application/src/main/java/org/opentripplanner/transit/service/TransitEditorService.java
  application/src/main/java/org/opentripplanner/transit/service/TransitService.java
  application/src/main/java/org/opentripplanner/updater/TimetableSnapshotParameters.java
  application/src/main/java/org/opentripplanner/updater/TimetableSnapshotSourceParameters.java
  application/src/main/java/org/opentripplanner/updater/UpdatersParameters.java
  application/src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
  application/src/main/java/org/opentripplanner/updater/package.md
  application/src/main/java/org/opentripplanner/updater/siri/SiriRealTimeTripUpdateAdapter.java
  application/src/main/java/org/opentripplanner/updater/siri/updater/EstimatedTimetableHandler.java
  application/src/main/java/org/opentripplanner/updater/siri/updater/SiriETUpdater.java
  application/src/main/java/org/opentripplanner/updater/siri/updater/configure/SiriUpdaterModule.java
  application/src/main/java/org/opentripplanner/updater/siri/updater/google/SiriETGooglePubsubUpdater.java
  application/src/main/java/org/opentripplanner/updater/trip/GtfsRealTimeTripUpdateAdapter.java
  application/src/main/java/org/opentripplanner/updater/trip/MqttGtfsRealtimeUpdater.java
  application/src/main/java/org/opentripplanner/updater/trip/PollingTripUpdater.java
  application/src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotManager.java
  application/src/main/java/org/opentripplanner/updater/trip/TripUpdateGraphWriterRunnable.java
  application/src/main/resources/logback.xml
  application/src/test/java/org/opentripplanner/GtfsTest.java
  application/src/test/java/org/opentripplanner/TestServerContext.java
  application/src/test/java/org/opentripplanner/model/TimetableSnapshotTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapperTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/RaptorTransitDataTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RaptorTransitDataMapperTest.java
  application/src/test/java/org/opentripplanner/routing/graph/GraphSerializationTest.java
  application/src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
  application/src/test/java/org/opentripplanner/transit/speed_test/TransferCacheTest.java
  application/src/test/java/org/opentripplanner/transit/speed_test/support/AssertSpeedTestSetup.java
  application/src/test/java/org/opentripplanner/updater/siri/SiriRealTimeTripUpdateAdapterTest.java
  application/src/test/java/org/opentripplanner/updater/trip/GtfsRealTimeTripUpdateAdapterTest.java
  application/src/test/java/org/opentripplanner/updater/trip/RealtimeTestEnvironment.java
  application/src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotManagerTest.java
  doc/dev/design/TimetableSnapshotManager.svg
  raptor/src/test/java/org/opentripplanner/raptor/_data/transit/TestCostCalculator.java
Labels: Technical Debt, bump serialization id, Skip Changelog

#6449 Disable OptimizeTransfers for via search temporarily.
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
Labels: Entur Test

#6440 Restore ability to click on stops in debug UI on first map load
  client/src/components/MapView/LayerControl.tsx
  client/src/components/MapView/MapView.tsx
  client/src/util/map.ts
Labels: OTP Debug UI, Skip Changelog

#6456 Update `azure-identity` to fix build
  application/pom.xml
Labels: Technical Debt, Skip Changelog

#6448 Return error codes from SiriFuzzyTripMatcher, add support for scheduled stop points
  application/src/main/java/org/opentripplanner/updater/siri/SiriFuzzyTripMatcher.java
  application/src/main/java/org/opentripplanner/updater/siri/SiriRealTimeTripUpdateAdapter.java
  application/src/main/java/org/opentripplanner/updater/spi/UpdateError.java
  application/src/test/java/org/opentripplanner/updater/siri/SiriEtBuilder.java
  application/src/test/java/org/opentripplanner/updater/siri/SiriFuzzyTripMatcherTest.java
Labels: Improvement, Technical Debt

#6414 Remove default accessegress penalty for car modes that use transit
  application/src/main/java/org/opentripplanner/routing/api/request/preference/AccessEgressPreferences.java
  application/src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
  application/src/test/java/org/opentripplanner/routing/api/request/preference/StreetPreferencesTest.java
  doc/user/RouteRequest.md
Labels: Improvement

#6432 Remove dependency from Timetable to GTFS-RT TripUpdate
  application/src/main/java/org/opentripplanner/model/Timetable.java
  application/src/main/java/org/opentripplanner/updater/trip/GtfsRealTimeTripUpdateAdapter.java
  application/src/main/java/org/opentripplanner/updater/trip/TripTimesUpdater.java
  application/src/main/resources/logback.xml
  application/src/test/java/org/opentripplanner/model/TimetableSnapshotTest.java
  application/src/test/java/org/opentripplanner/updater/trip/LegacyTimetableSnapshotIntegrationTest.java
  application/src/test/java/org/opentripplanner/updater/trip/TripTimesUpdaterTest.java
Labels: Technical Debt, Skip Changelog

#6457 Fix logging in ScheduledTransitLegReference
  application/src/main/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReference.java
Labels: Bug, Technical Debt, Skip Changelog

#6245 Fix stop time fetching in added or replacement trips
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/TripImpl.java
  application/src/main/java/org/opentripplanner/apis/transmodel/model/timetable/DatedServiceJourneyType.java
  application/src/main/java/org/opentripplanner/apis/transmodel/model/timetable/ServiceJourneyType.java
  application/src/main/java/org/opentripplanner/model/TripTimeOnDate.java
  application/src/main/java/org/opentripplanner/routing/TripTimeOnDateHelper.java
  application/src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  application/src/main/java/org/opentripplanner/transit/service/TransitService.java
  application/src/main/java/org/opentripplanner/updater/trip/GtfsRealTimeTripUpdateAdapter.java
  application/src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
  application/src/test/java/org/opentripplanner/transit/service/DefaultTransitServiceTest.java
  application/src/test/resources/org/opentripplanner/apis/gtfs/expectations/patterns.json
  application/src/test/resources/org/opentripplanner/apis/gtfs/expectations/realtime-trip.json
  application/src/test/resources/org/opentripplanner/apis/gtfs/queries/realtime-trip.graphql
Labels: Real-Time Update

#6450 Add CT Fares for Mar 1 fare changes + flex support
  application/src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
  application/src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
Labels: Sandbox, Skip Changelog

#6345 Release script for downstream OTP forks
  script/CUSTOM_RELEASE_README.md
  script/changelog-diff.py
  script/custom-release.py
  script/images/release-git-flow-feature-branch.svg
  script/images/release-git-flow.svg
  script/test.py
Labels: Improvement

#6454 Restore debug raster tiles as a sandbox feature, and add safety and vertex elevation text debug layers
  application/pom.xml
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/BikeSafetyEdgeRenderer.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/DefaultScalarColorPalette.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/EdgeVertexTileRenderer.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/ElevationEdgeRenderer.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/MapTile.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/NoThruTrafficEdgeRenderer.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/ScalarColorPalette.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/TileRenderer.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/TileRendererManager.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/TraversalPermissionsEdgeRenderer.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/WalkSafetyEdgeRenderer.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/WheelchairEdgeRenderer.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/api/resource/DebugRasterTileResource.java
  application/src/main/java/org/opentripplanner/apis/APIEndpoints.java
  application/src/main/java/org/opentripplanner/apis/vectortiles/DebugStyleSpec.java
  application/src/main/java/org/opentripplanner/apis/vectortiles/model/StyleBuilder.java
  application/src/main/java/org/opentripplanner/framework/application/OTPFeature.java
  application/src/test/java/org/opentripplanner/apis/vectortiles/DebugStyleSpecTest.java
  application/src/test/java/org/opentripplanner/test/support/JsonAssertions.java
  application/src/test/java/org/opentripplanner/test/support/ResourceLoader.java
  application/src/test/resources/org/opentripplanner/apis/vectortiles/style.json
  doc/user/Configuration.md
  doc/user/Developers-Guide.md
  doc/user/sandbox/DebugRasterTiles.md
  mkdocs.yml
Labels: Technical Debt

#6469 HSL prefers fares with zones identical to those required by the journey
  application/src/ext-test/java/org/opentripplanner/ext/fares/impl/HSLFareServiceTest.java
  application/src/ext/java/org/opentripplanner/ext/fares/impl/HSLFareService.java
Labels: Bug, Skip Changelog

#6339 Inject defaults into the planConnection query in the GTFS GraphQL schema
  application/src/main/java/org/opentripplanner/apis/gtfs/DefaultValueInjector.java
  application/src/main/java/org/opentripplanner/apis/gtfs/GraphQLRequestContext.java
  application/src/main/java/org/opentripplanner/apis/gtfs/GraphQLUtils.java
  application/src/main/java/org/opentripplanner/apis/gtfs/GtfsGraphQLIndex.java
  application/src/main/java/org/opentripplanner/apis/gtfs/SchemaFactory.java
  application/src/main/java/org/opentripplanner/apis/gtfs/configure/SchemaModule.java
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/RouteImpl.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/TransitModeMapper.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/AccessModeMapper.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/DirectModeMapper.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/EgressModeMapper.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/ModePreferencesMapper.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/RouteRequestMapper.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/StreetModeMapper.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/TransferModeMapper.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/VehicleOptimizationTypeMapper.java
  application/src/main/java/org/opentripplanner/routing/api/request/RouteRequest.java
  application/src/main/java/org/opentripplanner/routing/api/request/preference/filter/VehicleParkingSelect.java
  application/src/main/java/org/opentripplanner/standalone/api/OtpServerRequestContext.java
  application/src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java
  application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationFactory.java
  application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationModule.java
  application/src/main/java/org/opentripplanner/standalone/server/DefaultServerRequestContext.java
  application/src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
  application/src/test/java/org/opentripplanner/TestServerContext.java
  application/src/test/java/org/opentripplanner/apis/gtfs/GraphQLFormattingTest.java
  application/src/test/java/org/opentripplanner/apis/gtfs/GraphQLIndexTest.java
  application/src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
  application/src/test/java/org/opentripplanner/apis/gtfs/SchemaFactoryTest.java
  application/src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/LegacyRouteRequestMapperTest.java
  application/src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/RouteRequestMapperTest.java
  application/src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
  doc/user/RouteRequest.md
Labels: Improvement

#6455 Fix ClassCastException in Itinerary mapper
  application/src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/DefaultAccessEgress.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/RoutingAccessEgress.java
  application/src/test/java/org/opentripplanner/raptorlegacy/_data/RaptorTestConstants.java
  application/src/test/java/org/opentripplanner/raptorlegacy/_data/api/PathUtils.java
  application/src/test/java/org/opentripplanner/raptorlegacy/_data/api/TestPathBuilder.java
  application/src/test/java/org/opentripplanner/raptorlegacy/_data/api/TestPathBuilderTestRaptor.java
  application/src/test/java/org/opentripplanner/raptorlegacy/_data/stoparrival/AbstractStopArrival.java
  application/src/test/java/org/opentripplanner/raptorlegacy/_data/stoparrival/Access.java
  application/src/test/java/org/opentripplanner/raptorlegacy/_data/stoparrival/Egress.java
  application/src/test/java/org/opentripplanner/raptorlegacy/_data/stoparrival/FlexAccessAndEgressPathTestCase.java
  application/src/test/java/org/opentripplanner/raptorlegacy/_data/stoparrival/TestArrivals.java
  application/src/test/java/org/opentripplanner/raptorlegacy/_data/stoparrival/Transfer.java
  application/src/test/java/org/opentripplanner/raptorlegacy/_data/stoparrival/Transit.java
  application/src/test/java/org/opentripplanner/raptorlegacy/_data/transit/TestAccessEgress.java
  application/src/test/java/org/opentripplanner/raptorlegacy/_data/transit/TestTransfer.java
  application/src/test/java/org/opentripplanner/raptorlegacy/_data/transit/TestTransferPoint.java
  application/src/test/java/org/opentripplanner/raptorlegacy/_data/transit/TestTransitData.java
  application/src/test/java/org/opentripplanner/raptorlegacy/_data/transit/TestTripPattern.java
  application/src/test/java/org/opentripplanner/raptorlegacy/_data/transit/TestTripSchedule.java
  application/src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/DefaultAccessEgressTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/DefaultCostCalculatorTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/BasicPathTestCase.java
  application/src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/api/OptimizedPathTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/model/MinSafeTransferTimeCalculatorTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/model/OptimizedPathTailTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/model/costfilter/MinCostPathTailFilterTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGeneratorTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransitPathLegSelectorTest.java
  raptor/src/main/java/org/opentripplanner/raptor/api/model/AbstractAccessEgressDecorator.java
  raptor/src/main/java/org/opentripplanner/raptor/api/model/RaptorAccessEgress.java
  raptor/src/test/java/org/opentripplanner/raptor/api/model/AbstractAccessEgressDecoratorTest.java
Labels: Entur Test

#6460 Add unit tests for SIRI cancellation
  application/src/test/java/org/opentripplanner/updater/siri/SiriRealTimeTripUpdateAdapterTest.java
Labels: Real-Time Update, Skip Changelog

#6473 Fix initialisation logic of transit alert service
  application/src/main/java/org/opentripplanner/transit/service/TimetableRepository.java
Labels: Bug, Technical Debt, Entur Test, Skip Changelog

#6462 Convert SIRI tests to feature-specific module tests
  application/src/test/java/org/opentripplanner/updater/siri/SiriRealTimeTripUpdateAdapterTest.java
  application/src/test/java/org/opentripplanner/updater/siri/moduletests/cancellation/CancellationTest.java
  application/src/test/java/org/opentripplanner/updater/siri/moduletests/cancellation/CancelledStopTest.java
  application/src/test/java/org/opentripplanner/updater/siri/moduletests/extrajourney/ExtraJourneyTest.java
  application/src/test/java/org/opentripplanner/updater/siri/moduletests/fuzzymatching/FuzzyTripMatchingTest.java
  application/src/test/java/org/opentripplanner/updater/siri/moduletests/rejection/InvalidStopPointRefTest.java
  application/src/test/java/org/opentripplanner/updater/siri/moduletests/rejection/NegativeTimesTest.java
  application/src/test/java/org/opentripplanner/updater/siri/moduletests/rejection/NotMonitoredTest.java
  application/src/test/java/org/opentripplanner/updater/siri/moduletests/unsupported/UnsupportedTest.java
  application/src/test/java/org/opentripplanner/updater/siri/moduletests/update/QuayChangeTest.java
  application/src/test/java/org/opentripplanner/updater/siri/moduletests/update/UpdatedTimesTest.java
Labels: Technical Debt, Skip Changelog

#6486 Improve street routing within concave parts of area holes
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/OsmArea.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  application/src/main/java/org/opentripplanner/routing/linking/VertexLinker.java
  application/src/main/java/org/opentripplanner/street/model/edge/AreaGroup.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/_support/NodeBuilder.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/_support/RelationBuilder.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/_support/TestOsmProvider.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/walkablearea/ConcaveHoleTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/walkablearea/SimpleAreaTest.java
  application/src/test/java/org/opentripplanner/routing/linking/LinkStopToPlatformTest.java
  application/src/test/java/org/opentripplanner/test/support/GeoJsonIo.java
Labels: Improvement

#6498 Remove the usage of UUID in TemporaryStreetLocation
  application/src/main/java/org/opentripplanner/routing/graph/index/StreetIndex.java
  application/src/main/java/org/opentripplanner/street/model/vertex/TemporaryStreetLocation.java
  application/src/test/java/org/opentripplanner/astar/AStarTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
Labels: Technical Debt, Skip Changelog

#6492 Illustrate current behaviour of siri time interpolation
  application/src/main/java/org/opentripplanner/updater/trip/siri/ModifiedTripBuilder.java
  application/src/test/java/org/opentripplanner/updater/trip/siri/moduletests/InterpolationTest.java
Labels: Real-Time Update, Skip Changelog

#6487 Siri azure updater refactor
  application/src/ext-test/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureUpdaterTest.java
  application/src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  application/src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdaterParameters.java
  application/src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureMessageHandler.java
  application/src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java
  application/src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdaterParameters.java
  application/src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureUpdater.java
  application/src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureUpdaterParameters.java
  application/src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
Labels: Sandbox, Skanetrafiken, Skip Changelog
