Repository opentripplanner/OpenTripPlanner, pull requests merged in 2025-10, with the labels that each got.

#6914 Reduce log verbosity in GBFS station mapper
  application/src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/gbfs/v2/GbfsStationInformationMapper.java
  application/src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/gbfs/v3/GbfsStationInformationMapper.java
Labels: !Improvement, Entur Test, +Skip Changelog

#6876 Show GBFS Geofencing zones in debug UI
  application/src/main/java/org/opentripplanner/apis/vectortiles/DebugStyleSpec.java
  application/src/main/java/org/opentripplanner/apis/vectortiles/DebugVectorTilesResource.java
  application/src/main/java/org/opentripplanner/inspector/vector/KeyValue.java
  application/src/main/java/org/opentripplanner/inspector/vector/geofencing/GeofencingZonesLayerBuilder.java
  application/src/main/java/org/opentripplanner/inspector/vector/geofencing/GeofencingZonesPropertyMapper.java
  application/src/test/java/org/opentripplanner/apis/vectortiles/DebugStyleSpecTest.java
  application/src/test/resources/org/opentripplanner/apis/vectortiles/style.json
Labels: !Improvement, +OTP Debug UI, Vehicle Rental

#6865 Add OTP Badge to ServerInfo
  application/src/main/java/org/opentripplanner/api/model/serverinfo/OtpBadgeGenerator.java
  application/src/main/java/org/opentripplanner/api/resource/ServerInfoResource.java
  application/src/main/java/org/opentripplanner/apis/APIEndpoints.java
  application/src/test/java/org/opentripplanner/api/model/serverinfo/OtpBadgeGeneratorTest.java
Labels: !Improvement

#6877 Parse a GTFS route's network from `route_networks.txt`, compute fares for flex legs
  application/pom.xml
  application/src/ext-test/java/org/opentripplanner/ext/fares/impl/gtfs/AreasTest.java
  application/src/ext-test/java/org/opentripplanner/ext/fares/impl/gtfs/DistancesTest.java
  application/src/ext-test/java/org/opentripplanner/ext/fares/impl/gtfs/FlexLegTest.java
  application/src/ext-test/java/org/opentripplanner/ext/fares/impl/gtfs/GtfsFaresV2ServiceTest.java
  application/src/ext/java/org/opentripplanner/ext/fares/impl/gtfs/FareLookupService.java
  application/src/ext/java/org/opentripplanner/ext/fares/impl/gtfs/GtfsFaresV2Service.java
  application/src/ext/java/org/opentripplanner/ext/fares/impl/gtfs/LegOfferContainer.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/RouteMapper.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/RouteNetworkAssignmentMapper.java
  application/src/main/java/org/opentripplanner/model/plan/Itinerary.java
  application/src/main/java/org/opentripplanner/model/plan/leg/ScheduledTransitLeg.java
  application/src/main/java/org/opentripplanner/transit/model/network/GroupOfRoutes.java
  application/src/test/java/org/opentripplanner/gtfs/mapping/FareRuleMapperTest.java
  application/src/test/java/org/opentripplanner/gtfs/mapping/FrequencyMapperTest.java
  application/src/test/java/org/opentripplanner/gtfs/mapping/RouteMapperTest.java
  application/src/test/java/org/opentripplanner/gtfs/mapping/StopTimeMapperTest.java
  application/src/test/java/org/opentripplanner/gtfs/mapping/TransferMapperTest.java
  application/src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java
Labels: +GTFS, +Skip Changelog

#6762 Use prepared geometries to speed up flex zone computation
  application/src/ext/java/org/opentripplanner/ext/flex/AreaStopsToVerticesMapper.java
Labels: !Optimization, +Skip Changelog

#6919 Refactor set with
  application/src/ext-test/java/org/opentripplanner/ext/fares/FareRuleSetTest.java
  application/src/ext-test/java/org/opentripplanner/ext/fares/impl/HSLFareServiceTest.java
  application/src/ext-test/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceTest.java
  application/src/ext-test/java/org/opentripplanner/ext/fares/impl/_support/FareModelForTest.java
  application/src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
  application/src/ext-test/java/org/opentripplanner/ext/ridehailing/RideHailingAccessShifterTest.java
  application/src/ext/java/org/opentripplanner/ext/fares/model/FareAttributeBuilder.java
  application/src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/StreetFlexPathCalculator.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/LegacyRouteRequestMapper.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/ModePreferencesMapper.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/TransitPreferencesMapper.java
  application/src/main/java/org/opentripplanner/apis/transmodel/mapping/TripRequestMapper.java
  application/src/main/java/org/opentripplanner/apis/transmodel/mapping/ViaSegmentMapper.java
  application/src/main/java/org/opentripplanner/apis/transmodel/mapping/preferences/TransitPreferencesMapper.java
  application/src/main/java/org/opentripplanner/astar/AStarBuilder.java
  application/src/main/java/org/opentripplanner/graph_builder/module/nearbystops/StreetNearbyStopFinder.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/FareAttributeMapper.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RaptorRequestMapper.java
  application/src/main/java/org/opentripplanner/routing/api/request/preference/TransitPreferences.java
  application/src/main/java/org/opentripplanner/routing/api/request/request/JourneyRequestBuilder.java
  application/src/main/java/org/opentripplanner/routing/api/request/request/TransitRequestBuilder.java
  application/src/main/java/org/opentripplanner/routing/graphfinder/StreetGraphFinder.java
  application/src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
  application/src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
  application/src/main/java/org/opentripplanner/street/search/StreetSearchBuilder.java
  application/src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java
  application/src/test/java/org/opentripplanner/GtfsTest.java
  application/src/test/java/org/opentripplanner/astar/AStarTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/TurnRestrictionModuleTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/TriangleInequalityTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/UnroutableTest.java
  application/src/test/java/org/opentripplanner/routing/TestHalfEdges.java
  application/src/test/java/org/opentripplanner/routing/algorithm/TurnCostTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/mapping/BikeRentalSnapshotTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/mapping/TransitSnapshotTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/PatternCostCalculatorTest.java
  application/src/test/java/org/opentripplanner/routing/api/request/preference/TransitPreferencesTest.java
  application/src/test/java/org/opentripplanner/routing/api/request/request/JourneyRequestTest.java
  application/src/test/java/org/opentripplanner/routing/api/request/request/TransitRequestTest.java
  application/src/test/java/org/opentripplanner/street/integration/BikeRentalTest.java
  application/src/test/java/org/opentripplanner/street/integration/BikeWalkingTest.java
  application/src/test/java/org/opentripplanner/street/integration/CarPickupTest.java
  application/src/test/java/org/opentripplanner/street/integration/ParkAndRideTest.java
  application/src/test/java/org/opentripplanner/street/model/TurnRestrictionTest.java
  application/src/test/java/org/opentripplanner/street/search/request/StreetSearchRequestMapperTest.java
  application/src/test/java/org/opentripplanner/transit/speed_test/SpeedTestRequest.java
  raptor/src/main/java/org/opentripplanner/raptor/api/request/DebugRequestBuilder.java
  raptor/src/main/java/org/opentripplanner/raptor/rangeraptor/SystemErrDebugLogger.java
  raptor/src/test/java/org/opentripplanner/raptor/_data/transit/TestTransitData.java
Labels: !Technical Debt, +Skip Changelog

#6940 Improve GBFS v3 station validation
  application/src/ext-test/java/org/opentripplanner/updater/vehicle_rental/datasources/gbfs/v3/GbfsStationInformationMapperTest.java
  application/src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/gbfs/v3/GbfsStationInformationMapper.java
Labels: !Bug, Entur Test, +Real-Time, +Skip Changelog

#6850 Changes to TransitDataProviderFilter
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RouteRequestTransitDataProviderFilter.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TransitDataProviderFilter.java
  application/src/main/java/org/opentripplanner/routing/api/request/request/filter/SelectRequest.java
  application/src/main/java/org/opentripplanner/routing/api/request/request/filter/TransitFilterRequest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreatorTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RouteRequestTransitDataProviderFilterTest.java
Labels: +Skip Changelog
