Repository opentripplanner/OpenTripPlanner, pull requests merged in 2025-09, with the labels that each got.

#6826 Minor improvements in vertex to area linking
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/SafetyValueNormalizer.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
  application/src/main/java/org/opentripplanner/routing/linking/VertexLinker.java
  application/src/main/java/org/opentripplanner/street/model/edge/Area.java
  application/src/test/java/org/opentripplanner/routing/linking/LinkStopToPlatformTest.java
Labels: Bug, Technical Debt

#6841 Add raw gtfs type of routes to digitransit map stations
  application/src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/stations/DigitransitStationPropertyMapperTest.java
  application/src/ext/java/org/opentripplanner/ext/vectortiles/layers/stations/DigitransitStationPropertyMapper.java
Labels: Sandbox, Skip Changelog

#6838 Fix hashcode in NonLocalizedString
  application/src/main/java/org/opentripplanner/framework/i18n/NonLocalizedString.java
  application/src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/CarSnapshotTest.snap
Labels: Improvement, Skip Changelog

#6705 Integration tests
  .github/workflows/integration-test.yml
  pom.xml
  renovate.json5
  test/integration/Readme.md
  test/integration/pom.xml
  test/integration/src/test/java/org/opentripplanner/integrationtests/http/OtpHttpClientTest.java
Labels: Skip Changelog, Integration Test

#6846 Remove GTFS "remove repeated stops" feature
  application/src/ext-test/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTripIntegrationTest.java
  application/src/main/java/org/opentripplanner/graph_builder/module/ValidateAndInterpolateStopTimesForEachTrip.java
  application/src/main/java/org/opentripplanner/gtfs/config/GtfsDefaultParameters.java
  application/src/main/java/org/opentripplanner/gtfs/config/GtfsDefaultParametersBuilder.java
  application/src/main/java/org/opentripplanner/gtfs/config/GtfsFeedParameters.java
  application/src/main/java/org/opentripplanner/gtfs/config/GtfsFeedParametersBuilder.java
  application/src/main/java/org/opentripplanner/gtfs/graphbuilder/GtfsModule.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/AgencyAndIdMapper.java
  application/src/main/java/org/opentripplanner/netex/NetexModule.java
  application/src/main/java/org/opentripplanner/standalone/config/buildconfig/GtfsConfig.java
  application/src/test/java/org/opentripplanner/gtfs/GtfsContextBuilder.java
  application/src/test/java/org/opentripplanner/gtfs/config/GtfsParametersTest.java
  application/src/test/java/org/opentripplanner/standalone/config/buildconfig/GtfsConfigTest.java
  application/src/test/resources/standalone/config/build-config.json
  doc/user/BuildConfiguration.md
Labels: GTFS, Technical Debt

#6828 Enforce flex rule: at least two stop times per trip
  application/src/ext-test/java/org/opentripplanner/ext/flex/trip/FlexTripsMapperTest.java
  application/src/ext-test/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTripTest.java
  application/src/ext-test/java/org/opentripplanner/ext/flex/trip/UnscheduledDrivingDurationTest.java
  application/src/ext-test/java/org/opentripplanner/ext/flex/trip/UnscheduledTripTest.java
  application/src/ext-test/resources/org/opentripplanner/ext/flex/aspen-flex-on-demand.gtfs/calendar_dates.txt
  application/src/ext-test/resources/org/opentripplanner/ext/flex/aspen-flex-on-demand.gtfs/stop_times.txt
  application/src/ext/java/org/opentripplanner/ext/flex/FlexTripsMapper.java
  application/src/ext/java/org/opentripplanner/ext/flex/template/FlexTemplateFactory.java
  application/src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
  application/src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
  application/src/main/java/org/opentripplanner/model/StopTime.java
  application/src/test/java/org/opentripplanner/graph_builder/module/StreetLinkerModuleTest.java
Labels: Sandbox, Technical Debt

#6857 Rewrite Orca fare model to generate fare offers
  application/src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
  application/src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
Labels: Sandbox, Skip Changelog

#6891 Add prefix ! and + to GitHub labels
  .github/pull_request_template.md
  .github/workflows/integration-test.yml
  .github/workflows/post-merge.yml
  doc/user/Developers-Guide.md
  renovate.json5
  script/CUSTOM_RELEASE_README.md
  script/custom-release.py
Labels: !Documentation, +Skip Changelog

#6884 Add `code` to station vector tile layer
  application/src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/stations/DigitransitStationPropertyMapperTest.java
  application/src/ext/java/org/opentripplanner/ext/vectortiles/layers/stations/DigitransitStationPropertyMapper.java
Labels: +Sandbox, +Skip Changelog

#6895 fix: use PreparedGeometry in geofencing zone <-> street edge intersect check
  application/src/main/java/org/opentripplanner/updater/vehicle_rental/GeofencingVertexUpdater.java
Labels: !Optimization, +Real-Time, +Skip Changelog
