Repository opentripplanner/OpenTripPlanner, pull requests merged in 2025-04, with the labels that each got.

#6563 Document policy for doing breaking changes the the APIs.
  doc/dev/decisionrecords/APIGraphQLDesign.md
Labels: Documentation, Skip Changelog, Developer Decision Record

#6580 Fix crash on itineraries with frequencies where distanceMeters was not computed
  application/src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
Labels: Bug

#6573 Updating SIRI objects used to SIRI 2.1
  application/src/ext-test/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureUpdaterTest.java
  application/src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
  application/src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureMessageHandler.java
  application/src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java
  application/src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureUpdater.java
  application/src/main/java/org/opentripplanner/updater/alert/siri/SiriAlertsUpdateHandler.java
  application/src/main/java/org/opentripplanner/updater/alert/siri/SiriSXUpdater.java
  application/src/main/java/org/opentripplanner/updater/alert/siri/lite/SiriLiteHttpLoader.java
  application/src/main/java/org/opentripplanner/updater/alert/siri/mapping/AffectsMapper.java
  application/src/main/java/org/opentripplanner/updater/alert/siri/mapping/SiriSeverityMapper.java
  application/src/main/java/org/opentripplanner/updater/alert/siri/mapping/SiriTransportModeMapper.java
  application/src/main/java/org/opentripplanner/updater/support/siri/SiriFileLoader.java
  application/src/main/java/org/opentripplanner/updater/support/siri/SiriHelper.java
  application/src/main/java/org/opentripplanner/updater/support/siri/SiriHttpLoader.java
  application/src/main/java/org/opentripplanner/updater/support/siri/SiriLoader.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/AddedTripBuilder.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/CallWrapper.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/DebugString.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/EntityResolver.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/ModifiedTripBuilder.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/SiriFuzzyTripMatcher.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/SiriRealTimeTripUpdateAdapter.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/TimetableHelper.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/mapping/OccupancyMapper.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/mapping/PickDropMapper.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/updater/AsyncEstimatedTimetableProcessor.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/updater/AsyncEstimatedTimetableSource.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/updater/EstimatedTimetableHandler.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/updater/EstimatedTimetableSource.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/updater/SiriETHttpTripUpdateSource.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/updater/SiriETUpdater.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/updater/google/GooglePubsubEstimatedTimetableSource.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/updater/lite/SiriETLiteHttpTripUpdateSource.java
  application/src/test/java/org/opentripplanner/updater/alert/siri/SiriAlertsUpdateHandlerTest.java
  application/src/test/java/org/opentripplanner/updater/alert/siri/lite/SiriLiteHttpLoaderTest.java
  application/src/test/java/org/opentripplanner/updater/trip/RealtimeTestEnvironment.java
  application/src/test/java/org/opentripplanner/updater/trip/siri/AddedTripBuilderTest.java
  application/src/test/java/org/opentripplanner/updater/trip/siri/ModifiedTripBuilderTest.java
  application/src/test/java/org/opentripplanner/updater/trip/siri/SiriEtBuilder.java
  application/src/test/java/org/opentripplanner/updater/trip/siri/SiriFuzzyTripMatcherTest.java
  application/src/test/java/org/opentripplanner/updater/trip/siri/TestCall.java
  application/src/test/java/org/opentripplanner/updater/trip/siri/TimetableHelperTest.java
  application/src/test/java/org/opentripplanner/updater/trip/siri/mapper/PickDropMapperTest.java
Labels: Improvement, New Feature, Entur Test

#6597 Set correct transfer modes for scooters in deprecated `plan` query
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/api/resource/DebugRasterTileResource.java
  application/src/ext/java/org/opentripplanner/ext/debugrastertiles/api/resource/MIMEImageFormat.java
  application/src/main/java/org/opentripplanner/api/parameter/QualifiedModeSet.java
  application/src/main/java/org/opentripplanner/api/parameter/package-info.md
  application/src/test/java/org/opentripplanner/api/parameter/QualifiedModeSetTest.java
Labels: Bug

#6598 Boarding location linking accepts very short links instead of throwing an exception
  application/src/main/java/org/opentripplanner/routing/linking/VertexLinker.java
  application/src/test/java/org/opentripplanner/routing/linking/LinkStopToPlatformTest.java
Labels: Bug, Skip Changelog

#6587 Rename FilterValues implementations, make them package-private
  application/src/ext-test/java/org/opentripplanner/ext/flex/filter/FilterMapperTest.java
  application/src/main/java/org/opentripplanner/transit/api/model/EmptyIsEverythingFilter.java
  application/src/main/java/org/opentripplanner/transit/api/model/FilterValues.java
  application/src/main/java/org/opentripplanner/transit/api/model/NullIsEverythingFilter.java
  application/src/main/java/org/opentripplanner/transit/api/model/RequiredFilterValues.java
  application/src/main/java/org/opentripplanner/transit/api/request/TripOnServiceDateRequest.java
  application/src/main/java/org/opentripplanner/transit/api/request/TripOnServiceDateRequestBuilder.java
  application/src/test/java/org/opentripplanner/transit/api/model/EmptyIsEverythingFilterTest.java
Labels: Technical Debt, Skip Changelog

#6610 feature: Add version 2.8 to OtpVersion
  application/src/main/java/org/opentripplanner/standalone/config/framework/json/OtpVersion.java
Labels: Technical Debt, Skip Changelog

#6612 Split schema validation actions workflow into two jobs
  .github/workflows/schema-validation.yml
Labels: Technical Debt, Skip Changelog

#6069 Remove service date from cache key of SiriTripPatternCache
  application/src/main/java/org/opentripplanner/updater/trip/siri/SiriRealTimeTripUpdateAdapter.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/SiriTripPatternCache.java
Labels: Real-Time Update, Skip Changelog

#6493 Implement SIRI extra calls
  application/src/main/java/org/opentripplanner/updater/trip/siri/AddedTripBuilder.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/CallWrapper.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/ExtraCallTripBuilder.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/SiriRealTimeTripUpdateAdapter.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/StopTimesMapper.java
  application/src/main/java/org/opentripplanner/updater/trip/siri/support/NaturalLanguageStringHelper.java
  application/src/test/java/org/opentripplanner/updater/trip/siri/TestCall.java
  application/src/test/java/org/opentripplanner/updater/trip/siri/moduletests/extracall/ExtraCallTest.java
  application/src/test/java/org/opentripplanner/updater/trip/siri/moduletests/unsupported/UnsupportedTest.java
Labels: Entur Test
