Repository opentripplanner/OpenTripPlanner, pull requests merged in 2025-01, with the labels that each got.

#6356 Eslint 9 upgrades
  client/.eslintrc.cjs
  client/.gitignore
  client/.prettierignore
  client/eslint.config.mjs
  client/package-lock.json
  client/package.json
  client/prettier.config.mjs
  client/src/components/ItineraryList/ItineraryPaginationControl.tsx
  client/src/util/getApiUrl.ts
Labels: Technical Debt, Skip Changelog

#6284 Implement SIRI Lite
  application/src/main/java/org/opentripplanner/standalone/config/routerconfig/UpdatersConfig.java
  application/src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/SiriETLiteUpdaterConfig.java
  application/src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/SiriSXLiteUpdaterConfig.java
  application/src/main/java/org/opentripplanner/updater/UpdatersParameters.java
  application/src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
  application/src/main/java/org/opentripplanner/updater/siri/updater/EstimatedTimetableSource.java
  application/src/main/java/org/opentripplanner/updater/siri/updater/SiriETHttpTripUpdateSource.java
  application/src/main/java/org/opentripplanner/updater/siri/updater/SiriETUpdater.java
  application/src/main/java/org/opentripplanner/updater/siri/updater/SiriETUpdaterParameters.java
  application/src/main/java/org/opentripplanner/updater/siri/updater/SiriHttpLoader.java
  application/src/main/java/org/opentripplanner/updater/siri/updater/SiriSXUpdater.java
  application/src/main/java/org/opentripplanner/updater/siri/updater/SiriSXUpdaterParameters.java
  application/src/main/java/org/opentripplanner/updater/siri/updater/configure/SiriUpdaterModule.java
  application/src/main/java/org/opentripplanner/updater/siri/updater/lite/SiriETLiteHttpTripUpdateSource.java
  application/src/main/java/org/opentripplanner/updater/siri/updater/lite/SiriETLiteUpdaterParameters.java
  application/src/main/java/org/opentripplanner/updater/siri/updater/lite/SiriLiteHttpLoader.java
  application/src/main/java/org/opentripplanner/updater/siri/updater/lite/SiriSXLiteUpdaterParameters.java
  application/src/test/java/org/opentripplanner/generate/doc/SiriConfigDocTest.java
  application/src/test/java/org/opentripplanner/generate/doc/UpdaterConfigDocTest.java
  application/src/test/java/org/opentripplanner/updater/siri/updater/lite/SiriLiteHttpLoaderTest.java
  application/src/test/resources/org/opentripplanner/updater/siri/updater/lite/siri-sx.xml
  application/src/test/resources/standalone/config/router-config.json
  doc/templates/StopConsolidation.md
  doc/templates/UpdaterConfig.md
  doc/templates/sandbox/siri/SiriAzureUpdater.md
  doc/templates/sandbox/siri/SiriGooglePubSubUpdater.md
  doc/templates/sandbox/siri/SiriUpdater.md
  doc/user/Changelog.md
  doc/user/RouterConfiguration.md
  doc/user/UpdaterConfig.md
  doc/user/examples/skanetrafiken/Readme.md
  doc/user/features-explained/Netex-Siri-Compatibility.md
  doc/user/sandbox/StopConsolidation.md
  doc/user/sandbox/siri/SiriAzureUpdater.md
  doc/user/sandbox/siri/SiriGooglePubSubUpdater.md
  doc/user/sandbox/siri/SiriUpdater.md
Labels: New Feature, Real-Time Update

#6234 Add a matcher API for filters in the transit service used for regularStop lookup
  application/src/ext/java/org/opentripplanner/ext/parkAndRideApi/ParkAndRideResource.java
  application/src/ext/java/org/opentripplanner/ext/restapi/resources/IndexAPI.java
  application/src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/StopsLayerBuilder.java
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/QueryTypeImpl.java
  application/src/main/java/org/opentripplanner/apis/transmodel/TransmodelGraphQLSchema.java
  application/src/main/java/org/opentripplanner/apis/transmodel/model/stop/StopPlaceType.java
  application/src/main/java/org/opentripplanner/apis/vectortiles/GraphInspectorVectorTileResource.java
  application/src/main/java/org/opentripplanner/graph_builder/module/nearbystops/StraightLineNearbyStopFinder.java
  application/src/main/java/org/opentripplanner/standalone/api/OtpServerRequestContext.java
  application/src/main/java/org/opentripplanner/transit/api/model/FilterValues.java
  application/src/main/java/org/opentripplanner/transit/api/request/FindRegularStopsByBoundingBoxRequest.java
  application/src/main/java/org/opentripplanner/transit/api/request/FindRegularStopsByBoundingBoxRequestBuilder.java
  application/src/main/java/org/opentripplanner/transit/api/request/TripOnServiceDateRequest.java
  application/src/main/java/org/opentripplanner/transit/api/request/TripOnServiceDateRequestBuilder.java
  application/src/main/java/org/opentripplanner/transit/api/request/TripRequest.java
  application/src/main/java/org/opentripplanner/transit/api/request/TripRequestBuilder.java
  application/src/main/java/org/opentripplanner/transit/model/filter/expr/ExpressionBuilder.java
  application/src/main/java/org/opentripplanner/transit/model/filter/expr/GenericUnaryMatcher.java
  application/src/main/java/org/opentripplanner/transit/model/filter/transit/RegularStopMatcherFactory.java
  application/src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  application/src/main/java/org/opentripplanner/transit/service/StopModelIndex.java
  application/src/main/java/org/opentripplanner/transit/service/TransitService.java
  application/src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
  application/src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/LegacyRouteRequestMapperTest.java
  application/src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/RouteRequestMapperTest.java
  application/src/test/java/org/opentripplanner/routing/graph/DefaultRoutingServiceTest.java
  application/src/test/java/org/opentripplanner/transit/model/filter/expr/GenericUnaryMatcherTest.java
  application/src/test/java/org/opentripplanner/transit/model/filter/transit/RegularStopMatcherFactoryTest.java
Labels: Improvement

#6358 Update list of GTFS Fares v2 classes
  application/pom.xml
  application/src/main/java/org/opentripplanner/gtfs/graphbuilder/GtfsModule.java
Labels: Bug, GTFS, Skip Changelog

#6368 When using ScheduledTransitLeg's copy builder, also copy alerts
  application/src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
  application/src/main/java/org/opentripplanner/model/plan/ScheduledTransitLegBuilder.java
  application/src/test/java/org/opentripplanner/model/plan/ScheduledTransitLegBuilderTest.java
Labels: Bug

#6375 Improve handling of null values in argument lists to the serviceJourneys graphQL method in the Transmodel API
  application/src/main/java/org/opentripplanner/apis/transmodel/TransmodelGraphQLSchema.java
  application/src/main/java/org/opentripplanner/apis/transmodel/support/GqlUtil.java
Labels: Technical Debt, Entur Test, Skip Changelog

#6380 Add HTTP headers to GraphiQL, upgrade version
  application/src/client/graphiql/index.html
Labels: Skip Changelog

#6355 Make it possible to add custom API documentation based on the deployment location
  application/src/ext/resources/org/opentripplanner/ext/apis/transmodel/custom-documentation-entur.properties
  application/src/main/java/org/opentripplanner/apis/support/graphql/injectdoc/ApiDocumentationProfile.java
  application/src/main/java/org/opentripplanner/apis/support/graphql/injectdoc/CustomDocumentation.java
  application/src/main/java/org/opentripplanner/apis/support/graphql/injectdoc/InjectCustomDocumentation.java
  application/src/main/java/org/opentripplanner/apis/transmodel/TransmodelAPI.java
  application/src/main/java/org/opentripplanner/apis/transmodel/TransmodelGraphQLSchema.java
  application/src/main/java/org/opentripplanner/standalone/config/framework/project/EnvironmentVariableReplacer.java
  application/src/main/java/org/opentripplanner/standalone/config/routerconfig/ServerConfig.java
  application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java
  application/src/test/java/org/opentripplanner/_support/text/TextAssertions.java
  application/src/test/java/org/opentripplanner/_support/text/TextAssertionsTest.java
  application/src/test/java/org/opentripplanner/apis/support/graphql/injectdoc/CustomDocumentationTest.java
  application/src/test/java/org/opentripplanner/apis/support/graphql/injectdoc/InjectCustomDocumentationTest.java
  application/src/test/java/org/opentripplanner/apis/transmodel/TransmodelGraphQLSchemaTest.java
  application/src/test/resources/org/opentripplanner/apis/support/graphql/injectdoc/InjectCustomDocumentationTest.graphql
  application/src/test/resources/org/opentripplanner/apis/support/graphql/injectdoc/InjectCustomDocumentationTest.graphql.expected
  doc/user/RouterConfiguration.md
  utils/src/main/java/org/opentripplanner/utils/text/TextVariablesSubstitution.java
  utils/src/test/java/org/opentripplanner/utils/text/TextVariablesSubstitutionTest.java
Labels: New Feature, Entur Test

#6343 If configured, add subway station entrances from OSM to walk steps
  application/src/ext-test/java/org/opentripplanner/ext/restapi/mapping/EnumMapperTest.java
  application/src/ext/java/org/opentripplanner/ext/restapi/mapping/RelativeDirectionMapper.java
  application/src/ext/java/org/opentripplanner/ext/restapi/mapping/WalkStepMapper.java
  application/src/main/java/org/opentripplanner/apis/gtfs/GtfsGraphQLIndex.java
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/EntranceImpl.java
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/StepFeatureTypeResolver.java
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/stepImpl.java
  application/src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
  application/src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLTypes.java
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/DirectionMapper.java
  application/src/main/java/org/opentripplanner/apis/transmodel/mapping/RelativeDirectionMapper.java
  application/src/main/java/org/opentripplanner/apis/transmodel/model/plan/PathGuidanceType.java
  application/src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/ElevatorProcessor.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModule.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModuleBuilder.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/VertexGenerator.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/parameters/OsmExtractParameters.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/parameters/OsmExtractParametersBuilder.java
  application/src/main/java/org/opentripplanner/graph_builder/module/osm/parameters/OsmProcessingParameters.java
  application/src/main/java/org/opentripplanner/model/plan/RelativeDirection.java
  application/src/main/java/org/opentripplanner/model/plan/WalkStep.java
  application/src/main/java/org/opentripplanner/model/plan/WalkStepBuilder.java
  application/src/main/java/org/opentripplanner/osm/OsmProvider.java
  application/src/main/java/org/opentripplanner/osm/model/OsmNode.java
  application/src/main/java/org/opentripplanner/osm/model/OsmWithTags.java
  application/src/main/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapper.java
  application/src/main/java/org/opentripplanner/standalone/config/buildconfig/OsmConfig.java
  application/src/main/java/org/opentripplanner/street/model/edge/StreetTransitEntranceLink.java
  application/src/main/java/org/opentripplanner/street/model/vertex/StationEntranceVertex.java
  application/src/main/java/org/opentripplanner/street/model/vertex/VertexFactory.java
  application/src/main/java/org/opentripplanner/transit/model/site/StationElementBuilder.java
  application/src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
  application/src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
  application/src/test/java/org/opentripplanner/apis/gtfs/mapping/DirectionMapperTest.java
  application/src/test/java/org/opentripplanner/apis/transmodel/model/EnumTypesTest.java
  application/src/test/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilderTest.java
  application/src/test/java/org/opentripplanner/osm/model/OsmWithTagsTest.java
  application/src/test/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapperTest.java
  application/src/test/resources/org/opentripplanner/apis/gtfs/expectations/walk-steps.json
  application/src/test/resources/org/opentripplanner/apis/gtfs/queries/walk-steps.graphql
  doc/user/BuildConfiguration.md
Labels: New Feature, bump serialization id, Config Change

#6357 Revert allow multiple states during transfer edge traversals
  application/src/ext/java/org/opentripplanner/ext/flex/template/AbstractFlexTemplate.java
  application/src/ext/java/org/opentripplanner/ext/flex/template/FlexDirectPathFactory.java
  application/src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/Transfer.java
  application/src/main/java/org/opentripplanner/street/search/request/StreetSearchRequest.java
  application/src/main/java/org/opentripplanner/street/search/state/EdgeTraverser.java
  application/src/test/java/org/opentripplanner/_support/geometry/Coordinates.java
  application/src/test/java/org/opentripplanner/street/search/state/EdgeTraverserTest.java
  application/src/test/java/org/opentripplanner/street/search/state/TestStateBuilder.java
Labels: Bug, Entur Test

#6326 Generate Raptor transfer cache in parallel
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/RaptorTransferIndex.java
  application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRequestTransferCache.java
Labels: Optimization

#6393 Extract mapper for Transmodel `bookWhen`, new values for `relativeDirection`
  application/src/main/java/org/opentripplanner/apis/transmodel/mapping/BookingInfoMapper.java
  application/src/main/java/org/opentripplanner/apis/transmodel/mapping/RelativeDirectionMapper.java
  application/src/main/java/org/opentripplanner/apis/transmodel/model/EnumTypes.java
  application/src/main/java/org/opentripplanner/apis/transmodel/model/timetable/BookingArrangementType.java
  application/src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
  application/src/test/java/org/opentripplanner/apis/transmodel/mapping/BookingInfoMapperTest.java
  application/src/test/java/org/opentripplanner/apis/transmodel/model/EnumTypesTest.java
Labels: Improvement, Technical Debt, Skip Changelog

#6272 Add currentFuelPercent and currentRangeMeters to RentalVehichle in the GTFS GraphQL API
  application/src/ext-test/java/org/opentripplanner/ext/fares/impl/GtfsFaresV2ServiceTest.java
  application/src/ext/java/org/opentripplanner/ext/fares/model/Distance.java
  application/src/ext/java/org/opentripplanner/ext/fares/model/FareDistance.java
  application/src/main/java/org/opentripplanner/apis/gtfs/GtfsGraphQLIndex.java
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/RentalVehicleFuelImpl.java
  application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/RentalVehicleImpl.java
  application/src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
  application/src/main/java/org/opentripplanner/apis/gtfs/generated/graphql-codegen.yml
  application/src/main/java/org/opentripplanner/apis/transmodel/model/stop/RentalVehicleType.java
  application/src/main/java/org/opentripplanner/gtfs/mapping/FareLegRuleMapper.java
  application/src/main/java/org/opentripplanner/service/vehiclerental/model/RentalVehicleFuel.java
  application/src/main/java/org/opentripplanner/service/vehiclerental/model/VehicleRentalVehicle.java
  application/src/main/java/org/opentripplanner/transit/model/basic/Distance.java
  application/src/main/java/org/opentripplanner/transit/model/basic/Ratio.java
  application/src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFreeVehicleStatusMapper.java
  application/src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
  application/src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
  application/src/test/java/org/opentripplanner/gtfs/mapping/FareLegRuleMapperTest.java
  application/src/test/java/org/opentripplanner/routing/core/DistanceTest.java
  application/src/test/java/org/opentripplanner/routing/core/RatioTest.java
  application/src/test/java/org/opentripplanner/service/vehiclerental/model/TestFreeFloatingRentalVehicleBuilder.java
  application/src/test/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFreeVehicleStatusMapperTest.java
  application/src/test/resources/org/opentripplanner/apis/gtfs/expectations/rental-vehicle.json
  application/src/test/resources/org/opentripplanner/apis/gtfs/expectations/vehicle-rentals-bybbox.json
  application/src/test/resources/org/opentripplanner/apis/gtfs/queries/rental-vehicle.graphql
  application/src/test/resources/org/opentripplanner/apis/gtfs/queries/vehicle-rentals-bybbox.graphql
Labels: Improvement

#6408 Switch debug client CDN to Github Pages
  .github/workflows/debug-client.yml
  client/index.html
Labels: Skip Changelog

#6378 Add a matcher API for filters in the transit service used for route lookup
  application/src/ext/java/org/opentripplanner/ext/flex/FlexIndex.java
  application/src/main/java/org/opentripplanner/apis/transmodel/TransmodelGraphQLSchema.java
  application/src/main/java/org/opentripplanner/transit/api/request/FindRoutesRequest.java
  application/src/main/java/org/opentripplanner/transit/api/request/FindRoutesRequestBuilder.java
  application/src/main/java/org/opentripplanner/transit/model/filter/expr/CaseInsensitiveStringPrefixMatcher.java
  application/src/main/java/org/opentripplanner/transit/model/filter/expr/NullSafeWrapperMatcher.java
  application/src/main/java/org/opentripplanner/transit/model/filter/transit/RouteMatcherFactory.java
  application/src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
  application/src/main/java/org/opentripplanner/transit/service/TransitService.java
  application/src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
  application/src/test/java/org/opentripplanner/transit/model/filter/expr/CaseInsensitiveStringPrefixMatcherTest.java
  application/src/test/java/org/opentripplanner/transit/model/filter/expr/NullSafeWrapperMatcherTest.java
  application/src/test/java/org/opentripplanner/transit/model/filter/transit/RouteMatcherFactoryTest.java
Labels: Technical Debt, Entur Test

#6396 Add ci workflow for validating schema changes
  .github/workflows/schema-validation.yml
Labels: Improvement, Technical Debt, Skip Changelog

#6402 Only run "Debug Client" workflow on `dev-2.x` branch
  .github/workflows/debug-client.yml
Labels: Technical Debt, Entur Test, Skip Changelog
