Repository opentripplanner/OpenTripPlanner, pull requests merged in 2025-08, with the labels that each got.

#6778 Do not add turn duration into walk distance
  application/src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
  application/src/test/java/org/opentripplanner/street/model/edge/StreetEdgeTest.java
Labels: Skip Changelog

#6818 Fix some stop variable names
  application/src/main/java/org/opentripplanner/transit/model/network/TripPattern.java
  application/src/main/java/org/opentripplanner/transit/service/StopTimesHelper.java
Labels: Skip Changelog

#6810 Remove preferred agencies and routes
  application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/LegacyRouteRequestMapper.java
  application/src/main/java/org/opentripplanner/apis/transmodel/mapping/TripRequestMapper.java
  application/src/main/java/org/opentripplanner/routing/api/request/request/TransitRequest.java
  application/src/main/java/org/opentripplanner/routing/api/request/request/TransitRequestBuilder.java
  application/src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
  application/src/test/java/org/opentripplanner/routing/api/request/request/TransitRequestTest.java
Labels: Technical Debt, Skip Changelog

#6830 Doc: Update JavaDoc RaptorTransfer
  raptor/src/main/java/org/opentripplanner/raptor/api/model/RaptorTransfer.java
Labels: Documentation, Skip Changelog
